// ═══════════════════════════════════════════════════════════════
// MERA HAQ — CENTRAL GOVERNMENT SCHEMES DATABASE (Part 1: 1-100)
// Last Updated: March 2026
// ═══════════════════════════════════════════════════════════════
// Compact format: Each scheme is a data object ready for the matching engine.
// Fields: name, cat(egory), tag, benefit, desc, elig(ibility)[], docs[], apply[], link, helpline, amt, match()
// ═══════════════════════════════════════════════════════════════

export const CENTRAL_SCHEMES_1 = [

// ═══ HEALTHCARE (1-15) ═══
{name:"Ayushman Bharat PM-JAY",cat:"health",tag:"Health",benefit:"₹5L/yr health cover per family | ₹10L for 70+ seniors",desc:"World's largest health insurance. 1961 packages, 28K+ hospitals. From Sep 2024: all 70+ seniors covered regardless of income. 36.9 crore cards issued.",elig:["SECC-2011 families","Rural: kutcha house, landless, SC/ST, no earning member 16-59","Urban: ragpicker, beggar, domestic worker, vendor, construction worker","ALL seniors 70+ (no income limit from Sep 2024)","ASHA/Anganwadi workers + families (from Mar 2024)"],docs:["Aadhaar Card","Ration Card / BPL Card","Age proof (for 70+ category)"],apply:["Check: beneficiary.nha.gov.in","Download Ayushman App","Visit CSC for card","Helpline: 14555"],link:"https://pmjay.gov.in/",helpline:"14555",amt:500000,match:p=>["below1","1to2.5","2.5to5"].includes(p.income)||(p.age>=70)||p.lifeStage.includes("disabled")},

{name:"Janani Suraksha Yojana (JSY)",cat:"health",tag:"Health",benefit:"₹700-₹1,400 cash for institutional delivery",desc:"Cash incentive for pregnant women to deliver at government hospitals. ASHA workers facilitate the process.",elig:["Pregnant women","BPL / SC / ST families","Age 19+","Up to 2 live births"],docs:["Aadhaar","BPL/Ration Card","MCH Card","Bank passbook"],apply:["Register pregnancy at PHC/ANM","Deliver at government hospital","Cash credited post-delivery via DBT"],link:"https://nhm.gov.in/",helpline:"State NHM helpline",amt:1400,match:p=>p.gender==="female"&&p.lifeStage.includes("pregnant")},

{name:"PM Matru Vandana Yojana (PMMVY)",cat:"health",tag:"Health",benefit:"₹11,000 for 1st child | ₹6,000 for 2nd girl child",desc:"Maternity benefit in installments. ₹5,000 (PMMVY) + ₹6,000 (JSY) for 1st birth. ₹6,000 lump sum for 2nd child if girl.",elig:["Pregnant women, 1st live birth","2nd child only if girl","Age 19+","NOT govt employees"],docs:["Aadhaar","MCP Card","Bank passbook","Pregnancy registration"],apply:["Register at Anganwadi Centre or health facility","Forms 1-A, 1-B, 1-C at each stage","pmmvy.wcd.gov.in"],link:"https://pmmvy.wcd.gov.in/",helpline:"181",amt:11000,match:p=>p.gender==="female"&&p.lifeStage.includes("pregnant")},

{name:"Mission Indradhanush (Universal Immunization)",cat:"health",tag:"Health",benefit:"Free vaccination for children & pregnant women",desc:"Intensified drive to fully immunize all children under 2 and pregnant women. Covers 12 diseases. Special drives in low-coverage areas.",elig:["All children 0-2 years","Pregnant women","No income/caste restriction"],docs:["Mother-Child Health card","Aadhaar (optional)"],apply:["Visit nearest PHC/Sub-centre/Anganwadi","Free — no application needed","Vaccination schedule provided at registration"],link:"https://nhm.gov.in/",helpline:"104",amt:0,match:p=>p.lifeStage.includes("children")||p.lifeStage.includes("pregnant")},

{name:"National AYUSH Mission",cat:"health",tag:"Health",benefit:"Free AYUSH treatment at 12,500+ centres",desc:"Promotes Ayurveda, Yoga, Unani, Siddha, Homeopathy services. Free treatment at AYUSH centres. Wellness clinics at PHCs.",elig:["All Indian citizens","No restrictions"],docs:["None for walk-in treatment"],apply:["Visit nearest AYUSH wellness centre / hospital","Free consultation and medicines"],link:"https://namayush.gov.in/",helpline:"14461",amt:0,match:p=>p.needs.includes("health")},

{name:"Nikshay Poshan Yojana (TB Nutrition)",cat:"health",tag:"Health",benefit:"₹500/month nutrition support for TB patients",desc:"Monthly ₹500 nutrition allowance for all notified TB patients throughout treatment duration (6-24 months).",elig:["All notified TB patients in India","Registered on Nikshay portal"],docs:["Aadhaar","Nikshay ID","Bank passbook"],apply:["Automatically enrolled when TB is diagnosed at govt hospital","OR register at nikshay.in"],link:"https://nikshay.in/",helpline:"1800-11-6666",amt:6000,match:p=>p.needs.includes("health")},

{name:"PM National Dialysis Programme",cat:"health",tag:"Health",benefit:"Free dialysis for BPL patients at district hospitals",desc:"Free hemodialysis at government district hospitals for BPL patients. PPP model — private operators in govt hospitals.",elig:["BPL patients requiring dialysis","Ayushman Bharat beneficiaries"],docs:["Aadhaar","BPL/Ayushman card","Doctor's referral"],apply:["Get referral from government hospital","Visit nearest district hospital dialysis unit"],link:"https://nhm.gov.in/",helpline:"104",amt:200000,match:p=>["below1","1to2.5"].includes(p.income)&&p.needs.includes("health")},

{name:"Rashtriya Bal Swasthya Karyakram (RBSK)",cat:"health",tag:"Health",benefit:"Free health screening & treatment for children 0-18",desc:"Child health screening at all govt/govt-aided schools. Covers 30 health conditions including birth defects, diseases, deficiencies, developmental delays. Free treatment at tertiary hospitals.",elig:["Children 0-18 years","In government and government-aided schools","Newborns at government delivery points"],docs:["School ID","Aadhaar of parent"],apply:["Automatic — mobile health teams visit schools","Parents informed if treatment needed","Free referral to tertiary hospitals"],link:"https://rbsk.gov.in/",helpline:"104",amt:0,match:p=>p.lifeStage.includes("children")},

{name:"PM Ayushman Bharat Health Infrastructure Mission (ABHIM)",cat:"health",tag:"Health",benefit:"New hospitals, labs, and health infra in every district",desc:"₹64,180 crore for health infrastructure: critical care blocks in all districts, integrated public health labs, block-level health units. Focus on pandemic preparedness.",elig:["All citizens — infrastructure scheme benefiting everyone"],docs:["NA — infrastructure project"],apply:["Benefits accessed through improved health facilities","No individual application"],link:"https://www.mohfw.gov.in/",helpline:"104",amt:0,match:p=>p.needs.includes("health")},

{name:"National Mental Health Programme",cat:"health",tag:"Health",benefit:"Free mental health services at district hospitals",desc:"Free psychiatric OPD services at all district hospitals. Includes counselling, medicines, and rehabilitation. Anti-stigma campaigns. Training of PHC doctors in mental health.",elig:["Any person seeking mental health support","No income or age restriction"],docs:["None for OPD consultation"],apply:["Visit district hospital psychiatric OPD","OR call iCall helpline: 9152987821","Vandrevala Foundation: 1860-2662-345"],link:"https://nhm.gov.in/",helpline:"08046110007 (KIRAN helpline)",amt:0,match:p=>p.needs.includes("health")},

{name:"Ayushman Arogya Mandir (Health & Wellness Centres)",cat:"health",tag:"Health",benefit:"Free primary healthcare + screening + diagnostics at 1.6L+ centres",desc:"Upgraded PHCs/Sub-centres providing free comprehensive primary healthcare including NCD screening, mental health, ENT, dental, maternal care. Free essential medicines and diagnostics. 1.6 lakh+ centres operational.",elig:["All citizens — walk-in, no restrictions"],docs:["Aadhaar (optional)"],apply:["Visit nearest Ayushman Arogya Mandir / Health & Wellness Centre","Free — no registration needed for walk-in","ABHA Health ID can be created on site"],link:"https://ab-hwc.nhp.gov.in/",helpline:"14555",amt:0,match:p=>true},

{name:"Rashtriya Swasthya Bima Yojana (RSBY)",cat:"insurance",tag:"Insurance",benefit:"₹30,000 health insurance for BPL families (now mostly merged with PMJAY)",desc:"Health insurance for BPL/unorganized workers. Largely subsumed into Ayushman Bharat PMJAY. Still operational in some states for supplementary coverage.",elig:["BPL families","Unorganized sector workers","Building and construction workers"],docs:["BPL card","Aadhaar","Smart card (RSBY)"],apply:["Enrollment at health camps organized by district","Smart card issued on spot"],link:"https://www.india.gov.in/",helpline:"104",amt:30000,match:p=>["below1","1to2.5"].includes(p.income)},

{name:"Pradhan Mantri Swasthya Suraksha Yojana (PMSSY)",cat:"health",tag:"Health",benefit:"New AIIMS and upgraded medical colleges across India",desc:"Setting up new AIIMS (22 new AIIMS announced) and upgrading government medical colleges. Improves access to tertiary healthcare in underserved areas.",elig:["All citizens — infrastructure benefit"],docs:["NA"],apply:["Access through new/upgraded hospitals in your area"],link:"https://pmssy-mohfw.nic.in/",helpline:"104",amt:0,match:p=>p.needs.includes("health")},

{name:"Janani Shishu Suraksha Karyakram (JSSK)",cat:"health",tag:"Health",benefit:"100% free delivery + free treatment for sick newborns",desc:"Absolutely free delivery at government hospitals including: normal and C-section delivery, free medicines, free diagnostics, free blood, free diet, free transport (home to hospital and back), free treatment for sick newborns up to 30 days.",elig:["All pregnant women delivering at govt institutions","Sick newborns (0-30 days)","No income restriction"],docs:["Aadhaar","MCH card"],apply:["Visit any government hospital for delivery","All services are free — no charges at all","Report any demand for money to hospital superintendent"],link:"https://nhm.gov.in/",helpline:"104 / 108 (ambulance)",amt:50000,match:p=>p.gender==="female"&&p.lifeStage.includes("pregnant")},

{name:"PM Surakshit Matritva Abhiyan",cat:"health",tag:"Health",benefit:"Free antenatal checkup on 9th of every month",desc:"Free comprehensive antenatal checkup on the 9th of every month at government hospitals. Specialist doctors provide consultation. Helps identify high-risk pregnancies early.",elig:["All pregnant women","On 9th of every month at PHC/CHC/District Hospital"],docs:["MCH card","Aadhaar (optional)"],apply:["Visit any government health facility on 9th of any month","Free specialist consultation","No appointment needed"],link:"https://pmsma.nhp.gov.in/",helpline:"104",amt:0,match:p=>p.gender==="female"&&p.lifeStage.includes("pregnant")},

// ═══ PENSION & SAVINGS (16-25) ═══
{name:"Atal Pension Yojana (APY)",cat:"pension",tag:"Pension",benefit:"₹1,000-₹5,000/month guaranteed pension after 60",desc:"Government-guaranteed pension. Contribute ₹42-₹1,454/month based on age. 5.86 crore subscribers.",elig:["Age 18-40","Bank account holder","Not income taxpayer","Not EPF/EPS member"],docs:["Aadhaar","Bank passbook","Mobile number"],apply:["Visit bank branch","Fill APY form","Choose pension amount","Sign auto-debit mandate","Online: Through net banking"],link:"https://www.npscra.nsdl.co.in/scheme-details.php",helpline:"1800-889-1030",amt:60000,match:p=>p.age>=18&&p.age<=40&&p.bankAccount==="yes"&&!["above25","10to25"].includes(p.income)},

{name:"National Pension System (NPS)",cat:"pension",tag:"Pension",benefit:"Market-linked retirement corpus + tax benefit ₹50K extra under 80CCD(1B)",desc:"Voluntary pension scheme for all citizens 18-70. Market-linked returns (10-12% historical). Extra ₹50,000 tax deduction under 80CCD(1B) over and above 80C.",elig:["Any Indian citizen 18-70","Salaried or self-employed"],docs:["PAN Card","Aadhaar","Bank account","Photograph"],apply:["Online: enps.nsdl.com","OR visit any Point of Presence (PoP) — most banks are PoPs","Receive PRAN number"],link:"https://www.npscra.nsdl.co.in/",helpline:"1800-889-1030",amt:200000,match:p=>p.age>=18&&p.age<=70&&["salaried","self-employed"].includes(p.employment)},

{name:"PM Shram Yogi Maandhan (PMSYM)",cat:"pension",tag:"Pension",benefit:"₹3,000/month pension for unorganized workers after 60",desc:"Pension scheme for unorganized workers earning below ₹15,000/month. Contribute ₹55-₹200/month. ₹3,000 guaranteed monthly pension after age 60. Equal government contribution.",elig:["Unorganized worker aged 18-40","Monthly income below ₹15,000","Not member of EPFO/ESIC/NPS (govt)"],docs:["Aadhaar","Bank passbook","Mobile number"],apply:["Visit nearest CSC (Common Service Centre)","OR enroll at maandhan.in","₹30 one-time registration fee at CSC"],link:"https://maandhan.in/",helpline:"1800-267-6888",amt:36000,match:p=>p.age>=18&&p.age<=40&&["self-employed","business"].includes(p.employment)&&!["above25","10to25","5to10"].includes(p.income)},

{name:"PM Laghu Vyapari Maandhan Yojana",cat:"pension",tag:"Pension",benefit:"₹3,000/month pension for small traders after 60",desc:"Pension scheme for small traders, shopkeepers, self-employed with GST turnover below ₹1.5 crore. Same structure as PMSYM.",elig:["Small trader/shopkeeper aged 18-40","GST turnover below ₹1.5 crore","Not EPFO/ESIC/NPS member"],docs:["Aadhaar","GST registration","Bank passbook"],apply:["Visit CSC or maandhan.in","Self-enrollment with Aadhaar"],link:"https://maandhan.in/",helpline:"1800-267-6888",amt:36000,match:p=>p.age>=18&&p.age<=40&&["self-employed","business"].includes(p.employment)},

{name:"PM Kisan Maandhan Yojana",cat:"pension",tag:"Pension",benefit:"₹3,000/month pension for small/marginal farmers after 60",desc:"Pension for farmers with landholding up to 2 hectares. Contribute ₹55-₹200/month. Equal govt contribution. ₹3,000/month pension after 60.",elig:["Small/marginal farmer (up to 2 hectares)","Age 18-40","Not EPFO/ESIC/NPS member"],docs:["Aadhaar","Land records","Bank passbook"],apply:["Visit CSC or maandhan.in","Land records verified from state database"],link:"https://maandhan.in/",helpline:"1800-267-6888",amt:36000,match:p=>p.age>=18&&p.age<=40&&p.employment==="farmer"&&(p.ownLand==="small"||p.ownLand==="no")},

{name:"Sukanya Samriddhi Yojana (SSY)",cat:"pension",tag:"Savings",benefit:"8.2% interest (highest govt rate) + EEE tax benefit for girl child",desc:"Girl child savings. Deposit ₹250-₹1.5L/year for 15 years. Matures at 21. Triple tax exempt. 8.2% rate (Jan-Jun 2026).",elig:["Girl child below 10 years","Max 2 accounts per family","Indian resident only"],docs:["Girl's birth certificate","Guardian's Aadhaar + PAN","Address proof","Photographs"],apply:["Visit any Post Office or authorized bank","Fill SSY account opening form","Min deposit: ₹250"],link:"https://www.indiapost.gov.in/",helpline:"1800-266-6868",amt:150000,match:p=>p.lifeStage.includes("girl-child")},

{name:"PM Jan Dhan Yojana (PMJDY)",cat:"money",tag:"Banking",benefit:"Zero-balance account + ₹2L accident insurance + ₹30K life cover",desc:"Free bank account with RuPay debit card. ₹2L accident cover built-in. Overdraft up to ₹10K. 53+ crore accounts. Foundation for all DBT schemes.",elig:["Any Indian citizen 10+","No existing bank account"],docs:["Aadhaar (single document sufficient)","OR any 2 govt IDs"],apply:["Visit any bank branch","Account opened on spot","RuPay card within 2 weeks"],link:"https://pmjdy.gov.in/",helpline:"1800-11-0001",amt:230000,match:p=>p.bankAccount==="no"},

{name:"PM Vaya Vandana Yojana (PMVVY)",cat:"senior",tag:"Senior",benefit:"Guaranteed 7.4% return for senior citizens (invest up to ₹15L)",desc:"LIC-operated pension for seniors. Guaranteed returns. Invest up to ₹15 lakh. Monthly/quarterly/annual pension options.",elig:["Age 60+ years","Max investment ₹15 lakh"],docs:["Aadhaar","Age proof","PAN Card","Bank passbook"],apply:["Visit any LIC branch","OR apply online at licindia.in","Purchase policy with lump sum payment"],link:"https://www.licindia.in/",helpline:"1800-227-717",amt:111000,match:p=>p.age>=60},

{name:"Senior Citizen Savings Scheme (SCSS)",cat:"senior",tag:"Senior",benefit:"8.2% interest for senior citizens — quarterly payout",desc:"Highest fixed-return savings for seniors. 8.2% p.a. with quarterly interest payout. Max deposit ₹30 lakh. 5-year tenure (extendable by 3). Tax benefit under 80C.",elig:["Age 60+ (or 55+ for retired defence/govt)","Max deposit ₹30 lakh","Indian resident"],docs:["Age proof","PAN Card","Aadhaar","Retirement proof (if 55-60)"],apply:["Visit any Post Office or authorized bank","Fill SCSS form","Make deposit (min ₹1,000)"],link:"https://www.indiapost.gov.in/",helpline:"1800-266-6868",amt:246000,match:p=>p.age>=60},

{name:"Indira Gandhi National Old Age Pension (IGNOAPS)",cat:"senior",tag:"Senior",benefit:"₹200-₹500/month central pension + state top-up for BPL seniors",desc:"Central pension for BPL elderly. ₹200/month (60-79 years) + ₹500/month (80+). States add ₹300-₹1500 top-up. Total: ₹500-₹2000/month depending on state.",elig:["Age 60+","BPL family","Not receiving other govt pension"],docs:["Age proof","BPL card","Aadhaar","Bank passbook"],apply:["Apply through Panchayat office (rural) or Municipality (urban)","OR state social welfare department","Online: nsap.nic.in"],link:"https://nsap.nic.in/",helpline:"State social welfare helpline",amt:6000,match:p=>p.age>=60&&["below1","1to2.5"].includes(p.income)},

// ═══ AGRICULTURE (26-43) ═══
{name:"PM-KISAN Samman Nidhi",cat:"agriculture",tag:"Agriculture",benefit:"₹6,000/year (₹2,000 × 3) direct cash to farmers",desc:"Income support for all landholding farmers. 22nd installment released 13 Mar 2026. ₹4.27L crore total disbursed. 9.32 crore beneficiaries.",elig:["All landholding farmer families","NOT: institutional landholders, govt employees, taxpayers, professionals"],docs:["Aadhaar","Land records","Bank passbook (Aadhaar-linked)","e-KYC completion"],apply:["pmkisan.gov.in → New Registration","Enter Aadhaar, land details","Verified by state nodal officer","Status: pmkisan.gov.in → Beneficiary Status"],link:"https://pmkisan.gov.in/",helpline:"155261",amt:6000,match:p=>p.employment==="farmer"||(p.ownLand&&p.ownLand!=="no")},

{name:"PM Fasal Bima Yojana (PMFBY)",cat:"agriculture",tag:"Agriculture",benefit:"Crop insurance at 1.5-5% premium (govt pays 95%+)",desc:"Crop insurance. Farmer premium: 2% Kharif, 1.5% Rabi, 5% horticulture. Govt pays remaining. Satellite + drone-based claim assessment.",elig:["All farmers growing notified crops","Voluntary for all farmers","Landowners and tenants/sharecroppers"],docs:["Land records","Aadhaar","Bank details","Sowing certificate"],apply:["pmfby.gov.in → Farmer Corner","OR through bank (KCC loanees auto-enrolled)","Report loss within 72 hrs: 1800-200-7710"],link:"https://pmfby.gov.in/",helpline:"1800-200-7710",amt:200000,match:p=>p.employment==="farmer"||(p.ownLand&&p.ownLand!=="no")},

{name:"Kisan Credit Card (KCC)",cat:"agriculture",tag:"Agriculture",benefit:"₹3 lakh crop loan at 4% interest (after subvention)",desc:"Subsidized crop credit. 7% interest with 3% subvention for timely repayment = 4% effective. Extended to fisheries and animal husbandry. No collateral up to ₹1.6L.",elig:["All farmers, fishermen, animal husbandry practitioners","PM-KISAN beneficiaries get simplified 1-page application"],docs:["Aadhaar","Land records","PM-KISAN ID (optional)","Photograph"],apply:["Visit any bank branch","1-page form for PM-KISAN beneficiaries","Bank processes within 14 days"],link:"https://pmkisan.gov.in/KCC.aspx",helpline:"155261",amt:300000,match:p=>p.employment==="farmer"},

{name:"Soil Health Card Scheme",cat:"agriculture",tag:"Agriculture",benefit:"Free soil testing + crop-specific fertilizer recommendations",desc:"Free soil testing for all farmland. Provides Soil Health Card with nutrient status and fertilizer recommendations. Helps reduce fertilizer costs by 10-15%.",elig:["All farmers in India","No restrictions"],docs:["Land details","Aadhaar (optional)"],apply:["Contact nearest Krishi Vigyan Kendra (KVK)","OR register at soilhealth.dac.gov.in","Soil sample collected from your field","Report generated in 2-3 weeks"],link:"https://soilhealth.dac.gov.in/",helpline:"1800-180-1551",amt:0,match:p=>p.employment==="farmer"},

{name:"PM Krishi Sinchai Yojana (PMKSY)",cat:"agriculture",tag:"Agriculture",benefit:"Subsidized micro-irrigation (drip/sprinkler) — 55-100% subsidy",desc:"Subsidized drip and sprinkler irrigation. Central subsidy: 55% for general, 100% for SC/ST/small farmers in many states. Saves 30-50% water vs flood irrigation.",elig:["All farmers","Priority: small and marginal farmers","SC/ST farmers get higher subsidy"],docs:["Land records","Aadhaar","Bank passbook","Quotation from empanelled supplier"],apply:["Visit District Agriculture Office","Apply online through state agriculture portal","Subsidy directly released to supplier or farmer's account"],link:"https://pmksy.gov.in/",helpline:"State agriculture helpline",amt:100000,match:p=>p.employment==="farmer"&&p.needs.includes("agriculture")},

{name:"Paramparagat Krishi Vikas Yojana (PKVY)",cat:"agriculture",tag:"Agriculture",benefit:"₹50,000/hectare for organic farming (3 years)",desc:"Promotes organic farming. ₹50,000 per hectare over 3 years for conversion to organic. Covers inputs, certification, marketing. Cluster-based approach.",elig:["Farmers willing to adopt organic farming","Must form clusters of 20+ farmers (50+ acres)","3-year commitment to organic practices"],docs:["Land records","Cluster formation document","Aadhaar","Bank passbook"],apply:["Contact District Agriculture Office","Form a cluster with 20+ farmers","Apply through DAC state officer","Training and inputs provided free"],link:"https://pgsindia-ncof.gov.in/",helpline:"State agriculture dept",amt:50000,match:p=>p.employment==="farmer"&&p.needs.includes("agriculture")},

{name:"e-NAM (National Agriculture Market)",cat:"agriculture",tag:"Agriculture",benefit:"Sell produce online at best price — transparent bidding",desc:"Online trading platform connecting 1,000+ mandis across India. Farmers can sell produce to buyers across states at competitive prices. Transparent bidding eliminates middlemen.",elig:["All farmers","Must register at local APMC/mandi","No income restriction"],docs:["Aadhaar","Bank passbook","Mandi registration"],apply:["Register at nearest e-NAM mandi","OR enam.gov.in","Link Aadhaar and bank account","List your produce for online bidding"],link:"https://enam.gov.in/",helpline:"1800-270-0224",amt:0,match:p=>p.employment==="farmer"},

{name:"PM Matsya Sampada Yojana",cat:"agriculture",tag:"Agriculture",benefit:"Subsidies for fisheries: 40-60% for infrastructure, boats, equipment",desc:"₹20,050 crore scheme for fisheries development. Subsidies for fish farming, boats, cold storage, processing. 40% general, 60% SC/ST/women. Target: ₹1 lakh crore fish production by 2025.",elig:["Fishermen and fish farmers","Fish workers and vendors","SC/ST/Women get higher subsidy"],docs:["Aadhaar","Fishing license/registration","Bank passbook","Project report (for infrastructure)"],apply:["Apply through state fisheries department","Online: pmmsy.dof.gov.in","District Fisheries Officer processes applications"],link:"https://pmmsy.dof.gov.in/",helpline:"State fisheries dept",amt:200000,match:p=>p.employment==="farmer"&&p.needs.includes("agriculture")},

{name:"National Livestock Mission",cat:"agriculture",tag:"Agriculture",benefit:"Subsidies for poultry, dairy, goat, pig, sheep farming",desc:"Financial assistance for livestock farming. Covers poultry, dairy, goat, sheep, pig, rabbit. Subsidized feeds, breeding, insurance. Entrepreneurship development for rural youth.",elig:["Livestock farmers and aspiring entrepreneurs","Rural youth for entrepreneurship component","SHGs and FPOs"],docs:["Aadhaar","Land/premises proof","Project report","Bank passbook"],apply:["Contact District Animal Husbandry Office","Apply through state animal husbandry portal","Subsidy disbursed after verification"],link:"https://nlm.udyamimitra.in/",helpline:"State animal husbandry dept",amt:100000,match:p=>(p.employment==="farmer"||p.needs.includes("agriculture"))&&p.area==="rural"},

{name:"National Beekeeping & Honey Mission (NBHM)",cat:"agriculture",tag:"Agriculture",benefit:"₹2-3 lakh subsidy for beekeeping startups",desc:"Subsidies for beekeeping: purchase of bee colonies, boxes, processing equipment. Training provided. 35-50% subsidy on project cost.",elig:["Any farmer or rural entrepreneur","SC/ST/Women get additional subsidy","Must attend beekeeping training"],docs:["Aadhaar","Training certificate","Project report","Bank passbook"],apply:["Contact District Agriculture/Horticulture Office","Attend free beekeeping training","Apply for subsidy with project report"],link:"https://nbb.gov.in/",helpline:"011-24622627",amt:150000,match:p=>p.employment==="farmer"||p.area==="rural"},

{name:"Dairy Processing & Infrastructure Development Fund",cat:"agriculture",tag:"Agriculture",benefit:"Subsidized loans for dairy infrastructure",desc:"₹10,881 crore fund for dairy cooperatives and MSMEs. Concessional loans for milk processing, chilling, packaging, marketing infrastructure.",elig:["Dairy cooperatives","Milk producer companies","MSMEs in dairy sector"],docs:["Organization registration","Project report","Bank statements","Milk procurement data"],apply:["Apply through NDDB/state dairy federation","Project appraisal by lending bank"],link:"https://dahd.nic.in/",helpline:"State dairy dept",amt:500000,match:p=>["self-employed","business"].includes(p.employment)&&p.needs.includes("agriculture")},

{name:"PM Annadata Aay Sanrakshan Abhiyan (PM-AASHA)",cat:"agriculture",tag:"Agriculture",benefit:"MSP procurement guarantee for pulses, oilseeds, copra",desc:"Ensures farmers get Minimum Support Price for crops not covered under regular MSP procurement. Three components: Price Support Scheme, Price Deficiency Payment, Private Procurement.",elig:["Farmers growing notified crops (pulses, oilseeds, copra)","Registered on state procurement portal"],docs:["Land records","Crop sowing details","Aadhaar","Bank passbook"],apply:["Register on state procurement portal when window opens","Sell at designated procurement centres","MSP difference paid directly to bank"],link:"https://farmer.gov.in/",helpline:"State agriculture dept",amt:0,match:p=>p.employment==="farmer"},

{name:"Namo Drone Didi",cat:"agriculture",tag:"Agriculture",benefit:"Free drone training for SHG women + drone for agri services",desc:"15,000 SHGs will receive drones for agricultural use. Women SHG members trained as drone pilots. Income of ₹1 lakh+ per year from drone-as-a-service.",elig:["Women Self-Help Group members","Selected by NRLM/state rural livelihood mission","Must complete drone pilot training"],docs:["SHG membership proof","Aadhaar","Training certificate"],apply:["Through state rural livelihood mission","Selected SHGs receive training + drone","Apply through your SHG federation"],link:"https://nrlm.gov.in/",helpline:"State SRLM helpline",amt:100000,match:p=>p.gender==="female"&&p.area==="rural"},

{name:"Agriculture Infrastructure Fund (AIF)",cat:"agriculture",tag:"Agriculture",benefit:"₹2 crore loan at 3% interest subvention for agri infrastructure",desc:"₹1 lakh crore fund for farm-gate infrastructure: cold storage, warehouses, grading units, processing units. 3% interest subvention and CGTMSE guarantee.",elig:["Farmers, FPOs, cooperatives, agri startups","APMC markets, SHGs, JLGs","Agri-entrepreneurs"],docs:["Project report","KYC documents","Land/premises proof","Business plan"],apply:["Apply online at agriinfra.dac.gov.in","Select lending bank and project type","Bank processes with 3% interest subvention"],link:"https://agriinfra.dac.gov.in/",helpline:"State agriculture dept",amt:2000000,match:p=>p.employment==="farmer"||p.needs.includes("agriculture")||["self-employed","business"].includes(p.employment)},

{name:"Pradhan Mantri Kisan SAMPADA Yojana",cat:"agriculture",tag:"Agriculture",benefit:"Subsidies for food processing units (35-75% grant)",desc:"Umbrella scheme for food processing infrastructure: mega food parks, cold chains, processing units, agro-processing clusters. Grant: 35-75% of project cost.",elig:["Food processing entrepreneurs","FPOs, cooperatives, companies","Existing food businesses seeking expansion"],docs:["DPR (Detailed Project Report)","Company registration","Financial statements","Land documents"],apply:["Apply through MoFPI portal: mofpi.nic.in","Project evaluated by ministry committee","Grant released in stages based on milestones"],link:"https://mofpi.nic.in/",helpline:"011-26492174",amt:5000000,match:p=>["self-employed","business"].includes(p.employment)&&p.needs.includes("agriculture")},

{name:"Formation & Promotion of FPOs (10,000 FPOs)",cat:"agriculture",tag:"Agriculture",benefit:"₹18 lakh/FPO over 5 years + ₹15 lakh equity grant",desc:"Central scheme to form 10,000 new Farmer Producer Organizations. Each FPO gets ₹18 lakh for formation and ₹15 lakh equity grant. Professional CEO support.",elig:["Group of farmers (min 300 in plains, 100 in NE/hills)","Must register as company/cooperative/society"],docs:["Group of interested farmers","Community certificate","Aadhaar of members","Bank account for FPO"],apply:["Contact SFAC (sfacindia.com) or NABARD","Implementing agency helps formation","FPO registered and operationalized with support"],link:"https://www.sfacindia.com/",helpline:"011-26862367",amt:3300000,match:p=>p.employment==="farmer"},

// ═══ BUSINESS & MSME (44-63) ═══
{name:"PM Mudra Yojana (PMMY)",cat:"business",tag:"Business",benefit:"₹50K-₹20L collateral-free business loan (Shishu/Kishore/Tarun/Tarun Plus)",desc:"Collateral-free loans. Shishu ≤₹50K, Kishore ₹50K-5L, Tarun ₹5-10L, Tarun Plus ₹10-20L (new 2024). 52+ crore loans. Interest 8.5-12%.",elig:["Any Indian citizen with business plan","Non-farm micro/small enterprise","No defaulter status","Women/SC/ST: priority + interest concession"],docs:["Aadhaar + PAN","Business proof (Udyam/GST/Trade license)","Project report (for Kishore+)","Bank statements (6 months)","2 photographs"],apply:["mudra.org.in for forms","Visit any bank branch","psbloansin59minutes.com for faster processing","Shishu: 7 days. Tarun: 14 days processing"],link:"https://www.mudra.org.in/",helpline:"1800-11-0001",amt:2000000,match:p=>["self-employed","business"].includes(p.employment)||p.bizType!=="none"},

{name:"PM SVANidhi (Street Vendors)",cat:"business",tag:"Business",benefit:"₹10K-₹50K working capital loan at 7% interest subsidy",desc:"Micro-credit for street vendors. 1st loan: ₹10K, 2nd: ₹20K, 3rd: ₹50K. 7% interest subsidy on timely repayment. Digital payments incentive of ₹100/month.",elig:["Street vendor with vending certificate","OR recommendation letter from ULB/Town Vending Committee","Vending before/during/after COVID"],docs:["Vending certificate OR ULB letter","Aadhaar","Bank passbook","Photograph"],apply:["pmsvanidhi.mohua.gov.in","OR visit nearest bank/MFI","Quick disbursal within 10 days"],link:"https://pmsvanidhi.mohua.gov.in/",helpline:"1800-11-1979",amt:50000,match:p=>p.bizType==="street-vendor"},

{name:"Stand-Up India",cat:"business",tag:"Business",benefit:"₹10L-₹1Cr bank loan for SC/ST/Women entrepreneurs",desc:"Bank loans ₹10L-₹1Cr for SC/ST and women for new (greenfield) manufacturing/services/trading enterprises. Every bank branch must sanction at least one such loan.",elig:["SC or ST or Woman entrepreneur","Age 18+","Greenfield (new) enterprise","Not a defaulter"],docs:["Aadhaar + PAN","Caste certificate (SC/ST)","Business plan","Premises proof","Quotations"],apply:["standupmitra.in — register as entrepreneur","Select bank in your area","Submit project to bank","Bank processes within 30 days"],link:"https://www.standupmitra.in/",helpline:"1800-180-1111",amt:10000000,match:p=>(["sc","st"].includes(p.category)||p.gender==="female")&&["self-employed","business"].includes(p.employment)},

{name:"PM Employment Generation Programme (PMEGP)",cat:"business",tag:"Business",benefit:"15-35% subsidy on project cost (up to ₹50L manufacturing / ₹20L services)",desc:"Subsidy for new micro enterprises. Manufacturing up to ₹50L, service up to ₹20L. Subsidy: General 15-25%, SC/ST/Women/NE 25-35%. Higher in rural areas.",elig:["Age 18+","8th pass (manufacturing >₹10L)","New enterprise only","Not availed PMRY/REGP earlier"],docs:["Aadhaar + PAN","Educational certificates","Project report","Caste certificate (for higher subsidy)","EDP training certificate"],apply:["kviconline.gov.in/pmegp","Online application through KVIC/KVIB/DIC","Project screened by Task Force Committee","Subsidy directly to bank (margin money)"],link:"https://www.kviconline.gov.in/pmegp/pmegpmysql/index.php",helpline:"022-26711653",amt:1750000,match:p=>p.age>=18&&["self-employed","business"].includes(p.employment)&&!["above25","10to25"].includes(p.income)},

{name:"Udyam Registration (Free MSME)",cat:"business",tag:"Business",benefit:"Free instant MSME registration → 50+ government benefits",desc:"Free, instant, Aadhaar-based registration. Unlocks: priority lending, govt tender preference, patent/trademark subsidy, CGTMSE loans, lower electricity tariffs, ISO reimbursement.",elig:["Micro: ≤₹1Cr invest + ≤₹5Cr turnover","Small: ≤₹10Cr + ≤₹50Cr","Medium: ≤₹50Cr + ≤₹250Cr"],docs:["Aadhaar only (+ PAN auto-verified + GST auto-verified)"],apply:["udyamregistration.gov.in","10 minutes — completely free","Instant e-certificate with QR code"],link:"https://udyamregistration.gov.in/",helpline:"011-23061176",amt:0,match:p=>["self-employed","business"].includes(p.employment)||["micro","small","medium","startup"].includes(p.bizType)},

{name:"Credit Guarantee Trust for MSEs (CGTMSE)",cat:"business",tag:"Business",benefit:"Collateral-free loan guarantee up to ₹5 crore for MSMEs",desc:"Government guarantees MSME loans up to ₹5 crore. No collateral or third-party guarantee needed. Banks get 75-85% guarantee coverage, making them more willing to lend.",elig:["Micro and Small enterprises registered under Udyam","Both manufacturing and services","Individual/proprietor/partnership/company"],docs:["Udyam registration","PAN","Business plan","Bank loan application","Financial statements"],apply:["Apply for business loan at any bank","Request CGTMSE coverage","Bank applies to CGTMSE on your behalf","Loan sanctioned without collateral"],link:"https://www.cgtmse.in/",helpline:"022-22611612",amt:50000000,match:p=>["self-employed","business"].includes(p.employment)||["micro","small"].includes(p.bizType)},

{name:"PM Vishwakarma Yojana",cat:"business",tag:"Business",benefit:"₹3L loan at 5% + ₹15K toolkit + free training for 18 traditional crafts",desc:"For traditional artisans in 18 trades. ₹1L (1st) + ₹2L (2nd) loan at 5%. ₹15,000 toolkit grant. Training with ₹500/day stipend. PM Vishwakarma certificate.",elig:["Artisan in 18 trades: carpenter, blacksmith, goldsmith, potter, sculptor, cobbler, mason, tailor, barber, locksmith, boat maker, armourer, basket maker, doll maker, garland maker, washerman, fishing net maker, hammer/tool maker","Age 18+","NOT govt employee, NOT PM-KISAN beneficiary"],docs:["Aadhaar only","Self-declaration of trade","Verified by Gram Panchayat/ULB"],apply:["pmvishwakarma.gov.in","Register with Aadhaar OTP","Verified by local body","Training → Toolkit → Loan"],link:"https://pmvishwakarma.gov.in/",helpline:"18002677777",amt:315000,match:p=>["self-employed"].includes(p.employment)},

{name:"Startup India (DPIIT Recognition)",cat:"business",tag:"Business",benefit:"3-year tax holiday + angel tax exemption + self-certification + fast patent",desc:"DPIIT recognition unlocks: 80-IAC tax holiday (3 of 10 years), angel tax exemption, self-certification for 9 labor laws, 80% rebate on patent fees, fast-track patent exam.",elig:["Company/LLP incorporated in India","Age < 10 years since incorporation","Turnover < ₹100 crore","Working towards innovation/improvement"],docs:["Certificate of incorporation","Brief about innovation","PAN","Aadhaar of founders"],apply:["startupindia.gov.in → Register","DPIIT recognition application","Get recognition certificate within 2 days","Apply for 80-IAC with Inter-Ministerial Board"],link:"https://www.startupindia.gov.in/",helpline:"1800-115-565",amt:500000,match:p=>p.bizType==="startup"},

{name:"SFURTI (Scheme of Fund for Regeneration of Traditional Industries)",cat:"business",tag:"Business",benefit:"₹2.5 crore per cluster for traditional industry revival",desc:"Cluster development for traditional industries: khadi, coir, bamboo, handicraft. Up to ₹2.5 crore per cluster for infrastructure, training, marketing.",elig:["Groups of traditional industry artisans forming a cluster","100-500 artisans per cluster","Khadi, coir, bamboo, village industry clusters"],docs:["Cluster formation proposal","Artisan list with Aadhaar","Implementing agency details"],apply:["Submit DPR through Nodal Agency to KVIC","kvic.gov.in/sfurti"],link:"https://www.kviconline.gov.in/",helpline:"022-26711653",amt:2500000,match:p=>["self-employed"].includes(p.employment)&&p.area==="rural"},

{name:"ZED Certification for MSMEs",cat:"business",tag:"Business",benefit:"80% subsidy on quality certification (ISO, ZED) for MSMEs",desc:"Zero Defect Zero Effect certification. Government subsidizes 80% of certification cost for micro, 60% for small, 50% for medium enterprises.",elig:["Udyam registered MSMEs","Manufacturing and service enterprises"],docs:["Udyam registration","PAN","Application on ZED portal"],apply:["zed.msme.gov.in","Register and apply for assessment","Assessor visits and certifies","Subsidy credited to bank"],link:"https://zed.msme.gov.in/",helpline:"1800-599-2089",amt:200000,match:p=>["self-employed","business"].includes(p.employment)},

{name:"Technology Upgradation Fund Scheme (TUFS)",cat:"business",tag:"Business",benefit:"5% interest subsidy for textile and garment industry modernization",desc:"5% interest reimbursement on term loans for technology upgradation in textile/garment industry. Covers machinery purchase, modernization, expansion.",elig:["Textile and garment manufacturing units","Registered MSME or larger textile enterprise","Loan from scheduled bank"],docs:["Udyam/TUFS registration","Loan sanction letter","Machinery quotations","PAN + Aadhaar"],apply:["txcindia.gov.in","Apply online with project details","Interest subvention released quarterly"],link:"https://txcindia.gov.in/",helpline:"011-23063932",amt:500000,match:p=>["self-employed","business"].includes(p.employment)},

{name:"ASPIRE (Scheme for Promoting Innovation)",cat:"business",tag:"Business",benefit:"₹1 crore for MSME incubation centres and innovation labs",desc:"Sets up incubation centres and innovation labs in MSMEs. Livelihood Business Incubators and Technology Business Incubators. Training for aspiring entrepreneurs.",elig:["Aspiring entrepreneurs","Existing MSMEs seeking innovation support","Academic institutions setting up incubators"],docs:["Business idea/plan","Aadhaar","Educational certificates"],apply:["Contact nearest MSME-DI office","aspire.msme.gov.in","Apply for incubation support"],link:"https://aspire.msme.gov.in/",helpline:"1800-599-2089",amt:0,match:p=>["self-employed","business"].includes(p.employment)||p.bizType==="startup"},

{name:"GeM Portal Registration",cat:"business",tag:"Business",benefit:"Sell products/services to government — ₹4+ lakh crore market",desc:"Government e-Marketplace. Any MSME can register and sell to central/state government. ₹4 lakh crore+ procurement annually. No minimum turnover required. Direct payment to vendor.",elig:["Any business entity with GST/PAN","MSME/Udyam registered preferred","Individual service providers also eligible"],docs:["GST registration","PAN","Bank account","Udyam registration (for MSME benefits)"],apply:["gem.gov.in → Seller registration","Complete profile and list products/services","Participate in government tenders and direct purchase"],link:"https://gem.gov.in/",helpline:"1800-419-3436",amt:0,match:p=>["self-employed","business"].includes(p.employment)},

{name:"MSME Samadhaan (Delayed Payment Monitoring)",cat:"business",tag:"Business",benefit:"Legal recourse for delayed payments to MSMEs — within 90 days",desc:"Online portal for MSMEs to file complaints about delayed payments from buyers. MSEFC must resolve within 90 days. Interest at 3× bank rate for delayed period.",elig:["Udyam registered MSMEs","Payments overdue beyond 45 days from buyers"],docs:["Udyam registration","Invoice copies","Supply order/contract","Proof of delivery"],apply:["samadhaan.msme.gov.in","File case online against the buyer","MSEFC summons buyer within 15 days","Resolution within 90 days mandatory"],link:"https://samadhaan.msme.gov.in/",helpline:"011-23061176",amt:0,match:p=>["self-employed","business"].includes(p.employment)},

{name:"CHAMPIONS Portal (MSME Helpline)",cat:"business",tag:"Business",benefit:"Single-window grievance resolution for MSMEs",desc:"Creation and Harmonious Application of Modern Processes for Increasing Output and National Strength. Digital platform for MSME grievances, handholding, and information.",elig:["All MSMEs in India"],docs:["Udyam registration"],apply:["champions.gov.in","OR call 011-23061176","File grievance and track resolution"],link:"https://champions.gov.in/",helpline:"011-23061176",amt:0,match:p=>["self-employed","business"].includes(p.employment)},

// ═══ INSURANCE (64-67) ═══
{name:"PM Jeevan Jyoti Bima (PMJJBY)",cat:"insurance",tag:"Insurance",benefit:"₹2 lakh life insurance at ₹436/year",desc:"World's cheapest life insurance. ₹2L cover for ₹436/year. Death due to any cause. Auto-renewed annually via bank auto-debit.",elig:["Age 18-50","Bank account holder"],docs:["Bank passbook","Aadhaar","Consent form"],apply:["Fill 1-page form at your bank","Sign auto-debit for ₹436/year on 31 May","Online: through net banking"],link:"https://jansuraksha.gov.in/",helpline:"1800-180-1111",amt:200000,match:p=>p.age>=18&&p.age<=50&&p.bankAccount==="yes"},

{name:"PM Suraksha Bima (PMSBY)",cat:"insurance",tag:"Insurance",benefit:"₹2 lakh accident cover at ₹20/year",desc:"Accident insurance. ₹2L for death/total disability, ₹1L for partial disability. Just ₹20/year. Auto-debit from bank.",elig:["Age 18-70","Bank account holder"],docs:["Bank passbook","Aadhaar"],apply:["1-page form at bank","Auto-debit ₹20 on 1 June annually"],link:"https://jansuraksha.gov.in/",helpline:"1800-180-1111",amt:200000,match:p=>p.age>=18&&p.age<=70&&p.bankAccount==="yes"},

{name:"Ayushman Bharat for Senior Citizens 70+",cat:"insurance",tag:"Insurance",benefit:"Additional ₹5 lakh health cover for ALL seniors 70+ (no income limit)",desc:"From Sep 2024: All citizens 70+ get ₹5 lakh health cover regardless of income. Additional to existing PMJAY (total ₹10L if already covered). Separate Ayushman card for seniors.",elig:["All Indian citizens aged 70+","No income restriction","Can have private insurance and still avail"],docs:["Aadhaar","Age proof","Existing Ayushman card (if any)"],apply:["beneficiary.nha.gov.in","Apply at CSC","Separate senior citizen Ayushman card issued"],link:"https://pmjay.gov.in/",helpline:"14555",amt:500000,match:p=>p.age>=70},

{name:"ESI Scheme (Employees' State Insurance)",cat:"insurance",tag:"Insurance",benefit:"Free medical care + cash benefits for workers earning ≤₹21,000/month",desc:"Comprehensive social security: medical care, sickness benefits, maternity benefits, disability benefits, dependant benefits, funeral expenses. For workers in establishments with 10+ employees.",elig:["Employees earning ≤₹21,000/month","In establishments with 10+ employees","Employee contribution: 0.75% of wages","Employer contribution: 3.25% of wages"],docs:["Aadhaar","Employment letter","Bank passbook","Photograph"],apply:["Employer registers on esic.gov.in","Employee enrolled automatically","ESI card issued with unique ID"],link:"https://www.esic.gov.in/",helpline:"1800-11-2526",amt:100000,match:p=>p.employment==="salaried"&&!["above25","10to25","5to10"].includes(p.income)},

// ═══ HOUSING & SANITATION (68-77) ═══
{name:"PM Awas Yojana - Urban (PMAY-U 2.0)",cat:"housing",tag:"Housing",benefit:"₹1-2.5 lakh central assistance for urban housing",desc:"PMAY-U 2.0 launched Sep 2024. ₹10 lakh crore investment target. 1 crore new urban homes. Central assistance ₹1-2.5 lakh for EWS.",elig:["Urban resident","No pucca house in family","EWS: income <₹3L, LIG: ₹3-6L"],docs:["Aadhaar","Income certificate","No-house affidavit","Bank passbook"],apply:["pmaymis.gov.in → Citizen Assessment","OR through ULB/Municipal office","OR through CSC"],link:"https://pmaymis.gov.in/",helpline:"1800-11-6163",amt:267000,match:p=>["urban","semi-urban"].includes(p.area)&&p.ownHouse!=="yes"&&["below1","1to2.5","2.5to5"].includes(p.income)},

{name:"PM Awas Yojana - Gramin (PMAY-G)",cat:"housing",tag:"Housing",benefit:"₹1.20-1.30 lakh for pucca house in rural areas",desc:"₹1.20L (plains) / ₹1.30L (hilly areas) + ₹12K toilet (SBM) + 90 days MGNREGA wages. Total ~₹1.7L. 3.21 crore houses sanctioned.",elig:["Rural household in SECC-2011 list","Houseless or kutcha house dweller","No motorized vehicle, no fridge, no landline"],docs:["Aadhaar","SECC inclusion","Bank passbook","Job card (MGNREGA)"],apply:["Identified from SECC-2011 Permanent Wait List","Gram Sabha approval","Block office issues sanction","3-4 installments via DBT","Track: pmayg.nic.in"],link:"https://pmayg.nic.in/",helpline:"1800-11-6446",amt:130000,match:p=>p.area==="rural"&&(p.ownHouse==="no"||p.ownHouse==="kutcha")&&["below1","1to2.5"].includes(p.income)},

{name:"Swachh Bharat Mission 2.0 - Gramin",cat:"housing",tag:"Housing",benefit:"₹12,000 for toilet construction + ODF Plus villages",desc:"Phase 2 focuses on ODF Plus: solid/liquid waste management, grey water treatment. Individual toilet incentive continues at ₹12,000.",elig:["Households without toilets","Rural areas","BPL/low-income families priority"],docs:["Aadhaar","Bank passbook","Photograph of household"],apply:["Contact Gram Panchayat","Apply for individual toilet construction","₹12,000 released after construction + verification"],link:"https://swachhbharatmission.gov.in/",helpline:"1800-11-0707",amt:12000,match:p=>p.toilet==="no"},

{name:"Swachh Bharat Mission 2.0 - Urban",cat:"housing",tag:"Housing",benefit:"Free community/public toilets + waste management infrastructure",desc:"Urban sanitation: community and public toilets, waste processing plants, remediation of dumpsites. Individual toilet incentive for urban poor.",elig:["Urban households without toilets","Municipal areas"],docs:["Aadhaar","Address proof"],apply:["Contact Municipal Corporation/Municipality","Apply for individual toilet subsidy"],link:"https://sbmurban.org/",helpline:"State ULB helpline",amt:12000,match:p=>p.toilet==="no"&&["urban","semi-urban"].includes(p.area)},

{name:"Jal Jeevan Mission",cat:"housing",tag:"Housing",benefit:"Free piped tap water to every rural household",desc:"Functional Household Tap Connection (FHTC) to every rural household. 55 litres per capita per day. 14.7 crore+ connections provided. Target: 100% coverage.",elig:["Rural households without piped water","Priority: SC/ST, water quality-affected areas","All rural households eventually covered"],docs:["None for individual household — village-level implementation"],apply:["Implemented village by village","Contact Gram Panchayat for status","No individual application needed","Track: ejalshakti.gov.in"],link:"https://jaljeevanmission.gov.in/",helpline:"011-23714825",amt:0,match:p=>p.area==="rural"&&p.special.includes("no-water")},

{name:"PM Ujjwala Yojana 2.0",cat:"housing",tag:"Housing",benefit:"Free LPG connection + 1st refill + stove for BPL women",desc:"Free LPG for BPL women. 10.35 crore connections. Ujjwala 2.0: no address proof needed (self-declaration). Migrant workers eligible.",elig:["Adult woman of BPL household","No existing LPG connection","Ujjwala 2.0: self-declaration accepted"],docs:["Aadhaar","Bank passbook","Self-declaration of address","Photograph"],apply:["Visit nearest LPG distributor (HP/Bharat/Indane)","Fill Ujjwala form","Connection issued in 7-14 days"],link:"https://www.pmuy.gov.in/",helpline:"1800-233-3555",amt:3200,match:p=>p.gender==="female"&&p.special.includes("no-gas")&&["below1","1to2.5"].includes(p.income)},

{name:"Saubhagya (PM Sahaj Bijli Har Ghar Yojana)",cat:"housing",tag:"Housing",benefit:"Free electricity connection for all unelectrified households",desc:"Free electricity connection to all remaining un-electrified households. Includes meter, wiring, LED bulbs. BPL: completely free. APL: ₹500 in 10 installments.",elig:["Household without electricity connection","Priority to BPL families"],docs:["Aadhaar","Address proof"],apply:["Contact local DISCOM/electricity office","Apply for free connection","OR apply at saubhagya.gov.in"],link:"https://saubhagya.gov.in/",helpline:"State DISCOM helpline",amt:5000,match:p=>p.special.includes("no-electricity")},

{name:"SVAMITVA (Property Cards for Rural Land)",cat:"housing",tag:"Housing",benefit:"Free legal property ownership card for rural households using drone mapping",desc:"Drone survey of rural inhabited areas + issuance of legal property cards (Record of Rights). Enables rural homeowners to use property as collateral for bank loans.",elig:["All rural households in abadi (inhabited) areas","Pan-India coverage across all states"],docs:["Aadhaar","Existing land/house documents (if any)"],apply:["Drone survey conducted by Survey of India","Property card delivered to household","No individual application — survey-based"],link:"https://svamitva.nic.in/",helpline:"State revenue department",amt:0,match:p=>p.area==="rural"},

{name:"PM Surya Ghar: Muft Bijli Yojana",cat:"housing",tag:"Housing",benefit:"₹30,000-₹78,000 subsidy for rooftop solar + 300 units free electricity",desc:"Rooftop solar scheme. Subsidy: ₹30,000 for 1kW, ₹60,000 for 2kW, ₹78,000 for 3kW+. Generates 300 units/month free electricity. Target: 1 crore households.",elig:["All residential households in India","Must have suitable rooftop","Grid-connected electricity meter"],docs:["Electricity bill","Aadhaar","Bank passbook","Property ownership proof or NOC"],apply:["pmsuryaghar.gov.in","Register with electricity bill details","Select solar vendor from empanelled list","Subsidy credited to bank after installation"],link:"https://pmsuryaghar.gov.in/",helpline:"1800-180-3333",amt:78000,match:p=>p.ownHouse==="yes"},

{name:"PM KUSUM (Solar Pumps for Farmers)",cat:"agriculture",tag:"Agriculture",benefit:"60-90% subsidy on solar pumps for farmers",desc:"Solar pumps for farmers in 3 components: standalone pumps (60% subsidy), grid-connected (90% subsidy), solarization of existing pumps. Reduces electricity/diesel costs.",elig:["Farmers with existing pump connections or needing new irrigation","Agricultural land ownership or lease"],docs:["Land records","Aadhaar","Existing pump connection details","Bank passbook"],apply:["Apply through state renewable energy agency","mnre.gov.in/kusum","OR through DISCOM"],link:"https://mnre.gov.in/",helpline:"State renewable energy agency",amt:200000,match:p=>p.employment==="farmer"},

// ═══ EMPLOYMENT & SKILLS (78-90) ═══
{name:"MGNREGA",cat:"money",tag:"Money",benefit:"100 days guaranteed employment at ₹267-₹374/day",desc:"Legal right to 100 days work for every rural household. If not provided in 15 days, unemployment allowance due. ~7 crore active workers.",elig:["Any adult in rural household","Willing to do unskilled manual work"],docs:["Job Card from Gram Panchayat","Aadhaar (for wage payment)","Bank passbook"],apply:["Get Job Card from Gram Panchayat","Submit written work demand","Work within 15 days or unemployment allowance","Track: nrega.nic.in"],link:"https://nrega.nic.in/",helpline:"1800-111-555",amt:37400,match:p=>p.area==="rural"&&p.age>=18&&["below1","1to2.5","2.5to5"].includes(p.income)},

{name:"PM Kaushal Vikas Yojana 4.0 (PMKVY)",cat:"education",tag:"Education",benefit:"Free skill training + ₹8,000 reward + certification + placement",desc:"Free training in 40+ sectors (150-300 hrs). NSQF certification. ₹8,000 completion reward. PMKVY 4.0 has industry partnership model.",elig:["Age 15-59","No min education for most courses","Aadhaar mandatory"],docs:["Aadhaar","Any photo ID","Bank passbook"],apply:["pmkvyofficial.org OR skillindia.nsdcindia.org","Find nearest training centre","Enroll and attend training","₹8,000 reward after assessment"],link:"https://www.pmkvyofficial.org/",helpline:"1800-123-9626",amt:8000,match:p=>p.age>=15&&p.age<=59&&(p.employment==="unemployed"||p.needs.includes("skill")||p.needs.includes("employment"))},

{name:"National Apprenticeship Promotion Scheme (NAPS)",cat:"education",tag:"Education",benefit:"₹1,500/month stipend for apprentices + industry training",desc:"Government shares 25% of stipend (max ₹1,500/month) with employers for hiring apprentices. Covers all sectors. Apprenticeship of 6-36 months with on-job training.",elig:["Age 14+ (varies by trade)","Passed 5th-12th standard or ITI","Not currently employed full-time"],docs:["Aadhaar","Educational certificates","Bank passbook"],apply:["Register at apprenticeshipindia.gov.in","Search and apply for apprenticeship openings","OR register through ITI/college placement cell"],link:"https://www.apprenticeshipindia.gov.in/",helpline:"1800-599-0014",amt:18000,match:p=>(p.employment==="student"||p.employment==="unemployed")&&p.age>=14&&p.age<=35},

{name:"PM Daksh Yojana",cat:"education",tag:"Education",benefit:"Free skill training for SC/OBC/Safai Karamchari/DNT",desc:"Free skill training for marginalized communities: SC, OBC, EBC, DNT, Safai Karamcharis. Short-term (200-600 hrs) and long-term training. Stipend during training.",elig:["SC/OBC/EBC/DNT/Safai Karamchari","Age 18-45","Family income below ₹3 lakh (OBC) / ₹1 lakh (SC)"],docs:["Aadhaar","Caste certificate","Income certificate","Bank passbook"],apply:["pmdaksh.dosje.gov.in","Register and search courses near you","Apply online"],link:"https://pmdaksh.dosje.gov.in/",helpline:"011-23381027",amt:8000,match:p=>["sc","st","obc"].includes(p.category)&&(p.employment==="unemployed"||p.needs.includes("skill"))},

{name:"DDU-GKY (Deen Dayal Upadhyaya Grameen Kaushalya Yojana)",cat:"education",tag:"Education",benefit:"Free skill training + placement for rural youth (75%+ placement rate)",desc:"Placement-linked skill training for rural poor youth. Training duration: 3-12 months. Minimum 75% placement rate mandated. Stipend + food + accommodation during training.",elig:["Rural youth aged 15-35","From BPL/NFSA/MGNREGA/RSBY families","SC/ST/Women: age up to 45"],docs:["Aadhaar","BPL card / MGNREGA job card","Educational certificates","Bank passbook"],apply:["ddugky.gov.in","Contact block/district rural development office","Enroll through empanelled training partner"],link:"https://ddugky.gov.in/",helpline:"State SRLM helpline",amt:10000,match:p=>p.area==="rural"&&(p.employment==="unemployed"||p.needs.includes("employment"))&&p.age>=15&&p.age<=35},

{name:"PM Rojgar Protsahan Yojana (PMRPY)",cat:"money",tag:"Money",benefit:"Government pays EPF (12%) + EPS (12%) for new employees for 3 years",desc:"Government contributes employer's full EPF+EPS contribution for new employees earning below ₹15,000/month for 3 years. Incentivizes formal employment creation.",elig:["Employers registered with EPFO","New employees with salary ≤₹15,000","Must have Aadhaar and bank account","Must not have been EPF member before"],docs:["Employer: EPFO registration","Employee: Aadhaar, bank passbook","UAN number"],apply:["Employer claims through EPFO portal","shramsuvidha.gov.in","Employee benefits automatically"],link:"https://pmrpy.gov.in/",helpline:"1800-118-005",amt:0,match:p=>p.employment==="salaried"&&!["above25","10to25","5to10"].includes(p.income)},

{name:"National Career Service Portal (NCS)",cat:"money",tag:"Money",benefit:"Free job matching + career counselling + government job alerts",desc:"Government job portal with 1.2 crore+ registered job seekers and 50 lakh+ employers. Free job matching, career counselling, skill assessment. Links to PMKVY, apprenticeship.",elig:["Any Indian citizen seeking employment","Job seekers, employers, career counsellors"],docs:["Aadhaar","Educational certificates"],apply:["Register at ncs.gov.in","Build profile","Search and apply for jobs","Get career counselling"],link:"https://www.ncs.gov.in/",helpline:"1800-425-1514",amt:0,match:p=>p.employment==="unemployed"||p.needs.includes("employment")},

{name:"PM YUVA (Young, Upcoming and Versatile Authors)",cat:"education",tag:"Education",benefit:"₹50,000/month scholarship for 6 months for aspiring writers",desc:"Mentorship programme for young authors below 30. Selected authors get ₹50,000/month for 6 months. Published work gets promoted by National Book Trust.",elig:["Indian citizen below 30 years","Aspiring writers in any Indian language","Submit writing sample through portal"],docs:["Aadhaar","Writing samples","Educational certificates"],apply:["innovateindia.mygov.in/yuva (when open)","Submit writing sample","Selected by jury for mentorship"],link:"https://innovateindia.mygov.in/",helpline:"MyGov helpline",amt:300000,match:p=>p.age<=30&&p.employment==="student"},

{name:"PM Internship Scheme (Budget 2024)",cat:"education",tag:"Education",benefit:"₹5,000/month stipend + ₹6,000 one-time for internship in top 500 companies",desc:"1 crore internships in top 500 companies over 5 years. ₹5,000/month stipend (₹4,500 govt + ₹500 company CSR). ₹6,000 one-time assistance. 12-month internships.",elig:["Youth aged 21-24 years","Not from families where any member is a govt employee","Not from families where any member is income taxpayer","From families with income below ₹8 lakh"],docs:["Aadhaar","Educational certificates","Income proof","Bank passbook"],apply:["pminternship.mca.gov.in (when launched)","Register and apply for available positions","Matched with companies based on skills"],link:"https://pminternship.mca.gov.in/",helpline:"To be announced",amt:66000,match:p=>p.age>=21&&p.age<=24&&!["above25","10to25"].includes(p.income)&&(p.employment==="unemployed"||p.employment==="student")},

{name:"Startup India Seed Fund Scheme",cat:"business",tag:"Business",benefit:"₹20 lakh grant + ₹50 lakh loan for early-stage startups",desc:"Seed funding for early-stage startups through incubators. ₹20 lakh as grant for idea validation/POC. ₹50 lakh as debt/convertible for market entry.",elig:["DPIIT recognized startup","Incorporated ≤2 years ago","Not received ₹10 lakh+ govt funding","Working on innovative idea"],docs:["DPIIT recognition certificate","Business plan","Incorporation certificate","Founder KYC"],apply:["seedfund.startupindia.gov.in","Apply through an approved incubator","Incubator evaluates and recommends","Fund disbursed through incubator"],link:"https://seedfund.startupindia.gov.in/",helpline:"1800-115-565",amt:5000000,match:p=>p.bizType==="startup"},

// ═══ EDUCATION & SCHOLARSHIPS (91-100) ═══
{name:"National Scholarship Portal (NSP) — 100+ Scholarships",cat:"education",tag:"Education",benefit:"₹12,000-₹3,00,000/year scholarships for SC/ST/OBC/Minority/EWS/Merit",desc:"One-stop portal for 100+ central and state scholarships. Pre-matric, post-matric, merit, minority, disability scholarships. 2.5 crore+ students benefit annually.",elig:["Students from SC/ST/OBC/Minority/EWS/PwD/General merit","Income limits vary: ₹2L-₹8L by scheme","Minimum 50-60% marks in previous exam"],docs:["Aadhaar","Income certificate","Caste/community certificate","Previous marksheet","College bonafide","Bank passbook (student's name)","Disability certificate (if applicable)"],apply:["scholarships.gov.in → New Registration","Select applicable scholarship","Fill and submit with documents","Institute and district verify","DBT to bank account","Deadline: Usually Aug-Nov each year"],link:"https://scholarships.gov.in/",helpline:"0120-6619540",amt:300000,match:p=>(p.employment==="student"||p.needs.includes("education"))&&!["above25","10to25"].includes(p.income)},

{name:"PM YASASVI Scholarship (OBC/EBC/DNT)",cat:"education",tag:"Education",benefit:"₹75,000-₹1,25,000/year for OBC/EBC/DNT students (Class 9-12 and UG)",desc:"Vibrant India Scholarship for OBC, EBC, and DNT students. Top-class education in identified schools/colleges. ₹75,000 (Class 9-10) to ₹1,25,000 (Class 11-12).",elig:["OBC/EBC/DNT students","Class 9-12 or UG level","Family income below ₹2.5 lakh","Studying in listed schools/colleges"],docs:["Aadhaar","OBC/EBC/DNT certificate","Income certificate","Marksheet","Admission letter"],apply:["yet.nta.ac.in (exam-based selection)","Write YASASVI entrance test","Merit-based selection"],link:"https://yet.nta.ac.in/",helpline:"011-40759000",amt:125000,match:p=>["obc"].includes(p.category)&&(p.employment==="student"||p.needs.includes("education"))},

{name:"Post-Matric Scholarship for SC Students",cat:"education",tag:"Education",benefit:"Full tuition + ₹3,000-₹13,000/month maintenance for SC students",desc:"Comprehensive financial support for SC students in post-matric education. Covers tuition, maintenance, books, exam fees. ₹59,048 crore budget for 5 years.",elig:["SC category student","Post-matric education (Class 11 to PhD)","Family income below ₹2.5 lakh"],docs:["Caste certificate","Income certificate","Aadhaar","Marksheet","College admission proof","Bank passbook"],apply:["scholarships.gov.in","OR state scholarship portal","Apply within deadline (Aug-Nov)"],link:"https://scholarships.gov.in/",helpline:"State social welfare dept",amt:200000,match:p=>p.category==="sc"&&(p.employment==="student"||p.needs.includes("education"))},

{name:"Post-Matric Scholarship for ST Students",cat:"education",tag:"Education",benefit:"Full tuition + maintenance allowance for ST students",desc:"Similar to SC scholarship but for Scheduled Tribe students. Covers all post-matric courses including professional degrees.",elig:["ST category student","Post-matric education","Family income below ₹2.5 lakh"],docs:["ST certificate","Income certificate","Aadhaar","Marksheet","Admission proof"],apply:["scholarships.gov.in","State tribal welfare department"],link:"https://scholarships.gov.in/",helpline:"State tribal welfare dept",amt:200000,match:p=>p.category==="st"&&(p.employment==="student"||p.needs.includes("education"))},

{name:"Pre-Matric Scholarship for Minorities",cat:"education",tag:"Education",benefit:"₹5,700-₹11,100/year for minority students (Class 1-10)",desc:"Scholarship for Muslim, Christian, Sikh, Buddhist, Jain, Parsi students in Class 1-10. Maintenance and admission fee support.",elig:["Minority community student","Class 1-10","Family income below ₹1 lakh","Min 50% marks in previous exam"],docs:["Minority community declaration","Income certificate","Aadhaar","Marksheet","School bonafide"],apply:["scholarships.gov.in → Pre-Matric Minority","Apply within deadline","DBT to bank account"],link:"https://scholarships.gov.in/",helpline:"0120-6619540",amt:11100,match:p=>p.category==="minority"&&(p.employment==="student"||p.needs.includes("education"))},

{name:"Begum Hazrat Mahal Scholarship for Minority Girls",cat:"education",tag:"Education",benefit:"₹5,000-₹6,000/year for minority girl students (Class 9-12)",desc:"Maulana Azad Education Foundation scholarship specifically for minority girl students in Classes 9-12. For meritorious students from economically weak families.",elig:["Minority girl student","Class 9-12","Family income below ₹2 lakh","Min 50% marks"],docs:["Minority certificate","Income certificate","Aadhaar","Marksheet","School bonafide"],apply:["maef.nic.in","Apply online during application window","Verified by school and state"],link:"https://maef.nic.in/",helpline:"011-23583788",amt:6000,match:p=>p.gender==="female"&&p.category==="minority"&&p.employment==="student"},

{name:"AICTE Pragati Scholarship (Women in Tech)",cat:"education",tag:"Education",benefit:"₹50,000/year for women in AICTE-approved technical courses",desc:"For women pursuing degree/diploma in AICTE-approved institutions. ₹50,000/year (₹30,000 tuition + ₹20,000 books/equipment). Max 2 girl children per family.",elig:["Women pursuing technical degree/diploma","AICTE-approved institution","Family income below ₹8 lakh","Max 2 girls per family"],docs:["Aadhaar","Income certificate","AICTE approval of institution","Admission proof","Marksheet"],apply:["aicte-pragati-saksham-gov.in","Apply online during application window","Institute verifies and forwards"],link:"https://www.aicte-india.org/",helpline:"011-26131576",amt:50000,match:p=>p.gender==="female"&&p.employment==="student"&&p.needs.includes("education")},

{name:"AICTE Saksham Scholarship (PwD in Tech)",cat:"education",tag:"Education",benefit:"₹50,000/year for PwD students in AICTE-approved courses",desc:"For Persons with Disabilities pursuing technical education. Same amount as Pragati: ₹50,000/year.",elig:["PwD student (40%+ disability)","AICTE-approved institution","Family income below ₹8 lakh"],docs:["Disability certificate","Aadhaar","Income certificate","Admission proof"],apply:["aicte-pragati-saksham-gov.in","Apply online"],link:"https://www.aicte-india.org/",helpline:"011-26131576",amt:50000,match:p=>p.lifeStage.includes("disabled")&&p.employment==="student"},

{name:"Ishan Uday Scholarship (North-East Students)",cat:"education",tag:"Education",benefit:"₹5,400/month for NE students pursuing higher education outside NE",desc:"UGC scholarship for students from North-Eastern states studying outside NE. ₹5,400/month for general courses, ₹7,800 for professional/technical.",elig:["Domicile of NE states (Assam, Arunachal, Manipur, Meghalaya, Mizoram, Nagaland, Sikkim, Tripura)","Family income below ₹4.5 lakh","Studying outside NE in UGC-recognized institution"],docs:["Domicile certificate","Income certificate","Aadhaar","Admission proof"],apply:["scholarships.gov.in","Apply during UGC scholarship window"],link:"https://scholarships.gov.in/",helpline:"011-23604446",amt:93600,match:p=>p.employment==="student"&&["Assam","Arunachal Pradesh","Manipur","Meghalaya","Mizoram","Nagaland","Sikkim","Tripura"].includes(p.state)},

{name:"Central Sector Scheme of Scholarship (CSSS)",cat:"education",tag:"Education",benefit:"₹10,000-₹20,000/year merit-based scholarship (top 20 percentile, Class 12)",desc:"Merit-cum-means scholarship for students in top 20 percentile of Class 12 board exams. ₹10,000/year for UG first 3 years, ₹20,000 for PG. No category restriction.",elig:["Top 20 percentile in Class 12 board exam","Family income below ₹8 lakh","Pursuing regular degree in recognized institution","NOT professional degree (separate schemes exist)"],docs:["Class 12 marksheet","Income certificate","Aadhaar","College admission proof","Bank passbook"],apply:["scholarships.gov.in → Central Schemes → CSSS","Apply within deadline (usually Oct-Nov)","Verified by institution and state"],link:"https://scholarships.gov.in/",helpline:"0120-6619540",amt:20000,match:p=>p.employment==="student"&&!["above25","10to25"].includes(p.income)},
];

if(typeof module!=='undefined')module.exports={CENTRAL_SCHEMES_1};
