// Central Schemes Part 4 — Popular Missing Central Schemes (80)
export const CENTRAL_SCHEMES_4 = [
{name:"PM Surya Ghar: Muft Bijli Yojana",cat:"housing",tag:"Energy",benefit:"300 units free electricity/month via rooftop solar",desc:"Launched Feb 2024. Subsidizes rooftop solar panels for 1 crore households. Saves ₹15,000-₹18,000/year on electricity bills.",elig:["Indian citizen owning a house","Grid-connected electricity consumer","Roof suitable for solar panels"],docs:["Aadhaar","Electricity bill","Bank passbook","House ownership proof"],apply:["Apply at pmsuryaghar.gov.in","Select DISCOM & apply online","After approval, install via empanelled vendor"],link:"https://pmsuryaghar.gov.in/",helpline:"1800-180-3333",amt:78000,match:p=>p.ownHouse==="yes"},

{name:"PM Vishwakarma Yojana",cat:"employment",tag:"Business",benefit:"₹15,000 toolkit + ₹3L loan at 5% interest",desc:"Launched Sep 2023 for traditional artisans/craftspeople in 18 trades. Free skill training, toolkit, credit access, and digital marketing support.",elig:["Traditional artisans & craftspeople","18 trades: carpenter, blacksmith, goldsmith, potter, tailor, weaver, etc.","Age 18+","Self-employed, not in govt service"],docs:["Aadhaar","Bank passbook","Caste not mandatory","Skill verification by Gram Panchayat"],apply:["Register at pmvishwakarma.gov.in","Verify identity at CSC","Training → Toolkit → Credit"],link:"https://pmvishwakarma.gov.in/",helpline:"1800-267-6888",amt:315000,match:p=>["self-employed","business"].includes(p.employment)},

{name:"Mahatma Gandhi NREGA (MGNREGA)",cat:"employment",tag:"Employment",benefit:"100 days guaranteed wage employment per household/year",desc:"World's largest work guarantee programme. Provides unskilled manual work at ₹267-₹374/day (state-wise). Enhanced to 125 days from 2025.",elig:["Rural household members","Age 18+","Willing to do unskilled manual work","Must have job card"],docs:["Job Card (issued free)","Aadhaar","Bank/Post Office account"],apply:["Apply to Gram Panchayat for job card","Demand work in writing","Work within 15 days or get unemployment allowance"],link:"https://nrega.nic.in/",helpline:"1800-111-555",amt:37400,match:p=>p.area==="rural"&&["unemployed","farmer"].includes(p.employment)},

{name:"PM-KISAN Samman Nidhi",cat:"agriculture",tag:"Agriculture",benefit:"₹6,000/year in 3 installments to farmers",desc:"Direct income support to 11+ crore farmer families. ₹2,000 every 4 months via DBT. One of India's most popular schemes.",elig:["All landholding farmer families","Excludes: institutional landholders, income tax payers, govt employees","Both small and large farmers eligible"],docs:["Aadhaar","Land records","Bank passbook"],apply:["Apply at pmkisan.gov.in","Or through CSC/State agriculture dept","e-KYC mandatory"],link:"https://pmkisan.gov.in/",helpline:"155261",amt:6000,match:p=>p.employment==="farmer"},

{name:"Pradhan Mantri Mudra Yojana (PMMY)",cat:"employment",tag:"Business",benefit:"Loans up to ₹10 lakh without collateral",desc:"Micro finance for non-corporate small businesses. 3 categories: Shishu (₹50K), Kishore (₹5L), Tarun (₹10L). 36.9 crore loans disbursed.",elig:["Any Indian citizen with business plan","Non-farm income generating activity","Micro/small enterprise","No collateral needed for Shishu loans"],docs:["Aadhaar & PAN","Business plan","Identity & address proof","Last 6 months bank statement"],apply:["Approach any bank/NBFC/MFI","Apply via udyamimitra.in","Shishu: up to ₹50K, Kishore: ₹50K-5L, Tarun: ₹5L-10L"],link:"https://www.mudra.org.in/",helpline:"1800-180-1111",amt:1000000,match:p=>["self-employed","business"].includes(p.employment)||p.bizType!=="none"},

{name:"PM Awas Yojana - Urban 2.0 (PMAY-U)",cat:"housing",tag:"Housing",benefit:"₹2.5L subsidy for house construction/purchase",desc:"Housing for All urban. Interest subsidy on home loans for EWS/LIG/MIG. Covers new construction, enhancement, rental housing.",elig:["EWS: income up to ₹3L/yr","LIG: ₹3-6L/yr","MIG-I: ₹6-12L/yr, MIG-II: ₹12-18L/yr","Should not own pucca house anywhere in India"],docs:["Aadhaar","Income certificate","No-property certificate","Bank loan documents"],apply:["Apply at pmaymis.gov.in","Through CSC or ULB office","Apply through partner banks for CLSS"],link:"https://pmaymis.gov.in/",helpline:"1800-11-6446",amt:250000,match:p=>p.area==="urban"&&p.ownHouse!=="yes"&&["below1","1to2.5","2.5to5"].includes(p.income)},

{name:"PM Awas Yojana - Gramin (PMAY-G)",cat:"housing",tag:"Housing",benefit:"₹1.2L (plain) / ₹1.3L (hilly) for house construction",desc:"Houses for rural homeless. 130+ sq ft with kitchen, toilet. Converges with MGNREGA for 90 days wage. 3.21 crore houses built.",elig:["Houseless or living in kutcha/dilapidated house","Selected from SECC-2011 data","Verified by Gram Sabha","Rural resident"],docs:["Aadhaar","SECC data inclusion","Bank account","Land documents (if available)"],apply:["Identified from SECC-2011","Gram Sabha verification","Apply through Gram Panchayat","Fund transfer via DBT"],link:"https://pmayg.nic.in/",helpline:"1800-11-6446",amt:130000,match:p=>p.area==="rural"&&p.ownHouse!=="yes"&&["below1","1to2.5"].includes(p.income)},

{name:"Jal Jeevan Mission (Har Ghar Jal)",cat:"water",tag:"Water",benefit:"Tap water connection to every rural household",desc:"₹3.6 lakh crore mission to provide functional tap water to all 19.3 crore rural households by 2024. 15+ crore connections completed.",elig:["All rural households","Priority: SC/ST hamlets, quality-affected areas","No income restriction"],docs:["No documents needed for household","Gram Panchayat manages implementation"],apply:["Implemented through Gram Panchayat","No application needed","Village Water & Sanitation Committee oversees"],link:"https://jaljeevanmission.gov.in/",helpline:"1800-180-2345",amt:0,match:p=>p.area==="rural"&&p.special.includes("no-water")},

{name:"Swachh Bharat Mission - Gramin 2.0",cat:"sanitation",tag:"Sanitation",benefit:"₹12,000 for individual household toilet + ODF Plus",desc:"Phase 2 focuses on ODF sustainability, solid/liquid waste management. Free toilet construction for eligible households.",elig:["Rural households without toilet","BPL/SC/ST/small & marginal farmers","Women-headed households priority"],docs:["Aadhaar","BPL certificate (if applicable)","Bank passbook"],apply:["Apply to Gram Panchayat","Block Development Officer processes","Geo-tagged verification after construction"],link:"https://swachhbharatmission.gov.in/",helpline:"1969",amt:12000,match:p=>p.area==="rural"&&p.toilet==="no"},

{name:"Sukanya Samriddhi Yojana (SSY)",cat:"finance",tag:"Savings",benefit:"8.2% interest rate, tax-free maturity",desc:"Girl child savings scheme. ₹250 to ₹1.5L/yr deposit. Matures at 21 or marriage after 18. Tax benefits under 80C.",elig:["Girl child below 10 years","Maximum 2 accounts (1 per girl)","Parent/guardian opens account","Indian resident"],docs:["Birth certificate of girl child","Parent's Aadhaar & PAN","Address proof"],apply:["Open at any post office or authorized bank","Minimum ₹250 deposit","Annual minimum deposit required"],link:"https://www.indiapost.gov.in/",helpline:"1800-266-6868",amt:0,match:p=>p.lifeStage.includes("children")&&p.gender==="female"},

{name:"PM Jan Dhan Yojana (PMJDY)",cat:"finance",tag:"Banking",benefit:"Zero balance bank account + ₹2L accident insurance + ₹30K life cover",desc:"Financial inclusion scheme. 52+ crore accounts opened. RuPay debit card, ₹10,000 overdraft facility for eligible accounts.",elig:["Any Indian citizen","Age 10+ can open independently","No minimum balance required"],docs:["Aadhaar (if no documents, self-certification)","1 passport photo"],apply:["Visit any bank branch","Apply online through bank websites","Camp-based account opening in villages"],link:"https://pmjdy.gov.in/",helpline:"1800-11-0001",amt:200000,match:p=>p.bankAccount!=="yes"},

{name:"Atal Pension Yojana (APY)",cat:"finance",tag:"Pension",benefit:"₹1,000-₹5,000/month guaranteed pension after 60",desc:"Pension for unorganized sector. Govt co-contributes 50% for 5 yrs for eligible. Monthly contribution ₹42-₹1,454 based on age & pension amount.",elig:["Age 18-40 years","Must have bank account with Aadhaar","Not income tax payer","Not member of any statutory social security scheme"],docs:["Aadhaar","Bank account","Nominee details"],apply:["Apply through bank where savings account is held","Auto-debit from savings account","Net banking / mobile banking application"],link:"https://www.npscra.nsdl.co.in/",helpline:"1800-110-708",amt:60000,match:p=>p.age>=18&&p.age<=40&&!["salaried"].includes(p.employment)},

{name:"PM Jeevan Jyoti Bima Yojana (PMJJBY)",cat:"finance",tag:"Insurance",benefit:"₹2 lakh life insurance at ₹436/year",desc:"Cheapest life insurance. ₹2L on death from any cause. Annual premium auto-debited from bank account. Renewable yearly.",elig:["Age 18-50 years","Must have bank account","Aadhaar linked to bank account"],docs:["Aadhaar","Bank account","Nominee declaration"],apply:["Apply through bank branch","Auto-enroll via net banking","One-page form at bank"],link:"https://jansuraksha.gov.in/",helpline:"1800-180-1111",amt:200000,match:p=>p.age>=18&&p.age<=50},

{name:"PM Suraksha Bima Yojana (PMSBY)",cat:"finance",tag:"Insurance",benefit:"₹2 lakh accidental insurance at ₹20/year",desc:"World's cheapest accident insurance. ₹2L for accidental death, ₹1L for partial disability. Auto-renewed yearly.",elig:["Age 18-70 years","Active bank account","One policy per person per bank"],docs:["Aadhaar","Bank account","Nominee declaration"],apply:["Apply through bank branch","SMS/Net banking enrollment","Single form submission"],link:"https://jansuraksha.gov.in/",helpline:"1800-180-1111",amt:200000,match:p=>p.age>=18&&p.age<=70},

{name:"National Pension System (NPS)",cat:"finance",tag:"Pension",benefit:"Market-linked pension with tax benefits up to ₹2L",desc:"Voluntary retirement savings. Additional ₹50K tax deduction under 80CCD(1B). Partial withdrawal allowed. Government contributes for Govt employees.",elig:["Indian citizen age 18-70","NRI also eligible","Both salaried and self-employed"],docs:["PAN Card","Aadhaar","Address proof","Bank account"],apply:["Open online at enps.nsdl.com","Through Point of Presence (PoP)","Minimum ₹500/year for Tier I"],link:"https://www.npscra.nsdl.co.in/",helpline:"1800-222-080",amt:0,match:p=>p.age>=18&&p.age<=70&&p.employment!=="unemployed"},

{name:"Pradhan Mantri Kaushal Vikas Yojana 4.0 (PMKVY)",cat:"education",tag:"Skill",benefit:"Free skill training + ₹8,000 reward + certification",desc:"Flagship skill development scheme. 700+ job roles. Industry-relevant training by certified trainers. Placement support post-training.",elig:["Age 15-45","Indian citizen","School/college dropouts, unemployed youth","No educational qualification for many courses"],docs:["Aadhaar","Education certificates (if any)","Bank passbook","Passport photo"],apply:["Register at skillindia.gov.in","Enroll at nearest PMKVY Training Centre","Free training + certification"],link:"https://pmkvyofficial.org/",helpline:"1800-123-9626",amt:8000,match:p=>["student","unemployed"].includes(p.employment)||p.age<=35},

{name:"PM Internship Scheme",cat:"education",tag:"Skill",benefit:"₹5,000/month stipend + ₹6,000 one-time grant",desc:"Launched Oct 2024. 12-month internship with top 500 companies. 1 crore internships over 5 years. Practical industry exposure.",elig:["Age 21-24 years","Not employed full-time","Not enrolled in full-time education","Family income below ₹8L/year"],docs:["Aadhaar","Educational certificates","Income certificate","Bank passbook"],apply:["Apply at pminternship.mca.gov.in","Select companies & roles","Company shortlists candidates"],link:"https://pminternship.mca.gov.in/",helpline:"1800-267-6888",amt:66000,match:p=>p.age>=21&&p.age<=24&&p.employment==="unemployed"},

{name:"National Education Policy - Samagra Shiksha",cat:"education",tag:"Education",benefit:"Free education support: textbooks, uniforms, transport",desc:"Integrated scheme for school education pre-primary to class 12. ₹1,500/child for KGBVs, ₹600/child for uniforms, free textbooks.",elig:["All students in government schools","Pre-primary to Class 12","Priority: girls, SC/ST, CWSN, minority"],docs:["School enrollment","Aadhaar (optional)"],apply:["Automatic through government school enrollment","No separate application needed"],link:"https://samagra.education.gov.in/",helpline:"State education department",amt:0,match:p=>p.lifeStage.includes("children")||p.employment==="student"},

{name:"PM POSHAN (Mid-Day Meal Scheme)",cat:"health",tag:"Nutrition",benefit:"Free cooked meal to 11.8 crore school children daily",desc:"Renamed from Mid-Day Meal. Nutritious lunch for govt school students. Includes supplementary nutrition, health check-ups.",elig:["Students of government & govt-aided schools","Classes 1 to 8","Pre-primary in some states"],docs:["No documents needed","School enrollment sufficient"],apply:["Automatic for enrolled govt school students","No separate application"],link:"https://pmposhan.education.gov.in/",helpline:"State education department",amt:0,match:p=>p.lifeStage.includes("children")},

{name:"National Food Security Act (NFSA) / Ration",cat:"health",tag:"Food",benefit:"5 kg rice/wheat per person per month at ₹1-3/kg",desc:"Covers 81.35 crore people. Antyodaya (35 kg/family) & Priority households. Now free grains under PM Garib Kalyan Anna Yojana.",elig:["BPL families as per state list","Antyodaya: poorest of poor","Priority Household: based on SECC-2011/state criteria"],docs:["Ration Card (AAY/PHH)","Aadhaar for eKYC","Family details"],apply:["Apply at state food department","Apply through ration card portal","epds.nic.in for status check"],link:"https://nfsa.gov.in/",helpline:"1800-180-4567",amt:0,match:p=>["below1","1to2.5"].includes(p.income)},

{name:"PM Ujjwala Yojana 2.0",cat:"health",tag:"Energy",benefit:"Free LPG connection + first refill + stove",desc:"8+ crore free LPG connections to BPL women. Ujjwala 2.0 simplified with minimal documents. ₹200 subsidy per refill.",elig:["Adult woman from BPL household","No existing LPG connection in household","ID proof sufficient, BPL list not mandatory in 2.0"],docs:["Aadhaar or self-declaration","Ration card (optional)","Bank passbook"],apply:["Apply at nearest LPG distributor","Carry Aadhaar + bank passbook","Connection installed within 15 days"],link:"https://pmuy.gov.in/",helpline:"1800-266-6696",amt:1600,match:p=>p.gender==="female"&&p.special.includes("no-gas")&&["below1","1to2.5"].includes(p.income)},

{name:"Saubhagya (PM Sahaj Bijli Har Ghar)",cat:"housing",tag:"Energy",benefit:"Free electricity connection to all unconnected households",desc:"Free last-mile connectivity for 2.86 crore households. Solar power pack for remote areas. All equipment free for BPL families.",elig:["Households without electricity connection","Priority: BPL, remote/tribal areas","Both rural and urban"],docs:["Any identity proof","BPL card (for free connection)"],apply:["Apply at local electricity office","Or contact Gram Panchayat","Online via DISCOM website"],link:"https://saubhagya.gov.in/",helpline:"State DISCOM helpline",amt:0,match:p=>["below1","1to2.5"].includes(p.income)},

{name:"Deendayal Antyodaya - National Urban Livelihoods Mission (DAY-NULM)",cat:"employment",tag:"Employment",benefit:"SHG formation + ₹10L group loan + skill training",desc:"Urban poverty alleviation. Self-employment programme, SHG bank linkage, skill training for urban poor. Shelters for urban homeless.",elig:["Urban poor & vulnerable","Street vendors","Urban homeless","Women SHGs"],docs:["Aadhaar","Income certificate","Address proof","Bank account"],apply:["Through City/Urban Local Body","Apply at NULM office","SHG formation through ALF"],link:"https://nulm.gov.in/",helpline:"1800-180-5555",amt:1000000,match:p=>p.area==="urban"&&["below1","1to2.5","2.5to5"].includes(p.income)},

{name:"Deendayal Antyodaya - National Rural Livelihoods Mission (DAY-NRLM)",cat:"employment",tag:"Employment",benefit:"SHG bank linkage + ₹15L revolving fund + skill training",desc:"Mobilizes rural poor women into SHGs. 90 lakh SHGs formed. Community enterprise development, skill training, placement.",elig:["Rural poor women","One woman per household","Priority to BPL, SC/ST, minority, PwD households"],docs:["Aadhaar","BPL/Ration card","Bank account"],apply:["Contact Block office / NRLM State office","SHG formation by community organizers","Bank linkage after 6 months of active SHG"],link:"https://nrlm.gov.in/",helpline:"1800-180-5555",amt:0,match:p=>p.gender==="female"&&p.area==="rural"&&["below1","1to2.5","2.5to5"].includes(p.income)},

{name:"PM SVANidhi (Street Vendor's AtmaNirbhar Nidhi)",cat:"employment",tag:"Business",benefit:"₹10,000-₹50,000 working capital loan without collateral",desc:"Micro-credit for street vendors affected by COVID. ₹10K→₹20K→₹50K in 3 tranches. Interest subsidy of 7%. Digital payments incentive.",elig:["Street vendors with certificate of vending","Or identified in municipal survey","Operational on or before March 24, 2020"],docs:["Aadhaar","Certificate of Vending / Letter of Recommendation","Bank account"],apply:["Apply at pmsvanidhi.mohua.gov.in","Through bank/NBFC/MFI branch","Or through CSC/ULB"],link:"https://pmsvanidhi.mohua.gov.in/",helpline:"1800-11-6005",amt:50000,match:p=>p.bizType==="vendor"},

{name:"Stand Up India Scheme",cat:"employment",tag:"Business",benefit:"₹10L to ₹1 crore loan for SC/ST/Women entrepreneurs",desc:"Promotes entrepreneurship among SC, ST & women. Bank loan between ₹10L-₹1Cr for greenfield enterprise. Composite loan for mfg/services/trading.",elig:["SC or ST entrepreneur","OR Women entrepreneur (any caste)","Age 18+","Greenfield enterprise (new project)"],docs:["Aadhaar & PAN","Caste certificate (for SC/ST)","Business plan","Quotation for plant & machinery"],apply:["Apply at standupmitra.in","Through any scheduled commercial bank branch","1-2 loans per branch per category"],link:"https://www.standupmitra.in/",helpline:"1800-180-1111",amt:10000000,match:p=>(p.category==="sc"||p.category==="st"||p.gender==="female")&&p.bizType!=="none"},

{name:"PM Employment Generation Programme (PMEGP)",cat:"employment",tag:"Business",benefit:"15-35% subsidy on projects up to ₹50L (mfg) / ₹20L (service)",desc:"Credit-linked subsidy for micro enterprises. Generates 8+ lakh jobs/year. Higher subsidy for rural, women, SC/ST. KVIC, KVIB, DIC implement.",elig:["Age 18+, any Indian citizen","Educational: 8th pass for projects above ₹10L","Existing units (under PMEGP upgrading) also eligible","Self-employed / new entrepreneur"],docs:["Aadhaar","Educational certificate","Project report","Caste/special category certificate"],apply:["Apply online at kviconline.gov.in","Select location & project","Bank processes the loan application"],link:"https://www.kviconline.gov.in/pmegp/",helpline:"1800-180-6763",amt:5000000,match:p=>p.bizType!=="none"||["self-employed","business"].includes(p.employment)},

{name:"Startup India Seed Fund Scheme (SISFS)",cat:"employment",tag:"Startup",benefit:"Up to ₹50 lakh for proof of concept, prototype, market entry",desc:"Financial support to early-stage startups. Selected through incubators. Grant up to ₹20L for validation, ₹50L for market launch.",elig:["DPIIT-recognized startup","Incorporated not more than 2 years ago","Not received >₹10L under any central/state scheme","Innovative & scalable business idea"],docs:["DPIIT recognition certificate","Incorporation certificate","Business plan","Bank account"],apply:["Apply at seedfund.startupindia.gov.in","Through selected incubators","Incubator evaluates & disburses"],link:"https://seedfund.startupindia.gov.in/",helpline:"1800-115-565",amt:5000000,match:p=>p.bizType==="startup"},

{name:"PM Fasal Bima Yojana (PMFBY)",cat:"agriculture",tag:"Insurance",benefit:"Crop insurance at 1.5-5% premium, full claim payout",desc:"Crop insurance against natural calamities. Govt pays remaining premium. 6.39 crore farmers enrolled. Covers sowing to post-harvest.",elig:["All farmers: loanee & non-loanee","Sharecroppers & tenant farmers eligible","Notified crops in notified areas"],docs:["Aadhaar","Land records / tenancy agreement","Bank passbook","Sowing certificate"],apply:["Through bank at time of crop loan","Or apply at pmfby.gov.in","CSC online enrollment"],link:"https://pmfby.gov.in/",helpline:"1800-180-1551",amt:0,match:p=>p.employment==="farmer"},

{name:"Kisan Credit Card (KCC)",cat:"agriculture",tag:"Agriculture",benefit:"₹3L crop loan at 4% interest (after subsidy)",desc:"Instant credit for crop production, post-harvest, consumption. Interest subvention: 7%→4% for timely repayment. Also covers fishery & animal husbandry.",elig:["All farmers: owner cultivators, tenant farmers, sharecroppers","Also for animal husbandry & fisheries","Crop loan limit based on land holding"],docs:["Aadhaar","Land records","Passport photo","Existing crop loan details"],apply:["Apply at any commercial/cooperative/RRB bank","Single window at bank branch","Limit set by bank based on land & crop"],link:"https://pmkisan.gov.in/",helpline:"155261",amt:300000,match:p=>p.employment==="farmer"},

{name:"Soil Health Card Scheme",cat:"agriculture",tag:"Agriculture",benefit:"Free soil testing + fertilizer recommendations",desc:"12+ crore soil health cards distributed. Tests 12 parameters with crop-wise fertilizer recommendations. Improves yields 10-15%.",elig:["All farmers","No restrictions","Free service"],docs:["Farm location details"],apply:["Contact nearest Krishi Vigyan Kendra","Apply through agriculture department","Soil Health Card portal"],link:"https://soilhealth.dac.gov.in/",helpline:"State agriculture department",amt:0,match:p=>p.employment==="farmer"},

{name:"PM Krishi Sinchayee Yojana (PMKSY)",cat:"agriculture",tag:"Agriculture",benefit:"55-75% subsidy on micro/drip irrigation",desc:"Per Drop More Crop. Subsidy on drip/sprinkler irrigation. 55% for general, 75% for small/marginal/SC/ST farmers.",elig:["All farmers with cultivable land","Priority: water-scarce areas","Micro irrigation on horticulture crops"],docs:["Land records","Aadhaar","Bank passbook","Quotation from supplier"],apply:["Apply at state agriculture/horticulture dept","Online portal in some states","Block agriculture officer processes"],link:"https://pmksy.gov.in/",helpline:"State agriculture department",amt:0,match:p=>p.employment==="farmer"},

{name:"e-NAM (National Agriculture Market)",cat:"agriculture",tag:"Agriculture",benefit:"Online transparent trading platform for farm produce",desc:"1,389 mandis connected. Farmers sell produce online to traders across India. Better price discovery, reduced middlemen.",elig:["All farmers with produce to sell","Registered at local mandi/APMC","FPOs and cooperatives"],docs:["Aadhaar","Bank passbook","Mandi registration"],apply:["Register at enam.gov.in","Or enroll at connected APMC mandi","Free registration"],link:"https://enam.gov.in/",helpline:"1800-270-0224",amt:0,match:p=>p.employment==="farmer"},

{name:"National Horticulture Mission",cat:"agriculture",tag:"Agriculture",benefit:"35-50% subsidy on horticulture cultivation & infrastructure",desc:"Promotes fruits, vegetables, spices, flowers cultivation. Subsidy on planting material, cold storage, processing units.",elig:["All farmers including FPOs","Individual/group/cooperative","For horticulture crop cultivation"],docs:["Land records","Project proposal","Bank account","Aadhaar"],apply:["Apply through state horticulture dept","District horticulture officer","Online in some states"],link:"https://nhm.nic.in/",helpline:"State horticulture department",amt:0,match:p=>p.employment==="farmer"},

{name:"Dairy Entrepreneurship Development Scheme (DEDS)",cat:"agriculture",tag:"Agriculture",benefit:"25-33% subsidy on dairy unit setup (up to ₹7 lakh)",desc:"Promotes modern dairy farming. Subsidy for small dairy units of 2-10 cows/buffaloes. Includes milk processing & value addition.",elig:["Farmers, SHGs, cooperatives","Individual or group","Only one unit per person"],docs:["Project report","Land/shed ownership proof","Bank account","Quotation for animals/equipment"],apply:["Apply through NABARD/District Dairy Officer","Bank processes loan + subsidy","Subsidy back-ended to loan"],link:"https://dahd.nic.in/",helpline:"State dairy development office",amt:700000,match:p=>p.employment==="farmer"||p.area==="rural"},

{name:"Blue Revolution (Inland Fisheries)",cat:"agriculture",tag:"Fisheries",benefit:"40-60% subsidy on fishery infrastructure & ponds",desc:"Promotes fish production, aquaculture, marine fisheries. Subsidy on pond construction, fish seed, feed, boats, cold storage.",elig:["Fishermen & fish farmers","SHGs & cooperatives","Inland & marine fisheries"],docs:["Fisherman ID","Land/water body lease","Bank account","Project proposal"],apply:["Apply through state fisheries department","District Fisheries Officer","PMMSY portal"],link:"https://dof.gov.in/pmmsy",helpline:"State fisheries department",amt:0,match:p=>p.employment==="farmer"&&p.area==="rural"},

{name:"National Beekeeping & Honey Mission",cat:"agriculture",tag:"Agriculture",benefit:"₹2L subsidy for beekeeping setup per unit",desc:"Promotes beekeeping as livelihood. Free training, bee colonies, equipment. Processing & marketing support.",elig:["Any Indian citizen","Farmers, women SHGs, tribal communities","Training mandatory before starting"],docs:["Aadhaar","Training completion certificate","Bank passbook"],apply:["Apply through KVK/ATMA/State agriculture dept","NBHM portal","Free training provided first"],link:"https://nbb.gov.in/",helpline:"State agriculture department",amt:200000,match:p=>p.employment==="farmer"||p.area==="rural"},

{name:"PM Garib Kalyan Anna Yojana (PMGKAY)",cat:"health",tag:"Food",benefit:"5 kg free foodgrains per person per month",desc:"Free food grains to 81.35 crore NFSA beneficiaries. Extended till Dec 2028. Rice, wheat, coarse grains at zero cost.",elig:["All NFSA beneficiaries","AAY & PHH ration card holders","About 81.35 crore people covered"],docs:["Ration Card (AAY/PHH)","Aadhaar linked"],apply:["Automatic for ration card holders","Collect from nearest Fair Price Shop","ePoS verification at shop"],link:"https://nfsa.gov.in/",helpline:"1800-180-4567",amt:0,match:p=>["below1","1to2.5"].includes(p.income)},

{name:"Beti Bachao, Beti Padhao",cat:"women",tag:"Women",benefit:"Awareness + institutional convergence for girl child",desc:"Multi-ministry initiative for survival, protection, education of girl child. Improved sex ratio from 918 to 934 in target districts.",elig:["All families with girl children","Implemented across all districts","Special focus on gender-critical districts"],docs:["No documents needed for awareness programmes"],apply:["Participate through Anganwadi/school campaigns","District Women & Child office","State-level programmes"],link:"https://wcd.nic.in/bbbp-schemes",helpline:"181",amt:0,match:p=>p.gender==="female"||p.lifeStage.includes("children")},

{name:"One Stop Centre (Sakhi) Scheme",cat:"women",tag:"Women",benefit:"Integrated support for women in distress — medical, legal, shelter",desc:"700+ centres across India. 24/7 support for violence, abuse, harassment. Free medical aid, FIR support, legal help, psycho-social counselling.",elig:["Any woman facing violence/distress","No age/caste/income restriction","Includes children affected by violence"],docs:["No documents needed for emergency help"],apply:["Call Women Helpline 181","Visit nearest Sakhi Centre","Police can refer victims too"],link:"https://wcd.nic.in/schemes/one-stop-centre",helpline:"181",amt:0,match:p=>p.gender==="female"},

{name:"Mahila Shakti Kendra",cat:"women",tag:"Women",benefit:"Skill development + digital literacy + health awareness for rural women",desc:"Community participation through college student volunteers. Empowers rural women with skills, knowledge, health awareness.",elig:["Rural women","All age groups","Implemented through student volunteers at block/district level"],docs:["Aadhaar (for registration)"],apply:["Contact district/block WCD office","Through Anganwadi centres","Free programmes"],link:"https://wcd.nic.in/",helpline:"181",amt:0,match:p=>p.gender==="female"&&p.area==="rural"},

{name:"PM Matru Vandana Yojana 2.0 Enhanced",cat:"health",tag:"Health",benefit:"₹11,000 enhanced: ₹3K+₹2K+₹6K for 2nd girl child",desc:"From April 2024: ₹3,000 during pregnancy, ₹2,000 after institutional delivery + registration, ₹6,000 for 2nd girl child.",elig:["Pregnant women for first live birth","2nd child if girl — ₹6,000 lump sum","Not government/PSU employees"],docs:["Aadhaar","MCP card","Bank passbook","Hospital delivery certificate"],apply:["Register at Anganwadi Centre","Fill PMMVY forms 1-A, 1-B, 1-C","DBT to bank account"],link:"https://pmmvy.wcd.gov.in/",helpline:"181",amt:11000,match:p=>p.gender==="female"&&p.lifeStage.includes("pregnant")},

{name:"POSHAN Abhiyaan (National Nutrition Mission)",cat:"health",tag:"Nutrition",benefit:"Reduces stunting, undernutrition, anemia targets",desc:"Convergence of nutrition schemes across ministries. Jan Andolan, ICDS, technology-based monitoring. Covers 10 crore+ beneficiaries.",elig:["Children 0-6 years","Pregnant & lactating women","Adolescent girls"],docs:["Aadhaar (for registration)","MCH card"],apply:["Through Anganwadi centres","Automatic for ICDS beneficiaries","No separate application"],link:"https://poshanabhiyaan.gov.in/",helpline:"State WCD department",amt:0,match:p=>p.lifeStage.includes("children")||p.lifeStage.includes("pregnant")},

{name:"National Social Assistance Programme (NSAP) — Old Age Pension",cat:"social",tag:"Pension",benefit:"₹200-₹500/month + state top-up for elderly",desc:"Central pension for destitute elderly. ₹200/month (60-79 yrs), ₹500/month (80+ yrs). Most states add ₹500-₹2000 top-up.",elig:["Age 60+","BPL/Destitute","No/negligible regular income","Not receiving pension from other sources"],docs:["Aadhaar","Age proof","BPL certificate","Bank/Post Office passbook"],apply:["Apply through Gram Panchayat/ULB","Verification by BDO/SDM","nsap.nic.in for status check"],link:"https://nsap.nic.in/",helpline:"State social welfare department",amt:6000,match:p=>p.age>=60&&["below1","1to2.5"].includes(p.income)},

{name:"NSAP — Widow Pension (IGNWPS)",cat:"social",tag:"Pension",benefit:"₹300-₹500/month + state top-up for widows",desc:"Central pension + state top-up for destitute widows. ₹300/month (40-79), ₹500/month (80+). States add ₹500-₹2000.",elig:["Women 40+","Widowed","BPL household","Not receiving other govt pension"],docs:["Aadhaar","Death certificate of spouse","Age proof","BPL certificate","Bank account"],apply:["Apply through Gram Panchayat/ULB","State social welfare dept","nsap.nic.in"],link:"https://nsap.nic.in/",helpline:"State social welfare department",amt:6000,match:p=>p.gender==="female"&&p.lifeStage.includes("widow")},

{name:"NSAP — Disability Pension (IGNDPS)",cat:"social",tag:"Pension",benefit:"₹300-₹500/month for persons with disabilities",desc:"Central pension for disabled persons. ₹300/month (18-79), ₹500/month (80+). Most states add top-up amount.",elig:["Age 18+","80%+ disability","BPL household","Not receiving other pension"],docs:["Aadhaar","Disability certificate (80%+)","BPL certificate","Bank account"],apply:["Apply through Gram Panchayat/ULB","State social welfare dept","nsap.nic.in"],link:"https://nsap.nic.in/",helpline:"State social welfare department",amt:6000,match:p=>p.lifeStage.includes("disabled")&&["below1","1to2.5"].includes(p.income)},

{name:"National Family Benefit Scheme (NFBS)",cat:"social",tag:"Welfare",benefit:"₹20,000 lump sum on death of breadwinner",desc:"One-time grant to BPL household on death of primary breadwinner. Deceased should be 18-59 years of age.",elig:["BPL household","Death of primary breadwinner","Deceased aged 18-59","Any cause of death"],docs:["Death certificate","BPL card","Aadhaar of applicant","Bank passbook","FIR (if accidental)"],apply:["Apply to District Collector/SDM","Through Gram Panchayat/ULB","Within 1 year of death"],link:"https://nsap.nic.in/",helpline:"State social welfare department",amt:20000,match:p=>["below1","1to2.5"].includes(p.income)},

{name:"Rashtriya Vayoshri Yojana (RVY)",cat:"social",tag:"Senior",benefit:"Free assistive devices for senior citizens (hearing aid, wheelchair, etc.)",desc:"Provides walking sticks, hearing aids, wheelchairs, spectacles, dentures etc. free to BPL senior citizens.",elig:["Age 60+","BPL","Suffering from age-related disabilities","Priority: women, those above 80"],docs:["Aadhaar","Age proof","BPL certificate","Disability assessment"],apply:["Through district camps conducted by ALIMCO","State social welfare dept notification","Free distribution events"],link:"https://socialjustice.gov.in/",helpline:"State social welfare department",amt:0,match:p=>p.age>=60&&["below1","1to2.5"].includes(p.income)},

{name:"Accessible India Campaign (Sugamya Bharat Abhiyan)",cat:"social",tag:"Disability",benefit:"Making public buildings, transport, ICT accessible for PwD",desc:"Making 50% government buildings wheelchair-accessible, accessible transport, sign language on govt TV, accessible websites.",elig:["All persons with disabilities","Focus on physical & visual disabilities"],docs:["Not applicable — infrastructure scheme"],apply:["Report inaccessible buildings on app","Audit & retrofit initiated by government","Accessible India Campaign portal"],link:"https://accessibleindia.gov.in/",helpline:"1800-180-2345",amt:0,match:p=>p.lifeStage.includes("disabled")},

{name:"Assistance to Disabled Persons (ADIP) Scheme",cat:"social",tag:"Disability",benefit:"Free modern aids & appliances worth up to ₹10,000",desc:"Provides prosthetics, wheelchairs, braille kits, hearing aids, crutches etc. Through camps & artificial limb centres.",elig:["40%+ disability certified","Income below ₹20,000/month","Indian citizen","Not received same device in last 3 years"],docs:["Disability certificate","Income certificate","Aadhaar","Passport photo"],apply:["Through implementing agencies (NGOs/ALIMCO)","Apply at district camps","Online via socialjustice.gov.in"],link:"https://socialjustice.gov.in/",helpline:"State social welfare department",amt:10000,match:p=>p.lifeStage.includes("disabled")},

{name:"Deen Dayal Divyangjan Rehabilitation Scheme",cat:"social",tag:"Disability",benefit:"Grants to NGOs for PwD rehabilitation & skill training",desc:"Supports NGOs running special schools, vocational training centres, community-based rehabilitation for disabled persons.",elig:["Persons with disabilities through NGOs","Project proposals by registered organizations"],docs:["Through NGO application"],apply:["NGOs apply to Dept of Empowerment of PwD","Beneficiaries identified by implementing NGO"],link:"https://disabilityaffairs.gov.in/",helpline:"State disability commissioner",amt:0,match:p=>p.lifeStage.includes("disabled")},

{name:"National Action Plan for Seniors (NAPSrC)",cat:"social",tag:"Senior",benefit:"Integrated elderly care: health, nutrition, shelter, engagement",desc:"Comprehensive elderly welfare: old age homes, day care, mobile medicare, helpline. Implemented through state govts & NGOs.",elig:["Senior citizens 60+","Priority: destitute elderly","BPL/APL both for some components"],docs:["Age proof","Aadhaar","Income certificate"],apply:["Through District Social Welfare Office","NGOs running elderly homes","Helpline 14567 (Elderline)"],link:"https://socialjustice.gov.in/",helpline:"14567",amt:0,match:p=>p.age>=60},

{name:"Post Matric Scholarship for SC Students",cat:"education",tag:"Scholarship",benefit:"Full tuition + ₹550-₹1,200/month maintenance allowance",desc:"Central scheme for SC students Class 11 to PhD. Covers tuition, maintenance, study tour, thesis typing. 57 lakh+ beneficiaries.",elig:["SC students in Class 11 & above","Family income below ₹2.5 lakh/year","Regular course in recognized institution"],docs:["Caste certificate","Income certificate","Previous marksheet","Admission letter","Bank passbook"],apply:["Apply online via state scholarship portal","National Scholarship Portal at scholarships.gov.in","Before state deadline"],link:"https://scholarships.gov.in/",helpline:"0120-6619540",amt:14400,match:p=>p.category==="sc"&&(p.employment==="student"||p.education!=="no-formal")},

{name:"Post Matric Scholarship for ST Students",cat:"education",tag:"Scholarship",benefit:"Full tuition + ₹550-₹1,200/month maintenance allowance",desc:"Central scheme for ST students Class 11 to PhD. Covers tuition, maintenance, reader charges for blind students.",elig:["ST students in Class 11 & above","Family income below ₹2.5 lakh/year","Regular course in recognized institution"],docs:["Tribe certificate","Income certificate","Previous marksheet","Admission letter","Bank passbook"],apply:["Apply via National Scholarship Portal","State tribal welfare department","Before state deadline"],link:"https://scholarships.gov.in/",helpline:"0120-6619540",amt:14400,match:p=>p.category==="st"&&(p.employment==="student"||p.education!=="no-formal")},

{name:"Post Matric Scholarship for OBC Students",cat:"education",tag:"Scholarship",benefit:"Full tuition + maintenance allowance for OBC students",desc:"Scholarship for OBC students post-matric. Family income below ₹1L for full maintenance, ₹1-3L for non-maintenance.",elig:["OBC students in Class 11 & above","Family income below ₹1L (Group A) or ₹3L (Group B)","Regular course"],docs:["OBC (NCL) certificate","Income certificate","Previous marksheet","Bank passbook"],apply:["Apply via National Scholarship Portal","State BC welfare department"],link:"https://scholarships.gov.in/",helpline:"0120-6619540",amt:10000,match:p=>p.category==="obc"&&(p.employment==="student"||p.education!=="no-formal")},

{name:"PM Scholarship Scheme (Armed Forces)",cat:"education",tag:"Scholarship",benefit:"₹3,000/month (boys) ₹3,600/month (girls) for professional courses",desc:"Scholarship for dependents of ex-servicemen, para-military, police killed/disabled in action. Technical & professional courses.",elig:["Ward of ex-serviceman/CAPF/state police","Killed/disabled in action","Professional degree course","1st year admission"],docs:["ESM identity card","Disability certificate of parent","Previous marksheet","Admission letter"],apply:["Apply via KSB portal","ksb.gov.in","Annually renewed"],link:"https://ksb.gov.in/",helpline:"011-26715250",amt:43200,match:p=>p.employment==="student"},

{name:"Central Sector Scheme of Scholarship for College/University Students",cat:"education",tag:"Scholarship",benefit:"₹12,000/year (UG) & ₹20,000/year (PG) for top students",desc:"Merit-based scholarship for students above 80th percentile in Class 12. Renewal based on academic performance.",elig:["Passed Class 12 with 80+ percentile","Family income below ₹8 lakh/year","Admitted to regular degree course","Not availing other scholarship"],docs:["Class 12 marksheet","Income certificate","College admission","Aadhaar","Bank passbook"],apply:["Apply on National Scholarship Portal","scholarships.gov.in","Fresh & renewal applications"],link:"https://scholarships.gov.in/",helpline:"0120-6619540",amt:20000,match:p=>p.employment==="student"&&["below1","1to2.5","2.5to5","5to10"].includes(p.income)},

{name:"National Means-cum-Merit Scholarship (NMMSS)",cat:"education",tag:"Scholarship",benefit:"₹12,000/year for Class 9-12 meritorious students",desc:"For economically weaker students to reduce dropouts at secondary stage. 1 lakh fresh scholarships annually.",elig:["Studying in Class 8 in government school","Selected through exam","Family income below ₹3.5 lakh/year","For study in Class 9-12"],docs:["Class 8 marksheet","Income certificate","School enrollment","Aadhaar"],apply:["Appear in state-level NMMSS exam in Class 8","Apply via National Scholarship Portal if selected"],link:"https://scholarships.gov.in/",helpline:"0120-6619540",amt:12000,match:p=>p.employment==="student"&&["below1","1to2.5","2.5to5"].includes(p.income)},

{name:"NPS Vatsalya Yojana",cat:"finance",tag:"Pension",benefit:"NPS account for minors — long-term wealth building",desc:"Launched Sep 2024. Parents/guardians open NPS for children. Min ₹1,000/year. Converts to regular NPS at 18.",elig:["Any Indian citizen minor (below 18)","Parent/guardian opens account","Min contribution ₹1,000/year"],docs:["Child's birth certificate","Parent's Aadhaar & PAN","Bank account of parent","KYC documents"],apply:["Open at any PoP-SP bank/post office","Online via eNPS portal","Converts to regular NPS at 18"],link:"https://www.npscra.nsdl.co.in/",helpline:"1800-222-080",amt:0,match:p=>p.lifeStage.includes("children")},

{name:"Pradhan Mantri Gram Sadak Yojana (PMGSY)",cat:"infrastructure",tag:"Rural",benefit:"All-weather road to unconnected rural habitations",desc:"Connected 2.1 lakh+ habitations. PMGSY-III focuses on connecting habitats with hospitals, schools, markets.",elig:["Rural habitations with 500+ population (plain) / 250+ (hilly)","State proposes road list","Gram Panchayat involvement"],docs:["Not applicable — infrastructure project"],apply:["Through state PWD/RWD","Gram Panchayat proposes","pmgsy.nic.in for monitoring"],link:"https://pmgsy.nic.in/",helpline:"State rural development department",amt:0,match:p=>p.area==="rural"},

{name:"Digital India Programme",cat:"digital",tag:"Digital",benefit:"Free WiFi hotspots + digital services + e-governance",desc:"Transforms India into a digitally empowered society. 6.5 lakh+ CSCs, DigiLocker, UMANG, BharatNet for rural broadband.",elig:["All Indian citizens","Free digital services","Priority: rural connectivity"],docs:["Aadhaar for DigiLocker","Mobile number for UMANG"],apply:["Download UMANG app / DigiLocker","Visit nearest CSC","Free digital literacy training at CSCs"],link:"https://digitalindia.gov.in/",helpline:"1800-111-555",amt:0,match:p=>true},

{name:"BharatNet (National Optical Fibre Network)",cat:"digital",tag:"Digital",benefit:"High-speed broadband to all 2.5 lakh Gram Panchayats",desc:"Optical fibre to every gram panchayat. 2 lakh+ GPs connected. Enables telemedicine, e-learning, e-governance in villages.",elig:["All gram panchayats & rural institutions","Schools, hospitals, CSCs connected","Citizens benefit from WiFi hotspots"],docs:["Not applicable — infrastructure"],apply:["Through Gram Panchayat","BharatNet WiFi hotspots","Free/affordable broadband"],link:"https://bbnl.nic.in/",helpline:"1800-111-555",amt:0,match:p=>p.area==="rural"},

{name:"Khelo India Programme",cat:"sports",tag:"Sports",benefit:"₹5 lakh/year scholarship for talented athletes",desc:"Identifies & supports 1,000 athletes annually with ₹5L/year for 8 years. Sports infrastructure, competitions, training.",elig:["Age 8-18 for Khelo India Games","Talented athletes identified through competitions","All Indian citizens"],docs:["Aadhaar","Sports achievement certificates","School/college ID","Bank passbook"],apply:["Participate in district/state/national Khelo India events","Selected athletes get scholarship","kheloindia.gov.in"],link:"https://kheloindia.gov.in/",helpline:"State sports department",amt:500000,match:p=>p.age<=30&&(p.employment==="student"||p.needs.includes("sports"))},

{name:"PM e-DRIVE Scheme (EV Promotion)",cat:"environment",tag:"Transport",benefit:"Subsidy on electric vehicles: ₹10,000-₹50,000",desc:"Launched Oct 2024 replacing FAME-II. Subsidizes 2-wheelers, 3-wheelers, buses, trucks, ambulances. ₹10,900 Cr budget.",elig:["Indian citizens buying new EVs","2-wheelers: up to ₹10K subsidy","e-buses: for state transport","e-trucks: ₹50K subsidy"],docs:["Aadhaar","PAN","Vehicle purchase invoice","Bank account"],apply:["Subsidy applied at dealership","Auto-deducted from vehicle price","Dashboard at pmegov.in"],link:"https://morth.nic.in/",helpline:"1800-180-5555",amt:50000,match:p=>true},

{name:"UJALA LED Bulb Scheme",cat:"environment",tag:"Energy",benefit:"LED bulbs at ₹70 (market price ₹300+)",desc:"Distributed 36+ crore LED bulbs. Saves ₹20,000 crore in electricity bills nationally. Also ceiling fans & tube lights at subsidy.",elig:["Any domestic electricity consumer","Show latest electricity bill","Maximum 10 bulbs per household"],docs:["Electricity bill","Aadhaar (for some areas)"],apply:["Visit UJALA distribution kiosk","Available at post offices in some areas","ujala.gov.in"],link:"https://ujala.gov.in/",helpline:"1800-180-3333",amt:0,match:p=>true},

{name:"National Rural Health Mission (NHM)",cat:"health",tag:"Health",benefit:"Free healthcare at PHCs, CHCs, district hospitals",desc:"Strengthens public health system. 1.6 lakh sub-centres, 30K PHCs, 6K CHCs. Free medicines, diagnostics, ambulance (108/102).",elig:["All citizens","Free at government health facilities","No income restriction"],docs:["None for outpatient","Aadhaar for admission/referral"],apply:["Visit nearest PHC/CHC/District Hospital","Free treatment","Ambulance: dial 108 (emergency) or 102 (pregnancy)"],link:"https://nhm.gov.in/",helpline:"108 / 102",amt:0,match:p=>p.needs.includes("health")},

{name:"Rashtriya Swasthya Bima Yojana (RSBY)",cat:"health",tag:"Insurance",benefit:"₹30,000 health insurance for unorganized workers",desc:"Smart card-based cashless health insurance. Now merged with Ayushman Bharat in most states but continues in some.",elig:["BPL families","Unorganized sector workers","Building/construction workers","MGNREGA workers"],docs:["BPL card","Aadhaar","Family photo"],apply:["Enrollment at camps organized by insurance company","Smart card issued on the spot"],link:"https://labour.gov.in/",helpline:"State labour department",amt:30000,match:p=>["below1","1to2.5"].includes(p.income)&&!["salaried"].includes(p.employment)},

{name:"Ayushman Bharat Health & Wellness Centres",cat:"health",tag:"Health",benefit:"Free primary healthcare at 1.5 lakh+ upgraded centres",desc:"Upgraded sub-centres to Health & Wellness Centres. 12 types of free services including NCDs, mental health, ENT, eye care.",elig:["All Indian citizens","No income restriction","Walk-in service at nearest HWC"],docs:["None needed","Aadhaar helpful for records"],apply:["Walk into nearest AB-HWC","Free consultation & medicines","No registration fees"],link:"https://ab-hwc.nhp.gov.in/",helpline:"14555",amt:0,match:p=>p.needs.includes("health")},

{name:"Jan Aushadhi (Pradhan Mantri Bhartiya Janaushadhi Pariyojana)",cat:"health",tag:"Health",benefit:"Quality generic medicines at 50-90% less cost",desc:"10,000+ Jan Aushadhi stores. 1,900+ medicines, 285+ surgical items at affordable prices. Same quality as branded.",elig:["Any person can purchase","No prescription needed for OTC","Doctor prescription for scheduled drugs"],docs:["Prescription for scheduled drugs"],apply:["Visit nearest Pradhan Mantri Bhartiya Janaushadhi Kendra","janaushadhi.gov.in for store locator"],link:"https://janaushadhi.gov.in/",helpline:"1800-180-8080",amt:0,match:p=>true},

{name:"Pradhan Mantri Vidya Lakshmi Yojana",cat:"education",tag:"Education",benefit:"Single window for education loans across banks",desc:"Launched Jan 2025. Unified portal for education loan applications. Compare loans from multiple banks. Subsidy for EWS students.",elig:["Students admitted to recognized institutions","Higher education in India/abroad","Banks set individual eligibility"],docs:["Admission letter","Academic records","Income proof","Co-borrower documents"],apply:["Apply at vidyalakshmi.co.in","Compare offers from multiple banks","Submit single application"],link:"https://www.vidyalakshi.co.in/",helpline:"0120-6619540",amt:0,match:p=>p.employment==="student"},

{name:"PM Viksit Bharat Rozgar Yojana",cat:"employment",tag:"Employment",benefit:"EPFO incentive for new hires — 1 month salary + employer contribution",desc:"Announced for 2025. Incentivizes formal job creation. EPFO benefits for first-time employees. 4 lakh+ companies eligible.",elig:["First-time EPFO-registered employees","Salary up to ₹1L/month","Employer registered with EPFO"],docs:["Aadhaar","EPFO registration","Bank passbook"],apply:["Employer registers on EPFO portal","Employee auto-enrolled","Incentive credited by EPFO"],link:"https://epfindia.gov.in/",helpline:"1800-118-005",amt:0,match:p=>p.age>=18&&p.age<=35}
];
