// ═══════════════════════════════════════════════════════════════
// MERA HAQ — CENTRAL GOVERNMENT SCHEMES DATABASE (Part 2: 101-200)
// ═══════════════════════════════════════════════════════════════

export const CENTRAL_SCHEMES_2 = [

// ═══ WOMEN & CHILD (101-120) ═══
{name:"Beti Bachao Beti Padhao",cat:"women",tag:"Women",benefit:"Awareness + institutional support for girl child survival and education",desc:"Multi-sectoral campaign in 405 districts for girl child. Focus on preventing gender-biased sex selection, ensuring girls' survival, and education. Convergence of health, education, and women empowerment ministries.",elig:["All communities","Focus districts with low child sex ratio","Families with girl children"],docs:["No individual application — awareness programme"],apply:["Benefits through improved services at Anganwadi, schools, hospitals","Participate in BBBP events in your district"],link:"https://wcd.nic.in/bbbp-schemes",helpline:"181",amt:0,match:p=>p.lifeStage.includes("girl-child")},

{name:"One Stop Centre (Sakhi)",cat:"women",tag:"Women",benefit:"Integrated support for women facing violence — shelter, legal, medical, counselling",desc:"700+ centres across India providing 24/7 support to women facing violence. Free shelter (up to 5 days), legal aid, medical aid, police facilitation, psycho-social counselling.",elig:["Any woman facing violence/abuse","No age restriction","Includes domestic violence, sexual assault, trafficking, harassment"],docs:["None needed for emergency help","Aadhaar/ID for extended services"],apply:["Walk into nearest One Stop Centre","OR call Women Helpline 181","OR call 112 (emergency)","No referral needed"],link:"http://www.wcd.nic.in/schemes/one-stop-centre-scheme-1",helpline:"181 / 112",amt:0,match:p=>p.gender==="female"},

{name:"Mahila Shakti Kendra",cat:"women",tag:"Women",benefit:"Community engagement for women empowerment through student volunteers",desc:"Deploys student volunteers in underserved districts to create awareness about government schemes, rights, and digital literacy for women. Covers 115 most backward districts.",elig:["Women in underserved districts","Student volunteers (for deployment)"],docs:["None — awareness programme"],apply:["Access through local Anganwadi/Block office","Student volunteers visit communities"],link:"https://wcd.nic.in/",helpline:"181",amt:0,match:p=>p.gender==="female"&&p.area==="rural"},

{name:"Working Women Hostel",cat:"women",tag:"Women",benefit:"Safe, affordable hostel accommodation for working women",desc:"Subsidized hostel accommodation for working women with monthly income up to ₹50,000 in metros and ₹35,000 in other cities. Children up to 18 years can stay.",elig:["Working women (single, widowed, divorced, separated, married with husband away)","Income up to ₹50,000/month (metro) / ₹35,000 (non-metro)","Women undergoing training for max 1 year"],docs:["Employment proof","Income certificate","ID proof","Photograph"],apply:["Contact nearest Working Women Hostel","Apply through state women's development department"],link:"https://wcd.nic.in/",helpline:"181",amt:0,match:p=>p.gender==="female"&&p.employment==="salaried"},

{name:"Swadhar Greh (Shelter for Women in Distress)",cat:"women",tag:"Women",benefit:"Free shelter + food + rehabilitation for women in distress",desc:"Shelter homes for women in distress: widows, destitutes, domestic violence survivors, trafficked women, released prisoners, mentally challenged. Provides food, shelter, clothing, legal aid, and vocational training.",elig:["Women deserted/without family support","Domestic violence survivors","Trafficked women","Women prisoners released without support","Mentally challenged women"],docs:["None for emergency admission","ID proof (when available)","FIR/court order (if applicable)"],apply:["Contact nearest Swadhar Greh","Referral through police, court, One Stop Centre","Direct admission for distressed women"],link:"https://wcd.nic.in/",helpline:"181",amt:0,match:p=>p.gender==="female"&&p.lifeStage.includes("widow")},

{name:"Mahila Samman Savings Certificate",cat:"women",tag:"Women",benefit:"7.5% interest rate exclusively for women — invest up to ₹2 lakh",desc:"2-year deposit scheme for women/girls. 7.5% p.a. (highest among small savings for this tenure). Max deposit ₹2L. Partial withdrawal after 1 year.",elig:["Any woman or girl of any age","Indian resident","Maximum deposit ₹2 lakh"],docs:["Aadhaar","PAN (for ₹50K+)","Photograph"],apply:["Visit any Post Office","Fill account opening form","Deposit min ₹1,000 to max ₹2 lakh"],link:"https://www.indiapost.gov.in/",helpline:"1800-266-6868",amt:30000,match:p=>p.gender==="female"},

{name:"Free LPG Connection (Ujjwala 2.0)",cat:"women",tag:"Women",benefit:"Free LPG connection + first refill + stove for BPL women",desc:"10.35 crore free LPG connections to BPL women. Ujjwala 2.0: no address proof needed. First refill and stove free. Subsidy on refills via DBT.",elig:["Adult woman of BPL household","No existing LPG connection in household","Self-declaration for address (Ujjwala 2.0)"],docs:["Aadhaar","Bank passbook","Self-declaration"],apply:["Visit any LPG distributor","Fill form — connection in 7-14 days"],link:"https://www.pmuy.gov.in/",helpline:"1800-233-3555",amt:3200,match:p=>p.gender==="female"&&p.special.includes("no-gas")&&["below1","1to2.5"].includes(p.income)},

{name:"Mission Shakti (SAMBAL + SAMARTHYA)",cat:"women",tag:"Women",benefit:"Umbrella scheme for women safety + empowerment",desc:"Merged umbrella: SAMBAL (safety: OSC, Women Helpline, Nari Adalat) + SAMARTHYA (empowerment: SHGs, Palna creches, Shakti Sadans). ₹20,989 crore for 2021-26.",elig:["All women in India","Specific components target specific groups"],docs:["Varies by component"],apply:["Access through nearest Anganwadi, One Stop Centre, or Women Helpline 181"],link:"https://wcd.nic.in/",helpline:"181",amt:0,match:p=>p.gender==="female"},

{name:"Indira Gandhi National Widow Pension (IGNWPS)",cat:"women",tag:"Women",benefit:"₹300-₹500/month pension for BPL widows + state top-up",desc:"Central pension for BPL widows aged 40-79 (₹300/month) and 80+ (₹500/month). States add top-up: total ₹500-₹2,000/month.",elig:["Widow aged 40+","BPL family","Not receiving other pension"],docs:["Aadhaar","Husband's death certificate","BPL card","Age proof","Bank passbook"],apply:["nsap.nic.in","OR through Panchayat/Municipality office","State social welfare department"],link:"https://nsap.nic.in/",helpline:"State SW dept",amt:6000,match:p=>p.gender==="female"&&p.lifeStage.includes("widow")&&["below1","1to2.5"].includes(p.income)},

{name:"IGNDPS (Indira Gandhi National Disability Pension)",cat:"money",tag:"Money",benefit:"₹300-₹500/month pension for BPL disabled persons",desc:"Central pension for BPL persons with 80%+ disability. ₹300/month (18-79) + ₹500/month (80+). State top-up varies.",elig:["80%+ disability","Age 18+","BPL family","Not receiving other pension"],docs:["Disability certificate (80%+)","Aadhaar","BPL card","Bank passbook"],apply:["nsap.nic.in OR local Panchayat/Municipality"],link:"https://nsap.nic.in/",helpline:"State SW dept",amt:6000,match:p=>p.lifeStage.includes("disabled")&&["below1","1to2.5","2.5to5"].includes(p.income)},

{name:"PM CARES for Children",cat:"women",tag:"Women",benefit:"₹10 lakh + free education + health cover for children orphaned by COVID",desc:"For children who lost parents to COVID. ₹10 lakh corpus at age 23, free education till graduation/PG, health cover under Ayushman Bharat.",elig:["Children who lost both parents or surviving parent or legal guardian to COVID","Under 18 at time of parent's death"],docs:["Parent's death certificate (COVID)","Child's birth certificate","Aadhaar"],apply:["pmcaresforchildren.in","Apply online or through District Magistrate"],link:"https://pmcaresforchildren.in/",helpline:"State WCD dept",amt:1000000,match:p=>p.lifeStage.includes("children")},

{name:"Poshan Abhiyan (National Nutrition Mission)",cat:"women",tag:"Women",benefit:"Nutritional support + monitoring for children, pregnant/lactating women",desc:"₹37,000 crore mission to reduce stunting, undernutrition, anemia, and low birth weight. Supplementary nutrition through ICDS/Anganwadi. Growth monitoring with tech tools.",elig:["Children 0-6 years","Pregnant and lactating women","Adolescent girls","All — through Anganwadi centres"],docs:["None — access through nearest Anganwadi"],apply:["Visit nearest Anganwadi Centre","Register for supplementary nutrition","Growth monitoring done by Anganwadi worker"],link:"https://poshantracker.in/",helpline:"State WCD dept",amt:0,match:p=>p.lifeStage.includes("children")||p.lifeStage.includes("pregnant")},

{name:"Integrated Child Development Services (ICDS)",cat:"women",tag:"Women",benefit:"6 services: nutrition, immunization, health check, referral, preschool, health education",desc:"World's largest early childhood development programme. Through 13.9 lakh Anganwadi centres. Supplementary nutrition, immunization, health check, referral, preschool education, nutrition education.",elig:["Children 0-6 years","Pregnant women","Lactating mothers","Adolescent girls (11-18)","All — no income restriction"],docs:["None — register at Anganwadi"],apply:["Visit nearest Anganwadi Centre","Register child/self for services"],link:"https://wcd.nic.in/",helpline:"State WCD dept",amt:0,match:p=>p.lifeStage.includes("children")||p.lifeStage.includes("pregnant")},

{name:"Palna (National Creche Scheme)",cat:"women",tag:"Women",benefit:"Free day care for children (6 months - 6 years) of working women",desc:"Creche/day care facility for children of working mothers. Nutrition, education, health care, sleeping facility. 7 AM to 5 PM services.",elig:["Working women's children aged 6 months to 6 years","Family income below ₹12 lakh","Priority: single mothers, informal sector workers"],docs:["Employment proof","Income certificate","Child's birth certificate","Aadhaar"],apply:["Contact nearest Anganwadi/Palna centre","Apply through state WCD department"],link:"https://wcd.nic.in/",helpline:"State WCD dept",amt:0,match:p=>p.gender==="female"&&p.lifeStage.includes("children")},

{name:"Nari Shakti Puraskar",cat:"women",tag:"Women",benefit:"₹2 lakh award for outstanding women achievers",desc:"Highest civilian award for women. Recognizes outstanding contribution in various fields. ₹2 lakh cash + certificate. Nomination-based.",elig:["Exceptional women achievers in any field","Nominated by state/organizations"],docs:["Nomination through official channels"],apply:["Nominations through nfrw.nic.in when open"],link:"https://nfrw.nic.in/",helpline:"WCD ministry",amt:200000,match:p=>p.gender==="female"},

// Continue with remaining categories...

// ═══ DISABILITY WELFARE (121-130) ═══
{name:"Accessible India Campaign (Sugamya Bharat)",cat:"money",tag:"Money",benefit:"Making public spaces, transport, ICT accessible for disabled",desc:"Making built environment, transportation, and ICT accessible for PwDs. Free retrofitting of govt buildings, accessible buses, website accessibility.",elig:["All persons with disabilities","Public infrastructure benefit"],docs:["Disability certificate (for individual aids)"],apply:["Benefits accessed through improved public infrastructure","Individual aids: contact District Disability Rehab Centre"],link:"https://accessibleindia.gov.in/",helpline:"011-23382387",amt:0,match:p=>p.lifeStage.includes("disabled")},

{name:"ADIP Scheme (Assistive Devices for PwDs)",cat:"money",tag:"Money",benefit:"Free assistive devices: wheelchairs, hearing aids, prosthetics, braille kits",desc:"Free distribution of durable, sophisticated aids and appliances to PwDs. Wheelchairs, motorized tricycles, hearing aids, prosthetics, crutches, braille kits, smart canes.",elig:["Person with 40%+ disability","Monthly income below ₹20,000 (for free); ₹20K-₹25K (50% contribution)","Indian citizen"],docs:["Disability certificate","Income certificate","Aadhaar","Photograph","Medical prescription for aid"],apply:["Contact ALIMCO office or District Disability Rehabilitation Centre","OR attend free distribution camps","adfrip.gov.in"],link:"https://adfrip.gov.in/",helpline:"0512-2770873",amt:25000,match:p=>p.lifeStage.includes("disabled")},

{name:"Deendayal Disabled Rehabilitation Scheme (DDRS)",cat:"money",tag:"Money",benefit:"Grants to NGOs running disability rehabilitation centres",desc:"Financial assistance to NGOs for running rehabilitation centres, special schools, vocational training centres, community-based rehabilitation programmes for PwDs.",elig:["NGOs registered for disability rehabilitation","Minimum 2 years operational experience"],docs:["NGO registration","Audited accounts","Programme details"],apply:["disabilityaffairs.gov.in","Apply online for grant"],link:"https://disabilityaffairs.gov.in/",helpline:"011-23386054",amt:0,match:p=>p.lifeStage.includes("disabled")},

{name:"National Fellowship for PwD (NFPwD)",cat:"education",tag:"Education",benefit:"₹25,000-₹28,000/month fellowship for PwD pursuing MPhil/PhD",desc:"Research fellowship for disabled students pursuing MPhil/PhD. ₹25,000/month (JRF) and ₹28,000/month (SRF) + contingency.",elig:["PwD with 40%+ disability","Pursuing MPhil/PhD in recognized university","Qualified NET/SET or PG with 55%+"],docs:["Disability certificate","NET/SET qualification","PG marksheet","University enrollment proof"],apply:["scholarships.gov.in","Apply during fellowship window"],link:"https://scholarships.gov.in/",helpline:"011-23386054",amt:336000,match:p=>p.lifeStage.includes("disabled")&&p.employment==="student"},

{name:"Unique Disability ID (UDID)",cat:"money",tag:"Money",benefit:"Universal disability ID card for accessing all PwD benefits",desc:"National digital ID for persons with disabilities. Single document for accessing all govt schemes, concessions, and benefits. Replaces multiple disability certificates.",elig:["Any person with disability","Indian citizen"],docs:["Medical assessment at govt hospital","Aadhaar","Photograph"],apply:["swavlambancard.gov.in","OR visit designated district hospital","Medical board assessment","UDID card issued"],link:"https://swavlambancard.gov.in/",helpline:"011-23386054",amt:0,match:p=>p.lifeStage.includes("disabled")},

// ═══ TRIBAL & MINORITY WELFARE (131-145) ═══
{name:"Venture Capital Fund for SC (VCF-SC)",cat:"business",tag:"Business",benefit:"₹15 lakh loan at concessional rate for SC entrepreneurs",desc:"Concessional finance for SC entrepreneurs. Loans up to ₹15 lakh through NSFDC. Below-market interest rates. Manufacturing, services, trading.",elig:["SC entrepreneur","Family income below ₹3 lakh (double for urban)","Age 18+","Viable business plan"],docs:["SC certificate","Income certificate","Project report","Aadhaar + PAN"],apply:["nsfdc.nic.in","Through state channelizing agencies","Apply with project report"],link:"https://nsfdc.nic.in/",helpline:"011-24368484",amt:1500000,match:p=>p.category==="sc"&&["self-employed","business"].includes(p.employment)},

{name:"National Fellowship for SC Students",cat:"education",tag:"Education",benefit:"₹25,000-₹28,000/month for SC students pursuing MPhil/PhD",desc:"Research fellowship for SC students: JRF ₹25,000 and SRF ₹28,000/month. Covers 2,000 students/year. UGC NET qualification required.",elig:["SC category","Pursuing MPhil/PhD","Qualified UGC NET"],docs:["SC certificate","NET qualification","University enrollment"],apply:["scholarships.gov.in"],link:"https://scholarships.gov.in/",helpline:"State SW dept",amt:336000,match:p=>p.category==="sc"&&p.employment==="student"},

{name:"National Fellowship for ST Students",cat:"education",tag:"Education",benefit:"₹25,000-₹28,000/month for ST students pursuing MPhil/PhD",desc:"Same as SC fellowship but for Scheduled Tribes. 750 fellowships/year.",elig:["ST category","MPhil/PhD student","NET qualified"],docs:["ST certificate","NET qualification","University enrollment"],apply:["scholarships.gov.in"],link:"https://scholarships.gov.in/",helpline:"State tribal welfare",amt:336000,match:p=>p.category==="st"&&p.employment==="student"},

{name:"PM Adi Adarsh Gram Yojana",cat:"money",tag:"Money",benefit:"Integrated development of villages with 50%+ SC/ST population",desc:"Comprehensive development of 36,428 villages with significant tribal/SC population. Convergence of 20+ central schemes. Gap filling: infra that schemes don't cover.",elig:["Villages with 50%+ SC or 500+ SC population","All residents of identified village benefit"],docs:["None — village-level scheme"],apply:["Implemented by state governments","Benefits through improved village infrastructure"],link:"https://www.india.gov.in/",helpline:"State development dept",amt:0,match:p=>p.area==="rural"&&["sc","st"].includes(p.category)},

{name:"Eklavya Model Residential School (EMRS)",cat:"education",tag:"Education",benefit:"Free quality residential education for tribal students (Class 6-12)",desc:"740 residential schools for tribal students with quality education, sports, vocational training. JNV-equivalent quality in tribal areas. 100% free.",elig:["ST students in Class 6-12","Primarily for tribal-dominant sub-districts","Admission through entrance exam"],docs:["ST certificate","Previous class marksheet","Aadhaar"],apply:["Entrance exam conducted by state tribal welfare dept","Apply during admission season","Free boarding, lodging, uniform, books"],link:"https://www.tribal.nic.in/",helpline:"State tribal welfare dept",amt:100000,match:p=>p.category==="st"&&p.employment==="student"},

{name:"PM Jan Vikas Karyakram (for Minorities)",cat:"money",tag:"Money",benefit:"Infrastructure development in minority-concentrated areas",desc:"Development of educational, health, and skill infrastructure in minority-concentration areas. Schools, hostels, ITIs, health centres in 90 minority districts.",elig:["Residents of minority concentration districts","All communities benefit from infrastructure"],docs:["None — infrastructure scheme"],apply:["Benefits through improved schools, hospitals, skill centres"],link:"https://www.minorityaffairs.gov.in/",helpline:"State minority welfare",amt:0,match:p=>p.category==="minority"},

{name:"Nai Roshni (Leadership Training for Minority Women)",cat:"women",tag:"Women",benefit:"Free leadership and life skills training for minority women",desc:"6-day residential training for minority women in leadership, digital literacy, financial literacy, health, rights, government schemes awareness.",elig:["Minority community women aged 18-65","Priority: rural, BPL, less educated","No income restriction"],docs:["Minority community proof","Aadhaar","Photograph"],apply:["Contact nearest civil society organization implementing the scheme","OR state minority welfare dept"],link:"https://www.minorityaffairs.gov.in/",helpline:"State minority welfare",amt:0,match:p=>p.gender==="female"&&p.category==="minority"},

{name:"Nai Manzil (Skill Training for Minority Youth)",cat:"education",tag:"Education",benefit:"Free bridge education + skill training + placement for minority dropout youth",desc:"Combines formal education (bridge course for 8th/10th equivalence) with skill training for minority youth who dropped out of school. 9-12 month programme. Stipend during training.",elig:["Minority youth aged 17-35","School dropouts (not completed Class 10)","BPL/low-income families preferred"],docs:["Minority certificate","Aadhaar","Income proof","Educational certificates (if any)"],apply:["Contact state minority welfare department","Register at nearest training centre"],link:"https://www.minorityaffairs.gov.in/",helpline:"State minority welfare",amt:10000,match:p=>p.category==="minority"&&(p.employment==="unemployed"||p.needs.includes("skill"))},

{name:"Forest Rights Act (FRA) - Community Forest Rights",cat:"money",tag:"Money",benefit:"Legal ownership of forest land for tribals + rights to forest produce",desc:"Recognizes rights of tribals and forest dwellers over forest land they've been cultivating. Individual: up to 4 hectares. Community forest rights for minor forest produce, grazing, water.",elig:["Tribals residing in forest areas","Other Traditional Forest Dwellers (75+ years of occupation)","Must have been occupying forest land before Dec 2005"],docs:["Oral evidence/community verification","Revenue/forest department records","Satellite imagery (govt provides)","Gram Sabha resolution"],apply:["Submit claim to Gram Sabha","Gram Sabha verifies and approves","Sub-Divisional Committee reviews","District Committee issues title"],link:"https://www.tribal.nic.in/FRA.aspx",helpline:"State tribal welfare",amt:0,match:p=>p.category==="st"&&p.area==="rural"&&p.special.includes("tribal")},

{name:"Samagra Shiksha Abhiyan",cat:"education",tag:"Education",benefit:"Integrated scheme for school education quality — pre-nursery to Class 12",desc:"Umbrella scheme for school education: free textbooks, uniforms, mid-day meals, inclusive education for CWSN, teacher training, digital education (PM eVidya), transport allowance.",elig:["All students in government and govt-aided schools","Pre-nursery to Class 12","No income restriction"],docs:["School enrollment — benefits are automatic"],apply:["Benefits delivered through schools — no separate application","Free textbooks, uniforms distributed at school"],link:"https://samagra.education.gov.in/",helpline:"State education dept",amt:0,match:p=>p.lifeStage.includes("children")||p.employment==="student"},

// ═══ SUBSIDIES & FINANCIAL INCLUSION (146-165) ═══
{name:"PM Garib Kalyan Anna Yojana / NFSA",cat:"money",tag:"Money",benefit:"5 kg free rice/wheat per person per month (till 2028)",desc:"Free food grains to 81.35 crore people. Extended 5 years till Dec 2028. AAY families: 35 kg per household. Through 5.4 lakh+ ration shops. One Nation One Ration Card portability.",elig:["NFSA/PHH/AAY ration card holders","~58% of India's population covered"],docs:["Ration Card","Aadhaar (biometric at FPS)"],apply:["Visit your designated Fair Price Shop","Aadhaar biometric verification","Collect free grains monthly"],link:"https://nfsa.gov.in/",helpline:"State food dept / 1967",amt:12000,match:p=>["below1","1to2.5"].includes(p.income)},

{name:"LPG Subsidy (PAHAL - Direct Benefit Transfer)",cat:"money",tag:"Money",benefit:"₹200-₹300 subsidy per LPG cylinder via DBT",desc:"Subsidy on LPG cylinders transferred directly to bank account after purchase. Amount varies by cylinder type and market price. For eligible households.",elig:["Indian household with LPG connection","Aadhaar-linked bank account","Income below threshold (voluntary give-up for high-income)"],docs:["LPG connection with Aadhaar seeding","Bank account linked to Aadhaar"],apply:["Automatic — subsidy credited after each cylinder purchase","Ensure Aadhaar-bank linking at gas agency"],link:"https://www.india.gov.in/",helpline:"1800-233-3555",amt:3600,match:p=>!p.special.includes("no-gas")&&["below1","1to2.5","2.5to5"].includes(p.income)},

{name:"PM UJALA (LED Bulbs at ₹10)",cat:"money",tag:"Money",benefit:"LED bulbs at ₹10 each (70% cheaper than market) — save ₹1,500/year on bills",desc:"High-quality 9W LED bulbs at just ₹10 each. Saves 85W per bulb vs incandescent. Average family saves ₹1,500/year. 36+ crore bulbs distributed.",elig:["Any domestic electricity consumer","Show latest electricity bill at distribution centre"],docs:["Latest electricity bill"],apply:["Visit UJALA distribution centre (usually at DISCOM offices)","Show electricity bill","Buy LED bulbs at ₹10 each"],link:"https://www.ujala.gov.in/",helpline:"State DISCOM helpline",amt:1500,match:p=>true},

{name:"PM Surya Ghar Muft Bijli",cat:"housing",tag:"Housing",benefit:"₹30K-₹78K subsidy for rooftop solar + 300 units free electricity/month",desc:"Rooftop solar subsidy. ₹30K for 1kW, ₹60K for 2kW, ₹78K for 3kW+. Generates 300 units/month free. Target: 1 crore homes. Net metering: sell excess to grid.",elig:["All residential households","Must have suitable rooftop","Grid-connected electricity"],docs:["Electricity bill","Aadhaar","Property proof/NOC","Bank passbook"],apply:["pmsuryaghar.gov.in","Register with electricity bill","Select vendor","Subsidy after installation"],link:"https://pmsuryaghar.gov.in/",helpline:"1800-180-3333",amt:78000,match:p=>p.ownHouse==="yes"},

{name:"Fertilizer Subsidy (Neem-Coated Urea + DBT)",cat:"agriculture",tag:"Agriculture",benefit:"Urea at ₹242/bag (govt price) vs ₹900+ actual cost — 73% subsidy",desc:"Government subsidizes ~73% of fertilizer cost. Urea fixed at ₹242/45kg bag. DAP, MOP, NPK also subsidized. Subsidy paid directly to fertilizer companies on farmer's behalf.",elig:["All farmers purchasing fertilizers","Through authorized dealers/retailers","Aadhaar verification at point of sale"],docs:["Aadhaar (verified at fertilizer shop via PoS machine)"],apply:["Buy fertilizer at any authorized shop","Aadhaar fingerprint verified at PoS","You pay subsidized rate automatically"],link:"https://www.fert.nic.in/",helpline:"State agriculture dept",amt:50000,match:p=>p.employment==="farmer"},

{name:"National Social Assistance Programme (NSAP) — All Pensions",cat:"senior",tag:"Senior",benefit:"₹200-₹500/month pensions: old age, widow, disability (BPL)",desc:"Umbrella for 5 central pension schemes: IGNOAPS (old age), IGNWPS (widow), IGNDPS (disability), NFBS (family benefit ₹20K), Annapurna (10kg free grain for uncovered elderly).",elig:["BPL families","Old age: 60+, Widow: 40+, Disability: 18+ (80%+)","NFBS: death of breadwinner in BPL family"],docs:["Aadhaar","Age/death/disability proof","BPL card","Bank passbook"],apply:["nsap.nic.in","Through Panchayat/Municipality","State social welfare dept"],link:"https://nsap.nic.in/",helpline:"State SW dept",amt:6000,match:p=>(p.age>=60||p.lifeStage.includes("widow")||p.lifeStage.includes("disabled"))&&["below1","1to2.5"].includes(p.income)},

{name:"National Family Benefit Scheme (NFBS)",cat:"money",tag:"Money",benefit:"₹20,000 lump sum on death of breadwinner in BPL family",desc:"One-time ₹20,000 assistance to BPL family on death of primary breadwinner (age 18-59). Under NSAP umbrella.",elig:["BPL family","Death of breadwinner aged 18-59","Male or female breadwinner"],docs:["Death certificate","BPL card","Aadhaar of applicant","Bank passbook","FIR/post-mortem (if applicable)"],apply:["Apply within 1 year of death","Through Panchayat/Municipal office","nsap.nic.in"],link:"https://nsap.nic.in/",helpline:"State SW dept",amt:20000,match:p=>["below1","1to2.5"].includes(p.income)},

{name:"Annapurna Scheme",cat:"senior",tag:"Senior",benefit:"10 kg free food grains/month for elderly not covered under NSAP",desc:"10 kg rice/wheat per month free for destitute elderly (65+) who are eligible for old age pension but not receiving it.",elig:["Age 65+","Eligible for IGNOAPS but not receiving it","Destitute with no regular income"],docs:["Age proof","Aadhaar","Income declaration"],apply:["Through Panchayat/Municipal office","Distributed through PDS"],link:"https://nsap.nic.in/",helpline:"State food dept",amt:3000,match:p=>p.age>=65&&["below1"].includes(p.income)},

{name:"Public Provident Fund (PPF)",cat:"pension",tag:"Savings",benefit:"7.1% tax-free returns + EEE status — safest long-term savings",desc:"15-year savings instrument. 7.1% p.a. (compounded annually). EEE tax benefit. Min ₹500/year, max ₹1.5L/year. Loan against PPF from 3rd year. Partial withdrawal from 7th year.",elig:["Any Indian citizen (NRIs cannot open new)","One account per person","Can open for minor child"],docs:["Aadhaar","PAN","Photograph","Address proof"],apply:["Visit any Post Office or authorized bank","Fill PPF opening form","Min deposit ₹500"],link:"https://www.indiapost.gov.in/",helpline:"1800-266-6868",amt:150000,match:p=>p.age>=18&&p.bankAccount==="yes"},

{name:"National Savings Certificate (NSC)",cat:"pension",tag:"Savings",benefit:"7.7% guaranteed returns + 80C tax deduction",desc:"5-year fixed deposit with post office. 7.7% p.a. compounded annually. Tax deduction under 80C on investment. Interest reinvested counts as fresh 80C investment.",elig:["Any Indian resident","No max limit","Min ₹1,000"],docs:["Aadhaar","PAN","Photograph"],apply:["Visit any Post Office","Fill NSC purchase form","Min investment ₹1,000"],link:"https://www.indiapost.gov.in/",helpline:"1800-266-6868",amt:100000,match:p=>p.age>=18},

{name:"Kisan Vikas Patra (KVP)",cat:"pension",tag:"Savings",benefit:"Money doubles in 115 months (7.5% interest)",desc:"Post office savings instrument where money doubles. Current rate: 7.5% → doubles in 115 months (~9.5 years). No max limit. Transferable.",elig:["Any Indian citizen","Trusts, HUFs also eligible","Min ₹1,000"],docs:["Aadhaar","PAN (for ₹50K+)","Photograph"],apply:["Visit any Post Office","Purchase KVP certificate"],link:"https://www.indiapost.gov.in/",helpline:"1800-266-6868",amt:100000,match:p=>p.age>=18},

// ═══ HOUSING FINANCE (166-170) ═══
{name:"PM Urban Housing Interest Subsidy (CLSS)",cat:"housing",tag:"Housing",benefit:"6.5% interest subsidy on home loans for EWS/LIG (NPV up to ₹2.67L)",desc:"Credit Linked Subsidy under PMAY-U. 6.5% subsidy for EWS (<₹3L income) and LIG (₹3-6L). Subsidy NPV up to ₹2,67,280. Loan tenure up to 20 years.",elig:["First-time home buyer","EWS: income <₹3L | LIG: ₹3-6L","No pucca house in family name","Urban area"],docs:["Income certificate","Aadhaar of all family members","No-house affidavit","Bank loan application"],apply:["Apply for home loan at any bank/HFC","Bank applies CLSS automatically","Subsidy credited upfront to loan account","pmaymis.gov.in for tracking"],link:"https://pmaymis.gov.in/",helpline:"1800-11-6163",amt:267000,match:p=>["urban","semi-urban"].includes(p.area)&&p.ownHouse!=="yes"&&["below1","1to2.5","2.5to5"].includes(p.income)},

// ═══ DIGITAL INDIA & GOVERNANCE (171-180) ═══
{name:"DigiLocker",cat:"money",tag:"Money",benefit:"Free cloud storage for all government documents — paperless governance",desc:"Free digital storage of all government-issued documents: Aadhaar, PAN, driving licence, vehicle RC, marksheets, certificates. Legally valid digital copies. No need to carry physical documents.",elig:["Any Indian citizen with Aadhaar","Free — no charges"],docs:["Aadhaar (for registration)"],apply:["digilocker.gov.in OR download DigiLocker app","Register with Aadhaar OTP","Pull documents from issuing departments"],link:"https://digilocker.gov.in/",helpline:"011-24303714",amt:0,match:p=>true},

{name:"UMANG App (Unified Mobile App for Governance)",cat:"money",tag:"Money",benefit:"400+ government services on one app — pan-India",desc:"Single mobile app for accessing 400+ government services: EPFO, Aadhaar, DigiLocker, income tax, passport, scholarships, gas booking, rail tickets, etc.",elig:["Any Indian citizen with smartphone"],docs:["Aadhaar (for registration)"],apply:["Download UMANG app from Play Store/App Store","Register with mobile number","Access 400+ services"],link:"https://web.umang.gov.in/",helpline:"1800-115-246",amt:0,match:p=>true},

{name:"ABHA (Ayushman Bharat Health Account)",cat:"health",tag:"Health",benefit:"Free digital health ID — store all medical records digitally",desc:"14-digit health ID for every Indian. Store prescriptions, lab reports, discharge summaries digitally. Share with any hospital/doctor. Part of National Digital Health Mission.",elig:["Any Indian citizen","No age or income restriction"],docs:["Aadhaar OR Driving Licence"],apply:["abha.abdm.gov.in","OR Health ID section in Aadhaar app","Create in 2 minutes with Aadhaar OTP"],link:"https://abha.abdm.gov.in/",helpline:"1800-114-477",amt:0,match:p=>true},

{name:"Common Service Centres (CSC)",cat:"money",tag:"Money",benefit:"Access 400+ government and private services at your village",desc:"4+ lakh CSCs across India delivering government services at the last mile: Aadhaar enrollment, banking, insurance, pension, bill payment, digital literacy, telemedicine.",elig:["Any citizen can avail services","Small fee may apply for some services"],docs:["Varies by service"],apply:["Visit nearest CSC","Find CSC: locator.csccloud.in","Services available on the spot"],link:"https://csc.gov.in/",helpline:"1800-121-3468",amt:0,match:p=>true},

{name:"e-Shram Portal (Unorganized Worker Registration)",cat:"money",tag:"Money",benefit:"Free registration → ₹2L accident insurance + access to all welfare schemes",desc:"National database for unorganized workers. Registration gives ₹2L accident insurance (PMSBY) and links to all welfare schemes. 30+ crore workers registered.",elig:["Any unorganized worker aged 16-59","Not an EPFO/ESIC member","Self-employed, daily wage, domestic worker, street vendor, construction worker, gig worker, etc."],docs:["Aadhaar","Bank passbook","Mobile number"],apply:["eshram.gov.in","Self-registration with Aadhaar OTP","OR register at CSC for ₹20","e-Shram card downloaded instantly"],link:"https://eshram.gov.in/",helpline:"14434",amt:200000,match:p=>["self-employed","business"].includes(p.employment)&&!["above25","10to25"].includes(p.income)},

{name:"PM Digital Literacy Mission (PMGDISHA)",cat:"education",tag:"Education",benefit:"Free digital literacy training for rural households",desc:"Free 20-hour computer/digital training for one person per rural household. Covers: computer basics, internet, email, digital payments, government services.",elig:["One person per rural household (9-59 years)","Non-digitally literate","Priority: SC/ST/BPL/women/minorities/PwD"],docs:["Aadhaar","Bank passbook"],apply:["Visit nearest CSC/training centre","pmgdisha.in for centre locator","Free 20-hour training + certification"],link:"https://www.pmgdisha.in/",helpline:"1800-121-3468",amt:0,match:p=>p.area==="rural"},

// ═══ TRANSPORT & TRAVEL CONCESSIONS (181-185) ═══
{name:"Railway Concessions for Senior Citizens/Disabled/Students",cat:"senior",tag:"Senior",benefit:"40-75% concession on rail travel for seniors, PwDs, students",desc:"Indian Railways concessions: Senior women 50% (58+), Senior men 40% (60+), Disabled 75%, Students 25-50%, War widows 75%, Journalists 50%, Cancer/Thalassemia patients 75%.",elig:["Senior citizens (men 60+, women 58+)","PwDs with disability certificate","Students with bonafide certificate","Patients with medical certificate"],docs:["Age proof (seniors)","Disability certificate (PwDs)","Bonafide/medical certificate"],apply:["Book ticket with concession through IRCTC/counter","Show ID proof during travel"],link:"https://www.irctc.co.in/",helpline:"139",amt:0,match:p=>p.age>=58||p.lifeStage.includes("disabled")||p.employment==="student"},

// ═══ FOOD SECURITY & NUTRITION (186-190) ═══
{name:"Mid-Day Meal Scheme (PM POSHAN)",cat:"education",tag:"Education",benefit:"Free cooked lunch for all government school students (Class 1-8)",desc:"Free nutritious lunch for 11.8 crore+ students in government/govt-aided schools. Menu includes rice/wheat, dal, vegetables, oil, condiments. Eggs/fruits on specific days.",elig:["All students in govt/govt-aided schools (Class 1-8)","No income/caste restriction"],docs:["None — automatic for enrolled students"],apply:["No application — provided at school during lunch break"],link:"https://pmposhan.education.gov.in/",helpline:"State education dept",amt:0,match:p=>p.lifeStage.includes("children")},

{name:"National Food Security Act (NFSA) — Subsidized Atta/Rice",cat:"money",tag:"Money",benefit:"5 kg food grains/person/month at ₹0 (free since Jan 2024)",desc:"Legal entitlement to food. 75% rural and 50% urban population covered. PHH: 5 kg/person/month. AAY: 35 kg/household/month. FREE since Jan 2024 (was ₹1-3/kg before).",elig:["PHH (Priority Household) and AAY (Antyodaya) ration card holders","State-wise identification based on SECC and other criteria"],docs:["Ration Card","Aadhaar (for biometric at FPS)"],apply:["Existing card holders: Visit FPS monthly","New card: Apply at state food department","One Nation One Ration Card: Use at any FPS in India"],link:"https://nfsa.gov.in/",helpline:"State food dept helpline",amt:12000,match:p=>["below1","1to2.5"].includes(p.income)},

{name:"Integrated Child Development Services (ICDS) — Supplementary Nutrition",cat:"women",tag:"Women",benefit:"Free supplementary nutrition for children 0-6 and pregnant/lactating women",desc:"Through 13.9 lakh Anganwadi centres. Hot cooked meal or take-home ration for: children 6 months-3 years, children 3-6 years, pregnant women, lactating mothers. 500 calories + 12-15g protein daily.",elig:["Children 6 months to 6 years","Pregnant women","Lactating mothers","All — no income restriction"],docs:["Register at Anganwadi — no formal documents needed"],apply:["Visit nearest Anganwadi Centre","Register child/mother","Receive daily supplementary nutrition"],link:"https://wcd.nic.in/",helpline:"State WCD dept",amt:0,match:p=>p.lifeStage.includes("children")||p.lifeStage.includes("pregnant")},

// ═══ EX-SERVICEMAN WELFARE (191-193) ═══
{name:"Armed Forces Flag Day Fund (AFFDF)",cat:"money",tag:"Money",benefit:"Financial assistance for ex-servicemen and war widows",desc:"Welfare fund for ex-servicemen, widows, and dependants. Grants for: housing, education, medical, penury, business. Annual grants up to ₹2-5 lakh.",elig:["Ex-servicemen and dependants","War widows","Disabled in service"],docs:["Service records","Discharge certificate","Aadhaar"],apply:["Contact Rajya/Zila Sainik Board","ksb.gov.in","Apply for specific grant scheme"],link:"https://ksb.gov.in/",helpline:"011-26192361",amt:500000,match:p=>p.special.includes("ex-serviceman")},

{name:"ECHS (Ex-Servicemen Contributory Health Scheme)",cat:"health",tag:"Health",benefit:"Cashless medical care for ex-servicemen and dependants at 2,800+ hospitals",desc:"Comprehensive healthcare for retired armed forces personnel and families. OPD, IPD, medicines, surgeries at ECHS polyclinics and empanelled hospitals.",elig:["Retired armed forces personnel","Dependants: spouse, children, parents"],docs:["ECHS card","Discharge book","PPO (Pension Payment Order)"],apply:["Apply through nearest ECHS polyclinic","Get ECHS smart card issued","Use at any ECHS polyclinic or empanelled hospital"],link:"https://echs.gov.in/",helpline:"011-23094832",amt:0,match:p=>p.special.includes("ex-serviceman")},

// ═══ LEGAL AID & JUSTICE (194-196) ═══
{name:"Free Legal Aid (NALSA)",cat:"money",tag:"Money",benefit:"100% free legal services for SC/ST, women, seniors, disabled, BPL",desc:"Free lawyer, free court fees, free legal advice for eligible categories. Through District Legal Services Authority. Lok Adalats for quick dispute resolution.",elig:["SC/ST persons","Women and children","Senior citizens (60+)","Disabled persons","BPL/low-income (annual income <₹3L)","Industrial workmen","Victims of trafficking/disaster"],docs:["Proof of eligibility category","Income certificate (for BPL)","Case details"],apply:["Contact District Legal Services Authority (DLSA)","OR call 15100 (NALSA helpline)","nalsa.gov.in","Visit nearest Taluk Legal Services Committee office"],link:"https://nalsa.gov.in/",helpline:"15100",amt:0,match:p=>["sc","st"].includes(p.category)||p.gender==="female"||p.age>=60||p.lifeStage.includes("disabled")||["below1","1to2.5"].includes(p.income)},

// ═══ MISCELLANEOUS IMPORTANT (197-200) ═══
{name:"Aadhaar (Free Enrollment and Update)",cat:"money",tag:"Money",benefit:"Free universal ID — foundation for all government services",desc:"Free 12-digit identity number for all residents. Required for all government schemes, bank accounts, SIM cards, tax filing. Free enrollment and first 2 online updates.",elig:["All residents of India","Including children (0+)"],docs:["Any one ID proof OR introducer/HOF (for new enrollment)"],apply:["Visit nearest Aadhaar Enrollment Centre","uidai.gov.in for centre locator","Free enrollment","Online update: myaadhaar.uidai.gov.in"],link:"https://uidai.gov.in/",helpline:"1947",amt:0,match:p=>true},

{name:"Passport Seva (Passport at Post Office)",cat:"money",tag:"Money",benefit:"Passport services at 428+ Post Office Passport Seva Kendras",desc:"Apply for passport at nearest post office. Reduced waiting time. POPSK in 428+ head post offices. Normal: ₹1,500 (36 pages). Tatkal: ₹3,500.",elig:["Any Indian citizen"],docs:["Aadhaar","Proof of address","Date of birth proof"],apply:["passportindia.gov.in","Book appointment at nearest POPSK/RPO","Biometric and document verification","Passport delivered by Speed Post"],link:"https://passportindia.gov.in/",helpline:"1800-258-1800",amt:0,match:p=>true},

{name:"Jan Samarth Portal (Government Loans Single Window)",cat:"business",tag:"Business",benefit:"13 government loan schemes on one portal — single application",desc:"Digital platform linking 13 government credit schemes: Mudra, Stand-Up India, PM SVANidhi, education loans, etc. Apply for multiple schemes from one portal.",elig:["Varies by scheme — portal checks eligibility"],docs:["Aadhaar","PAN","Business/education documents"],apply:["jansamarth.in","Register and check eligible schemes","Apply for multiple schemes from single dashboard","Track all applications in one place"],link:"https://www.jansamarth.in/",helpline:"Portal helpdesk",amt:0,match:p=>true},

{name:"myScheme (Government Scheme Discovery Portal)",cat:"money",tag:"Money",benefit:"Discover all government schemes you're eligible for — official govt portal",desc:"Official Government of India scheme discovery platform. Enter your profile and find schemes. Links to application portals. 500+ schemes listed.",elig:["Any Indian citizen"],docs:["None — discovery tool"],apply:["myscheme.gov.in","Enter demographic details","View eligible schemes","Link to apply for each scheme"],link:"https://www.myscheme.gov.in/",helpline:"support-myscheme@digitalindia.gov.in",amt:0,match:p=>true},
];

if(typeof module!=='undefined')module.exports={CENTRAL_SCHEMES_2};
