// ═══════════════════════════════════════════════════════════════
// MERA HAQ — CENTRAL GOVERNMENT SCHEMES DATABASE (Part 3: 201-300)
// Last Updated: March 2026
// ═══════════════════════════════════════════════════════════════
// NEW CATEGORIES COVERED (not in Parts 1 & 2):
// Digital India, Sports & Youth, Environment, Urban Development,
// Minority Welfare, Fisheries, Textile/Handloom, Tourism,
// Cooperative/Rural Credit, Startup/Innovation Deep, Tribal Welfare,
// Senior Citizen Extended, Child-specific, Water & Sanitation,
// Infrastructure Access, Self-Help Groups, Farmer Extended
// ═══════════════════════════════════════════════════════════════

export const CENTRAL_SCHEMES_3 = [

// ═══ DIGITAL INDIA & TECHNOLOGY (201-215) ═══
{name:"PM WANI (Wi-Fi Access Network Interface)",cat:"digital",tag:"Digital",benefit:"Free/cheap public Wi-Fi via PDO hotspots across India",desc:"Decentralized public Wi-Fi network via small shops and businesses as PDOs (Public Data Offices). No licence needed for PDOs. Cheap broadband for citizens. 1 lakh+ hotspots operational.",elig:["Any citizen with smartphone","No income restriction"],docs:["None — scan QR / use app"],apply:["Find nearest PM-WANI hotspot via app","tec.gov.in for PDO registration","Any shop can become a PDO with router — no licence fee"],link:"https://dot.gov.in/",helpline:"DoT helpline: 1800-11-0420",amt:0,match:p=>p.needs.includes("digital")||p.area==="rural"},

{name:"DigiLocker (Free Secure Digital Document Wallet)",cat:"digital",tag:"Digital",benefit:"Free secure digital locker for all govt documents — legally valid",desc:"Government cloud storage for digital documents. Store Aadhaar, PAN, driving licence, marksheets, RC, insurance. Linked to 1,600+ government issuers. Legally equivalent to physical documents.",elig:["Any Indian resident with Aadhaar and mobile number"],docs:["Aadhaar","Mobile number linked to Aadhaar"],apply:["digilocker.gov.in OR Umang app","Sign up with Aadhaar + OTP","Fetch documents from linked issuers"],link:"https://digilocker.gov.in/",helpline:"1800-889-1004",amt:0,match:p=>true},

{name:"BharatNet (Rural Broadband Connectivity)",cat:"digital",tag:"Digital",benefit:"High-speed broadband to all 6.4 lakh gram panchayats",desc:"Optical fibre network connecting all gram panchayats. Provides cheap broadband to rural India. Wi-Fi hotspots at GP level. 200+ mbps to GPs.",elig:["All rural citizens — infrastructure benefit","CSC operators, gram panchayats"],docs:["None for usage","Aadhaar for connection"],apply:["Access broadband through BharatNet at GP/CSC","bbnl.nic.in for operator info"],link:"https://bbnl.nic.in/",helpline:"1800-180-1515",amt:0,match:p=>p.area==="rural"&&p.needs.includes("digital")},

{name:"PM eVIDYA (Digital Education Platform)",cat:"digital",tag:"Digital",benefit:"Free digital education: DTH TV channels + DIKSHA app + SWAYAM",desc:"Multi-mode digital education: DIKSHA app (370+ crore downloads), PM eVIDYA DTH channels (one per state, Classes 1-12), SWAYAM for UG/PG free online courses. NIOS for dropouts.",elig:["All students — no restriction","School and college level"],docs:["None for free content"],apply:["diksha.gov.in (free app)","TV: Swayam Prabha DTH channels (free to air)","swayam.gov.in for college courses"],link:"https://diksha.gov.in/",helpline:"Diksha helpline: 1800-11-4555",amt:0,match:p=>p.employment==="student"||p.needs.includes("education")},

{name:"Common Service Centres (CSC) — Government Services at Doorstep",cat:"digital",tag:"Digital",benefit:"300+ government services at nearest village-level CSC",desc:"1.9 lakh+ CSCs providing government services in rural areas: Aadhaar enrolment, insurance, banking, passport, PAN, pension, certificates. VLE (Village Level Entrepreneur) model.",elig:["All citizens for services","Rural unemployed youth to become VLE"],docs:["Varies by service"],apply:["Locate nearest CSC: locator.csccloud.in","Apply for VLE: register.csc.gov.in","Minimum 10th pass for VLE registration"],link:"https://www.csc.gov.in/",helpline:"1800-121-3468",amt:0,match:p=>p.area==="rural"},

{name:"UMANG App (Unified Mobile Application for New Governance)",cat:"digital",tag:"Digital",benefit:"1,600+ government services on single mobile app",desc:"Unified app for central and state government services: EPFO, NPS, Aadhaar, PM-KISAN, tax, passport, scholarship, electricity. Free download on Android and iOS.",elig:["Any Indian with smartphone"],docs:["Varies by service"],apply:["Download Umang app from Play Store/App Store","Login with mobile number","Access all government services in one place"],link:"https://web.umang.gov.in/",helpline:"1800-11-5246",amt:0,match:p=>true},

{name:"India Stack / ABHA Health ID",cat:"digital",tag:"Digital",benefit:"Free unified health ID — all medical records in one place",desc:"Ayushman Bharat Health Account (ABHA) — 14-digit health ID linking all your medical records, prescriptions, reports across hospitals. Supports Ayushman Bharat Digital Mission.",elig:["Any Indian resident"],docs:["Aadhaar OR mobile number","PAN (optional)"],apply:["abdm.gov.in OR Ayushman Bharat app","Create ABHA account free","Link health records from any ABDM-linked hospital"],link:"https://abdm.gov.in/",helpline:"1800-11-4477",amt:0,match:p=>p.needs.includes("health")},

{name:"GeM (Government e-Marketplace) — Seller Registration",cat:"business",tag:"Business",benefit:"Sell directly to govt agencies — ₹2.01 lakh crore+ transactions",desc:"Government's online marketplace for goods and services. MSMEs, startups, women entrepreneurs get priority. No commission for transactions below ₹5 lakh. 70,000+ buyer organisations.",elig:["Any Indian MSME, manufacturer, service provider","Startups, artisans, SHGs, women entrepreneurs","Must be registered business"],docs:["PAN","Aadhaar","MSME/GST registration","Bank account"],apply:["gem.gov.in → Seller Registration","Upload business documents","Create product/service catalogue","Bid for tenders and receive orders"],link:"https://gem.gov.in/",helpline:"1800-419-3436",amt:0,match:p=>["self-employed","business"].includes(p.employment)},

{name:"Startup India (DPIIT Recognition + Tax Benefits)",cat:"business",tag:"Business",benefit:"3-year income tax exemption + no angel tax + SEBI fast-track for recognized startups",desc:"DPIIT-recognized startups get: 3-year income tax holiday (80-IAC), no capital gains tax (54GB), no angel tax (Section 56), patent fee 80% rebate, faster insolvency resolution. 1.40 lakh+ recognized startups.",elig:["Company/LLP/Partnership incorporated <10 years","Turnover <₹100 crore in any year","Working on innovative product/process/service","Not formed by splitting existing business"],docs:["Incorporation certificate","PAN","Innovation description","Self-certification"],apply:["startupindia.gov.in → Apply for Recognition","Free DPIIT recognition in 1-2 days","Apply for 80-IAC tax exemption separately (CBDT)"],link:"https://www.startupindia.gov.in/",helpline:"1800-115-565",amt:0,match:p=>p.bizType==="startup"},

{name:"PM Gati Shakti — Infrastructure Planning Tool",cat:"digital",tag:"Digital",benefit:"Free enterprise GIS platform for project planning and connectivity",desc:"National Master Plan integrating 16 ministries' infrastructure plans on one GIS platform. PM Gati Shakti portal enables integrated planning. States can access for project planning.",elig:["Government departments, state agencies, large project developers"],docs:["Official government login"],apply:["pmgatishakti.gov.in"],link:"https://pmgatishakti.gov.in/",helpline:"DPIIT helpline",amt:0,match:p=>["self-employed","business"].includes(p.employment)&&p.bizType==="startup"},

{name:"Atal Innovation Mission (AIM) — Atal Tinkering Labs",cat:"education",tag:"Education",benefit:"₹20 lakh setup grant for school Tinkering Labs",desc:"ATLs in 10,000+ schools with tools for 3D printing, robotics, electronics, IoT. Free for students. Annual Innovation Festival. ₹1 lakh prize for Atal New India Challenge.",elig:["School students: free access at ATL schools","Schools: apply for ATL grant (govt/aided schools)","Innovators: apply for Atal New India Challenge"],docs:["School: Application through AIM portal","Students: attend ATL school"],apply:["aim.gov.in","Schools apply for ATL setup grant","Students participate through school"],link:"https://aim.gov.in/",helpline:"011-23048853",amt:1000000,match:p=>p.employment==="student"},

{name:"Meity Startup Hub — Technology Startup Support",cat:"business",tag:"Business",benefit:"Funding, mentorship, market access for deep-tech startups",desc:"MeitY's initiative for technology startups. Supports AI, cybersecurity, quantum, IoT, semiconductors. Connects with investors, mentors, government buyers. Free incubation at partner hubs.",elig:["Technology startups","DPIIT recognized preferred","Working in digital/deep-tech domain"],docs:["DPIIT recognition","Business plan","Demo/prototype"],apply:["msins.in","Apply for incubation support","Access investor network"],link:"https://msins.in/",helpline:"support@msins.in",amt:2000000,match:p=>p.bizType==="startup"&&p.needs.includes("business")},

{name:"Digital Saksharta Abhiyan (PMGDISHA)",cat:"digital",tag:"Digital",benefit:"Free digital literacy training for rural households",desc:"Making 6 crore rural households digitally literate. Free 20-hour training covering: internet, email, digital payments, govt services online. Certificate from NIELIT.",elig:["Rural household members aged 14-60","Non-digitally literate individuals","Priority: SC/ST, minorities, BPL, differently abled, women"],docs:["Aadhaar","Photograph"],apply:["pmgdisha.in","Contact nearest CSC for enrolment","Free training at CSC or designated centre"],link:"https://pmgdisha.in/",helpline:"1800-3000-3468",amt:0,match:p=>p.area==="rural"&&p.needs.includes("digital")},

{name:"National Supercomputing Mission (NSM) — Research Access",cat:"digital",tag:"Digital",benefit:"Free HPC computing access for researchers at national supercomputing facilities",desc:"₹4,500 crore mission to set up 70+ supercomputers. Free HPC access for researchers at IITs, IISc, IISER, national labs. Param Siddhi, Param Brahma, Param Porul etc.",elig:["Researchers, PhD scholars, faculty at institutions","National labs, IITs, IISc, central universities"],docs:["Institutional affiliation proof","Research proposal"],apply:["npsf.iit.ac.in (National Param Supercomputing Facility)","Apply through institution","HPC allocation based on research merit"],link:"https://nsm.gov.in/",helpline:"NSM helpdesk",amt:0,match:p=>p.employment==="student"&&p.needs.includes("education")},

// ═══ SPORTS & YOUTH (216-225) ═══
{name:"Khelo India Programme",cat:"sports",tag:"Sports",benefit:"₹6.28 lakh/year scholarship for 2,500+ talented young athletes",desc:"₹6.28 lakh/year scholarship for 8 years to identified talent. Khelo India Games (national multi-sport event). Infrastructure in schools and sports academies. Rehabilitation for injured athletes.",elig:["Young athletes aged 8-18","Identified through selection trials","Sports: 40+ disciplines"],docs:["Age proof","Sport achievement certificates","School certificate"],apply:["kheloindia.gov.in","Attend district/state Khelo India selection","OR Khelo India Games participation"],link:"https://kheloindia.gov.in/",helpline:"1800-208-9155",amt:628000,match:p=>p.age>=8&&p.age<=18&&p.needs.includes("sports")},

{name:"Target Olympic Podium Scheme (TOPS)",cat:"sports",tag:"Sports",benefit:"₹50,000/month cash support + foreign training for top athletes",desc:"Elite support for Olympic/Paralympic medal prospects. Monthly cash support, customized training abroad, best coaches, equipment, exposure tours, diet/nutrition support. Select 150+ athletes.",elig:["Athletes with realistic medal prospects at Olympics/Paralympics/Asian/CWG","Identified by SAI TOPS committee"],docs:["National/International performance record","NOC endorsement"],apply:["sportsindia.gov.in → TOPS","Recommendation through National Sports Federation","Annual review of beneficiaries"],link:"https://sportsindia.gov.in/",helpline:"SAI: 011-24362104",amt:600000,match:p=>p.needs.includes("sports")&&p.age>=15&&p.age<=35},

{name:"Nehru Yuva Kendra Sangathan (NYKS)",cat:"youth",tag:"Youth",benefit:"Free youth club membership + skill development + leadership training",desc:"World's largest youth organization. 8,000+ NYKCs. Free membership for rural youth 15-29. Activities: skill training, sports, cultural, national integration. Volunteer for government programmes.",elig:["Rural youth aged 15-29","No income/category restriction"],docs:["Age proof","Aadhaar"],apply:["Register at nearest Nehru Yuva Kendra","OR nyks.nic.in","Form youth club in your village (minimum 15 members)"],link:"https://www.nyks.nic.in/",helpline:"011-23073030",amt:0,match:p=>p.age>=15&&p.age<=29&&p.area==="rural"},

{name:"National Discipline Scheme for Youth in Sports (NSFs)",cat:"sports",tag:"Sports",benefit:"Free coaching, equipment, nutrition support via national federations",desc:"National Sports Federations (Hockey India, BCCI, AFI etc.) provide free talent identification, coaching, training kits, competition exposure through NSF programmes. State-level referral to national camps.",elig:["Youth with exceptional talent in specific sport","Age criteria varies by sport"],docs:["Performance records","Medical fitness certificate","Age proof"],apply:["Register with State Sports Association","Attend district/state trials","Selected players referred to national camp"],link:"https://sportsindia.gov.in/",helpline:"SAI helpline: 011-24362104",amt:0,match:p=>p.age<=25&&p.needs.includes("sports")},

{name:"PM YuvaShakti (National Youth Policy)",cat:"youth",tag:"Youth",benefit:"Internships, innovation grants, leadership programs for youth 15-29",desc:"Umbrella youth policy with multiple interventions: internship with PSUs, innovation challenge grants, Yuva Sangam cultural exchange, volunteer programmes. Links skill development with nation-building.",elig:["Youth aged 15-29","Various sub-schemes have specific criteria"],docs:["Aadhaar","Educational certificates","Varies by scheme"],apply:["mygov.in for challenges and programmes","NYKS portal for local activities"],link:"https://www.nyks.nic.in/",helpline:"1800-11-2525",amt:50000,match:p=>p.age>=15&&p.age<=29},

{name:"Sports Authority of India (SAI) Training Centres (STC/SAG/NCOE)",cat:"sports",tag:"Sports",benefit:"Free residential training at 28 SAI centres + ₹2,500/month pocket money",desc:"Free residential sports training at SAI Training Centres, Special Area Games centres, National Centres of Excellence. Free food, accommodation, coaching, equipment. ₹2,500/month pocket money.",elig:["Young athletes 8-25 years","Talent trial-based selection","30+ sports disciplines"],docs:["Age proof","School TC","Previous sports achievements","Medical certificate"],apply:["sportsindia.gov.in → Training","Attend SAI selection trials in your district","State referral also accepted"],link:"https://sportsindia.gov.in/",helpline:"011-24362104",amt:30000,match:p=>p.age>=8&&p.age<=25&&p.needs.includes("sports")},

{name:"YUVA PM Mentorship Programme",cat:"youth",tag:"Youth",benefit:"₹50,000/month stipend for 6-month mentorship with distinguished personalities",desc:"45 young authors/innovators selected annually. 6-month mentorship by eminent personalities. Monthly stipend. Published/showcased work. Applications through national contest.",elig:["Indian citizen below 30","Students, professionals, writers, innovators","Specific contest in announced area each year"],docs:["Aadhaar","Writing/innovation sample","Qualification certificates"],apply:["innovateindia.mygov.in","Online contest — open submission","Jury selection from shortlisted candidates"],link:"https://innovateindia.mygov.in/",helpline:"MyGov: 1800-11-0088",amt:300000,match:p=>p.age<=30},

{name:"Fit India Movement",cat:"sports",tag:"Sports",benefit:"Free fitness events, tracking app, gym discount tie-ups",desc:"National fitness campaign. Fit India app for tracking. Fit India School certification. District-level Fit India competitions. Yoga sessions, cycling events, walkathons. MoUs with Cult.fit and other gyms for discounts.",elig:["Any Indian citizen","Schools, colleges, corporates can apply for certification"],docs:["None for participation"],apply:["fitindia.gov.in","Download Fit India app","Participate in local Fit India events"],link:"https://fitindia.gov.in/",helpline:"011-24361606",amt:0,match:p=>true},

{name:"National Youth Corps (NYC)",cat:"youth",tag:"Youth",benefit:"₹5,000/month stipend for youth serving in underserved communities for 1 year",desc:"Selected youth serve for 12 months in rural/underserved areas: teaching, health camps, tree plantation, cleanliness drives. Stipend ₹5,000/month. Certificate recognized for government jobs.",elig:["Youth aged 18-29","Any educational background","Not employed/in college"],docs:["Aadhaar","Age proof","Educational certificate","Photograph"],apply:["nyks.nic.in → NYC registration","Selection through district NYKS office","Medical fitness required"],link:"https://www.nyks.nic.in/",helpline:"011-23073030",amt:60000,match:p=>p.age>=18&&p.age<=29&&p.employment==="unemployed"},

// ═══ ENVIRONMENT & CLEAN ENERGY (226-235) ═══
{name:"National Clean Air Programme (NCAP)",cat:"environment",tag:"Environment",benefit:"Anti-pollution measures in 130 non-attainment cities",desc:"Target: 40% reduction in PM2.5/PM10 by 2026 in 131 cities. City-specific action plans. Electric buses, smog towers, green zones, EV charging. Real-time air quality dashboards.",elig:["All citizens — infrastructure programme"],docs:["NA"],apply:["Check NCAP city action for your city at prana.cpcb.gov.in"],link:"https://cpcb.nic.in/",helpline:"CPCB: 011-43102030",amt:0,match:p=>p.needs.includes("environment")},

{name:"FAME India Phase II (EV Subsidy)",cat:"environment",tag:"Environment",benefit:"₹10,000-₹1,50,000 subsidy on electric 2-wheelers, 3-wheelers, buses",desc:"₹10,000 crore scheme for electric vehicle adoption. 2-wheelers: up to ₹15,000 subsidy. E-rickshaws: up to ₹50,000. Electric buses: ₹50-55 lakh. 7,432 EV charging stations sanctioned.",elig:["Individual buyers of eligible EVs","Fleet operators","State transport undertakings"],docs:["Purchase invoice","Aadhaar","Bank passbook","Vehicle registration"],apply:["Subsidy deducted upfront at dealer","Buy from FAME-empanelled dealer","emissionscontrol.in for empanelled list"],link:"https://fame2.heavyindustries.gov.in/",helpline:"HI Ministry: 011-23063832",amt:150000,match:p=>p.needs.includes("vehicle")||p.needs.includes("business")},

{name:"PM Green Hydrogen Mission",cat:"environment",tag:"Environment",benefit:"₹19,744 crore for green hydrogen ecosystem — SIGHT incentives for producers",desc:"Targets 5 MMT green hydrogen by 2030. SIGHT incentives: ₹30-50/kg for green hydrogen producers. Electrolyser manufacturing incentive. 125 GW renewable energy linked.",elig:["Green hydrogen producers","Electrolyser manufacturers","Pilot project developers"],docs:["Company registration","Project feasibility report","MoP/MNRE approval"],apply:["mnre.gov.in/hydrogen","Apply through SECI/NTPC for SIGHT incentive","RFPs issued by MNRE"],link:"https://mnre.gov.in/hydrogen/",helpline:"MNRE: 011-24360707",amt:50000000,match:p=>p.bizType==="startup"||["self-employed","business"].includes(p.employment)},

{name:"National Adaptation Fund for Climate Change (NAFCC)",cat:"environment",tag:"Environment",benefit:"Project grants for states to adapt to climate change impacts",desc:"Funding for state-level climate adaptation projects: drought-resistant crops, coastal protection, urban flood management, glacier-fed irrigation. ₹100-200 crore per project.",elig:["State governments","State agencies","Civil society with state support"],docs:["Project Concept Note (PCN)","State govt endorsement"],apply:["nafcc.nic.in","Submit PCN to National Implementing Entity (NABARD/SIDBI)","Full project document after PCN approval"],link:"https://nafcc.nic.in/",helpline:"MoEFCC: 011-24695197",amt:200000000,match:p=>p.needs.includes("agriculture")||p.area==="rural"},

{name:"Nal Jal Har Ghar (Jal Jeevan Mission)",cat:"water",tag:"Water",benefit:"Free/subsidized tap water connection at home in rural areas",desc:"Tap water to every rural household. 77% coverage (15.36 crore connections). Functional Household Tap Connection (FHTC). Quality testing at Jal Jeevan Labs.",elig:["All rural households without piped water","Priority: SC/ST habitations, aspirational districts, water-scarce areas"],docs:["Aadhaar","Household proof","Village Pani Samiti registration"],apply:["Village Pani Samiti applies on behalf of village","OR approach Block Development Officer","jaljeevanmission.gov.in for tracking"],link:"https://jaljeevanmission.gov.in/",helpline:"1800-180-7008",amt:15000,match:p=>p.area==="rural"&&p.special.includes("no-water")},

{name:"AMRUT 2.0 (Urban Water & Sewerage)",cat:"water",tag:"Water",benefit:"Piped water + sewerage connections in 500 AMRUT cities",desc:"Urban water supply and sewerage for 500 cities. Target: 100% coverage in all AMRUT cities. Water supply 24x7, sewerage network, rejuvenation of water bodies. ₹2.77 lakh crore.",elig:["Urban residents in 500 AMRUT cities"],docs:["Property/utility connection application to municipal body"],apply:["Apply to your Municipal Corporation/Council for water connection","amrut.gov.in for AMRUT city list"],link:"https://amrut.gov.in/",helpline:"State urban development dept",amt:0,match:p=>p.area==="urban"},

{name:"National Biogas Programme (NBMMP)",cat:"environment",tag:"Environment",benefit:"₹10,000-₹22,000 subsidy for household biogas plants",desc:"Central subsidy for family-type biogas plants (1-6 cubic metres). Converts cattle dung to cooking gas + organic manure. ₹10,000 for small plants, higher for larger. Additional state subsidy.",elig:["Rural/semi-urban household with cattle","Minimum 2-3 cattle recommended","SC/ST get higher subsidy"],docs:["Land ownership / lease document","Aadhaar","Bank passbook","Cattle ownership proof"],apply:["Contact KVIC or state nodal agency","mnre.gov.in/biogas","Tie-up with empanelled biogas contractor"],link:"https://mnre.gov.in/",helpline:"KVIC: 022-26716969",amt:22000,match:p=>p.area==="rural"&&p.employment==="farmer"},

{name:"Pradhan Mantri JI-VAN Yojana (Ethanol from Biomass)",cat:"agriculture",tag:"Agriculture",benefit:"Viability Gap Funding for 2G ethanol plants using farm residue",desc:"Support for 2nd generation ethanol plants using rice straw, wheat straw, sugarcane bagasse. Prevents stubble burning. ₹1,800 crore VGF over 6 years. Circular economy for farmers.",elig:["Companies/cooperatives setting up 2G ethanol plants","States with agricultural residue surplus"],docs:["Company registration","Project feasibility report","Land documents","State NOC"],apply:["mopng.gov.in","Apply through Department of Food and Public Distribution","Bid process for VGF allocation"],link:"https://efts.gov.in/",helpline:"DFPD: 011-23386534",amt:10000000,match:p=>p.employment==="farmer"||p.bizType==="agri"},

{name:"MISHTI (Mangrove Initiative for Shoreline Habitats & Tangible Incomes)",cat:"environment",tag:"Environment",benefit:"Mangrove plantation on 540 sq km + livelihood for coastal communities",desc:"Budget 2023 scheme: mangrove plantation along coastline through convergence of MGNREGA and CAMPA. Livelihood for coastal fishing communities through eco-tourism, honey collection.",elig:["Coastal fishing communities","States with coastline"],docs:["Via Panchayat/MGNREGA job card for plantation work"],apply:["Participate through MGNREGA job demand in coastal Gram Panchayats","Eco-tourism activities through coastal Panchayat"],link:"https://moef.gov.in/",helpline:"MoEFCC: 011-24695197",amt:10000,match:p=>p.area==="coastal"||p.employment==="farmer"},

// ═══ MINORITY WELFARE (236-243) ═══
{name:"PM Jan Vikas Karyakram (PMJVK)",cat:"minority",tag:"Minority",benefit:"Infrastructure (schools, hospitals, skill centres) in 308 minority-concentrated districts",desc:"Multi-sectoral development of minority concentrated areas. Schools, colleges, hospitals, ITIs, hostels, skill development centres. Covers Muslim, Christian, Sikh, Buddhist, Jain, Parsi communities.",elig:["Residents of 308 identified Minority Concentration Districts","Minority community members"],docs:["Community certificate","District residency proof"],apply:["Access improved facilities in your district","Contact District Minority Welfare Officer for scheme benefits"],link:"https://www.minorityaffairs.gov.in/",helpline:"011-23813075",amt:0,match:p=>p.category==="minority"},

{name:"Seekho Aur Kamao (Learn & Earn — Minority Skill Development)",cat:"minority",tag:"Minority",benefit:"Free skill training + ₹100-150/day stipend for minority youth",desc:"Market-based skill training for minority communities. 3-6 month courses in hospitality, construction, apparel, healthcare. 75% placement commitment. Stipend during training.",elig:["Minority community members (Muslim, Christian, Sikh, Buddhist, Jain, Parsi)","Age 14-45","Educated up to Class 5 minimum"],docs:["Minority community certificate","Aadhaar","Educational certificate","Bank passbook"],apply:["minorityaffairs.gov.in","Apply through empanelled PIA (Project Implementing Agency)","OR contact State Minority Development Corporation"],link:"https://www.minorityaffairs.gov.in/",helpline:"011-23813075",amt:15000,match:p=>p.category==="minority"&&(p.employment==="unemployed"||p.needs.includes("skill"))},

{name:"Nai Manzil (Madrasa/Non-Formal Education + Skill for Minority Youth)",cat:"minority",tag:"Minority",benefit:"Free bridge education + skill training + ₹3,000/month stipend for minority school dropouts",desc:"For minority youth who left formal schooling. Provides 9-month bridge course (NIOS Class 10/12 equivalent) + vocational training. ₹3,000/month stipend. 100% residential.",elig:["Minority youth aged 17-35","Educated at madrasa or non-formal schools","Do NOT have Class 10/12 certificate"],docs:["Minority certificate","Aadhaar","Self-declaration of non-formal education"],apply:["Contact nearest approved NGO/institution","minorityaffairs.gov.in for approved institutions"],link:"https://www.minorityaffairs.gov.in/",helpline:"011-23813075",amt:27000,match:p=>p.category==="minority"&&(p.employment==="unemployed"||p.needs.includes("education"))},

{name:"Jiyo Parsi (Increasing Parsi Population)",cat:"minority",tag:"Minority",benefit:"IVF/ART subsidy + financial support for Parsi couples",desc:"Medical assistance (IVF, ART) for Parsi couples trying to have children. Cash support: ₹2,500-₹5,000/month after child birth. Counselling and awareness. Only for Parsis.",elig:["Parsi couples (both Parsi Zoroastrian)","No age restriction for awareness","Medical criteria for ART/IVF support"],docs:["Parsi community certificate from registered trust","Marriage certificate","Medical reports"],apply:["Contact Parzor Foundation","jiyo-parsi.com","Recommendation from local Parsi Panchayat"],link:"https://jiyo-parsi.com/",helpline:"011-23073000",amt:60000,match:p=>p.category==="minority"},

{name:"Hamari Dharohar (Minority Cultural Heritage)",cat:"minority",tag:"Minority",benefit:"Grants to preserve minority cultural heritage and traditions",desc:"Preserves cultural heritage of minority communities: manuscripts, monuments, traditional art, music, craft. Grants to institutions and NGOs for documentation, conservation, and promotion.",elig:["Institutions, NGOs, trusts working on minority cultural heritage","Minority community artisans"],docs:["Institution registration","Project proposal","Community endorsement"],apply:["minorityaffairs.gov.in","Submit project proposals during call for applications"],link:"https://www.minorityaffairs.gov.in/",helpline:"011-23813075",amt:1000000,match:p=>p.category==="minority"},

{name:"Garib Nawaz Skill Development Centre",cat:"minority",tag:"Minority",benefit:"Free 2-month skill training for minority youth near dargahs and mosques",desc:"Skill training centres near minority-concentrated areas and dargahs. 45+ trades. Short duration (45-60 days). Certification. Managed by MAEF (Maulana Azad Education Foundation).",elig:["Minority community youth","Age 18-45","Minimum Class 5 education"],docs:["Minority certificate","Aadhaar","Educational certificate"],apply:["maef.nic.in","Apply at nearest Garib Nawaz centre","Contact State Waqf Board for locations"],link:"https://maef.nic.in/",helpline:"011-23583788",amt:5000,match:p=>p.category==="minority"&&p.needs.includes("skill")},

{name:"Waqf Development Scheme",cat:"minority",tag:"Minority",benefit:"Grants to develop Waqf properties for community income",desc:"Central assistance to develop Waqf properties (mosques, dargahs, graveyards) into income-generating assets: commercial complexes, schools, hospitals. Income goes to minority welfare.",elig:["State Waqf Boards","Waqf mutawallis (trustees)","Muslim community institutions"],docs:["Waqf registration","State Waqf Board approval","Project proposal"],apply:["Contact State Waqf Board","Central Waqf Council: cwc.nic.in"],link:"https://cwc.nic.in/",helpline:"011-23070029",amt:5000000,match:p=>p.category==="minority"},

{name:"Concessional Education Loan for Minority Students (NSF-EL)",cat:"minority",tag:"Minority",benefit:"3% interest subvention on education loans for minority students studying abroad",desc:"Interest subsidy: 3% on education loans for minority students pursuing higher education abroad. Applies to study period + 1 year after. For recognized universities abroad.",elig:["Minority community student","Loan from a scheduled bank","Studying in top-ranked foreign institutions","Family income below ₹6 lakh"],docs:["Minority certificate","Admission letter from foreign university","Bank loan sanction letter","Income certificate"],apply:["Apply through lending bank","Bank claims subsidy from Ministry of Minority Affairs"],link:"https://www.minorityaffairs.gov.in/",helpline:"011-23813075",amt:100000,match:p=>p.category==="minority"&&p.employment==="student"},

// ═══ FISHERIES & AQUACULTURE (244-250) ═══
{name:"PM Matsya Sampada Yojana (PMMSY)",cat:"agriculture",tag:"Agriculture",benefit:"₹3-25 lakh subsidy for fisheries infrastructure (boat, net, pond, cold chain)",desc:"₹20,050 crore umbrella scheme for fisheries. Components: new fishing boats (40-60% subsidy), fish feed units, hatcheries, cold chain infrastructure, seaweed farming, cage culture, ornamental fish. Insurance for fisherfolk.",elig:["Fishermen, fish farmers, SHGs, cooperatives","Fish worker entrepreneurs","State fisheries departments"],docs:["Aadhaar","Caste certificate (SC/ST get higher subsidy)","Bank passbook","Land documents (for pond)","Boat registration"],apply:["pmmsy.dof.gov.in","OR State Department of Fisheries","District Fisheries Officer"],link:"https://pmmsy.dof.gov.in/",helpline:"1800-425-1660",amt:2500000,match:p=>p.employment==="farmer"||p.bizType==="fishing"},

{name:"Pradhan Mantri Matsya Kisan Samridhi Sah-Yojana (PM-MKSSY)",cat:"agriculture",tag:"Agriculture",benefit:"₹2 lakh micro-enterprise loan + ₹1 lakh accident cover for fish workers",desc:"₹6,000 crore to formalize and finance small fish traders, fish vendors, retail fish sellers. Micro-enterprise creation loans via FPOs. ₹1 lakh PM Suraksha Bima accident insurance.",elig:["Small fish vendors, retailers, processors","Fish worker cooperatives, FPOs","Annual turnover below ₹40 lakh"],docs:["Aadhaar","Business proof","Bank passbook"],apply:["dof.gov.in","Apply through fisheries cooperative or FPO","OR bank linkage through NABARD"],link:"https://dof.gov.in/",helpline:"1800-425-1660",amt:200000,match:p=>p.bizType==="fishing"||p.employment==="self-employed"},

{name:"Kisan Credit Card for Fishermen (KCC-Fish)",cat:"agriculture",tag:"Agriculture",benefit:"₹2 lakh revolving credit at 4% interest for fishermen (after subvention)",desc:"KCC extended to fishermen and fish farmers. Credit limit up to ₹2 lakh for working capital. 2% interest subvention (if repaid timely: effective rate 4%). Covers boat fuel, net purchase, etc.",elig:["Marine/inland fishermen","Fish farmers","SHGs, Joint Liability Groups of fishermen"],docs:["Aadhaar","Fishing licence / boat registration","Land/lease documents (for fish farmers)","Bank passbook"],apply:["Apply at any nationalized bank or cooperative bank","OR through fisheries department","OR fisheries cooperative"],link:"https://dof.gov.in/",helpline:"Nearest bank branch",amt:200000,match:p=>p.employment==="farmer"||p.bizType==="fishing"},

{name:"Blue Revolution — Integrated Development of Fisheries",cat:"agriculture",tag:"Agriculture",benefit:"₹10-50 lakh grants for aquaculture units, fish seed farms, feed mills",desc:"National Fisheries Development Board (NFDB) schemes. Subsidies for: freshwater aquaculture (25-40%), shrimp farming (25%), biofloc units (25%), recirculating aquaculture systems (40%), fish feed mills, fish processing units.",elig:["Individual fish farmers","Cooperatives, FPOs","Companies in aquaculture"],docs:["Aadhaar","Land ownership/lease","Project report","Bank passbook"],apply:["nfdb.gov.in → Subsidy Schemes","State Fisheries Department","NFDB Regional Office"],link:"https://nfdb.gov.in/",helpline:"040-24015369",amt:5000000,match:p=>p.bizType==="fishing"||p.employment==="farmer"},

{name:"National Scheme of Welfare of Fishermen",cat:"agriculture",tag:"Agriculture",benefit:"₹75,000 housing grant + boat insurance + ₹5,000 for fish festivals",desc:"Welfare for marine fishermen: ₹75,000 housing grant per house, boat insurance (premium shared), savings-cum-relief during ban period, fish melas. State-implemented.",elig:["Traditional/active marine fishermen","Below poverty line fishermen for housing"],docs:["Aadhaar","Fishing licence","BPL card","State fisherman ID card"],apply:["State Fisheries Department","District Fisheries Officer"],link:"https://dof.gov.in/",helpline:"State fisheries dept",amt:75000,match:p=>p.bizType==="fishing"},

{name:"Group Accident Insurance for Fishermen",cat:"insurance",tag:"Insurance",benefit:"₹5 lakh accident cover for fishermen at ₹ negligible premium (govt-paid)",desc:"Personal accident insurance for active fishermen going to sea. ₹5 lakh for accidental death/permanent disability. ₹2.5 lakh for partial disability. 100% premium paid by central + state govt.",elig:["Active marine fishermen","State fisherman ID card holder","Age 18-70"],docs:["Aadhaar","State Fisherman ID card","Photograph"],apply:["Auto-enrolled through State Fisheries Department","OR apply at District Fisheries Office"],link:"https://dof.gov.in/",helpline:"State fisheries dept",amt:500000,match:p=>p.bizType==="fishing"},

{name:"Seaweed Cultivation Mission",cat:"agriculture",tag:"Agriculture",benefit:"₹1-5 lakh subsidy for seaweed farming in coastal areas",desc:"New PMMSY component. Subsidy for seaweed rafts, nets, seeds. Buyback arrangements with industry. Coastal SHG women identified as primary beneficiaries. High value crop for coastal economy.",elig:["Coastal fishermen and fish workers","SHGs in coastal areas","Women in fisheries sector"],docs:["Aadhaar","State fisherman/SHG registration","Coastal land/water access proof"],apply:["State Fisheries Department","CMFRI for technical guidance: cmfri.org.in"],link:"https://pmmsy.dof.gov.in/",helpline:"1800-425-1660",amt:500000,match:p=>p.bizType==="fishing"||p.area==="coastal"},

// ═══ TEXTILE, HANDLOOM & HANDICRAFTS (251-258) ═══
{name:"PM MITRA (Mega Integrated Textile Region and Apparel Parks)",cat:"business",tag:"Business",benefit:"Plug-and-play factory in PM MITRA park — subsidized land, utilities, common facilities",desc:"7 PM MITRA parks across India. Plug-and-play factory sheds for textile manufacturers. Development Capital Support: 30% of project cost (max ₹500 crore per park). Competitive Infrastructure Fee.",elig:["Textile manufacturers (spinning, weaving, processing, apparel)","Anchor and tenant investors in PM MITRA parks"],docs:["Company registration","Project report","Environmental clearance"],apply:["texmin.nic.in/schemes","Apply to State Industrial Development Corp in relevant park state"],link:"https://texmin.nic.in/",helpline:"Textile Ministry: 011-23061236",amt:50000000,match:p=>["self-employed","business"].includes(p.employment)&&p.bizType==="textile"},

{name:"National Handloom Development Programme (NHDP)",cat:"business",tag:"Business",benefit:"₹50,000-₹2 lakh for handloom weavers — loom, yarn, design support",desc:"Comprehensive support: modern loom upgradation subsidy, yarn supply at subsidized rates, design inputs, marketing support through exhibitions. Weavers Service Centres in 25 cities for free training.",elig:["Handloom weavers","SHGs and cooperatives of weavers","BPL weavers get priority"],docs:["Weaver ID card / Pehchaan Card","Aadhaar","Bank passbook"],apply:["handlooms.gov.in","Contact your District Industry Centre OR State Handloom Corporation","Register on Bunkar Mitra portal"],link:"https://handlooms.nic.in/",helpline:"1800-208-9988",amt:200000,match:p=>p.bizType==="handloom"||p.employment==="self-employed"},

{name:"Hathkargha Samridhi Yojana (Weaver Credit Card)",cat:"business",tag:"Business",benefit:"₹2 lakh credit card for handloom weavers at 6% interest",desc:"Working capital credit for handloom weavers. Credit limit ₹2 lakh. Subsidized interest — 6% after government subvention. For purchase of yarn, dyes, loom spare parts.",elig:["Handloom weavers with Weaver ID/Pehchaan Card","Member of weavers cooperative/SHG"],docs:["Pehchaan Card","Aadhaar","Bank passbook","Cooperative membership"],apply:["Apply at nearest nationalized bank","Through weavers cooperative"],link:"https://handlooms.nic.in/",helpline:"1800-208-9988",amt:200000,match:p=>p.bizType==="handloom"},

{name:"Rajiv Gandhi Udyami Mitra Yojana (Handicraft)",cat:"business",tag:"Business",benefit:"₹1-5 lakh capital subsidy + free design training for artisans",desc:"Integrated support for handicraft artisans. Subsidy for tools and equipment. Free training at Design Resource Centres. Marketing through Crafts Museum and export promotion. Artisan Pehchaan card.",elig:["Traditional handicraft artisans","Craftspersons with Artisan ID/Pehchaan Card","Any caste/community"],docs:["Artisan Pehchaan Card","Aadhaar","Bank passbook"],apply:["handicrafts.gov.in","Contact Office of Development Commissioner (Handicrafts) in your state"],link:"https://handicrafts.gov.in/",helpline:"1800-208-0808",amt:500000,match:p=>p.bizType==="handicraft"||p.employment==="self-employed"},

{name:"SAMARTH (Scheme for Capacity Building in Textile Sector)",cat:"business",tag:"Business",benefit:"Free skill training + ₹8,000 on completion for textile workers",desc:"Placement-oriented skilling in garments, handlooms, technical textiles, carpets. 1 lakh workers/year. Free residential training. 70% placement guaranteed. ₹8,000 completion reward.",elig:["Age 14-35 (up to 45 for differently abled)","Min 5th pass for most trades","Preference: SC/ST, women, minorities, PwD"],docs:["Aadhaar","Age proof","Educational certificate","Bank passbook"],apply:["samarth.texmin.gov.in","Apply online or through training partner","Find nearest training centre on portal"],link:"https://samarth.texmin.gov.in/",helpline:"1800-208-1555",amt:8000,match:p=>p.needs.includes("skill")||(p.employment==="unemployed"&&p.age>=14&&p.age<=45)},

{name:"Raw Material Supply Scheme for Khadi (KVIC)",cat:"business",tag:"Business",benefit:"Subsidized raw material + ₹30,000-2 lakh working capital for Khadi spinners/weavers",desc:"KVIC provides raw material (cotton, wool, silk) to Khadi institutions at subsidized rates. Rebate on Khadi products: 15% extra during Gandhi Jayanti (October). Working capital loans at 6%.",elig:["Khadi artisans in KVIC-registered institutions","Khadi societies and institutions"],docs:["KVIC institution registration","Artisan membership","Aadhaar"],apply:["kvic.gov.in","Contact nearest KVIC State/Divisional Office","Register as Khadi artisan through institution"],link:"https://www.kvic.gov.in/",helpline:"022-26716969",amt:200000,match:p=>p.bizType==="khadi"||p.employment==="self-employed"},

{name:"Design Resource Centre (Craft Design Training)",cat:"business",tag:"Business",benefit:"Free design training + CAD tools + export market linkage for artisans",desc:"19 Design Resource Centres across India under O/o DC Handicrafts. Free 3-6 month design courses. CAD/CAM software training. Export promotion through participation in international fairs.",elig:["Artisans with Pehchaan card","Traditional craftspersons","Design/art graduates wanting craft specialization"],docs:["Artisan Pehchaan Card OR art degree","Aadhaar","Portfolio samples"],apply:["handicrafts.gov.in/DRC","Contact nearest DRC (Delhi, Jaipur, Varanasi, Moradabad, Mumbai etc.)"],link:"https://handicrafts.gov.in/",helpline:"1800-208-0808",amt:50000,match:p=>p.bizType==="handicraft"},

// ═══ TRIBAL WELFARE (259-266) ═══
{name:"PM Janjati Adivasi Nyaya Maha Abhiyan (PM JANMAN)",cat:"tribal",tag:"Tribal",benefit:"13 interventions for 75 PVTGs — housing, roads, mobile connectivity, livelihood",desc:"₹24,000 crore targeted for 75 Particularly Vulnerable Tribal Groups (PVTGs). Benefits: PM Awas housing (100% subsidy), all-weather roads, mobile network, solar power, drinking water, anganwadi, VHSNCs.",elig:["Members of 75 identified PVTGs","Residing in PVTG habitations"],docs:["PVTG community certificate","Aadhaar","Village/habitation residence proof"],apply:["Benefits delivered through gram sabha and district administration","pmajanman.tribal.gov.in"],link:"https://tribal.nic.in/",helpline:"011-23387505",amt:130000,match:p=>p.category==="st"&&p.special.includes("pvtg")},

{name:"Van Dhan Vikas Kendra (VDVK) — Tribal Livelihood",cat:"tribal",tag:"Tribal",benefit:"₹15 lakh seed grant for tribal SHG for MFP processing unit",desc:"Tribal SHG-based enterprise clusters for adding value to Minor Forest Produce (MFP). ₹15 lakh capital for processing units. 20+ MFPs like Mahua, Honey, Amla, Bamboo. TRIFED marketing support.",elig:["Tribal SHGs of 15-20 members","Forest dwellers with MFP access","Preferably in forest-rich districts"],docs:["SHG registration","Tribal certificate of members","Aadhaar","Bank passbook (SHG account)"],apply:["trifed.gov.in/vdvk","Contact State TRIFED or District Collector","OR approach ITDA (Integrated Tribal Development Agency)"],link:"https://www.trifed.in/",helpline:"011-23454211",amt:1500000,match:p=>p.category==="st"&&p.area==="rural"},

{name:"Minimum Support Price for Minor Forest Produce (MFP)",cat:"tribal",tag:"Tribal",benefit:"Guaranteed MSP for 90+ forest products — no middleman exploitation",desc:"TRIFED ensures MSP for 90+ MFPs: Mahua flower, Amla, Honey, Tendu leaves, Bamboo shoots, Gum Karaya etc. State agencies procure at MSP. Prevents distress sale to traders.",elig:["Tribal forest dwellers who collect MFPs","PVTG members","Any tribal living in forest areas"],docs:["Tribal certificate","Aadhaar","Community forest rights (if available)"],apply:["Contact nearest Primary Agricultural Cooperative (PACS) or LAMPS","OR Van Dhan Kendra","TRIFED: trifed.gov.in"],link:"https://www.trifed.in/",helpline:"1800-425-3839",amt:20000,match:p=>p.category==="st"&&p.area==="rural"},

{name:"Eklavya Model Residential Schools (EMRS)",cat:"tribal",tag:"Tribal",benefit:"Free quality residential education (Class 6-12) for ST children",desc:"Residential schools on par with Navodaya Vidyalayas for ST students in areas with 50%+ tribal population. ₹20,000/student/year. Sports, cultural activities, computer labs.",elig:["ST children in eligible blocks (50%+ tribal population)","Class 6-12","Free: admission, tuition, boarding, food, uniform"],docs:["ST caste certificate","Aadhaar","Previous school TC"],apply:["Apply at nearest EMRS at start of academic year","OR through State Tribal Welfare Department","emrs.tribal.gov.in"],link:"https://emrs.tribal.gov.in/",helpline:"011-23387505",amt:20000,match:p=>p.category==="st"&&(p.lifeStage.includes("children")||p.employment==="student")},

{name:"Tribal Research Institutes (TRI) — Scholarship & Research",cat:"tribal",tag:"Tribal",benefit:"Research grants + fellowship for tribal culture documentation",desc:"State TRIs with central support conduct research on tribal communities. Fellowships for tribal researchers. Documentation of tribal language, art, medicine, traditions. Central sponsorship for select research.",elig:["Tribal researchers and PhD scholars","Tribal community leaders, knowledge keepers","Social scientists studying tribal issues"],docs:["ST certificate","Research proposal","Institutional affiliation"],apply:["Contact State TRI","Ministry of Tribal Affairs: tribal.nic.in"],link:"https://tribal.nic.in/",helpline:"011-23387505",amt:500000,match:p=>p.category==="st"&&p.employment==="student"},

{name:"National/State Fellowship for Scheduled Tribe (UGC-NFST)",cat:"tribal",tag:"Tribal",benefit:"₹25,000-₹28,000/month JRF/SRF fellowship for ST PhD scholars",desc:"UGC National Fellowship for ST scholars. JRF: ₹25,000/month (2 years), SRF: ₹28,000/month (remaining years). Additional HRA. 667 fellowships per year. Any subject.",elig:["ST category student","Admitted to PhD in UGC-recognized university","NET/JRF or equivalent score preferred"],docs:["ST certificate","PhD admission letter","NET/JRF certificate","Aadhaar","Bank passbook"],apply:["scholarships.gov.in → UGC → National Fellowship for ST","Apply within UGC deadline (usually Jan-March)"],link:"https://scholarships.gov.in/",helpline:"UGC: 011-23604446",amt:336000,match:p=>p.category==="st"&&p.employment==="student"},

{name:"PM Adi Adarsh Gram Yojana",cat:"tribal",tag:"Tribal",benefit:"₹20 lakh for infrastructure in tribal-majority villages (50%+ ST population)",desc:"Integrated development of 36,000 tribal villages with 50%+ ST population. ₹20 lakh per village for gaps in: roads, electricity, drinking water, health centre, mobile connectivity. Village-level planning.",elig:["Residents of identified Adi Adarsh villages","ST community members"],docs:["Village residence proof","ST certificate"],apply:["Benefits delivered through Gram Panchayat","Identify your village through tribal.nic.in"],link:"https://tribal.nic.in/",helpline:"011-23387505",amt:20000,match:p=>p.category==="st"&&p.area==="rural"},

// ═══ URBAN DEVELOPMENT & HOUSING EXTENDED (267-274) ═══
{name:"Smart Cities Mission",cat:"housing",tag:"Housing",benefit:"Smart infrastructure — smart roads, CCTV, transit, waste mgmt in 100 cities",desc:"₹2.05 lakh crore investment in 100 selected smart cities. Projects include smart roads, LED lighting, SCADA for water, CCTV safety, integrated command centres, smart bus transit.",elig:["Residents of 100 Smart Cities","Entrepreneurs in smart city domains"],docs:["NA — infrastructure benefit"],apply:["Track projects at smartcities.gov.in","Participate in citizen consultation for your smart city SPV"],link:"https://smartcities.gov.in/",helpline:"State smart city SPV",amt:0,match:p=>p.area==="urban"},

{name:"PM SVANidhi (Street Vendor Loan Scheme)",cat:"business",tag:"Business",benefit:"₹10,000 → ₹20,000 → ₹50,000 collateral-free loan for street vendors",desc:"3-tier collateral-free loans: ₹10,000 (1st), ₹20,000 (2nd), ₹50,000 (3rd). Interest subsidy 7%. ₹1,200/year cashback on digital payments. 57 lakh+ vendors benefited.",elig:["Street vendors — both with and without certificate","Urban AND peri-urban vendors","All categories: food, clothes, fruits, repair etc."],docs:["Aadhaar","Vendor ID / LoR from ULB / Self-certification","Bank passbook"],apply:["pmsvanidhi.mohua.gov.in","OR visit nearest bank branch","OR contact urban local body for vendor ID"],link:"https://pmsvanidhi.mohua.gov.in/",helpline:"1800-11-1979",amt:50000,match:p=>p.bizType==="vendor"||p.employment==="self-employed"},

{name:"PMAY-Urban 2.0 (Interest Subsidy for Middle Income)",cat:"housing",tag:"Housing",benefit:"₹2.5 lakh interest subsidy on home loan for MIG-I and MIG-II",desc:"PMAY-U 2.0 launched Aug 2024. Target: 1 crore new houses. CLSS (Credit Linked Subsidy) for MIG: ₹2.5 lakh subsidy for income ₹6-18 lakh. BLC for EWS/LIG: ₹1.5 lakh grant.",elig:["First-time home buyer","Annual income: EWS <₹3L, LIG ₹3-6L, MIG ₹6-18L","No pucca house in family name anywhere in India"],docs:["Aadhaar","Income proof","No property affidavit","Home loan sanction letter","Land documents"],apply:["pmaymis.gov.in","Apply through bank/HFC for CLSS","OR through state/ULB for BLC/BPS"],link:"https://pmay-urban.gov.in/",helpline:"1800-11-6163",amt:250000,match:p=>p.area==="urban"&&p.special.includes("no-home")},

{name:"Heritage City Development (HRIDAY)",cat:"housing",tag:"Housing",benefit:"Heritage infrastructure in 12 cities — ghats, temples, walkways restored",desc:"12 heritage cities: Mathura, Varanasi, Dwarka, Amritsar, Ajmer, Kanchipuram, Puri, Gaya, Badami, Warangal, Velankanni, Amaravati. Improved ghats, streetscaping, temples, lighting.",elig:["Residents and businesses in HRIDAY cities"],docs:["NA — public infrastructure"],apply:["Engage through city Heritage Management Plans"],link:"https://hridayindia.in/",helpline:"State urban development dept",amt:0,match:p=>["Mathura","Varanasi","Dwarka","Amritsar","Ajmer","Kanchipuram","Puri","Gaya"].includes(p.city)},

{name:"Pradhan Mantri Awas Yojana Gramin (PMAY-G) 2.0",cat:"housing",tag:"Housing",benefit:"₹1.2-1.3 lakh grant for rural house (₹1.3L in hilly/difficult areas)",desc:"PMAY-G 2.0: Target additional 2 crore houses by 2028-29. ₹1.2 lakh (plains) + ₹3,000 for toilet (SBM) + wages (MGNREGA). Geo-tagged and tech-enabled monitoring.",elig:["Homeless or kutcha house rural household","SECC 2011 based exclusion criteria","Persons not excluded: SC/ST, minorities, freed bonded labour"],docs:["Aadhaar","Ration card","Land ownership proof","Bank passbook","MGNREGA job card"],apply:["Gram Panchayat application","State Rural Development Dept","pmayg.nic.in for tracking"],link:"https://pmayg.nic.in/",helpline:"1800-11-6446",amt:130000,match:p=>p.area==="rural"&&p.special.includes("no-home")},

{name:"Swamitva Scheme (Urban Property Rights)",cat:"housing",tag:"Housing",benefit:"Legal property ownership certificate for urban land/house",desc:"Urban extension of SVAMITVA — property rights for unauthorized colonies. ₹3,305 crore PM Uday scheme for unauthorized colonies in Delhi given ownership rights. Expanding to other states.",elig:["Residents of unauthorized/regularized colonies","Urban plot owners without legal title"],docs:["Property possession proof","Aadhaar","Old documents showing possession"],apply:["Contact State Urban Development Department","OR municipality for property regularization in your city"],link:"https://svamitva.nic.in/",helpline:"State revenue/urban dept",amt:0,match:p=>p.area==="urban"&&p.ownHouse==="yes"},

{name:"National Urban Livelihood Mission (DAY-NULM)",cat:"business",tag:"Business",benefit:"₹2 lakh SHG loan at 7% + free skill training + subsidized vendor credit",desc:"Urban poverty alleviation through: SHG formation + ₹10,000 revolving fund + ₹50,000-2L bank linkage at 7%, street vendor support, skill training, shelter for urban homeless.",elig:["Urban poor with income below ₹1 lakh/year","Priority: SC/ST, minorities, PwD, women-headed households","Urban SHGs"],docs:["Aadhaar","Income certificate","SHG membership","Bank passbook"],apply:["Contact Urban Local Body (Municipality/MC)","nulm.gov.in","Join nearest Urban SHG through municipality"],link:"https://nulm.gov.in/",helpline:"1800-11-8867",amt:200000,match:p=>p.area==="urban"&&["below1","1to2.5"].includes(p.income)},

// ═══ COOPERATIVE & RURAL CREDIT (275-280) ═══
{name:"PM Cooperative Dairy Development Programme",cat:"agriculture",tag:"Agriculture",benefit:"₹280 crore for dairy cooperatives infrastructure — milking machines, bulk milk coolers",desc:"Support for dairy cooperatives to add processing and storage capacity. Subsidized milking machines, bulk milk coolers, village-level collection infrastructure. Boost for cooperative dairy (Amul model).",elig:["Primary dairy cooperative societies","Member dairy farmers through cooperatives"],docs:["Cooperative registration","Member farmer Aadhaar","Land/cattle records"],apply:["National Cooperative Development Corporation (NCDC): ncdc.in","Contact State Cooperative Dairy Federation"],link:"https://www.ncdc.in/",helpline:"011-26561765",amt:500000,match:p=>p.employment==="farmer"},

{name:"National Cooperative Development Corporation (NCDC) Loans",cat:"business",tag:"Business",benefit:"Low-interest loans for agricultural, fishery, consumer, housing cooperatives",desc:"NCDC provides loans at 8-11% for cooperatives: processing, storage, marketing, input supply, irrigation, fishery, handloom, transport, labour cooperatives. Collateral: cooperative assets.",elig:["Registered cooperative societies","Federations of cooperatives","State cooperative institutions"],docs:["Cooperative registration","Balance sheet","Project report","Collateral documents"],apply:["ncdc.in","Submit project proposal to NCDC regional office","Or through State Cooperative Bank"],link:"https://www.ncdc.in/",helpline:"011-26561765",amt:50000000,match:p=>p.bizType==="cooperative"},

{name:"NABARD Rural Infrastructure Development Fund (RIDF)",cat:"agriculture",tag:"Agriculture",benefit:"Low-interest loans to states for rural roads, irrigation, storage infrastructure",desc:"NABARD lends to state govts at below-market rates for rural infrastructure. 29 categories: rural roads, bridges, irrigation, drinking water, health centres, schools, godowns.",elig:["State governments and state agencies"],docs:["State government project proposal"],apply:["State government applies through NABARD state office"],link:"https://www.nabard.org/",helpline:"022-26539895",amt:0,match:p=>p.employment==="farmer"},

{name:"Agri Infrastructure Fund (AIF) — Post-Harvest Infrastructure",cat:"agriculture",tag:"Agriculture",benefit:"₹2 crore loan at 3% interest subvention for warehouse, cold storage, grading unit",desc:"₹1 lakh crore fund for post-harvest infra. 3% interest subvention + CGTMSE credit guarantee. Projects: cold chains, warehouses, silos, sorting/grading units, CA chambers, primary processing centres.",elig:["Farmers, FPOs, agri-entrepreneurs, startups, cooperatives, SHGs","Project for primary agricultural produce"],docs:["Aadhaar","Land documents","Project report","Business entity registration"],apply:["agriinfra.dac.gov.in","Apply online → bank assigns project manager","Interest subvention auto-credited to account"],link:"https://agriinfra.dac.gov.in/",helpline:"1800-180-1551",amt:20000000,match:p=>p.employment==="farmer"||p.bizType==="agri"},

{name:"NABARD Farmer Producer Organisation (FPO) Promotion",cat:"agriculture",tag:"Agriculture",benefit:"₹18 lakh equity grant per FPO + ₹15 lakh bank loan at 6.5% for new FPOs",desc:"₹6,865 crore for 10,000 new FPOs. SFAC/NABARD/NCDEx implement. Equity grant matching farmer investment. Credit guarantee. Training support through CBOs. Free agri extension.",elig:["Minimum 300 farmers (100 for NE/hilly areas)","New FPO registered under Companies Act","Promoted by Cluster Based Business Organisation (CBBO)"],docs:["FPO registration","Member list with Aadhaar","Bank account","Land records of member farmers"],apply:["sfacindia.com or NABARD state office","OR connect with CBBO in your district","Find CBBO at agriinfra.dac.gov.in"],link:"https://www.sfacindia.com/",helpline:"1800-270-0224",amt:1800000,match:p=>p.employment==="farmer"},

{name:"PM Kisan Maan Dhan Yojana (Farmer Pension)",cat:"pension",tag:"Pension",benefit:"₹3,000/month pension for small farmers after 60",desc:"Pension for small/marginal farmers (land <2 hectares). Contribute ₹55-₹200/month from 18-40. Equal contribution by govt. ₹3,000/month pension after 60.",elig:["Small/marginal farmers with land below 2 ha","Age 18-40","Name in land records","Not income taxpayer"],docs:["Aadhaar","Land records (Khatauni/passbook)","Bank passbook"],apply:["maandhan.in → Farmer section","OR visit nearest CSC","PM-KISAN beneficiaries auto-verified"],link:"https://maandhan.in/",helpline:"1800-267-6888",amt:36000,match:p=>p.employment==="farmer"&&p.age>=18&&p.age<=40},

// ═══ SENIOR CITIZEN EXTENDED (281-286) ═══
{name:"Rashtriya Vayoshri Yojana (Physical Aids for Seniors)",cat:"senior",tag:"Senior",benefit:"Free assistive devices (walking stick, spectacles, hearing aid, wheelchair) for BPL seniors",desc:"Free assistive devices for BPL seniors with age-related disabilities. Walking frames, tripods, wheelchair, hearing aid, spectacles, false teeth, elbow crutches. One-time distribution at camp.",elig:["Senior citizen (60+)","BPL category","Has age-related disability/impairment"],docs:["Aadhaar","BPL card","Age proof","Disability/medical proof"],apply:["Organised camps in districts by ALIMCO","Contact Social Welfare Department for camp schedule","alimco.in"],link:"https://www.alimco.in/",helpline:"1800-180-5129",amt:5000,match:p=>p.age>=60&&["below1","1to2.5"].includes(p.income)},

{name:"Senior Citizens Savings Scheme (SCSS)",cat:"senior",tag:"Senior",benefit:"8.2% interest p.a. on up to ₹30 lakh deposit — guaranteed by govt",desc:"Post Office savings scheme for 60+ (or 55+ VRS). Highest guaranteed return: 8.2% p.a. quarterly payout. Max ₹30 lakh. 5-year tenure, extendable by 3 years. ₹1.5L deduction under 80C.",elig:["Senior citizens aged 60+","Persons aged 55-60 who have taken VRS","HUFs and NRIs NOT eligible"],docs:["Age proof (passport/birth certificate/PAN)","Aadhaar","Photograph","Bank details"],apply:["Visit any Post Office or authorized bank (SBI, HDFC, ICICI etc.)","Open SCSS account with minimum ₹1,000"],link:"https://www.indiapost.gov.in/",helpline:"1800-266-6868",amt:246000,match:p=>p.age>=60},

{name:"Pradhan Mantri Vaya Vandana Yojana (PMVVY)",cat:"senior",tag:"Senior",benefit:"7.4% guaranteed pension on lump sum investment up to ₹15 lakh",desc:"Pension product for 60+. Pay lump sum, get guaranteed 7.4% p.a. pension for 10 years. At maturity, purchase price returned. ₹15 lakh max investment. Death benefit to nominee.",elig:["Senior citizen aged 60+ (no upper age limit)","Must invest lump sum"],docs:["Aadhaar","Age proof","Bank details","PAN"],apply:["Buy from LIC of India","Online: licindia.in/PMVVY","Walk-in at any LIC branch"],link:"https://licindia.in/",helpline:"022-68276827",amt:111000,match:p=>p.age>=60},

{name:"National Programme for Elder Care (NPEC)",cat:"senior",tag:"Senior",benefit:"Day care centres, mobile health services, helplines for seniors in 660+ districts",desc:"Old Age Homes, Day Care Centres, Mobile Medicare Units for needy seniors. Maintenance grant for 60+ without family support. Integrated Programme of Older Persons (IPOP).",elig:["Seniors 60+ with low income or no family support","BPL seniors get priority for residential care"],docs:["Age proof","Income proof","Medical certificate"],apply:["Contact District Social Welfare Office","OR State Social Welfare Department","Find old age home: socialwelfare.gov.in"],link:"https://socialjustice.gov.in/",helpline:"14567 (Elder Helpline)",amt:3000,match:p=>p.age>=60&&["below1","1to2.5"].includes(p.income)},

{name:"SAGE Portal (Senior Care Ageing Growth Engine)",cat:"senior",tag:"Senior",benefit:"One-stop portal for senior care products and services (trusted startups)",desc:"Government-curated portal listing DPIIT-recognized startups offering elder care: home care, health tech, finance, legal aid, travel. Quality assurance by government.",elig:["All seniors (60+)","Caregivers looking for services"],docs:["None for browsing","Registration for using services"],apply:["sagecart.in","Browse services by category","Contact listed startups directly"],link:"https://sagecart.in/",helpline:"14567",amt:0,match:p=>p.age>=60},

{name:"Varishtha Pension Bima Yojana (VPBY 2017)",cat:"senior",tag:"Senior",benefit:"Guaranteed 8% pension on investment up to ₹7.5 lakh for seniors",desc:"LIC pension plan for senior citizens. 8% guaranteed p.a. return on single premium. Policy term 10 years. Monthly pension payout. Surrender value if needed. Loan after 3 years.",elig:["Senior citizen 60+","Indian resident"],docs:["Age proof","Aadhaar","Bank passbook"],apply:["LIC offices","licindia.in"],link:"https://licindia.in/",helpline:"022-68276827",amt:60000,match:p=>p.age>=60},

// ═══ WATER SANITATION & HYGIENE (287-292) ═══
{name:"Swachh Bharat Mission — Urban (SBM-U 2.0)",cat:"sanitation",tag:"Sanitation",benefit:"ODF+ and solid waste management in all urban areas — garbage-free cities",desc:"SBM-U 2.0: ₹1.41 lakh crore for waste processing, faecal sludge management, grey water management, ODF+ sustainability. Star ratings for garbage-free cities.",elig:["All urban citizens — infrastructure programme"],docs:["NA"],apply:["swachhbharaturban.gov.in","Report complaints at CPGRAMS","Apply for toilet construction through ULB"],link:"https://swachhbharaturban.gov.in/",helpline:"1800-11-2345",amt:0,match:p=>p.area==="urban"},

{name:"Swachh Bharat Mission Gramin (SBM-G Phase II)",cat:"sanitation",tag:"Sanitation",benefit:"₹12,000 grant for individual household toilet + ₹750 for maintenance",desc:"ODF Plus villages: solid and liquid waste management in addition to toilets. ₹12,000 incentive for new household toilet. Village-level solid waste management. Gobar-Dhan for biogas.",elig:["Rural households without toilet","SC/ST get higher priority","APL families also eligible"],docs:["Aadhaar","Bank passbook","MGNREGA job card (optional)","Application to Gram Panchayat"],apply:["Application at Gram Panchayat","sbm.gov.in/sbmReport","GP verifies, incentive via DBT","MGNREGA convergence for labour cost"],link:"https://sbm.gov.in/",helpline:"1800-11-0303",amt:12000,match:p=>p.area==="rural"&&p.special.includes("no-toilet")},

{name:"Atal Bhujal Yojana (Groundwater Management)",cat:"water",tag:"Water",benefit:"Gram Panchayat water budget + farmer incentives for groundwater conservation",desc:"₹6,000 crore World Bank assisted scheme in 7 water-stressed states. Gram Panchayat level water security plans. Demand-side management. Incentives for farmers to shift to drip irrigation, crop diversification.",elig:["Gram Panchayats in 7 states: Gujarat, Haryana, Karnataka, MP, Maharashtra, Rajasthan, UP","Farmers in these GPs"],docs:["GP resolution","Farmer Aadhaar"],apply:["Contact Block level office in eligible states","ataljalshakti.gov.in"],link:"https://ataljal.mowr.gov.in/",helpline:"State groundwater board",amt:10000,match:p=>["Gujarat","Haryana","Karnataka","Madhya Pradesh","Maharashtra","Rajasthan","Uttar Pradesh"].includes(p.state)&&p.employment==="farmer"},

{name:"National Rural Drinking Water Programme (Renamed: JJM)",cat:"water",tag:"Water",benefit:"Water quality testing at village level — free kit for SHG/AWW",desc:"Jal Jeevan Mission water quality testing: free test kits to gram panchayats and women SHGs. 5-parameter field test kits. 1,636 district labs for comprehensive testing.",elig:["Gram Panchayats","Women SHGs","Anganwadi Workers","School children (testing clubs)"],docs:["GP/SHG registration","Aadhaar"],apply:["Apply for test kit: jaljeevanmission.gov.in","OR Block Development Office","Train 5 women per village as water quality testers"],link:"https://jaljeevanmission.gov.in/",helpline:"1800-180-7008",amt:0,match:p=>p.area==="rural"&&p.gender==="female"},

{name:"AMRUT (Rejuvenation of Urban Water Bodies)",cat:"water",tag:"Water",benefit:"Urban lakes, ponds, rivers rejuvenated in 500 AMRUT cities",desc:"Urban water body rejuvenation under AMRUT 2.0. Parks, jogging tracks, water sports around rejuvenated lakes. Green spaces for urban citizens.",elig:["Urban residents near water bodies — public benefit"],docs:["NA"],apply:["Participate in citizen consultation through municipal corporation"],link:"https://amrut.gov.in/",helpline:"State urban development dept",amt:0,match:p=>p.area==="urban"},

// ═══ TOURISM (293-297) ═══
{name:"Swadesh Darshan 2.0 (Thematic Tourism Circuits)",cat:"tourism",tag:"Tourism",benefit:"Developed tourist infrastructure at pilgrimage and heritage sites",desc:"₹2,500 crore for tourism circuits. Swadesh Darshan 2.0: sustainable, responsible tourism. Developed circuits across themes: tribal, spiritual, coastal, eco, heritage, rural tourism.",elig:["Tourism businesses in identified circuits","SHGs and communities near tourist sites","Homestay operators"],docs:["Business registration","Land proof"],apply:["tourism.gov.in","State Tourism Department","Apply for homestay registration under Incredible India"],link:"https://tourism.gov.in/",helpline:"1800-111-363",amt:500000,match:p=>p.bizType==="tourism"||p.employment==="self-employed"},

{name:"PRASHAD (Pilgrimage Rejuvenation & Spiritual Heritage Augmentation Drive)",cat:"tourism",tag:"Tourism",benefit:"Free tourist infrastructure at major religious sites",desc:"Development of 46 pilgrimage sites: Amritsar, Mathura, Puri, Varanasi, Tirupati, Ajmer, Bodhgaya, Hazur Sahib, Kedarnath, Rameshwaram. Amenities: parking, toilets, ghats, paths.",elig:["Pilgrims — public benefit"],docs:["NA"],apply:["Access improved facilities at notified pilgrimage sites","State tourism dept for local enterprise opportunities near sites"],link:"https://tourism.gov.in/prashad",helpline:"1800-111-363",amt:0,match:p=>true},

{name:"Incredible India Homestay Programme",cat:"tourism",tag:"Tourism",benefit:"Certification + marketing support for rural/heritage homestays",desc:"Recognition and promotion of authentic homestays. Listed on incredibleindia.org. Training in hospitality. Minimum standards certification. Integration with OTAs. ₹1 crore insurance for certified homestays.",elig:["Individual homeowners with spare rooms","Located in tourist areas, villages, heritage zones","Minimum facilities: clean room, bathroom, meals"],docs:["Property ownership/rent agreement","Local body NOC","Food licence","Aadhaar"],apply:["incredibleindia.org → Homestay registration","State Tourism Corporation","District Tourism Officer"],link:"https://www.incredibleindia.org/",helpline:"1800-111-363",amt:0,match:p=>p.ownHouse==="yes"&&p.needs.includes("tourism")},

{name:"Dekho Apna Desh Initiative (Domestic Tourism)",cat:"tourism",tag:"Tourism",benefit:"Subsidized domestic travel packages — ₹50,000 insurance included",desc:"Ministry of Tourism promotes domestic travel. Train tourism packages, Bharat Gaurav trains. ₹50,000 travel insurance with tourism packages. Online webinars, virtual tours.",elig:["All Indian citizens","Travel packages for school students at discounted rates"],docs:["Standard travel documents"],apply:["incredibleindia.org/travel-packages","IRCTC for Bharat Gaurav trains","School tour packages through Tourism Ministry"],link:"https://www.incredibleindia.org/",helpline:"1800-111-363",amt:0,match:p=>true},

{name:"National Skill Training Institutes for Hospitality (IHLS)",cat:"tourism",tag:"Tourism",benefit:"Free/subsidized hospitality skill training at 21 IHM institutes",desc:"21 Institute of Hotel Management colleges with PMKVY integration for subsidized programmes. Short-term courses (45 days to 6 months) in food production, housekeeping, front office, bakery.",elig:["Youth aged 15-35 seeking hospitality career","Class 10 pass for most diploma courses"],docs:["Aadhaar","Class 10 certificate","Age proof","Bank passbook"],apply:["ihmindia.org","OR nchmct.nic.in","Apply for subsidized PMKVY short-term courses"],link:"https://www.nchmct.nic.in/",helpline:"0124-4785500",amt:8000,match:p=>p.needs.includes("skill")||(p.employment==="unemployed"&&p.age>=15&&p.age<=35)},

// ═══ ADDITIONAL FARMER SCHEMES (298-303) ═══
{name:"PM Fasal Bima Yojana (PMFBY) & RWBCIS",cat:"agriculture",tag:"Agriculture",benefit:"Crop insurance at 1.5-5% premium for ₹5-50 lakh crop cover",desc:"Crop insurance: kharif premium 2%, rabi premium 1.5%, horticulture 5%. Government pays remaining. Tech-based quick claim settlement via drones and satellite. RWBCIS for weather-linked payouts.",elig:["All farmers — loanee farmers compulsorily covered","Non-loanee farmers can voluntarily enrol","All crops notified by state government"],docs:["Land records","Bank passbook","Sowing certificate","Aadhaar","Crop and area declaration"],apply:["Loanee farmers: auto-enrolled by bank","Non-loanee: pmfby.gov.in OR nearest bank/CSC","Enrol before crop season cutoff date"],link:"https://pmfby.gov.in/",helpline:"1800-180-1551",amt:500000,match:p=>p.employment==="farmer"},

{name:"PM-AASHA (Price Support & Market Intervention Scheme)",cat:"agriculture",tag:"Agriculture",benefit:"MSP price guaranteed for oilseeds, pulses, copra — government procures at MSP",desc:"PM-AASHA has 3 sub-schemes: PSS (government procurement at MSP), PDPS (price deficiency payment — no procurement), PMSS (private procurement at MSP). For oilseeds, pulses, copra.",elig:["Farmers growing oilseeds, pulses, copra, cotton, jute, sugarcane","State must notify procurement"],docs:["Land records","Aadhaar","Bank passbook","Crop sowing certificate"],apply:["Register at nearest NAFED/state procurement agency","Or agmarknet.gov.in","When notified, bring crop to designated mandi"],link:"https://agricoop.gov.in/",helpline:"1800-270-0224",amt:0,match:p=>p.employment==="farmer"},

{name:"Paramparagat Krishi Vikas Yojana (PKVY — Organic Farming)",cat:"agriculture",tag:"Agriculture",benefit:"₹50,000/hectare/3 years support for organic farming cluster",desc:"Supports farmer clusters (50+ farmers, 50 ha) to convert to organic farming. ₹50,000/hectare support over 3 years for: inputs, certification, marketing. PGS-India certification.",elig:["Farmers willing to form clusters of 50+ members","50 hectares contiguous land","Committed to organic practices for 3 years"],docs:["Land records","Cluster registration","Aadhaar","Bank passbook"],apply:["pkvy.gov.in","Contact District Agriculture Officer","Form farmer cluster with 50 members"],link:"https://pgsindia-ncof.gov.in/",helpline:"1800-180-1551",amt:50000,match:p=>p.employment==="farmer"},

{name:"Kisan Drones Scheme (Agricultural Drones)",cat:"agriculture",tag:"Agriculture",benefit:"40-100% subsidy on agricultural drones for FPOs, cooperatives, and custom hiring centres",desc:"100% subsidy for ICAR institutes/KVKs. 75% for SC/ST women/NE farmers. 50% for other farmers/FPOs. Drone for pesticide/fertilizer spraying, crop monitoring.",elig:["Farmers: 50% subsidy up to ₹5 lakh","FPOs/Cooperatives: 75% subsidy","SC/ST/Women/NE/small farmers: 75-100% subsidy"],docs:["Aadhaar","Land records","FPO/cooperative registration","Bank passbook"],apply:["agricoop.gov.in/drone","Apply through State Agriculture Department","OR FPO applies through NABARD/SFAC"],link:"https://agricoop.gov.in/",helpline:"1800-180-1551",amt:500000,match:p=>p.employment==="farmer"},

{name:"National Beekeeping & Honey Mission (NBHM)",cat:"agriculture",tag:"Agriculture",benefit:"₹1-2 lakh subsidy for beehive units, extractor, processing",desc:"Support for beekeepers: 85-100% subsidy (SC/ST/women) for bee boxes, nucleus stock, extractor, honey processing equipment. Training through KVKs. FPO formation for marketing.",elig:["Aspiring and existing beekeepers","Farmers wanting additional income","SC/ST/women get higher subsidy"],docs:["Aadhaar","Land records (for placement of hives)","Bank passbook"],apply:["State Horticulture Department","NABARD state office","kvk.icar.gov.in for training"],link:"https://agricoop.gov.in/",helpline:"1800-180-1551",amt:200000,match:p=>p.employment==="farmer"},

{name:"Krishonnati Yojana (Integrated Horticulture, Plantation, Organic)",cat:"agriculture",tag:"Agriculture",benefit:"Multiple benefits: ₹10,000-2 lakh for micro-irrigation, horticulture crops, soil health",desc:"Umbrella scheme: MIDH (horticulture: 40-100% subsidy), NFSM (food security: seed/fertilizer support), SMAM (farm machinery: 40-50% subsidy for small tractors, tools).",elig:["All farmers for NFSM and soil health card","Small/marginal farmers: higher subsidy for machinery","Horticulture farmers for MIDH"],docs:["Aadhaar","Land records","Soil Health Card","Bank passbook"],apply:["District Agriculture Office","agricoop.gov.in","Separate sub-scheme applications at state level"],link:"https://agricoop.gov.in/",helpline:"1800-180-1551",amt:200000,match:p=>p.employment==="farmer"},

];

if(typeof module!=='undefined')module.exports={CENTRAL_SCHEMES_3};
