// State Schemes Part 2 — Additional State & UT Government Schemes (90)
// Tamil Nadu (extra), Odisha, J&K, Manipur, Nagaland, Mizoram, Sikkim, Arunachal Pradesh + additional coverage
export const STATE_SCHEMES_2 = [
// ═══ TAMIL NADU EXTRA (1-10) ═══
{name:"TN Magalir Urimai Thogai Scheme",cat:"women",tag:"Women",benefit:"₹1,000/month for women heads of family",desc:"Monthly financial assistance for eligible women in Tamil Nadu. 1.06 crore women beneficiaries. DBT to bank account.",elig:["Women-headed family in Tamil Nadu","Family income below ₹2.5L/year","Not income tax payer"],docs:["Aadhaar","Ration Card","Bank passbook","Family income proof"],apply:["Apply through e-Sevai centre","Or Taluk/Tahsildar office","magalirurimaithogai.tn.gov.in"],link:"https://magalirurimaithogai.tn.gov.in/",helpline:"1800-425-1002",amt:12000,match:p=>p.state==="Tamil Nadu"&&p.gender==="female"},

{name:"TN Free Laptop Scheme for Students",cat:"education",tag:"Education",benefit:"Free laptop for students entering college",desc:"Free laptop for every government & aided school student who joins higher education. Over 50 lakh laptops distributed since launch.",elig:["Tamil Nadu student","Passed class 12 from TN board","Admitted to college/university","Government/aided school students"],docs:["12th certificate","College admission","Aadhaar","School ID"],apply:["Automatic through college","College submits eligible list","Distribution at college"],link:"https://tndge.tn.gov.in/",helpline:"044-25670444",amt:15000,match:p=>p.state==="Tamil Nadu"&&p.employment==="student"},

{name:"TN Uzhavar Pathukappu Thittam (Farmer Protection)",cat:"agriculture",tag:"Agriculture",benefit:"₹10,000/year for small/marginal farmers",desc:"State income support for small and marginal farmers. Supplements PM-KISAN. Crop insurance coverage included.",elig:["Small/marginal farmer in TN","Landholding up to 5 acres","Registered with agriculture department"],docs:["Land records (chitta/patta)","Aadhaar","Bank passbook"],apply:["Register at nearest agriculture office","Through uzhavan app","Automatic disbursement"],link:"https://agri.tn.gov.in/",helpline:"044-28524894",amt:10000,match:p=>p.state==="Tamil Nadu"&&p.employment==="farmer"},

{name:"TN Chief Minister's Health Insurance (CMCHHIS)",cat:"health",tag:"Insurance",benefit:"₹5L cashless health insurance per family",desc:"State health insurance for TN families. Covers 1,000+ procedures. In addition to PM-JAY coverage.",elig:["Tamil Nadu resident family","Rice card holder","All family members covered","Cashless at empanelled hospitals"],docs:["Aadhaar","Rice card","Family details"],apply:["Register at empanelled hospital","CMCHHIS card issued","Cashless at network hospitals"],link:"https://cmchistn.com/",helpline:"104",amt:500000,match:p=>p.state==="Tamil Nadu"},

{name:"TN Dr. APJ Abdul Kalam Award Merit Scholarship",cat:"education",tag:"Scholarship",benefit:"₹7,500/year for meritorious students",desc:"Merit scholarship for class 10 and 12 toppers from government schools. Encourages competitive exam preparation.",elig:["TN government school student","Top performers in class 10/12 board","Pursuing higher education","All categories eligible"],docs:["Board marksheet","School certificate","Aadhaar","Bank passbook"],apply:["Apply through school","Education department selects","Disbursement to bank account"],link:"https://dge.tn.gov.in/",helpline:"044-25670444",amt:7500,match:p=>p.state==="Tamil Nadu"&&p.employment==="student"},

// ═══ ADDITIONAL KARNATAKA (6-10) ═══
{name:"Karnataka Krishi Bhagya Scheme",cat:"agriculture",tag:"Agriculture",benefit:"80% subsidy for farm pond & drip irrigation",desc:"Supports dry-land farming with water harvesting. 80% subsidy on farm ponds, drip/sprinkler irrigation systems.",elig:["Farmer in Karnataka","Dry-land/rainfed agriculture","All categories of farmers","Priority for SC/ST farmers"],docs:["Land records (RTC/Pahani)","Aadhaar","Bank passbook","Photo of land"],apply:["Apply at Raita Samparka Kendra","Or through krishi.karnataka.gov.in","District agriculture department"],link:"https://krishi.karnataka.gov.in/",helpline:"080-22210885",amt:50000,match:p=>p.state==="Karnataka"&&p.employment==="farmer"},

{name:"Karnataka Vidya Siri Scholarship (SC/ST)",cat:"education",tag:"Scholarship",benefit:"₹17,000-₹30,000/year for SC/ST students",desc:"Post-matric scholarship for SC/ST students in Karnataka. Covers tuition, maintenance, and exam fees.",elig:["SC/ST student in Karnataka","Studying post-matric course","Family income below ₹2.5L/year","Admitted in recognized institution"],docs:["Caste certificate","Income certificate","Previous marksheet","Admission letter","Bank passbook"],apply:["Apply on SSP portal","Through college verification","sw.kar.nic.in"],link:"https://sw.kar.nic.in/",helpline:"080-22261789",amt:30000,match:p=>p.state==="Karnataka"&&["sc","st"].includes(p.category)&&p.employment==="student"},

// ═══ ADDITIONAL MAHARASHTRA (8-12) ═══
{name:"Maharashtra Mukhyamantri Teerth Darshan Yojana",cat:"social",tag:"Welfare",benefit:"Free pilgrimage for senior citizens",desc:"Free travel for senior citizens to pilgrimage destinations. Government bears all travel, stay and food costs.",elig:["Senior citizen aged 60+ in Maharashtra","Income below ₹2.5L/year","Physically fit for travel"],docs:["Aadhaar","Age proof","Income certificate","Medical fitness certificate"],apply:["Apply through district office","Selection by lottery","Before pilgrimage season"],link:"https://pilgrim.maharashtra.gov.in/",helpline:"022-22610777",amt:15000,match:p=>p.state==="Maharashtra"&&p.age>=60},

{name:"Maharashtra Shetkari Yojana (Crop Insurance)",cat:"agriculture",tag:"Agriculture",benefit:"₹1 premium crop insurance + debt relief",desc:"Maharashtra supplements PM Fasal Bima. Only ₹1 premium for farmers. State pays rest. Covers Kharif and Rabi crops.",elig:["Farmer in Maharashtra","Crop loan from bank or regular loanee","For notified crops in notified areas"],docs:["Land records (7/12)","Aadhaar","Bank passbook","Crop sowing certificate"],apply:["Through bank at time of crop loan","Or CSC centre","pmfby.gov.in + state portal"],link:"https://pmfby.gov.in/",helpline:"1800-209-0001",amt:0,match:p=>p.state==="Maharashtra"&&p.employment==="farmer"},

// ═══ ADDITIONAL GUJARAT (10-13) ═══
{name:"Gujarat Vahli Dikri Yojana",cat:"women",tag:"Children",benefit:"₹1,10,000 for first two daughters at milestone ages",desc:"₹4K at class 1, ₹6K at class 9, ₹1L at 18/wedding. For first 2 daughters of family. Over 5 lakh beneficiaries.",elig:["Girl child born in Gujarat","Family income below ₹2L/year","Maximum first two daughters","Must be enrolled in education"],docs:["Birth certificate","Income certificate","Aadhaar of girl","School enrollment","Bank passbook"],apply:["Register within 2 years of birth","Through Anganwadi/school","digitalgujarat.gov.in"],link:"https://digitalgujarat.gov.in/",helpline:"079-232-56591",amt:110000,match:p=>p.state==="Gujarat"&&p.gender==="female"&&p.lifeStage.includes("children")},

{name:"Gujarat Manav Garima Yojana",cat:"employment",tag:"Business",benefit:"Equipment/tools kit worth ₹15,000 for SC families",desc:"Self-employment for SC families. Kit includes tools relevant to 28 types of occupations like carpentry, tailoring, plumbing etc.",elig:["SC family in Gujarat","BPL or near-BPL","Age 18-60","Purpose: self-employment"],docs:["Caste certificate","BPL card","Aadhaar","Self-declaration for business","Bank passbook"],apply:["Apply through district SC welfare office","Or through e-Samaj Kalyan portal","esamajkalyan.gujarat.gov.in"],link:"https://esamajkalyan.gujarat.gov.in/",helpline:"079-23254601",amt:15000,match:p=>p.state==="Gujarat"&&p.category==="sc"&&p.employment!=="salaried"},

// ═══ ADDITIONAL RAJASTHAN (12-15) ═══
{name:"Rajasthan Jan Aadhar Card Scheme",cat:"social",tag:"Governance",benefit:"Single card for 100+ government services",desc:"Universal family ID card. Links all govt benefits, subsidies, pensions to one card. Eliminates need for multiple documents.",elig:["All Rajasthan families","Aadhaar of all family members required","No income restriction"],docs:["Aadhaar of all members","Address proof","Mobile number"],apply:["Register at Jan Aadhaar Kendra","Or janaadhaar.rajasthan.gov.in","Free registration"],link:"https://janaadhaar.rajasthan.gov.in/",helpline:"181",amt:0,match:p=>p.state==="Rajasthan"},

{name:"Rajasthan Indira Rasoi Yojana",cat:"health",tag:"Food",benefit:"Food at ₹8 per plate in government kitchens",desc:"Subsidised nutritious meals at 1,000+ Indira Rasoi centers. Full meal with roti, dal, sabzi, rice for just ₹8.",elig:["Any person in Rajasthan","No income/age/caste restriction","No ID needed","Available at all Rasoi centres"],docs:["No documents needed","Walk-in service"],apply:["Visit nearest Indira Rasoi center","No application needed","Meals available lunch and dinner"],link:"https://indirarasoi.rajasthan.gov.in/",helpline:"181",amt:0,match:p=>p.state==="Rajasthan"&&["below1","1to2.5"].includes(p.income)},

// ═══ ADDITIONAL UP (14-18) ═══
{name:"UP Mukhyamantri Kisan & Sarvhit Bima Yojana",cat:"health",tag:"Insurance",benefit:"₹2.5L accident insurance + ₹5L health cover for farmers",desc:"Insurance coverage for BPL families and farmers. Accident death/disability + health insurance at empanelled hospitals.",elig:["BPL/farmer families in UP","Head of family aged 18-70","Yellow/Antyodaya ration card holder"],docs:["Aadhaar","Ration card","Age proof","Bank passbook"],apply:["Register at Jan Suraksha Kendra","Or district office","Cashless at empanelled hospitals"],link:"https://balrampur.nic.in/",helpline:"1800-180-1234",amt:500000,match:p=>p.state==="Uttar Pradesh"&&p.employment==="farmer"},

{name:"UP Mukhyamantri Awas Yojana (Urban)",cat:"housing",tag:"Housing",benefit:"₹1-₹3.5L subsidy for urban housing",desc:"UP's urban housing scheme complementing PM Awas. ₹1L for EWS new house, ₹1.5L for LIG, ₹3.5L for in-situ slum redevelopment.",elig:["EWS/LIG urban resident in UP","No pucca house anywhere in India","Income: EWS <₹3L, LIG <₹6L"],docs:["Aadhaar","Income certificate","No-house certificate","Bank passbook","Photo"],apply:["Apply through Urban Local Body","pmay-urban.gov.in","Common Service Centres"],link:"https://pmay-urban.gov.in/",helpline:"011-23060484",amt:350000,match:p=>p.state==="Uttar Pradesh"&&p.ownHouse!=="yes"&&p.area==="urban"&&["below1","1to2.5","2.5to5"].includes(p.income)},

// ═══ ADDITIONAL BIHAR (16-19) ═══
{name:"Bihar Mukhyamantri Gram Parivahan Yojana",cat:"transport",tag:"Transport",benefit:"50% subsidy up to ₹1L on purchasing 4-wheeler",desc:"Subsidy on purchasing a vehicle for passenger transport service. SC/ST/EBC families can buy vehicle at 50% cost.",elig:["Bihar domicile","SC/ST/EBC category","Age 21+","Must use for passenger transport"],docs:["Caste certificate","Aadhaar","Driving license","Age proof","Bank passbook"],apply:["Apply at transport.bih.nic.in","District transport office","Vehicle purchase after sanction"],link:"https://transport.bih.nic.in/",helpline:"0612-2215417",amt:100000,match:p=>p.state==="Bihar"&&["sc","st","obc"].includes(p.category)},

{name:"Bihar Mukhyamantri Udyami Yojana",cat:"employment",tag:"Business",benefit:"₹10L interest-free loan + ₹5L grant for SC/ST/EBC entrepreneurs",desc:"Entrepreneurship scheme. ₹10L project cost: ₹5L as grant, ₹5L as interest-free loan. For manufacturing and service sectors.",elig:["Bihar domicile","SC/ST/EBC/Women/Youth category","Age 18-50","Minimum 10th pass","New enterprise setup"],docs:["Caste certificate","Educational certificate","Aadhaar","DPR/Business plan","Bank passbook"],apply:["Apply at udyami.bihar.gov.in","Online application with DPR","District industry centre verification"],link:"https://udyami.bihar.gov.in/",helpline:"1800-345-6214",amt:1000000,match:p=>p.state==="Bihar"&&(["sc","st","obc"].includes(p.category)||p.gender==="female")&&p.age>=18&&p.age<=50},

// ═══ ADDITIONAL MP (18-21) ═══
{name:"MP Mukhyamantri Jan Kalyan Sambal Yojana",cat:"social",tag:"Welfare",benefit:"₹5K funeral aid + ₹2L accident cover + free electricity",desc:"Multi-benefit welfare scheme for unorganized workers. Death benefit, accident insurance, electricity subsidy, education scholarship.",elig:["BPL family in MP","Unorganized sector worker","Registered on Sambal portal","Not income tax payer"],docs:["Aadhaar","Samagra ID","BPL certificate","Labour card"],apply:["Register at sambal.mp.gov.in","Or through Lok Seva Kendra","Auto-enrollment for BPL families"],link:"https://sambal.mp.gov.in/",helpline:"0755-2700800",amt:200000,match:p=>p.state==="Madhya Pradesh"&&["below1","1to2.5"].includes(p.income)},

{name:"MP Mukhyamantri Kalyani Sahayata Yojana",cat:"women",tag:"Women",benefit:"₹300-₹600/month pension for widows",desc:"Monthly pension for widows in MP. ₹300 for age 18-59, ₹600 for 80+. Additional support under NSAP supplement.",elig:["Widow in MP","Not remarried","BPL family","MP domicile"],docs:["Aadhaar","Death certificate of husband","Samagra ID","BPL card","Bank passbook"],apply:["Apply at socialjustice.mp.gov.in","Through district collector office","Lok Seva Kendra"],link:"https://socialjustice.mp.gov.in/",helpline:"0755-2571929",amt:7200,match:p=>p.state==="Madhya Pradesh"&&p.lifeStage.includes("widow")},

// ═══ ADDITIONAL WB (20-23) ═══
{name:"West Bengal Taposili Bandhu (SC Development)",cat:"social",tag:"Welfare",benefit:"₹10,000 one-time grant for SC families for livelihood",desc:"Livelihood assistance for SC families. Grant for purchasing tools, equipment, livestock for income generation.",elig:["SC family in West Bengal","BPL/near-BPL household","Adult member aged 18-50","For livelihood purposes"],docs:["Caste certificate","BPL card","Aadhaar","Self-declaration of purpose","Bank passbook"],apply:["Apply at Duare Sarkar camp","Or Block SC welfare office","casteminoritywelfare.wb.gov.in"],link:"https://casteminoritywelfare.wb.gov.in/",helpline:"033-22143800",amt:10000,match:p=>p.state==="West Bengal"&&p.category==="sc"},

{name:"West Bengal Gatidhara Scheme (Two-Wheeler Subsidy)",cat:"transport",tag:"Transport",benefit:"₹1L subsidy on purchase of commercial vehicle",desc:"Subsidy for SC/ST youth to purchase commercial vehicles. Promotes self-employment in transport sector.",elig:["SC/ST youth in West Bengal","Age 18-45","Valid driving license","For commercial vehicle purchase"],docs:["Caste certificate","Aadhaar","Driving license","Age proof","Bank passbook"],apply:["Apply at Block SC/ST welfare office","Or through Duare Sarkar","District level approval"],link:"https://casteminoritywelfare.wb.gov.in/",helpline:"033-22143800",amt:100000,match:p=>p.state==="West Bengal"&&["sc","st"].includes(p.category)&&p.age>=18&&p.age<=45},

// ═══ ADDITIONAL KERALA (22-25) ═══
{name:"Kerala Karunya Health Scheme",cat:"health",tag:"Health",benefit:"₹2L-₹3L financial assistance for critical illnesses",desc:"Financial assistance for critical diseases like cancer, heart surgery, kidney transplant etc. Supplements health insurance.",elig:["Kerala resident","Suffering from critical illness listed in scheme","Family income below ₹3L/year","BPL families get higher assistance"],docs:["Medical certificate from govt hospital","Income certificate","Aadhaar","Treatment estimate","Bank passbook"],apply:["Apply at district Karunya Office","Or through collectorate","Online at karunya.kerala.gov.in"],link:"https://karunya.kerala.gov.in/",helpline:"0471-2369100",amt:300000,match:p=>p.state==="Kerala"&&["below1","1to2.5","2.5to5"].includes(p.income)},

{name:"Kerala Kudumbashree Mission (Women SHG)",cat:"employment",tag:"Business",benefit:"₹10,000-₹50,000 seed money for women micro-enterprises",desc:"World's largest women's SHG network. 45+ lakh members. Seed capital for women-led micro enterprises and business training.",elig:["Women in Kerala","BPL/near-BPL families","Member of Kudumbashree neighbourhood group","Age 18-55"],docs:["Aadhaar","BPL/income certificate","Kudumbashree membership","Business plan","Bank passbook"],apply:["Join local Kudumbashree NHG","Apply for micro-enterprise through CDS","Block-level approval"],link:"https://kudumbashree.org/",helpline:"0471-2330530",amt:50000,match:p=>p.state==="Kerala"&&p.gender==="female"&&["below1","1to2.5","2.5to5"].includes(p.income)},

// ═══ ADDITIONAL AP (24-27) ═══
{name:"AP YSR Kapu Nestham",cat:"women",tag:"Women",benefit:"₹15,000/year for Kapu/EBC/Balija women",desc:"Annual financial assistance for women of Kapu/Balija/Telaga/Ontari communities aged 45-60.",elig:["Women aged 45-60 in AP","Kapu/Balija/Telaga/Ontari community","Annual family income below ₹2.5L","White ration card holder"],docs:["Caste certificate","Age proof","Aadhaar","White ration card","Bank passbook"],apply:["Through Village/Ward Secretariat","Navasakam portal","DBT on beneficiary birthday"],link:"https://navasakam.ap.gov.in/",helpline:"1902",amt:15000,match:p=>p.state==="Andhra Pradesh"&&p.gender==="female"&&p.age>=45&&p.age<=60},

{name:"AP Jagananna Vidya Deevena",cat:"education",tag:"Scholarship",benefit:"Full tuition fee reimbursement for college students",desc:"Complete tuition fee reimbursement for ITI/Degree/PG/Professional courses. SC/ST/BC/minority/EBC students covered.",elig:["Student in AP from SC/ST/BC/Minority/EBC","Pursuing ITI/degree/PG/professional course","Family income below ₹2.5L/year","80% attendance required"],docs:["Caste certificate","Income certificate","College admission","Aadhaar","Fee receipt"],apply:["Apply through Jnanabhumi portal","College processes application","jnanabhumi.ap.gov.in"],link:"https://jnanabhumi.ap.gov.in/",helpline:"1902",amt:100000,match:p=>p.state==="Andhra Pradesh"&&p.employment==="student"&&["sc","st","obc","minority"].includes(p.category)},

{name:"AP YSR Matsyakara Bharosa (Fishermen Support)",cat:"social",tag:"Welfare",benefit:"₹10,000/year during fishing ban period",desc:"Livelihood support for fishermen during annual fishing ban season. ₹10K per fisherman family.",elig:["Active fisherman in AP","Registered with fisheries department","During annual fishing ban period"],docs:["Fisher ID card","Aadhaar","Bank passbook"],apply:["Automatic for registered fishermen","Through fisheries department","Village Secretariat verification"],link:"https://navasakam.ap.gov.in/",helpline:"1902",amt:10000,match:p=>p.state==="Andhra Pradesh"&&p.employment==="self-employed"},

// ═══ ADDITIONAL TELANGANA (26-29) ═══
{name:"Telangana Rythu Bandhu Scheme",cat:"agriculture",tag:"Agriculture",benefit:"₹10,000/acre per year for all farmers",desc:"Farmer investment support. ₹5K/acre per season × 2 seasons. No income limit. Covers tenant farmers too. 65L+ beneficiaries.",elig:["All farmers with land in Telangana","No income restriction","Land must be registered","Covers pattadar land only"],docs:["Land records (Pattadar passbook)","Aadhaar","Bank passbook"],apply:["Automatic for registered pattadars","Agriculture department processes","DBT before each cropping season"],link:"https://rythubandhu.telangana.gov.in/",helpline:"040-23381026",amt:10000,match:p=>p.state==="Telangana"&&p.employment==="farmer"},

{name:"Telangana Rythu Bima (Farmer Insurance)",cat:"agriculture",tag:"Insurance",benefit:"₹5L life insurance for farmers, 100% state funded",desc:"Free life insurance for all enrolled farmers. ₹5L on death (any cause). State pays entire premium. 58L+ farmers covered.",elig:["All registered farmers in Telangana","Age 18-59","Must be Rythu Bandhu beneficiary","No premium from farmer"],docs:["Land records","Aadhaar","Nominee details"],apply:["Automatic for Rythu Bandhu beneficiaries","Agriculture officer enrolls","Claim through district agriculture office"],link:"https://rythubandhu.telangana.gov.in/",helpline:"040-23381026",amt:500000,match:p=>p.state==="Telangana"&&p.employment==="farmer"},

{name:"Telangana KCR Nutrition Kit for Pregnant Women",cat:"health",tag:"Health",benefit:"₹12,000 cash + nutrition kit during pregnancy",desc:"Cash assistance for institutional delivery. ₹12K for boy child, ₹13K for girl child. Plus nutrition kit throughout pregnancy.",elig:["Pregnant women in Telangana","Institutional delivery at govt hospital","All income groups eligible"],docs:["Aadhaar","MCH Card","Hospital registration","Bank passbook"],apply:["Register at government hospital/health centre","Anganwadi worker registration","Automatic at delivery"],link:"https://health.telangana.gov.in/",helpline:"104",amt:13000,match:p=>p.state==="Telangana"&&p.gender==="female"&&p.lifeStage.includes("pregnant")},

// ═══ ADDITIONAL ODISHA (28-32) ═══
{name:"Odisha Madhu Babu Pension Yojana",cat:"social",tag:"Pension",benefit:"₹500-₹700/month pension for elderly/widows/disabled",desc:"State pension scheme. ₹500 for 60-79, ₹700 for 80+. Also covers widows, persons with disabilities, and leprosy patients.",elig:["Odisha domicile","Old age: 60+","Widow: any age","Disabled: 40%+","BPL family"],docs:["Aadhaar","Age proof","BPL card","Bank passbook","Disability certificate (if applicable)"],apply:["Apply through Block/ULB office","Online at ssepd.odisha.gov.in","Gram Panchayat recommends"],link:"https://ssepd.odisha.gov.in/",helpline:"1800-345-6778",amt:8400,match:p=>p.state==="Odisha"&&(p.age>=60||p.lifeStage.includes("widow")||p.lifeStage.includes("disabled"))&&["below1","1to2.5"].includes(p.income)},

{name:"Odisha Biju Swasthya Kalyan Yojana (BSKY)",cat:"health",tag:"Insurance",benefit:"₹5L (women ₹10L) cashless health insurance",desc:"State health insurance. ₹5L for men, ₹10L for women per family. Covers 200+ empanelled hospitals across Odisha.",elig:["Odisha resident family","SECC/NFSA beneficiary","Smart Health Card holder"],docs:["Aadhaar","BSKY Smart Health Card","Family details"],apply:["Register at bfrsby.odisha.gov.in","Or empanelled hospital","Cards distributed through camps"],link:"https://bfrsby.odisha.gov.in/",helpline:"104",amt:1000000,match:p=>p.state==="Odisha"},

{name:"Odisha Mission Shakti (Women SHG Loans)",cat:"employment",tag:"Business",benefit:"₹50,000-₹5L loan at 0% interest for women SHGs",desc:"Interest-free loans for women SHGs. 70 lakh women across 6 lakh SHGs. For micro-enterprises and livelihood activities.",elig:["Woman member of Mission Shakti SHG in Odisha","SHG must be 6+ months old","Regular savings and meeting records"],docs:["SHG registration","Member Aadhaar","Bank passbook","Business plan"],apply:["Through Mission Shakti district office","Or bank branch","SHG applies collectively"],link:"https://missionshakti.odisha.gov.in/",helpline:"1800-345-6778",amt:500000,match:p=>p.state==="Odisha"&&p.gender==="female"},

// ═══ JAMMU & KASHMIR (30-33) ═══
{name:"J&K UMEED Self Employment Scheme",cat:"employment",tag:"Business",benefit:"Interest subsidy on loans up to ₹10L for youth",desc:"Self-employment for J&K youth. Interest subsidy on bank loans for setting up business. Covers manufacturing and services.",elig:["J&K domicile","Age 18-35","Unemployed","Minimum 8th pass","For new enterprise"],docs:["Domicile certificate","Educational certificate","Aadhaar","Business plan","Bank passbook"],apply:["Apply at jkedi.org","Through JKEDI district office","Online application"],link:"https://jkedi.org/",helpline:"0194-2430010",amt:1000000,match:p=>p.state==="Jammu & Kashmir"&&p.employment==="unemployed"&&p.age>=18&&p.age<=35},

{name:"J&K Ladli Beti Scheme",cat:"women",tag:"Children",benefit:"₹1,000/year from birth + ₹75,000 at 21",desc:"Investment for girl children in J&K. ₹1,000/year deposit till age 14. Maturity amount at age 21 for marriage/education.",elig:["Girl child born in J&K","Family income below ₹75,000/year","Maximum 2 girl children","Registration within 1 year of birth"],docs:["Birth certificate","Parent's Aadhaar","Income certificate","Bank passbook"],apply:["Register at Anganwadi centre","Or WCD district office","Within 1 year of birth"],link:"https://jksocialwelfare.nic.in/",helpline:"0194-2457511",amt:75000,match:p=>p.state==="Jammu & Kashmir"&&p.gender==="female"&&p.lifeStage.includes("children")},

// ═══ NORTHEAST: MANIPUR, NAGALAND, MIZORAM (32-37) ═══
{name:"Manipur Chief Minister's Start-Up Scheme",cat:"employment",tag:"Business",benefit:"₹5-₹20L seed funding for startups",desc:"Seed funding for innovative startups by Manipur youth. Covers IT, agri-tech, handicraft, tourism, food processing.",elig:["Manipur domicile","Age 18-40","Innovative business idea","Minimum graduate (relaxed for tribal areas)"],docs:["Educational certificate","Business plan/DPR","Aadhaar","Domicile certificate","Bank passbook"],apply:["Apply at mi-startup.mn.gov.in","Through District Industries Centre","Evaluation committee reviews"],link:"https://mi-startup.mn.gov.in/",helpline:"0385-2415905",amt:2000000,match:p=>p.state==="Manipur"&&p.age>=18&&p.age<=40},

{name:"Nagaland Chief Minister's Health Insurance Scheme",cat:"health",tag:"Insurance",benefit:"₹2L cashless health insurance per family",desc:"State health insurance for BPL families in Nagaland. Cashless treatment at empanelled hospitals.",elig:["BPL family in Nagaland","SECC-listed households","Indigenous Naga families priority"],docs:["BPL card","Aadhaar","Family details","Indigenous certificate"],apply:["Register at district health office","Or Community Health Centre","Cashless at empanelled hospitals"],link:"https://health.nagaland.gov.in/",helpline:"0370-2270740",amt:200000,match:p=>p.state==="Nagaland"&&["below1","1to2.5"].includes(p.income)},

{name:"Mizoram Socially & Educationally Backward Classes Scholarship",cat:"education",tag:"Scholarship",benefit:"₹5,000-₹15,000/year for backward class students",desc:"Educational support for students from backward communities in Mizoram. Covers school to university level.",elig:["Student from backward community in Mizoram","Studying in recognized institution","Family income below ₹2L/year"],docs:["Backward class certificate","Income certificate","Previous marksheet","Admission letter","Bank passbook"],apply:["Apply through school/college","District welfare office","scholarship portal"],link:"https://education.mizoram.gov.in/",helpline:"0389-2322148",amt:15000,match:p=>p.state==="Mizoram"&&p.employment==="student"},

// ═══ SIKKIM & ARUNACHAL PRADESH (35-38) ═══
{name:"Sikkim One Family One Job Scheme",cat:"employment",tag:"Employment",benefit:"Government job for one member per family",desc:"Unique scheme guaranteeing one government job per family in Sikkim. Monthly salary as per government scale.",elig:["Sikkim domicile family","One member per family","No family member in government service","Minimum age 18"],docs:["Sikkim Subject Certificate","Family certificate","Aadhaar","Educational certificates","Employment exchange registration"],apply:["Apply through district administration","Or employment exchange","Sikkim state government portal"],link:"https://sikkim.gov.in/",helpline:"03592-202263",amt:0,match:p=>p.state==="Sikkim"&&p.employment==="unemployed"},

{name:"Arunachal Pradesh Dulari Kanya Scheme",cat:"women",tag:"Children",benefit:"₹20,000 one-time deposit for girl child at birth",desc:"Fixed deposit of ₹20,000 for every girl child born in government hospital. Matures at age 18 for education/marriage.",elig:["Girl child born in AP government hospital","All communities eligible","Registration within 6 months of birth"],docs:["Birth certificate","Parent's Aadhaar","Hospital delivery certificate","Bank passbook"],apply:["Register at government hospital at birth","Through WCD department","District-level processing"],link:"https://arunachalpradesh.gov.in/",helpline:"0360-2212032",amt:20000,match:p=>p.state==="Arunachal Pradesh"&&p.gender==="female"&&p.lifeStage.includes("children")},

// ═══ ADDITIONAL CROSS-STATE POPULAR SCHEMES (37-55) ═══
{name:"Ladli Foundation Scheme (Delhi)",cat:"women",tag:"Children",benefit:"₹5,000-₹11,000 at milestones for girl child",desc:"Staggered financial assistance for girl children in Delhi. ₹5K-₹11K at milestones from birth to class 12 pass.",elig:["Girl child born in Delhi","Family income below ₹1L/year","Born in hospital","Registered within 1 year"],docs:["Birth certificate","Parent's Aadhaar","Income certificate","School enrollment proof"],apply:["Apply through WCD office Delhi","Or through school","Anganwadi centre registration"],link:"https://wcd.delhi.gov.in/",helpline:"181",amt:36000,match:p=>p.state==="Delhi"&&p.gender==="female"&&p.lifeStage.includes("children")},

{name:"Delhi Ration at Home Scheme",cat:"health",tag:"Food",benefit:"Free ration for NFSA beneficiaries in Delhi",desc:"Door-step delivery of free ration for eligible families. 5 kg wheat, 5 kg rice per person per month.",elig:["NFSA ration card holder in Delhi","PHH and AAY card holders","All family members eligible"],docs:["Delhi ration card","Aadhaar"],apply:["Automatic for ration card holders","Collect from Fair Price Shop","Or door-step delivery scheme"],link:"https://nfs.delhi.gov.in/",helpline:"1800-110-841",amt:0,match:p=>p.state==="Delhi"&&["below1","1to2.5"].includes(p.income)},

{name:"Jharkhand Savitribai Phule Kishori Samridhi Yojana",cat:"education",tag:"Education",benefit:"₹40,000 in installments from class 8 to graduation",desc:"Girl education scheme. ₹2,500 each in class 8 and 9, ₹5,000 in class 10-12, ₹20,000 at age 18-19 for graduation.",elig:["Girl student in Jharkhand","SECC-listed family","Studying in recognized school/college","Unmarried"],docs:["SECC inclusion proof","School enrollment","Aadhaar","Age proof","Bank passbook"],apply:["Apply through school","Or Anganwadi centre","District WCD office processes"],link:"https://wcd.jharkhand.gov.in/",helpline:"181",amt:40000,match:p=>p.state==="Jharkhand"&&p.gender==="female"&&p.employment==="student"},

{name:"Chhattisgarh Mukhyamantri Shahari Slum Swasthya Yojana",cat:"health",tag:"Health",benefit:"Free primary healthcare in urban slums",desc:"Mobile health units providing free primary healthcare in urban slums. Covers diagnostics, medicines, referral.",elig:["Residents of urban slums in Chhattisgarh","All income groups","No documents needed for OPD"],docs:["Aadhaar (optional)","Ration card (optional)"],apply:["Visit mobile health unit in your slum","Or nearest Urban PHC","No prior registration needed"],link:"https://health.cg.gov.in/",helpline:"14411",amt:0,match:p=>p.state==="Chhattisgarh"&&p.area==="urban"},

{name:"Gujarat Mukhyamantri Apprenticeship Scheme",cat:"employment",tag:"Skill",benefit:"₹3,000-₹6,000/month stipend during apprenticeship",desc:"State-sponsored apprenticeship with private firms. Govt pays 50% of stipend. Covers ITI, diploma, graduate apprentices.",elig:["ITI/diploma/graduate from Gujarat","Age 16-30","Registered on apprenticeship portal","Completed relevant technical course"],docs:["Educational certificates","Aadhaar","Bank passbook","NAPS registration"],apply:["Register at apprenticeshipindia.gov.in","Or digitalgujarat.gov.in","Employer-student matching"],link:"https://digitalgujarat.gov.in/",helpline:"079-232-56591",amt:72000,match:p=>p.state==="Gujarat"&&p.age>=16&&p.age<=30&&p.employment!=="salaried"},

{name:"AP YSR Nethanna Nestham (Weaver Support)",cat:"employment",tag:"Employment",benefit:"₹24,000/year for handloom weavers",desc:"Annual financial assistance for handloom weavers and ancillary workers. ₹24K to maintain loom and buy raw materials.",elig:["Active handloom weaver in AP","Registered with handloom department","Working on handloom","Age 18-60"],docs:["Weaver ID/registration","Aadhaar","Bank passbook","Loom details"],apply:["Through Village Secretariat","Handloom department registration","DBT to bank account"],link:"https://navasakam.ap.gov.in/",helpline:"1902",amt:24000,match:p=>p.state==="Andhra Pradesh"&&p.employment==="self-employed"},

{name:"Telangana Bathukamma Sarees Distribution",cat:"social",tag:"Welfare",benefit:"Free Bathukamma saree for every woman",desc:"Annual distribution of high-quality saree to all women during Bathukamma festival. 1 crore+ sarees distributed.",elig:["All women in Telangana","No income/age restriction","During Bathukamma festival season"],docs:["Aadhaar or any ID"],apply:["Collect at designated distribution centres","Panchayat/Ward level distribution","During festival season Oct-Nov"],link:"https://telangana.gov.in/",helpline:"040-23450267",amt:500,match:p=>p.state==="Telangana"&&p.gender==="female"},

{name:"Maharashtra Bhausaheb Fundkar Falbag Yojana",cat:"agriculture",tag:"Agriculture",benefit:"₹50,000-₹1L subsidy for fruit orchards",desc:"Subsidy for setting up fruit orchards, vineyards, and plantations. Promotes horticulture in Maharashtra.",elig:["Farmer in Maharashtra","Land suitable for horticulture","Minimum 0.20 hectare area","All categories"],docs:["Land records (7/12)","Aadhaar","Bank passbook","Soil testing report"],apply:["Apply through district agriculture/horticulture office","mahadbt.maharashtra.gov.in","Online application"],link:"https://mahadbt.maharashtra.gov.in/",helpline:"1800-120-8040",amt:100000,match:p=>p.state==="Maharashtra"&&p.employment==="farmer"},

{name:"Rajasthan Mukhyamantri Laghu Udyog Protsahan Yojana",cat:"employment",tag:"Business",benefit:"5-8% interest subsidy on loans up to ₹10 crore",desc:"Interest subsidy for MSMEs in Rajasthan. 5% for ₹25L-₹5Cr, 6% for ₹5Cr-₹10Cr. Promotes manufacturing.",elig:["Enterprise setting up in Rajasthan","Manufacturing/service sector MSME","New or expansion project","Udyam registered"],docs:["Udyam registration","DPR","Land/rent documents","Aadhaar/PAN","Bank sanction letter"],apply:["Apply at sso.rajasthan.gov.in","Through DIC district office","Before/within 3 months of starting production"],link:"https://sso.rajasthan.gov.in/",helpline:"0141-2227725",amt:0,match:p=>p.state==="Rajasthan"&&["self-employed","business"].includes(p.employment)},

{name:"UP Mukhyamantri Bal Sewa Yojana",cat:"social",tag:"Children",benefit:"₹4,000/month + free education for COVID orphans",desc:"Support for children orphaned during COVID. Monthly maintenance, free tablet, education support, and residential care option.",elig:["Child (below 18) who lost parent(s) to COVID in UP","UP domicile","Not already in institutional care"],docs:["Death certificate of parent","COVID treatment records","Child's Aadhaar","Bank passbook"],apply:["Apply at mksy.up.gov.in or through DM office","District child protection unit","CDO/SDM verification"],link:"https://mksy.up.gov.in/",helpline:"1800-180-1234",amt:48000,match:p=>p.state==="Uttar Pradesh"&&p.lifeStage.includes("children")},

{name:"Bihar Kabir Anteyeshti Yojana (Funeral Aid)",cat:"social",tag:"Welfare",benefit:"₹3,000 funeral assistance for BPL families",desc:"Financial assistance for funeral/last rites of BPL family member. Quick disbursement within 3 days of application.",elig:["BPL family in Bihar","On death of any family member","All categories eligible"],docs:["Death certificate","BPL card","Aadhaar of applicant","Bank passbook"],apply:["Apply within 3 months of death","Through Block/Panchayat office","serviceonline.bihar.gov.in"],link:"https://serviceonline.bihar.gov.in/",helpline:"0612-2215417",amt:3000,match:p=>p.state==="Bihar"&&["below1","1to2.5"].includes(p.income)},

{name:"Karnataka Prabuddha Scholarship (Backward Classes)",cat:"education",tag:"Scholarship",benefit:"₹2,500-₹10,000/year for OBC students",desc:"Pre & post-matric scholarship for OBC/Backward class students in Karnataka. Covers tuition and maintenance.",elig:["OBC/Backward class student in Karnataka","Family income below ₹2L/year","Studying in recognized institution"],docs:["Caste certificate","Income certificate","Previous marksheet","Admission letter","Bank passbook"],apply:["Apply through e-Scholarship portal","College verification","sw.kar.nic.in"],link:"https://sw.kar.nic.in/",helpline:"080-22261789",amt:10000,match:p=>p.state==="Karnataka"&&p.category==="obc"&&p.employment==="student"},

{name:"MP Mukhyamantri Medhavi Vidyarthi Yojana",cat:"education",tag:"Scholarship",benefit:"Full tuition fee for meritorious students (JEE/NEET qualified)",desc:"Full tuition fee payment for MP students scoring 70%+ in 12th and admitted to NIT/IIT/Govt Medical/CLAT/AIIMS etc.",elig:["MP domicile student","12th board: 70%+ (general), 85%+ CBSE","Admits to NIT/IIT/AIIMS/Govt engineering or medical","Family income below ₹6L/year"],docs:["12th marksheet","Admission letter","Income certificate","Aadhaar","Samagra ID"],apply:["Apply at scholarshipportal.mp.nic.in","Through college","Within admission period"],link:"https://scholarshipportal.mp.nic.in/",helpline:"0755-2660063",amt:200000,match:p=>p.state==="Madhya Pradesh"&&p.employment==="student"},

{name:"WB Banglar Bari Housing Scheme",cat:"housing",tag:"Housing",benefit:"₹1.5-₹2.5L subsidy for rural/urban housing",desc:"West Bengal's housing scheme for homeless families. Provides financial assistance for construction of pucca house.",elig:["Houseless family in West Bengal","BPL/EWS category","No pucca house anywhere","Rural and urban eligible"],docs:["Address proof","Income certificate","No-house certificate","Aadhaar","Bank passbook"],apply:["Apply through Block/Municipality office","Or through Duare Sarkar camp","Housing department processes"],link:"https://wbhousing.gov.in/",helpline:"1800-345-7007",amt:250000,match:p=>p.state==="West Bengal"&&p.ownHouse!=="yes"&&["below1","1to2.5"].includes(p.income)},

{name:"Haryana Kaushal Rojgar Nigam",cat:"employment",tag:"Employment",benefit:"Transparent contractual hiring for government jobs",desc:"State corporation for providing contractual government jobs transparently. Eliminates middlemen. Online recruitment.",elig:["Haryana domicile","Minimum education as per post","Age as per post requirements","Register on HKRN portal"],docs:["Aadhaar","PPP ID","Educational certificates","Domicile certificate"],apply:["Register at hkrnl.itiharyana.gov.in","Apply for available positions","Online selection process"],link:"https://hkrnl.itiharyana.gov.in/",helpline:"1800-180-2403",amt:0,match:p=>p.state==="Haryana"&&p.employment==="unemployed"},

{name:"Punjab Atta-Dal Scheme",cat:"health",tag:"Food",benefit:"Free wheat and dal for BPL families",desc:"2 kg dal and wheat flour per person per month for BPL families. Over 14.5 lakh families covered.",elig:["BPL family in Punjab","Blue ration card holder","All family members eligible"],docs:["BPL ration card","Aadhaar"],apply:["Automatic for blue card holders","Collect from Fair Price Shop","Monthly distribution"],link:"https://foodsuppb.gov.in/",helpline:"0172-2741818",amt:0,match:p=>p.state==="Punjab"&&["below1","1to2.5"].includes(p.income)},

{name:"Assam Arundhati Gold Scheme",cat:"social",tag:"Welfare",benefit:"1 tola (10g) gold for brides during marriage",desc:"10g gold for brides whose marriage is registered. Worth approx ₹60,000. Aims to promote marriage registration.",elig:["Bride in Assam","Marriage must be registered","Bride's age 18+, groom 21+","Family income below ₹5L/year"],docs:["Marriage registration certificate","Aadhaar","Income certificate","Age proof","Bank passbook"],apply:["Register marriage first","Apply through district administration","Gold/cash equivalent disbursed"],link:"https://finance.assam.gov.in/",helpline:"1800-345-3611",amt:60000,match:p=>p.state==="Assam"&&p.gender==="female"},

{name:"Goa Dayanand Social Security Scheme",cat:"social",tag:"Pension",benefit:"₹2,500/month pension for elderly/PWD/widows",desc:"Goa's social security pension. One of highest in India. ₹2,500/month for elderly (60+), widows, and persons with disability.",elig:["Goa resident for 15+ years","Old age: 60+, Widow: any age, PWD: 40%+","Income below ₹3L/year"],docs:["Aadhaar","Residency proof","Age proof","Income certificate","Bank passbook"],apply:["Apply at Mamlatdar office","Or through provedoria.goa.gov.in","Renewal annually"],link:"https://provedoria.goa.gov.in/",helpline:"0832-2226025",amt:30000,match:p=>p.state==="Goa"&&(p.age>=60||p.lifeStage.includes("widow")||p.lifeStage.includes("disabled"))},

{name:"Kerala KSFE Chitty (Lucky Star) for Women",cat:"social",tag:"Finance",benefit:"Prioritised chit-fund savings + ₹1L bonus for women",desc:"Kerala State Financial Enterprises chit initiative for women SHGs. Regular savings with dividend + bonus on completion.",elig:["Women in Kerala","Member of Kudumbashree/SHG","Regular savings capacity","Aadhaar linked bank account"],docs:["Aadhaar","SHG membership proof","Bank passbook"],apply:["Apply at nearest KSFE branch","Through Kudumbashree NHG","ksfe.com"],link:"https://ksfe.com/",helpline:"0471-2577555",amt:100000,match:p=>p.state==="Kerala"&&p.gender==="female"},

{name:"Tamil Nadu Chief Minister's Breakfast Scheme for Primary School",cat:"education",tag:"Food",benefit:"Free nutritious breakfast for govt school students (class 1-5)",desc:"Hot breakfast served daily at government primary schools. Includes idly, upma, pongal, kesari. 1.14 lakh students benefited.",elig:["Students in class 1-5 in TN government schools","All children regardless of background","No application needed"],docs:["No documents required"],apply:["Automatic in government primary schools","Served daily before classes","School provides"],link:"https://middaymeals.tn.gov.in/",helpline:"044-25670444",amt:0,match:p=>p.state==="Tamil Nadu"&&p.lifeStage.includes("children")},

{name:"AP YSR Sunna Vaddi (Zero Interest Loans for SHGs)",cat:"employment",tag:"Business",benefit:"100% interest reimbursement on SHG loans up to ₹1.5L",desc:"Zero-interest loans for women SHGs. Government reimburses entire bank interest. 9.8 lakh SHGs covered.",elig:["Women SHG member in AP","SHG registered with SERP/APRIGP","Regular loan repayment record","Loan amount up to ₹1.5L"],docs:["SHG registration","Member Aadhaar","Bank loan details","Repayment records"],apply:["Through SHG federation","Village Organization processes","Bank/SERP coordinates"],link:"https://navasakam.ap.gov.in/",helpline:"1902",amt:0,match:p=>p.state==="Andhra Pradesh"&&p.gender==="female"},

{name:"Telangana Dalit Bandhu Scheme",cat:"social",tag:"Welfare",benefit:"₹10 lakh unit cost grant for SC families",desc:"India's biggest SC welfare scheme. ₹10L non-refundable grant per SC family for setting up business/enterprise.",elig:["SC family in Telangana","One beneficiary per family","For setting up enterprise","No income restriction for SC"],docs:["Caste certificate","Aadhaar","DPR/business plan","Bank passbook","Family details"],apply:["Apply through district SC corporation","Selected by Gram Sabha/Ward committee","dalitbandhu.telangana.gov.in"],link:"https://dalitbandhu.telangana.gov.in/",helpline:"040-23450267",amt:1000000,match:p=>p.state==="Telangana"&&p.category==="sc"},

{name:"Odisha Subhadra Yojana (Women Income Support)",cat:"women",tag:"Women",benefit:"₹10,000/year for women aged 21-60",desc:"Annual income support for women in Odisha from all eligible categories. Targets BPL and near-BPL households.",elig:["Women aged 21-60 in Odisha","Not government employee","Not income tax payer","Aadhaar linked bank account"],docs:["Aadhaar","Bank passbook","Self-declaration","Age proof"],apply:["Apply through women helpline","Or Mo Seva Kendra","subhadra.odisha.gov.in"],link:"https://subhadra.odisha.gov.in/",helpline:"181",amt:10000,match:p=>p.state==="Odisha"&&p.gender==="female"&&p.age>=21&&p.age<=60}
];
