// State Schemes Part 1 — Major State Government Schemes (80)
// Karnataka, Maharashtra, Gujarat, Rajasthan, UP, Bihar, MP
export const STATE_SCHEMES_1 = [
// ═══ KARNATAKA (1-12) ═══
{name:"Karnataka Gruha Lakshmi Scheme",cat:"women",tag:"Women",benefit:"₹2,000/month to women head of household",desc:"Monthly financial assistance to women heads of families in Karnataka. Covers 1.28 crore women beneficiaries.",elig:["Woman head of household in Karnataka","Must be BPL/APL","Aadhaar linked to bank account","Not a government employee"],docs:["Aadhaar Card","Ration Card","Bank passbook","Photo"],apply:["Apply at seva sindhu portal","Or Gram Panchayat/ULB office","DBT to bank account"],link:"https://sevasindhu.karnataka.gov.in/",helpline:"080-22230282",amt:24000,match:p=>p.state==="Karnataka"&&p.gender==="female"},

{name:"Karnataka Gruha Jyoti Scheme",cat:"housing",tag:"Energy",benefit:"200 units free electricity per month",desc:"Free electricity up to 200 units for domestic consumers in Karnataka. Saves ₹1,500-₹2,500/month for households.",elig:["Domestic electricity consumer in Karnataka","One connection per household","All income groups eligible"],docs:["Electricity bill","Aadhaar","Address proof"],apply:["Automatic for existing consumers","Apply at BESCOM/HESCOM/GESCOM/MESCOM","No separate application for most"],link:"https://keb.karnataka.gov.in/",helpline:"1912",amt:30000,match:p=>p.state==="Karnataka"},

{name:"Karnataka Anna Bhagya Scheme",cat:"health",tag:"Food",benefit:"10 kg free rice per person per month",desc:"Free rice distribution to BPL families in addition to NFSA entitlement. Benefits 4.22 crore people.",elig:["BPL ration card holder in Karnataka","Antyodaya and Priority households","Must have Aadhaar-linked ration card"],docs:["BPL Ration Card","Aadhaar"],apply:["Automatic for BPL card holders","Collect from nearest Fair Price Shop"],link:"https://ahara.kar.nic.in/",helpline:"1800-425-9339",amt:0,match:p=>p.state==="Karnataka"&&["below1","1to2.5"].includes(p.income)},

{name:"Karnataka Yuva Nidhi Scheme",cat:"employment",tag:"Employment",benefit:"₹1,500-₹3,000/month for unemployed graduates",desc:"Monthly allowance to unemployed graduates for 2 years. ₹1,500 for diploma, ₹3,000 for degree holders.",elig:["Graduate/diploma holder from Karnataka","Unemployed","Age below 35","Family income below ₹6L/year"],docs:["Degree/Diploma certificate","Aadhaar","Income certificate","Unemployment certificate","Bank passbook"],apply:["Apply at Seva Sindhu portal","District employment office verification"],link:"https://sevasindhu.karnataka.gov.in/",helpline:"080-22230282",amt:36000,match:p=>p.state==="Karnataka"&&p.employment==="unemployed"&&["graduate","post-graduate"].includes(p.education)},

{name:"Karnataka Bhagyalaxmi Scheme",cat:"women",tag:"Children",benefit:"₹1 lakh on girl child birth + ₹1 lakh at 18",desc:"Financial support for girl children from BPL families. ₹19,300 in installments + ₹1L bond maturing at 18.",elig:["Girl child born in BPL family in Karnataka","Must be registered within 1 year","Family income below BPL threshold","Maximum 2 girl children"],docs:["Birth certificate","BPL card","Parent's Aadhaar","Bank passbook"],apply:["Register at Anganwadi centre","Apply through Women & Child Welfare Dept"],link:"https://dwcd.karnataka.gov.in/",helpline:"181",amt:100000,match:p=>p.state==="Karnataka"&&p.gender==="female"&&p.lifeStage.includes("children")},

{name:"Karnataka Shakti Scheme (Free Bus Travel)",cat:"transport",tag:"Transport",benefit:"Free bus travel for women in state transport",desc:"Women can travel free on all KSRTC, BMTC, NEKRTC, NWKRTC buses across Karnataka. No distance limit.",elig:["All women in Karnataka","No income restriction","Must carry Aadhaar/ID"],docs:["Aadhaar or any government ID"],apply:["No pass required","Simply board the bus","Show ID if asked"],link:"https://ksrtc.in/",helpline:"080-22222340",amt:0,match:p=>p.state==="Karnataka"&&p.gender==="female"},

{name:"Karnataka Udyogini Scheme",cat:"employment",tag:"Business",benefit:"Subsidy on loans up to ₹3 lakh for women entrepreneurs",desc:"Financial assistance for self-employment of women. Subsidy on bank loan for starting/expanding micro business.",elig:["Women aged 18-65 in Karnataka","Family income below ₹2L/year","For new business setup"],docs:["Aadhaar","Income certificate","Business plan","Bank account","Caste certificate (if applicable)"],apply:["Apply through Karnataka State Women's Dev Corp","Or bank branches","District level offices"],link:"https://kswdc.karnataka.gov.in/",helpline:"080-22373654",amt:300000,match:p=>p.state==="Karnataka"&&p.gender==="female"&&["self-employed","business","unemployed"].includes(p.employment)},

// ═══ MAHARASHTRA (8-19) ═══
{name:"Mukhyamantri Mazi Ladki Bahin Yojana",cat:"women",tag:"Women",benefit:"₹1,500/month for women aged 21-65",desc:"Economic independence for women in Maharashtra. ₹1,500 monthly via DBT. 2.34 crore women beneficiaries.",elig:["Women aged 21-65 in Maharashtra","Family income below ₹2.5L/year","Not a government employee","Not income tax payer"],docs:["Aadhaar","Domicile certificate","Income certificate","Age proof","Bank passbook"],apply:["Apply at Mahaswayamrojgar portal","Or through CSC","ladkibahin.maharashtra.gov.in"],link:"https://ladkibahin.maharashtra.gov.in/",helpline:"1800-120-8040",amt:18000,match:p=>p.state==="Maharashtra"&&p.gender==="female"&&p.age>=21&&p.age<=65},

{name:"Maharashtra Majhi Kanya Bhagyashree",cat:"women",tag:"Children",benefit:"₹50,000 per girl child (up to 2 girls)",desc:"Financial support for girl children. Single girl child: ₹50K, two girls: ₹25K each. Deposit till 18.",elig:["Girl child born in Maharashtra","Mother should have undergone family planning (1 child) or both parents (2 children)","Annual income below ₹7.5L"],docs:["Birth certificate","Parent's Aadhaar","Family planning certificate","Income certificate","Bank passbook"],apply:["Apply at district WCD office","Through Anganwadi centre"],link:"https://womenchild.maharashtra.gov.in/",helpline:"181",amt:50000,match:p=>p.state==="Maharashtra"&&p.gender==="female"&&p.lifeStage.includes("children")},

{name:"Maharashtra Lek Ladki Yojana",cat:"women",tag:"Children",benefit:"₹1.01 lakh in 5 installments from birth to 18",desc:"Staggered financial assistance for girls from yellow/orange ration card families. ₹5K at birth to ₹1L at 18.",elig:["Girl child born in Maharashtra","Family with yellow/orange ration card","For children born after 1 April 2023"],docs:["Birth certificate","Ration Card","Parent Aadhaar","Bank passbook"],apply:["Register at nearest Anganwadi centre","Or hospital at time of birth"],link:"https://womenchild.maharashtra.gov.in/",helpline:"181",amt:101000,match:p=>p.state==="Maharashtra"&&p.gender==="female"&&p.lifeStage.includes("children")},

{name:"Mukhyamantri Yuva Karya Prashikshan Yojana (Maharashtra)",cat:"education",tag:"Skill",benefit:"Paid internship + stipend for youth",desc:"Maharashtra's skilling programme. 10 lakh youth trained with corporate internships. ₹5,500 crore budget allocation.",elig:["Youth in Maharashtra","Age 18-35","Graduate/diploma holder","Unemployed or underemployed"],docs:["Educational certificates","Aadhaar","Bank passbook"],apply:["Apply online at mahaswayamrojgar.in","Through district skill development centre"],link:"https://mahaswayamrojgar.maharashtra.gov.in/",helpline:"1800-120-8040",amt:0,match:p=>p.state==="Maharashtra"&&p.age>=18&&p.age<=35},

{name:"Mahatma Jyotirao Phule Jan Arogya Yojana (MJPJAY)",cat:"health",tag:"Health",benefit:"₹1.5L-₹5L cashless health insurance per family",desc:"Maharashtra's own health insurance in addition to Ayushman Bharat. Covers 996 procedures at 1,000+ hospitals.",elig:["Yellow/Orange/White ration card holders in Maharashtra","Farmers with crop insurance","Construction workers registered with BOCW"],docs:["Ration Card","Aadhaar","Health card"],apply:["Register at empanelled hospital","jeevandayee.gov.in for e-card","Cashless treatment at network hospitals"],link:"https://jeevandayee.gov.in/",helpline:"155388",amt:500000,match:p=>p.state==="Maharashtra"&&["below1","1to2.5","2.5to5"].includes(p.income)},

{name:"Maharashtra Gharkul Yojana (Housing)",cat:"housing",tag:"Housing",benefit:"₹2.5L subsidy for house construction",desc:"Affordable housing for EWS/LIG in Maharashtra. Supplements PM Awas with state contribution.",elig:["Houseless or living in kutcha house","EWS/LIG family in Maharashtra","BPL preferred"],docs:["Income certificate","No-property certificate","Aadhaar","Domicile certificate"],apply:["Apply through Gram Panchayat","Or urban local body","Ramai Awas Yojana for SC beneficiaries"],link:"https://housing.maharashtra.gov.in/",helpline:"022-22025225",amt:250000,match:p=>p.state==="Maharashtra"&&p.ownHouse!=="yes"&&["below1","1to2.5","2.5to5"].includes(p.income)},

// ═══ GUJARAT (14-23) ═══
{name:"Gujarat Namo Lakshmi Yojana",cat:"education",tag:"Education",benefit:"₹50,000 over 4 years for girls in class 9-12",desc:"₹10,000/year for class 9-10, ₹15,000/year for class 11-12. Reduces girl dropout rates in Gujarat.",elig:["Girls studying in class 9-12 in Gujarat","Government/grant-in-aid/private schools","No income restriction"],docs:["School enrollment certificate","Aadhaar of student","Parent's bank passbook","Previous year marksheet"],apply:["Apply through school","Digital Gujarat portal","Direct scholarship to bank account"],link:"https://digitalgujarat.gov.in/",helpline:"079-232-56591",amt:50000,match:p=>p.state==="Gujarat"&&p.gender==="female"&&p.employment==="student"},

{name:"Gujarat Namo Saraswati Scheme",cat:"education",tag:"Scholarship",benefit:"₹25,000 over 2 years for science students",desc:"₹10,000 in class 11, ₹15,000 in class 12 for science stream students from low/middle-income families.",elig:["Science stream students in Gujarat class 11-12","Low and middle-income families","Studying in recognized school"],docs:["School admission receipt","Aadhaar","Income certificate","Previous marksheet"],apply:["Apply through school","Digital Gujarat portal"],link:"https://digitalgujarat.gov.in/",helpline:"079-232-56591",amt:25000,match:p=>p.state==="Gujarat"&&p.employment==="student"},

{name:"Gujarat Namo Shri Yojana",cat:"health",tag:"Health",benefit:"₹12,000 for pregnant & lactating mothers",desc:"Nutritional support for pregnant and lactating women from 11 categories including SC/ST/NFSA/PM-JAY beneficiaries.",elig:["Pregnant/lactating women in Gujarat","SC/ST/NFSA/PM-JAY beneficiary categories","Registered at health centre"],docs:["Aadhaar","MCH Card","SC/ST/BPL certificate","Bank passbook"],apply:["Register at nearest health centre","Through ICDS/Anganwadi centre","DBT to bank account"],link:"https://guj-nrhm.gujarat.gov.in/",helpline:"104",amt:12000,match:p=>p.state==="Gujarat"&&p.gender==="female"&&p.lifeStage.includes("pregnant")},

{name:"Gujarat Mukhyamantri Kisan Sahay Yojana",cat:"agriculture",tag:"Agriculture",benefit:"₹20,000-₹25,000/ha crop loss compensation",desc:"Financial assistance for crop loss due to drought, flood, unseasonal rain. Quick relief without insurance premium.",elig:["All farmers in Gujarat","Land records required","For notified natural calamity areas"],docs:["7/12 land record","Aadhaar","Bank passbook","Crop damage report from talathi"],apply:["Automatic for affected areas","Talathi assesses damage","Amount credited via DBT"],link:"https://agri.gujarat.gov.in/",helpline:"1800-180-0010",amt:25000,match:p=>p.state==="Gujarat"&&p.employment==="farmer"},

{name:"Gujarat Digital Gujarat Scholarship",cat:"education",tag:"Scholarship",benefit:"₹10,000-₹25,000 scholarship for SC/ST/OBC students",desc:"Post-matric scholarship for economically weaker students pursuing higher education in Gujarat.",elig:["SC/ST/OBC/Minority students in Gujarat","Family income below ₹2.5L/year","Studying in recognized institution"],docs:["Caste certificate","Income certificate","Previous marksheet","Admission letter","Bank passbook"],apply:["Apply on digitalgujarat.gov.in","During scholarship period","College verification required"],link:"https://digitalgujarat.gov.in/",helpline:"079-232-56591",amt:25000,match:p=>p.state==="Gujarat"&&["sc","st","obc","minority"].includes(p.category)&&p.employment==="student"},

// ═══ RAJASTHAN (19-28) ═══
{name:"Rajasthan Mukhyamantri Rajshree Yojana",cat:"women",tag:"Children",benefit:"₹50,000 in 6 installments from birth to class 12",desc:"Girl child welfare scheme. ₹2,500 at birth, increasing installments at class 1,6,10,12. Max ₹50K total.",elig:["Girl child born in Rajasthan govt hospital","Rajasthan resident family","Up to 2 girl children"],docs:["Birth certificate","Bhamashah/Jan Aadhaar Card","Mother's Aadhaar","School enrollment"],apply:["Register at time of birth at hospital","Updates at school enrollment milestones","jansoochna.rajasthan.gov.in"],link:"https://wcd.rajasthan.gov.in/",helpline:"181",amt:50000,match:p=>p.state==="Rajasthan"&&p.gender==="female"&&p.lifeStage.includes("children")},

{name:"Rajasthan Indira Gandhi Matritva Poshan Yojana",cat:"health",tag:"Health",benefit:"₹6,000 in 5 installments for pregnant women",desc:"Cash assistance for pregnant and lactating women for improved nutrition. 5 installments across pregnancy and lactation.",elig:["Pregnant women in Rajasthan","2nd child onwards","BPL/SC/ST/tribal women priority"],docs:["Aadhaar","MCH Card","Bank passbook","Pregnancy registration"],apply:["Register at Anganwadi centre","Or nearest health centre","DBT to bank account"],link:"https://wcd.rajasthan.gov.in/",helpline:"181",amt:6000,match:p=>p.state==="Rajasthan"&&p.gender==="female"&&p.lifeStage.includes("pregnant")},

{name:"Rajasthan Mukhyamantri Yuva Sambal Yojana",cat:"employment",tag:"Employment",benefit:"₹3,500/month (men) ₹4,000/month (women) unemployment allowance",desc:"Monthly allowance for unemployed youth for 2 years. Higher amount for women and disabled candidates.",elig:["Rajasthan domicile","Age 21-25 (general), extended for SC/ST/PwD","Graduate or post-graduate","Unemployed"],docs:["Graduation certificate","Domicile certificate","Aadhaar","Unemployment certificate","Bank passbook"],apply:["Apply at employment.livelihoods.rajasthan.gov.in","District employment exchange","Quarterly renewal required"],link:"https://employment.livelihoods.rajasthan.gov.in/",helpline:"141-2226704",amt:48000,match:p=>p.state==="Rajasthan"&&p.employment==="unemployed"&&p.age>=21&&p.age<=25},

{name:"Rajasthan Mukhyamantri Chiranjeevi Swasthya Bima Yojana",cat:"health",tag:"Insurance",benefit:"₹25L cashless health insurance per family",desc:"Universal health coverage in Rajasthan. ₹25 lakh per family per year at empanelled hospitals. Free for eligible categories.",elig:["Rajasthan domicile","All families can opt in","Free for: NFSA, SECC, small/marginal farmers, contractual workers","Others: ₹850/year premium"],docs:["Jan Aadhaar Card","Aadhaar","Family details"],apply:["Register at chiranjeevi.rajasthan.gov.in","e-Mitra kiosk","Or empanelled hospital"],link:"https://chiranjeevi.rajasthan.gov.in/",helpline:"181",amt:2500000,match:p=>p.state==="Rajasthan"},

{name:"Rajasthan Palanhar Yojana",cat:"social",tag:"Children",benefit:"₹1,500/month for orphaned children's guardians",desc:"Financial support for guardians fostering orphaned/destitute children. ₹500 for 0-5 yrs, ₹1,000 for 6-18 yrs + ₹2,000/yr clothing.",elig:["Guardian of orphan/destitute child in Rajasthan","Child's parent deceased/life imprisonment/disabled","BPL family of guardian"],docs:["Death certificate of parents (or relevant proof)","Guardian's Aadhaar","Child's Aadhaar","BPL certificate","School enrollment (for 6-18)"],apply:["Apply at district social justice office","Or e-Mitra kiosk","jansoochna.rajasthan.gov.in"],link:"https://sje.rajasthan.gov.in/",helpline:"181",amt:18000,match:p=>p.state==="Rajasthan"&&p.lifeStage.includes("children")},

{name:"Rajasthan Free Scooty Yojana (Devnarayan/Kali Bai)",cat:"education",tag:"Education",benefit:"Free scooty for meritorious girl students",desc:"Free scooty to girl students scoring 65%+ in class 12 and pursuing higher education. Multiple schemes based on caste category.",elig:["Girl student in Rajasthan","75%+ marks in class 12 (general), 65%+ (SC/ST)","Pursuing regular college/university course","Family income below ₹2.5L (SC/ST) or ₹2L"],docs:["Marksheet","College admission proof","Caste certificate","Income certificate","Aadhaar"],apply:["Apply through Rajasthan SSO portal","College recommends eligible students","Scooty distributed at state events"],link:"https://hte.rajasthan.gov.in/",helpline:"0141-2706106",amt:50000,match:p=>p.state==="Rajasthan"&&p.gender==="female"&&p.employment==="student"},

// ═══ UTTAR PRADESH (25-35) ═══
{name:"UP Kanya Sumangala Yojana",cat:"women",tag:"Children",benefit:"₹25,000 in 6 installments from birth to graduation",desc:"Up from ₹15K to ₹25K from 2024-25. ₹5K at birth, installments at milestones including class 1,6,9,10,12 & graduation.",elig:["Girl child born in UP","Family annual income below ₹3L","Maximum 2 girl children in family","UP domicile"],docs:["Birth certificate","Aadhaar of parent","Income certificate","Bank passbook","Photo"],apply:["Apply at mksy.up.gov.in","Or through CSC","District Probation Office"],link:"https://mksy.up.gov.in/",helpline:"1800-180-1234",amt:25000,match:p=>p.state==="Uttar Pradesh"&&p.gender==="female"&&p.lifeStage.includes("children")},

{name:"UP Mukhyamantri Abhyudaya Yojana (Free Coaching)",cat:"education",tag:"Education",benefit:"Free coaching for UPSC, JEE, NEET, NDA and other competitive exams",desc:"Free coaching for economically weaker students. Expert faculty from top coaching centres. Online + offline mode.",elig:["UP domicile student","Preparing for competitive exams","Economically weaker background preferred","No formal income restriction for online"],docs:["Aadhaar","Student ID","Educational certificates","Domicile proof"],apply:["Register at abhyuday.up.gov.in","Online classes available on YouTube","Divisional headquarters for offline coaching"],link:"https://abhyuday.up.gov.in/",helpline:"0522-2240122",amt:0,match:p=>p.state==="Uttar Pradesh"&&p.employment==="student"},

{name:"UP Shramik Bharan Poshan Yojana",cat:"employment",tag:"Employment",benefit:"₹1,000/month + subsidized food for daily wage workers",desc:"Financial assistance and food security for registered daily wage labourers and construction workers in UP.",elig:["Registered construction/daily wage worker in UP","BOCW card holder","Age 18-60"],docs:["BOCW registration card","Aadhaar","Bank passbook"],apply:["Through BOCW department","District labour office","Automatic for registered workers"],link:"https://upbocw.in/",helpline:"1800-180-5412",amt:12000,match:p=>p.state==="Uttar Pradesh"&&["unemployed","self-employed"].includes(p.employment)&&["below1","1to2.5"].includes(p.income)},

{name:"UP Mukhyamantri Jan Arogya Yojana",cat:"health",tag:"Health",benefit:"₹5L health insurance for families not covered under PMJAY",desc:"State health insurance for families above PMJAY threshold but still needing support. Cashless treatment at empanelled hospitals.",elig:["UP resident family","Not covered under PMJAY","Income up to ₹1.8L/year","Priority: MGNREGA, ration card holders"],docs:["Aadhaar","Income certificate","Family ID/Ration card"],apply:["Register at nearest empanelled hospital","Or district health office","jan arogya application"],link:"https://jan-arogya.up.nic.in/",helpline:"180-018-01234",amt:500000,match:p=>p.state==="Uttar Pradesh"&&["below1","1to2.5","2.5to5"].includes(p.income)},

{name:"UP Samuhik Vivah Yojana",cat:"social",tag:"Welfare",benefit:"₹51,000 assistance per couple for mass wedding",desc:"Government organizes mass weddings. ₹35K gift items + ₹10K cash + ₹6K administrative cost per couple.",elig:["Bride/groom from UP","Bride age 18+, groom 21+","Family income below ₹2L (rural)/₹2.5L (urban)","SC/ST/OBC/minority/BPL families"],docs:["Aadhaar of bride and groom","Income certificate","Age proof","Caste certificate","Residence proof"],apply:["Apply through district WCD office","Gram Panchayat/Nagar Palika","Before mass wedding date announcement"],link:"https://sspy-up.gov.in/",helpline:"180-018-01234",amt:51000,match:p=>p.state==="Uttar Pradesh"&&["below1","1to2.5"].includes(p.income)},

{name:"UP Pension Scheme (Old Age/Widow/Disabled)",cat:"social",tag:"Pension",benefit:"₹1,000-₹1,500/month pension",desc:"UP state pension for elderly (₹1,000), widows (₹500-₹1,000), and disabled (₹1,000). Quarterly disbursement.",elig:["UP resident","Old Age: 60+, BPL","Widow: 18+, BPL","Disabled: 40%+ disability, any age, BPL"],docs:["Aadhaar","Age proof","BPL card","Death certificate (widow)","Disability certificate","Bank passbook"],apply:["Apply at sspy-up.gov.in","Through District Social Welfare","Gram Panchayat recommends"],link:"https://sspy-up.gov.in/",helpline:"18004190001",amt:12000,match:p=>p.state==="Uttar Pradesh"&&(p.age>=60||p.lifeStage.includes("widow")||p.lifeStage.includes("disabled"))&&["below1","1to2.5"].includes(p.income)},

// ═══ BIHAR (30-38) ═══
{name:"Bihar Mukhyamantri Kanya Utthan Yojana",cat:"women",tag:"Children",benefit:"₹54,100 from birth to graduation",desc:"Comprehensive girl child empowerment. ₹2K at birth, ₹1K at 1yr, ₹2K at 2yr, ₹25K at graduation etc. Maximum ₹54,100.",elig:["Girl child born in Bihar","All families eligible","Up to 2 daughters","Must pursue education till graduation"],docs:["Birth certificate","Aadhaar","School enrollment","Graduation certificate","Bank passbook"],apply:["Apply at medhasoft.bih.nic.in","Through school/college","District WCD office"],link:"https://medhasoft.bih.nic.in/",helpline:"0612-2506068",amt:54100,match:p=>p.state==="Bihar"&&p.gender==="female"},

{name:"Bihar Student Credit Card Scheme",cat:"education",tag:"Education",benefit:"₹4 lakh education loan at 0% interest for students",desc:"Interest-free education loan for 12th pass students. Covers 42 courses. Guarantor not needed for girls.",elig:["Bihar domicile","Passed class 12","Age below 25","Admission in recognized institution","Course duration max 4 years"],docs:["12th marksheet","Aadhaar","Admission letter","Income certificate","Bank passbook"],apply:["Apply at 7nishchay-yuvaupmission.bihar.gov.in","DRCC office processes","Loan disbursed to institution"],link:"https://7nishchay-yuvaupmission.bihar.gov.in/",helpline:"1800-3456-444",amt:400000,match:p=>p.state==="Bihar"&&p.employment==="student"},

{name:"Bihar Mukhyamantri Cycle Yojana",cat:"education",tag:"Education",benefit:"Free bicycle for class 9 students",desc:"Free bicycle to encourage higher secondary education. Reduced dropout rate by 12% since implementation.",elig:["Students in Bihar government schools","Entering class 9","All categories eligible"],docs:["School enrollment","Aadhaar","Previous class marksheet"],apply:["Automatic through school","No separate application","School distributes"],link:"https://education.bih.nic.in/",helpline:"0612-2215417",amt:3000,match:p=>p.state==="Bihar"&&p.employment==="student"},

{name:"Bihar Kushal Yuva Program",cat:"education",tag:"Skill",benefit:"Free skill training in communication, computer & soft skills",desc:"3-month training for unemployed youth. Computer skills, soft skills, communication training. Certificate on completion.",elig:["Bihar domicile","Age 15-25 (25-28 for SC/ST/OBC/PwD)","Minimum 10th pass","Unemployed"],docs:["Aadhaar","10th marksheet","Age proof","Bank passbook"],apply:["Apply at skillmissionbihar.org","Or nearest BELTRON centre","Free enrollment"],link:"https://skillmissionbihar.org/",helpline:"1800-3456-444",amt:0,match:p=>p.state==="Bihar"&&p.age>=15&&p.age<=28&&p.employment==="unemployed"},

{name:"Bihar Mukhyamantri Vriddhjan Pension Yojana",cat:"social",tag:"Pension",benefit:"₹400-₹500/month pension for elderly",desc:"State pension for senior citizens. ₹400/month for 60-79 yrs, ₹500/month for 80+ yrs. Supplements central pension.",elig:["Bihar resident","Age 60+","Not receiving any other government pension","All categories eligible"],docs:["Aadhaar","Age proof","Bank passbook","Voter ID"],apply:["Apply at serviceonline.bihar.gov.in","Through Block/Mukhiya office","Verification by Mukhiya"],link:"https://serviceonline.bihar.gov.in/",helpline:"0612-2215417",amt:6000,match:p=>p.state==="Bihar"&&p.age>=60},

// ═══ MADHYA PRADESH (35-43) ═══
{name:"MP Ladli Behna Yojana",cat:"women",tag:"Women",benefit:"₹1,250/month for women aged 23-60",desc:"Monthly financial assistance for women in MP. 1.29 crore+ women enrolled. Increased from ₹1,000 to ₹1,250/month.",elig:["Married women aged 23-60 in MP","Family income below ₹2.5L/year","Not income tax payer","Not receiving > ₹12K from other pension"],docs:["Aadhaar","Samagra ID","Bank passbook","Date of birth proof"],apply:["Apply at cmladlibahna.mp.gov.in","Through Gram Panchayat camp","Ward/village level registration"],link:"https://cmladlibahna.mp.gov.in/",helpline:"0755-2700800",amt:15000,match:p=>p.state==="Madhya Pradesh"&&p.gender==="female"&&p.age>=23&&p.age<=60},

{name:"MP Mukhyamantri Seekho Kamao Yojana",cat:"education",tag:"Skill",benefit:"₹8,000-₹10,000/month stipend during training",desc:"On-the-job training scheme. ₹8K (12th pass), ₹8.5K (ITI), ₹9K (diploma), ₹10K (graduate). 46 sectors, 700+ courses.",elig:["MP domicile","Age 18-29","Minimum 12th pass/ITI/diploma/degree","Unemployed/underemployed"],docs:["Aadhaar","Samagra ID","Educational certificates","Bank passbook"],apply:["Register at mmsky.mp.gov.in","Apply to establishments offering training","Govt pays 75% stipend, employer pays 25%"],link:"https://mmsky.mp.gov.in/",helpline:"0755-2525252",amt:120000,match:p=>p.state==="Madhya Pradesh"&&p.age>=18&&p.age<=29&&["unemployed","student"].includes(p.employment)},

{name:"MP Mukhyamantri Kisan Samman Nidhi",cat:"agriculture",tag:"Agriculture",benefit:"₹4,000/year additional income for farmers",desc:"State top-up to PM-KISAN. ₹2,000 every 6 months in addition to central ₹6,000. Total ₹10,000/year for MP farmers.",elig:["Farmer in MP","Must be PM-KISAN beneficiary","Landholding up to 5 acres","Registered on Samagra"],docs:["PM-KISAN registration","Aadhaar","Samagra ID","Land records"],apply:["Automatic for registered PM-KISAN farmers in MP","Through agriculture department","DBT to bank account"],link:"https://mpkisan.mp.gov.in/",helpline:"0755-2700800",amt:4000,match:p=>p.state==="Madhya Pradesh"&&p.employment==="farmer"},

{name:"MP Ladli Laxmi Yojana 2.0",cat:"women",tag:"Children",benefit:"₹1.43 lakh for girl child from birth to marriage",desc:"Pioneer girl child scheme. ₹6K/year for 5 years (total ₹30K) + ₹1.18L at age 21 on graduation. Free higher education too.",elig:["Girl child born in MP","Parents are MP domicile","Not income tax payers","Registered within 1 year of birth"],docs:["Birth certificate","Parent's Aadhaar","Samagra ID","Bank passbook"],apply:["Apply at ladlilaxmi.mp.gov.in","Through Anganwadi centre","District WCD office"],link:"https://ladlilaxmi.mp.gov.in/",helpline:"0755-2550911",amt:143000,match:p=>p.state==="Madhya Pradesh"&&p.gender==="female"&&p.lifeStage.includes("children")},

// ═══ WEST BENGAL (39-46) ═══
{name:"West Bengal Kanyashree Prakalpa",cat:"education",tag:"Education",benefit:"₹25,000 one-time grant at 18 + ₹1,000/year",desc:"International award-winning scheme. Annual ₹1,000 for 13-18 yr girls in school. ₹25K one-time at 18 if unmarried & in education.",elig:["Girl student aged 13-18 in WB","Studying in recognized institution","Unmarried","Family income below ₹1.2L/year"],docs:["School certificate","Age proof","Income certificate","Aadhaar","Bank passbook"],apply:["Apply through school","Kanyashree online portal","Schools process applications"],link:"https://wbkanyashree.gov.in/",helpline:"1800-345-7007",amt:25000,match:p=>p.state==="West Bengal"&&p.gender==="female"&&p.employment==="student"},

{name:"West Bengal Lakshmir Bhandar (Duare Sarkar)",cat:"women",tag:"Women",benefit:"₹500-₹1,000/month for women",desc:"Monthly income support for women. ₹1,000 for SC/ST women, ₹500 for general category. 1.6 crore beneficiaries.",elig:["Women aged 25-60 in West Bengal","Not income tax payer","Not government employee","Annual family income below ₹2.5L"],docs:["Aadhaar","Voter ID","Bank passbook","Income self-declaration"],apply:["Apply at Duare Sarkar camps","Or online application","Through Block/Municipal office"],link:"https://socialsecurity.wb.gov.in/",helpline:"1800-345-7007",amt:12000,match:p=>p.state==="West Bengal"&&p.gender==="female"&&p.age>=25&&p.age<=60},

{name:"West Bengal Swasthya Sathi Scheme",cat:"health",tag:"Insurance",benefit:"₹5L cashless health insurance per family",desc:"Universal health coverage for WB families. ₹5L/year. Smart card for cashless treatment at 2,000+ hospitals.",elig:["All families in West Bengal","Swasthya Sathi card holder","No income restriction — universal coverage"],docs:["Voter ID/Aadhaar of head of family","Family details","Smart card issued at camp"],apply:["Register at Duare Sarkar camp","District health office","Smart card issued on spot"],link:"https://swasthyasathi.gov.in/",helpline:"1800-345-7007",amt:500000,match:p=>p.state==="West Bengal"},

{name:"West Bengal Rupashree Prakalpa",cat:"social",tag:"Welfare",benefit:"₹25,000 one-time marriage assistance for girls",desc:"Financial assistance for marriage of girls from economically weaker families. Over 15 lakh beneficiaries.",elig:["Girl aged 18+ from WB","Family annual income below ₹1.5L","Applied before marriage date","First marriage only"],docs:["Age proof","Income certificate","Aadhaar","Bank passbook","Marriage registration"],apply:["Apply through Block Development Office","Or Duare Sarkar portal","60 days before marriage"],link:"https://socialsecurity.wb.gov.in/",helpline:"1800-345-7007",amt:25000,match:p=>p.state==="West Bengal"&&p.gender==="female"&&["below1","1to2.5"].includes(p.income)},

// ═══ KERALA (43-49) ═══
{name:"Kerala LIFE Mission (Housing)",cat:"housing",tag:"Housing",benefit:"Free house for landless & homeless families",desc:"Complete housing for homeless families in Kerala. 4.32 lakh houses planned. Apartment complexes in urban areas.",elig:["Landless/homeless family in Kerala","Selected by Gram Sabha","Priority: SC/ST, fishermen, tribal, disabled"],docs:["Landlessness certificate","Income certificate","Aadhaar","Family details"],apply:["Through Gram Panchayat/Municipality","LIFE Mission ward-level survey","life.kerala.gov.in"],link:"https://life.kerala.gov.in/",helpline:"0471-2365041",amt:400000,match:p=>p.state==="Kerala"&&p.ownHouse!=="yes"&&["below1","1to2.5"].includes(p.income)},

{name:"Kerala Welfare Pension Scheme",cat:"social",tag:"Pension",benefit:"₹1,600/month pension for elderly/widows/disabled",desc:"Kerala's social security pension. ₹1,600/month (one of highest in India). Covers old age, widow, disabled categories.",elig:["Kerala resident","Old age: 60+, BPL","Widow/Deserted women: any age, BPL","Disabled: 40%+, any age"],docs:["Aadhaar","Age proof","BPL certificate","Bank passbook","Disability certificate (if applicable)"],apply:["Apply at pension.socialsecuritymission.gov.in","Through LSG (Panchayat/Municipality)","Renewal annually"],link:"https://socialsecuritymission.gov.in/",helpline:"0471-2334414",amt:19200,match:p=>p.state==="Kerala"&&(p.age>=60||p.lifeStage.includes("widow")||p.lifeStage.includes("disabled"))},

{name:"Kerala Snehapoorvam Scholarship",cat:"education",tag:"Scholarship",benefit:"₹300-₹1,000/month for orphaned/vulnerable students",desc:"Educational financial assistance for orphaned and vulnerable children. Monthly scholarship from class 1 to professional courses.",elig:["Orphan/single parent/deserted child in Kerala","Studying in recognized institution","Below poverty line family"],docs:["Death certificate of parent","School certificate","Income certificate","BPL card","Bank passbook"],apply:["Apply through ICDS office","District Social Justice Office","pension.socialsecuritymission.gov.in"],link:"https://socialsecuritymission.gov.in/",helpline:"0471-2334414",amt:12000,match:p=>p.state==="Kerala"&&p.employment==="student"&&["below1","1to2.5"].includes(p.income)},

// ═══ ANDHRA PRADESH (47-53) ═══
{name:"AP YSR Cheyutha Scheme",cat:"women",tag:"Women",benefit:"₹18,750/year for women aged 45-60",desc:"Annual financial assistance for women in BC/SC/ST/Minority communities. Over 23 lakh beneficiaries.",elig:["Women aged 45-60 in AP","BC/SC/ST/Minority community","Family income below ₹10,000/month","Not income tax payer"],docs:["Aadhaar","Caste certificate","Age proof","White ration card","Bank passbook"],apply:["Through Village/Ward Secretariat","Navasakam portal","DBT on birthday of beneficiary"],link:"https://navasakam.ap.gov.in/",helpline:"1902",amt:18750,match:p=>p.state==="Andhra Pradesh"&&p.gender==="female"&&p.age>=45&&p.age<=60},

{name:"AP YSR Aarogyasri Health Insurance",cat:"health",tag:"Insurance",benefit:"₹5 lakh cashless treatment for BPL families",desc:"AP's health insurance covering 2,400+ procedures at 1,400+ hospitals. White ration card holders eligible.",elig:["White ration card holder in AP","Below poverty line family","All family members covered"],docs:["White ration card","Aadhaar","Aarogyasri Health Card"],apply:["Register at empanelled hospital","Through Aadhaar-based authentication","Cashless at network hospitals"],link:"https://aarogyasri.ap.gov.in/",helpline:"104",amt:500000,match:p=>p.state==="Andhra Pradesh"&&["below1","1to2.5"].includes(p.income)},

{name:"AP Amma Vodi Scheme",cat:"education",tag:"Education",benefit:"₹15,000/year to mothers for sending children to school",desc:"Cash incentive to mothers/guardians to ensure children attend school. Reduces dropout rates. 44 lakh beneficiaries.",elig:["Mother/guardian of school-going child in AP","Child studying in class 1-12 in govt/aided school","Family below poverty line"],docs:["Aadhaar of mother","Child's school enrollment","White ration card","Bank passbook"],apply:["Through school","Village/Ward Secretariat","Automatic for eligible families"],link:"https://navasakam.ap.gov.in/",helpline:"1902",amt:15000,match:p=>p.state==="Andhra Pradesh"&&p.lifeStage.includes("children")&&["below1","1to2.5"].includes(p.income)},

{name:"AP Jagananna Vasathi Deevena",cat:"education",tag:"Scholarship",benefit:"₹10,000-₹20,000/year for hostel & mess charges",desc:"Hostel fee reimbursement for SC/ST/BC/Minority/EBC/Disabled/Kapu students in degree/PG/professional courses.",elig:["Student in AP from SC/ST/BC/Minority/EBC","Studying ITI/degree/PG/professional course","Family income below ₹2.5L/year"],docs:["Caste certificate","Income certificate","College admission","Aadhaar","Bank passbook"],apply:["Apply through Jnanabhumi portal","College processes application","jnanabhumi.ap.gov.in"],link:"https://jnanabhumi.ap.gov.in/",helpline:"1902",amt:20000,match:p=>p.state==="Andhra Pradesh"&&p.employment==="student"&&["sc","st","obc","minority"].includes(p.category)},

// ═══ TELANGANA (51-56) ═══
{name:"Telangana Aasara Pension Scheme",cat:"social",tag:"Pension",benefit:"₹2,016/month pension for elderly/widows/disabled",desc:"One of India's highest state pensions. ₹2,016/month for eligible categories. 44 lakh beneficiaries.",elig:["Telangana domicile","Old age: 57+","Widow: any age","Disabled: 40%+","BPL/EWS families"],docs:["Aadhaar","Age proof","Bank passbook","Death certificate of husband (widow)","Disability certificate"],apply:["Apply through MeeSeva centre","Or online at telanganaepasssite.cgg.gov.in","Tahsildar verification"],link:"https://telanganaepasssite.cgg.gov.in/",helpline:"040-23450267",amt:24192,match:p=>p.state==="Telangana"&&(p.age>=57||p.lifeStage.includes("widow")||p.lifeStage.includes("disabled"))},

{name:"Telangana Kalyana Lakshmi/Shaadi Mubarak",cat:"social",tag:"Welfare",benefit:"₹1,00,116 marriage assistance for girls",desc:"₹1,00,116 for marriage of girls from BPL families. Kalyana Lakshmi for Hindus, Shaadi Mubarak for Muslims.",elig:["Girl aged 18+ in Telangana","Bride's family income below ₹2L/year","First marriage","Family registered in food security cards"],docs:["Aadhaar","Food security card","Age proof","Caste certificate","Marriage date proof","Bank passbook"],apply:["Apply at telanganaepass.cgg.gov.in","Through MeeSeva","10 days before marriage to 1 year after"],link:"https://telanganaepass.cgg.gov.in/",helpline:"040-23450267",amt:100116,match:p=>p.state==="Telangana"&&p.gender==="female"&&["below1","1to2.5"].includes(p.income)},

{name:"Telangana KCR Kit Scheme",cat:"health",tag:"Health",benefit:"₹12,000 worth baby care kit for newborns",desc:"Comprehensive baby care kit for children born in govt hospitals. Includes baby clothes, toys, mosquito net, diapers, oil, soap etc.",elig:["Baby born in Telangana govt hospital","Mother registered for institutional delivery","All income groups"],docs:["Hospital delivery record","Mother's Aadhaar","MCH card"],apply:["Automatic at government hospital","Kit given at discharge","No separate application"],link:"https://health.telangana.gov.in/",helpline:"104",amt:12000,match:p=>p.state==="Telangana"&&p.lifeStage.includes("pregnant")},

// ═══ ODISHA (54-58) ═══
{name:"Odisha KALIA Yojana",cat:"agriculture",tag:"Agriculture",benefit:"₹12,500/year for farmers in 5 installments",desc:"Krushak Assistance for Livelihood & Income Augmentation. ₹25,000 over 5 seasons for cultivation. Also covers landless labourers.",elig:["Small/marginal farmer in Odisha","Landless agricultural labourers also eligible","Cultivators & sharecroppers"],docs:["Aadhaar","Land records (or landless certificate)","Bank passbook"],apply:["kalia.odisha.gov.in","Through Block agriculture office","Gram Panchayat endorsement"],link:"https://kalia.odisha.gov.in/",helpline:"1800-345-6778",amt:12500,match:p=>p.state==="Odisha"&&p.employment==="farmer"},

{name:"Odisha Mamata Yojana",cat:"health",tag:"Health",benefit:"₹5,000 for pregnant & lactating women",desc:"Conditional cash transfer for 1st & 2nd pregnancy. ₹5,000 in installments. Must register pregnancy and follow ANC protocols.",elig:["Pregnant women in Odisha","1st and 2nd live births only","Age 19+","Registered at Anganwadi/health centre"],docs:["Aadhaar","MCH card","Bank passbook","Pregnancy registration"],apply:["Register at Anganwadi centre","Or ANM/ASHA worker","DBT after each condition met"],link:"https://wcdodisha.gov.in/",helpline:"181",amt:5000,match:p=>p.state==="Odisha"&&p.gender==="female"&&p.lifeStage.includes("pregnant")},

// ═══ HARYANA (56-60) ═══
{name:"Haryana Ladli Pension Yojana",cat:"social",tag:"Pension",benefit:"₹2,750/month pension for various categories",desc:"Haryana's social security pension. Old age (₹2,750), widow (₹2,750), disabled (₹2,550), ladli (girls' parents).",elig:["Haryana domicile","Old age: 60+","Widow: any age","Disabled: 60%+","Income below ₹2L/year"],docs:["Aadhaar","PPP ID","Age proof","Bank passbook","BPL/Income certificate"],apply:["Apply at pension.socialjusticehry.gov.in","Through Atal Seva Kendra","Saral Haryana portal"],link:"https://pension.socialjusticehry.gov.in/",helpline:"1800-180-8757",amt:33000,match:p=>p.state==="Haryana"&&(p.age>=60||p.lifeStage.includes("widow")||p.lifeStage.includes("disabled"))},

{name:"Haryana Mukhyamantri Vivah Shagun Yojana",cat:"social",tag:"Welfare",benefit:"₹71,000 marriage assistance for economically weaker girls",desc:"Financial assistance for marriage. ₹71K for SC girls, ₹51K for BPL sports, ₹11K for general. Athlete bonus included.",elig:["Girl's family from Haryana","Bride age 18+, groom 21+","Family income below ₹1.8L/year (non-SC)","SC/Destitute/Widows: no income limit"],docs:["Aadhaar","PPP ID","Marriage card/proof","Domicile certificate","Caste/Income certificate"],apply:["Apply through Saral Haryana portal","Antyodaya SARAL Kendra","Within 6 months of marriage"],link:"https://shaadi.edisha.gov.in/",helpline:"1800-180-8757",amt:71000,match:p=>p.state==="Haryana"&&p.gender==="female"&&["below1","1to2.5"].includes(p.income)},

// ═══ PUNJAB (58-62) ═══
{name:"Punjab Aashirwad Scheme (Marriage Assistance)",cat:"social",tag:"Welfare",benefit:"₹51,000 marriage assist for SC/BC/EWS girls",desc:"Marriage assistance for daughters of SC, BC and economically weaker families. ₹51,000 per daughter (max 2).",elig:["SC/BC/EWS family in Punjab","Bride age 18+","Family income below ₹2L/year","Maximum 2 daughters"],docs:["Caste certificate","Income certificate","Aadhaar","Marriage proof","Bank passbook"],apply:["Apply at district SC/BC welfare office","Or through e-Sewa/Saanjh centre","Before or within 1 year of marriage"],link:"https://socialservices.punjab.gov.in/",helpline:"0172-2742000",amt:51000,match:p=>p.state==="Punjab"&&p.gender==="female"&&["sc","obc"].includes(p.category)},

{name:"Punjab Old Age Pension Scheme",cat:"social",tag:"Pension",benefit:"₹1,500/month pension for elderly",desc:"State pension for senior citizens in Punjab. ₹1,500/month. Additional top-up to central ₹200-500.",elig:["Punjab domicile","Age 58+ (for women: 58+, men: 65+)","Annual income below ₹60,000","BPL preferred"],docs:["Aadhaar","Age proof","Income certificate","Bank passbook"],apply:["Apply at district social security office","Online at connect.punjab.gov.in","Block/Tehsil level camps"],link:"https://connect.punjab.gov.in/",helpline:"0172-2742000",amt:18000,match:p=>p.state==="Punjab"&&p.age>=58&&["below1","1to2.5"].includes(p.income)},

// ═══ JHARKHAND (60-63) ═══
{name:"Jharkhand Mukhyamantri Sukanya Yojana",cat:"women",tag:"Children",benefit:"₹40,000 from birth to age 18",desc:"Girl child scheme for Jharkhand. Financial assistance in installments at birth, 1yr, 2yr, and at age 18/20.",elig:["Girl child born in Jharkhand","SECC-2011 listed family","Maximum 2 girl children"],docs:["Birth certificate","SECC inclusion proof","Aadhaar","Bank passbook"],apply:["Register at Anganwadi within 1 year of birth","District WCD office","DBT at each milestone"],link:"https://wcd.jharkhand.gov.in/",helpline:"181",amt:40000,match:p=>p.state==="Jharkhand"&&p.gender==="female"&&p.lifeStage.includes("children")},

{name:"Jharkhand Mukhyamantri Maiya Samman Yojana",cat:"women",tag:"Women",benefit:"₹1,000/month for women aged 21-50",desc:"Monthly financial assistance for women in Jharkhand. Launched 2024. Covers non-earning women from BPL families.",elig:["Women aged 21-50 in Jharkhand","Not income tax payer","Not government employee","Family ration card holder"],docs:["Aadhaar","Ration card","Age proof","Bank passbook"],apply:["Apply at district WCD office","Through block office","maiyasamman.jharkhand.gov.in"],link:"https://maiyasamman.jharkhand.gov.in/",helpline:"181",amt:12000,match:p=>p.state==="Jharkhand"&&p.gender==="female"&&p.age>=21&&p.age<=50},

// ═══ CHHATTISGARH (62-65) ═══
{name:"Chhattisgarh Mahtari Vandana Yojana",cat:"women",tag:"Women",benefit:"₹1,000/month for married women",desc:"Monthly financial assistance for married women in Chhattisgarh. 70+ lakh beneficiaries. DBT to bank account.",elig:["Married women in Chhattisgarh","Age 21-60","Not income tax payer","Not government employee"],docs:["Aadhaar","Marriage certificate","Bank passbook","Domicile proof"],apply:["Apply at mahtarivandan.cgstate.gov.in","Through Gram Panchayat","DBT monthly"],link:"https://mahtarivandan.cgstate.gov.in/",helpline:"14411",amt:12000,match:p=>p.state==="Chhattisgarh"&&p.gender==="female"},

{name:"Chhattisgarh Rajiv Gandhi Kisan Nyay Yojana",cat:"agriculture",tag:"Agriculture",benefit:"₹9,000/acre for paddy + ₹10,000/acre other crops",desc:"Input subsidy for farmers. Highest per-acre support in India. Covers paddy, sugarcane, maize, soybean & other Kharif crops.",elig:["Registered farmer in Chhattisgarh","All landholding categories","Must grow notified crops","Registered on Kisan Nyay portal"],docs:["Land records","Aadhaar","Bank passbook","Crop sowing declaration"],apply:["Register at nearest cooperative society","Or through Patwari","rajivgandhi-kisannyay-yojna.cg.nic.in"],link:"https://rajivgandhi-kisannyay-yojna.cg.nic.in/",helpline:"14411",amt:10000,match:p=>p.state==="Chhattisgarh"&&p.employment==="farmer"},

// ═══ ASSAM (64-66) ═══
{name:"Assam Orunodoi Scheme",cat:"women",tag:"Women",benefit:"₹1,250/month for women-headed families",desc:"Monthly financial assistance for economically weaker families through nominated woman member. 27 lakh beneficiaries.",elig:["Woman member of household in Assam","Family income below ₹2L/year","Not income tax payer","Must have Aadhaar-linked bank account"],docs:["Aadhaar","BPL certificate","Bank passbook","Family details"],apply:["Apply through Assam Direct Benefit Transfer portal","Or through Circle/Block office"],link:"https://finance.assam.gov.in/",helpline:"1800-345-3611",amt:15000,match:p=>p.state==="Assam"&&p.gender==="female"&&["below1","1to2.5"].includes(p.income)},

{name:"Assam Pragyan Bharati Scheme",cat:"education",tag:"Education",benefit:"₹10,000-₹50,000 for admission in higher education",desc:"Financial assistance for students from Assam pursuing higher education. Covers degree, engineering, medical courses.",elig:["Student from Assam","Pursuing higher education in recognized institution","Family income below ₹2L/year","Minimum 60% in qualifying exam"],docs:["Previous marksheet","Admission letter","Income certificate","Aadhaar","Bank passbook"],apply:["Apply through Assam Higher Education portal","Or through college admission office"],link:"https://dhe.assam.gov.in/",helpline:"0361-2237055",amt:50000,match:p=>p.state==="Assam"&&p.employment==="student"},

// ═══ HIMACHAL PRADESH & UTTARAKHAND (66-68) ═══
{name:"Himachal Pradesh Indira Gandhi Mahila Samman Nidhi",cat:"women",tag:"Women",benefit:"₹1,500/month for women aged 18-65",desc:"Monthly financial support for women in HP. All women aged 18-65 eligible regardless of income (some exclusions).",elig:["Women aged 18-65 in HP","HP domicile","Not government employee","Not income tax payer","Not receiving ≥₹10K pension"],docs:["Aadhaar","HP domicile certificate","Age proof","Bank passbook"],apply:["Apply at Lok Mitra Kendra","Or district welfare office","DBT monthly"],link:"https://edistrict.hp.gov.in/",helpline:"0177-2621640",amt:18000,match:p=>p.state==="Himachal Pradesh"&&p.gender==="female"&&p.age>=18&&p.age<=65},

{name:"Uttarakhand Vatsalya Yojana (Orphan Support)",cat:"social",tag:"Children",benefit:"₹3,000/month + free education for COVID orphans",desc:"Support for children orphaned during COVID. Monthly assistance, free education, health insurance coverage.",elig:["Children orphaned due to COVID in Uttarakhand","Lost one or both parents","Age below 21"],docs:["Death certificate of parent","Child's Aadhaar","Bank passbook","School enrollment"],apply:["Apply at wcd.uk.gov.in","District WCD office","Block level officers"],link:"https://wcd.uk.gov.in/",helpline:"181",amt:36000,match:p=>p.state==="Uttarakhand"&&p.lifeStage.includes("children")},

// ═══ GOA & NORTHEASTERN STATES (68-72) ═══
{name:"Goa Griha Aadhaar Scheme",cat:"women",tag:"Women",benefit:"₹1,500/month for women heads of household",desc:"Monthly financial assistance for women-headed families in Goa. Covers about 1.3 lakh beneficiaries.",elig:["Woman-headed family in Goa","Goa resident for 15+ years","Not income tax payer","Annual income below ₹3L"],docs:["Aadhaar","Residential proof (15 yrs)","Income certificate","Bank passbook"],apply:["Apply at provedoria.goa.gov.in","Or through Mamlatdar office"],link:"https://provedoria.goa.gov.in/",helpline:"0832-2226025",amt:18000,match:p=>p.state==="Goa"&&p.gender==="female"},

{name:"Tripura TBSE Merit Scholarship",cat:"education",tag:"Scholarship",benefit:"₹10,000-₹20,000/year for meritorious students",desc:"Scholarship for class 10 and 12 top performers. Covers all categories with enhanced rates for ST/SC students.",elig:["Tripura Board student","Top performers in class 10/12","Pursuing higher education in recognized institution"],docs:["Marksheet","Aadhaar","Admission letter","Bank passbook","Caste certificate (if applicable)"],apply:["Apply through school/college","Education department processes"],link:"https://education.tripura.gov.in/",helpline:"0381-2325725",amt:20000,match:p=>p.state==="Tripura"&&p.employment==="student"},

{name:"Meghalaya FOCUS Scheme (SC/ST Scholarship)",cat:"education",tag:"Scholarship",benefit:"₹10,000-₹30,000/year scholarship for ST students",desc:"Financial support for ST students in Meghalaya pursuing professional courses. Covers tuition and maintenance.",elig:["ST student from Meghalaya","Pursuing professional/technical course","Family income below ₹2.5L/year"],docs:["ST certificate","Income certificate","Admission letter","Previous marksheet","Bank passbook"],apply:["Apply through college","Or district welfare officer","Online scholarship portal"],link:"https://meghalaya.gov.in/",helpline:"0364-2500150",amt:30000,match:p=>p.state==="Meghalaya"&&p.category==="st"&&p.employment==="student"}
];
