// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xprafkvyhdztdxprbqfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwcmFma3Z5aGR6dGR4cHJicWZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4MjQwMTAsImV4cCI6MjA4NzQwMDAxMH0.SfZlsqmQr9vCFQhCnma5hKSRqUzLo_dQ9t3FLpa0QGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});