export interface GSTStateEntry { sNo: number; stateCode: string; stateName: string; tin: string; gstinPrefix: string; zone: string; }

export const gstStateCodesData: GSTStateEntry[] = [
    { sNo: 1, stateCode: '01', stateName: 'Jammu & Kashmir', tin: '01', gstinPrefix: '01', zone: 'Northern' },
    { sNo: 2, stateCode: '02', stateName: 'Himachal Pradesh', tin: '02', gstinPrefix: '02', zone: 'Northern' },
    { sNo: 3, stateCode: '03', stateName: 'Punjab', tin: '03', gstinPrefix: '03', zone: 'Northern' },
    { sNo: 4, stateCode: '04', stateName: 'Chandigarh', tin: '04', gstinPrefix: '04', zone: 'Northern' },
    { sNo: 5, stateCode: '05', stateName: 'Uttarakhand', tin: '05', gstinPrefix: '05', zone: 'Northern' },
    { sNo: 6, stateCode: '06', stateName: 'Haryana', tin: '06', gstinPrefix: '06', zone: 'Northern' },
    { sNo: 7, stateCode: '07', stateName: 'Delhi', tin: '07', gstinPrefix: '07', zone: 'Northern' },
    { sNo: 8, stateCode: '08', stateName: 'Rajasthan', tin: '08', gstinPrefix: '08', zone: 'Northern' },
    { sNo: 9, stateCode: '09', stateName: 'Uttar Pradesh', tin: '09', gstinPrefix: '09', zone: 'Northern' },
    { sNo: 10, stateCode: '10', stateName: 'Bihar', tin: '10', gstinPrefix: '10', zone: 'Eastern' },
    { sNo: 11, stateCode: '11', stateName: 'Sikkim', tin: '11', gstinPrefix: '11', zone: 'Eastern' },
    { sNo: 12, stateCode: '12', stateName: 'Arunachal Pradesh', tin: '12', gstinPrefix: '12', zone: 'Eastern' },
    { sNo: 13, stateCode: '13', stateName: 'Nagaland', tin: '13', gstinPrefix: '13', zone: 'Eastern' },
    { sNo: 14, stateCode: '14', stateName: 'Manipur', tin: '14', gstinPrefix: '14', zone: 'Eastern' },
    { sNo: 15, stateCode: '15', stateName: 'Mizoram', tin: '15', gstinPrefix: '15', zone: 'Eastern' },
    { sNo: 16, stateCode: '16', stateName: 'Tripura', tin: '16', gstinPrefix: '16', zone: 'Eastern' },
    { sNo: 17, stateCode: '17', stateName: 'Meghalaya', tin: '17', gstinPrefix: '17', zone: 'Eastern' },
    { sNo: 18, stateCode: '18', stateName: 'Assam', tin: '18', gstinPrefix: '18', zone: 'Eastern' },
    { sNo: 19, stateCode: '19', stateName: 'West Bengal', tin: '19', gstinPrefix: '19', zone: 'Eastern' },
    { sNo: 20, stateCode: '20', stateName: 'Jharkhand', tin: '20', gstinPrefix: '20', zone: 'Eastern' },
    { sNo: 21, stateCode: '21', stateName: 'Odisha', tin: '21', gstinPrefix: '21', zone: 'Eastern' },
    { sNo: 22, stateCode: '22', stateName: 'Chhattisgarh', tin: '22', gstinPrefix: '22', zone: 'Central' },
    { sNo: 23, stateCode: '23', stateName: 'Madhya Pradesh', tin: '23', gstinPrefix: '23', zone: 'Central' },
    { sNo: 24, stateCode: '24', stateName: 'Gujarat', tin: '24', gstinPrefix: '24', zone: 'Western' },
    { sNo: 25, stateCode: '25', stateName: 'Dadra & Nagar Haveli and Daman & Diu', tin: '25', gstinPrefix: '25', zone: 'Western' },
    { sNo: 26, stateCode: '26', stateName: 'Dadra & Nagar Haveli and Daman & Diu', tin: '26', gstinPrefix: '26', zone: 'Western' },
    { sNo: 27, stateCode: '27', stateName: 'Maharashtra', tin: '27', gstinPrefix: '27', zone: 'Western' },
    { sNo: 28, stateCode: '29', stateName: 'Karnataka', tin: '29', gstinPrefix: '29', zone: 'Southern' },
    { sNo: 29, stateCode: '30', stateName: 'Goa', tin: '30', gstinPrefix: '30', zone: 'Western' },
    { sNo: 30, stateCode: '31', stateName: 'Lakshadweep', tin: '31', gstinPrefix: '31', zone: 'Southern' },
    { sNo: 31, stateCode: '32', stateName: 'Kerala', tin: '32', gstinPrefix: '32', zone: 'Southern' },
    { sNo: 32, stateCode: '33', stateName: 'Tamil Nadu', tin: '33', gstinPrefix: '33', zone: 'Southern' },
    { sNo: 33, stateCode: '34', stateName: 'Puducherry', tin: '34', gstinPrefix: '34', zone: 'Southern' },
    { sNo: 34, stateCode: '35', stateName: 'Andaman & Nicobar Islands', tin: '35', gstinPrefix: '35', zone: 'Eastern' },
    { sNo: 35, stateCode: '36', stateName: 'Telangana', tin: '36', gstinPrefix: '36', zone: 'Southern' },
    { sNo: 36, stateCode: '37', stateName: 'Andhra Pradesh', tin: '37', gstinPrefix: '37', zone: 'Southern' },
    { sNo: 37, stateCode: '38', stateName: 'Ladakh', tin: '38', gstinPrefix: '38', zone: 'Northern' },
    { sNo: 38, stateCode: '97', stateName: 'Other Territory (Sea/Air)', tin: '97', gstinPrefix: '97', zone: 'Central' },
    { sNo: 39, stateCode: '99', stateName: 'Centre Jurisdiction (IGST)', tin: '99', gstinPrefix: '99', zone: 'Central' },
];
