export interface ParliamentEntry { sNo: number; constituency: string; state: string; house: 'Lok Sabha' | 'Rajya Sabha'; type: string; reservedFor: string; }

export const indianParliamentData: ParliamentEntry[] = [
    // Lok Sabha — Major State constituencies (sample coverage)
    { sNo: 1, constituency: 'New Delhi', state: 'Delhi', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 2, constituency: 'Chandni Chowk', state: 'Delhi', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 3, constituency: 'East Delhi', state: 'Delhi', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 4, constituency: 'North East Delhi', state: 'Delhi', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 5, constituency: 'North West Delhi', state: 'Delhi', house: 'Lok Sabha', type: 'General', reservedFor: 'SC' },
    { sNo: 6, constituency: 'South Delhi', state: 'Delhi', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 7, constituency: 'West Delhi', state: 'Delhi', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 8, constituency: 'Mumbai North', state: 'Maharashtra', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 9, constituency: 'Mumbai North Central', state: 'Maharashtra', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 10, constituency: 'Mumbai North East', state: 'Maharashtra', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 11, constituency: 'Mumbai North West', state: 'Maharashtra', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 12, constituency: 'Mumbai South', state: 'Maharashtra', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 13, constituency: 'Mumbai South Central', state: 'Maharashtra', house: 'Lok Sabha', type: 'General', reservedFor: 'SC' },
    { sNo: 14, constituency: 'Pune', state: 'Maharashtra', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 15, constituency: 'Baramati', state: 'Maharashtra', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 16, constituency: 'Nagpur', state: 'Maharashtra', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 17, constituency: 'Nashik', state: 'Maharashtra', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 18, constituency: 'Aurangabad', state: 'Maharashtra', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 19, constituency: 'Kolhapur', state: 'Maharashtra', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 20, constituency: 'Solapur', state: 'Maharashtra', house: 'Lok Sabha', type: 'General', reservedFor: 'SC' },
    { sNo: 21, constituency: 'Bangalore South', state: 'Karnataka', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 22, constituency: 'Bangalore North', state: 'Karnataka', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 23, constituency: 'Bangalore Central', state: 'Karnataka', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 24, constituency: 'Bangalore Rural', state: 'Karnataka', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 25, constituency: 'Mysore', state: 'Karnataka', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 26, constituency: 'Dharwad', state: 'Karnataka', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 27, constituency: 'Mangalore', state: 'Karnataka', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 28, constituency: 'Shimoga', state: 'Karnataka', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 29, constituency: 'Chennai South', state: 'Tamil Nadu', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 30, constituency: 'Chennai North', state: 'Tamil Nadu', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 31, constituency: 'Chennai Central', state: 'Tamil Nadu', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 32, constituency: 'Kancheepuram', state: 'Tamil Nadu', house: 'Lok Sabha', type: 'General', reservedFor: 'SC' },
    { sNo: 33, constituency: 'Coimbatore', state: 'Tamil Nadu', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 34, constituency: 'Madurai', state: 'Tamil Nadu', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 35, constituency: 'Tiruchirappalli', state: 'Tamil Nadu', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 36, constituency: 'Hyderabad', state: 'Telangana', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 37, constituency: 'Secunderabad', state: 'Telangana', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 38, constituency: 'Malkajgiri', state: 'Telangana', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 39, constituency: 'Medak', state: 'Telangana', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 40, constituency: 'Warangal', state: 'Telangana', house: 'Lok Sabha', type: 'General', reservedFor: 'SC' },
    { sNo: 41, constituency: 'Ahmedabad East', state: 'Gujarat', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 42, constituency: 'Ahmedabad West', state: 'Gujarat', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 43, constituency: 'Gandhinagar', state: 'Gujarat', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 44, constituency: 'Surat', state: 'Gujarat', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 45, constituency: 'Vadodara', state: 'Gujarat', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 46, constituency: 'Rajkot', state: 'Gujarat', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 47, constituency: 'Varanasi', state: 'Uttar Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 48, constituency: 'Lucknow', state: 'Uttar Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 49, constituency: 'Kanpur', state: 'Uttar Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 50, constituency: 'Allahabad', state: 'Uttar Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 51, constituency: 'Agra', state: 'Uttar Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'SC' },
    { sNo: 52, constituency: 'Meerut', state: 'Uttar Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 53, constituency: 'Ghaziabad', state: 'Uttar Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 54, constituency: 'Noida (Gautam Buddh Nagar)', state: 'Uttar Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 55, constituency: 'Gorakhpur', state: 'Uttar Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 56, constituency: 'Amethi', state: 'Uttar Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 57, constituency: 'Rae Bareli', state: 'Uttar Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 58, constituency: 'Kolkata North', state: 'West Bengal', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 59, constituency: 'Kolkata South', state: 'West Bengal', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 60, constituency: 'Kolkata North West', state: 'West Bengal', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 61, constituency: 'Dum Dum', state: 'West Bengal', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 62, constituency: 'Howrah', state: 'West Bengal', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 63, constituency: 'Medinipur', state: 'West Bengal', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 64, constituency: 'Patna Sahib', state: 'Bihar', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 65, constituency: 'Pataliputra', state: 'Bihar', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 66, constituency: 'Muzaffarpur', state: 'Bihar', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 67, constituency: 'Gaya', state: 'Bihar', house: 'Lok Sabha', type: 'General', reservedFor: 'SC' },
    { sNo: 68, constituency: 'Jaipur', state: 'Rajasthan', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 69, constituency: 'Jaipur Rural', state: 'Rajasthan', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 70, constituency: 'Jodhpur', state: 'Rajasthan', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 71, constituency: 'Udaipur', state: 'Rajasthan', house: 'Lok Sabha', type: 'General', reservedFor: 'ST' },
    { sNo: 72, constituency: 'Kota', state: 'Rajasthan', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 73, constituency: 'Gurgaon', state: 'Haryana', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 74, constituency: 'Faridabad', state: 'Haryana', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 75, constituency: 'Ambala', state: 'Haryana', house: 'Lok Sabha', type: 'General', reservedFor: 'SC' },
    { sNo: 76, constituency: 'Chandigarh', state: 'Chandigarh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 77, constituency: 'Amritsar', state: 'Punjab', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 78, constituency: 'Ludhiana', state: 'Punjab', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 79, constituency: 'Jalandhar', state: 'Punjab', house: 'Lok Sabha', type: 'General', reservedFor: 'SC' },
    { sNo: 80, constituency: 'Anandpur Sahib', state: 'Punjab', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 81, constituency: 'Shimla', state: 'Himachal Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'SC' },
    { sNo: 82, constituency: 'Dehradun', state: 'Uttarakhand', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 83, constituency: 'Haridwar', state: 'Uttarakhand', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 84, constituency: 'Panaji', state: 'Goa', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 85, constituency: 'South Goa', state: 'Goa', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 86, constituency: 'Bhubaneswar', state: 'Odisha', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 87, constituency: 'Cuttack', state: 'Odisha', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 88, constituency: 'Raipur', state: 'Chhattisgarh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 89, constituency: 'Bilaspur', state: 'Chhattisgarh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 90, constituency: 'Ranchi', state: 'Jharkhand', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 91, constituency: 'Jamshedpur', state: 'Jharkhand', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 92, constituency: 'Guwahati', state: 'Assam', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 93, constituency: 'Silchar', state: 'Assam', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 94, constituency: 'Imphal', state: 'Manipur', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 95, constituency: 'Shillong', state: 'Meghalaya', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 96, constituency: 'Aizawl', state: 'Mizoram', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 97, constituency: 'Nagaland', state: 'Nagaland', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 98, constituency: 'Agartala', state: 'Tripura', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 99, constituency: 'Sikkim', state: 'Sikkim', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 100, constituency: 'Arunachal West', state: 'Arunachal Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    // Rajya Sabha sample
    { sNo: 101, constituency: 'Maharashtra (RS)', state: 'Maharashtra', house: 'Rajya Sabha', type: 'Elected', reservedFor: 'None' },
    { sNo: 102, constituency: 'Uttar Pradesh (RS)', state: 'Uttar Pradesh', house: 'Rajya Sabha', type: 'Elected', reservedFor: 'None' },
    { sNo: 103, constituency: 'Tamil Nadu (RS)', state: 'Tamil Nadu', house: 'Rajya Sabha', type: 'Elected', reservedFor: 'None' },
    { sNo: 104, constituency: 'West Bengal (RS)', state: 'West Bengal', house: 'Rajya Sabha', type: 'Elected', reservedFor: 'None' },
    { sNo: 105, constituency: 'Karnataka (RS)', state: 'Karnataka', house: 'Rajya Sabha', type: 'Elected', reservedFor: 'None' },
    { sNo: 106, constituency: 'Gujarat (RS)', state: 'Gujarat', house: 'Rajya Sabha', type: 'Elected', reservedFor: 'None' },
    { sNo: 107, constituency: 'Rajasthan (RS)', state: 'Rajasthan', house: 'Rajya Sabha', type: 'Elected', reservedFor: 'None' },
    { sNo: 108, constituency: 'Bihar (RS)', state: 'Bihar', house: 'Rajya Sabha', type: 'Elected', reservedFor: 'None' },
    { sNo: 109, constituency: 'Telangana (RS)', state: 'Telangana', house: 'Rajya Sabha', type: 'Elected', reservedFor: 'None' },
    { sNo: 110, constituency: 'Delhi (RS)', state: 'Delhi', house: 'Rajya Sabha', type: 'Elected', reservedFor: 'None' },
    // More Lok Sabha — Uttar Pradesh
    { sNo: 111, constituency: 'Bareilly', state: 'Uttar Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 112, constituency: 'Moradabad', state: 'Uttar Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 113, constituency: 'Saharanpur', state: 'Uttar Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 114, constituency: 'Muzaffarnagar', state: 'Uttar Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 115, constituency: 'Aligarh', state: 'Uttar Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'SC' },
    { sNo: 116, constituency: 'Mathura', state: 'Uttar Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 117, constituency: 'Jhansi', state: 'Uttar Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 118, constituency: 'Sultanpur', state: 'Uttar Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 119, constituency: 'Faizabad (Ayodhya)', state: 'Uttar Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 120, constituency: 'Azamgarh', state: 'Uttar Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 121, constituency: 'Sambhal', state: 'Uttar Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 122, constituency: 'Budaun', state: 'Uttar Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 123, constituency: 'Rampur', state: 'Uttar Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    // More Bihar
    { sNo: 124, constituency: 'Darbhanga', state: 'Bihar', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 125, constituency: 'Madhubani', state: 'Bihar', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 126, constituency: 'Purnia', state: 'Bihar', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 127, constituency: 'Bhagalpur', state: 'Bihar', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 128, constituency: 'Araria', state: 'Bihar', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 129, constituency: 'Kishanganj', state: 'Bihar', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 130, constituency: 'Samastipur', state: 'Bihar', house: 'Lok Sabha', type: 'General', reservedFor: 'SC' },
    { sNo: 131, constituency: 'Begusarai', state: 'Bihar', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 132, constituency: 'Nalanda', state: 'Bihar', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    // More Tamil Nadu
    { sNo: 133, constituency: 'Sivaganga', state: 'Tamil Nadu', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 134, constituency: 'Virudhunagar', state: 'Tamil Nadu', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 135, constituency: 'Tenkasi', state: 'Tamil Nadu', house: 'Lok Sabha', type: 'General', reservedFor: 'SC' },
    { sNo: 136, constituency: 'Thanjavur', state: 'Tamil Nadu', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 137, constituency: 'Salem', state: 'Tamil Nadu', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 138, constituency: 'Erode', state: 'Tamil Nadu', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 139, constituency: 'Tiruppur', state: 'Tamil Nadu', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 140, constituency: 'Dindigul', state: 'Tamil Nadu', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    // More Maharashtra
    { sNo: 141, constituency: 'Thane', state: 'Maharashtra', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 142, constituency: 'Kalyan', state: 'Maharashtra', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 143, constituency: 'Bhiwandi', state: 'Maharashtra', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 144, constituency: 'Satara', state: 'Maharashtra', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 145, constituency: 'Sangli', state: 'Maharashtra', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 146, constituency: 'Ahmednagar', state: 'Maharashtra', house: 'Lok Sabha', type: 'General', reservedFor: 'SC' },
    { sNo: 147, constituency: 'Latur', state: 'Maharashtra', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 148, constituency: 'Nanded', state: 'Maharashtra', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 149, constituency: 'Parbhani', state: 'Maharashtra', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    // West Bengal additional
    { sNo: 150, constituency: 'Barasat', state: 'West Bengal', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 151, constituency: 'Basirhat', state: 'West Bengal', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 152, constituency: 'Diamond Harbour', state: 'West Bengal', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 153, constituency: 'Joynagar', state: 'West Bengal', house: 'Lok Sabha', type: 'General', reservedFor: 'SC' },
    { sNo: 154, constituency: 'Jadavpur', state: 'West Bengal', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 155, constituency: 'Krishnanagar', state: 'West Bengal', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 156, constituency: 'Bardhaman-Durgapur', state: 'West Bengal', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 157, constituency: 'Asansol', state: 'West Bengal', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    // Kerala
    { sNo: 158, constituency: 'Thiruvananthapuram', state: 'Kerala', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 159, constituency: 'Ernakulam', state: 'Kerala', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 160, constituency: 'Kozhikode', state: 'Kerala', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 161, constituency: 'Thrissur', state: 'Kerala', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 162, constituency: 'Kannur', state: 'Kerala', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 163, constituency: 'Alappuzha', state: 'Kerala', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 164, constituency: 'Pathanamthitta', state: 'Kerala', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 165, constituency: 'Idukki', state: 'Kerala', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 166, constituency: 'Palakkad', state: 'Kerala', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 167, constituency: 'Malappuram', state: 'Kerala', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    // Madhya Pradesh
    { sNo: 168, constituency: 'Bhopal', state: 'Madhya Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 169, constituency: 'Indore', state: 'Madhya Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 170, constituency: 'Gwalior', state: 'Madhya Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 171, constituency: 'Jabalpur', state: 'Madhya Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 172, constituency: 'Ujjain', state: 'Madhya Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 173, constituency: 'Sagar', state: 'Madhya Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 174, constituency: 'Rewa', state: 'Madhya Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 175, constituency: 'Chhindwara', state: 'Madhya Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    // Odisha
    { sNo: 176, constituency: 'Puri', state: 'Odisha', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 177, constituency: 'Sambalpur', state: 'Odisha', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 178, constituency: 'Berhampur', state: 'Odisha', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 179, constituency: 'Kendrapara', state: 'Odisha', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    // Andhra Pradesh
    { sNo: 180, constituency: 'Vijayawada', state: 'Andhra Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 181, constituency: 'Visakhapatnam', state: 'Andhra Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 182, constituency: 'Tirupati', state: 'Andhra Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'SC' },
    { sNo: 183, constituency: 'Guntur', state: 'Andhra Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 184, constituency: 'Nellore', state: 'Andhra Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    { sNo: 185, constituency: 'Anantapur', state: 'Andhra Pradesh', house: 'Lok Sabha', type: 'General', reservedFor: 'None' },
    // More Rajya Sabha
    { sNo: 186, constituency: 'Andhra Pradesh (RS)', state: 'Andhra Pradesh', house: 'Rajya Sabha', type: 'Elected', reservedFor: 'None' },
    { sNo: 187, constituency: 'Odisha (RS)', state: 'Odisha', house: 'Rajya Sabha', type: 'Elected', reservedFor: 'None' },
    { sNo: 188, constituency: 'Kerala (RS)', state: 'Kerala', house: 'Rajya Sabha', type: 'Elected', reservedFor: 'None' },
    { sNo: 189, constituency: 'Madhya Pradesh (RS)', state: 'Madhya Pradesh', house: 'Rajya Sabha', type: 'Elected', reservedFor: 'None' },
    { sNo: 190, constituency: 'Punjab (RS)', state: 'Punjab', house: 'Rajya Sabha', type: 'Elected', reservedFor: 'None' },
    { sNo: 191, constituency: 'Haryana (RS)', state: 'Haryana', house: 'Rajya Sabha', type: 'Elected', reservedFor: 'None' },
    { sNo: 192, constituency: 'Jharkhand (RS)', state: 'Jharkhand', house: 'Rajya Sabha', type: 'Elected', reservedFor: 'None' },
    { sNo: 193, constituency: 'Chhattisgarh (RS)', state: 'Chhattisgarh', house: 'Rajya Sabha', type: 'Elected', reservedFor: 'None' },
    { sNo: 194, constituency: 'Assam (RS)', state: 'Assam', house: 'Rajya Sabha', type: 'Elected', reservedFor: 'None' },
    { sNo: 195, constituency: 'Uttarakhand (RS)', state: 'Uttarakhand', house: 'Rajya Sabha', type: 'Elected', reservedFor: 'None' },
    { sNo: 196, constituency: 'Himachal Pradesh (RS)', state: 'Himachal Pradesh', house: 'Rajya Sabha', type: 'Elected', reservedFor: 'None' },
    { sNo: 197, constituency: 'Goa (RS)', state: 'Goa', house: 'Rajya Sabha', type: 'Elected', reservedFor: 'None' },
    // Nominated Members
    { sNo: 198, constituency: 'Nominated (RS-1)', state: 'India', house: 'Rajya Sabha', type: 'Nominated', reservedFor: 'None' },
    { sNo: 199, constituency: 'Nominated (RS-2)', state: 'India', house: 'Rajya Sabha', type: 'Nominated', reservedFor: 'None' },
    { sNo: 200, constituency: 'Nominated (RS-3)', state: 'India', house: 'Rajya Sabha', type: 'Nominated', reservedFor: 'None' },
];
