export interface BankEntry { sNo: number; bankName: string; ifscPrefix: string; type: string; headquarters: string; established: string; branches: string; }

export const indianBanksData: BankEntry[] = [
    // Public Sector Banks
    { sNo: 1, bankName: 'State Bank of India (SBI)', ifscPrefix: 'SBIN', type: 'Public Sector', headquarters: 'Mumbai', established: '1955', branches: '22,000+' },
    { sNo: 2, bankName: 'Punjab National Bank (PNB)', ifscPrefix: 'PUNB', type: 'Public Sector', headquarters: 'New Delhi', established: '1894', branches: '10,000+' },
    { sNo: 3, bankName: 'Bank of Baroda (BOB)', ifscPrefix: 'BARB', type: 'Public Sector', headquarters: 'Vadodara', established: '1908', branches: '8,200+' },
    { sNo: 4, bankName: 'Canara Bank', ifscPrefix: 'CNRB', type: 'Public Sector', headquarters: 'Bengaluru', established: '1906', branches: '9,600+' },
    { sNo: 5, bankName: 'Union Bank of India', ifscPrefix: 'UBIN', type: 'Public Sector', headquarters: 'Mumbai', established: '1919', branches: '8,700+' },
    { sNo: 6, bankName: 'Bank of India (BOI)', ifscPrefix: 'BKID', type: 'Public Sector', headquarters: 'Mumbai', established: '1906', branches: '5,100+' },
    { sNo: 7, bankName: 'Indian Bank', ifscPrefix: 'IDIB', type: 'Public Sector', headquarters: 'Chennai', established: '1907', branches: '6,000+' },
    { sNo: 8, bankName: 'Central Bank of India', ifscPrefix: 'CBIN', type: 'Public Sector', headquarters: 'Mumbai', established: '1911', branches: '4,600+' },
    { sNo: 9, bankName: 'Indian Overseas Bank (IOB)', ifscPrefix: 'IOBA', type: 'Public Sector', headquarters: 'Chennai', established: '1937', branches: '3,400+' },
    { sNo: 10, bankName: 'UCO Bank', ifscPrefix: 'UCBA', type: 'Public Sector', headquarters: 'Kolkata', established: '1943', branches: '3,200+' },
    { sNo: 11, bankName: 'Bank of Maharashtra', ifscPrefix: 'MAHB', type: 'Public Sector', headquarters: 'Pune', established: '1935', branches: '2,000+' },
    { sNo: 12, bankName: 'Punjab & Sind Bank', ifscPrefix: 'PSIB', type: 'Public Sector', headquarters: 'New Delhi', established: '1908', branches: '1,500+' },
    // Private Sector Banks
    { sNo: 13, bankName: 'HDFC Bank', ifscPrefix: 'HDFC', type: 'Private Sector', headquarters: 'Mumbai', established: '1994', branches: '8,000+' },
    { sNo: 14, bankName: 'ICICI Bank', ifscPrefix: 'ICIC', type: 'Private Sector', headquarters: 'Mumbai', established: '1994', branches: '5,900+' },
    { sNo: 15, bankName: 'Axis Bank', ifscPrefix: 'UTIB', type: 'Private Sector', headquarters: 'Mumbai', established: '1993', branches: '5,000+' },
    { sNo: 16, bankName: 'Kotak Mahindra Bank', ifscPrefix: 'KKBK', type: 'Private Sector', headquarters: 'Mumbai', established: '2003', branches: '1,800+' },
    { sNo: 17, bankName: 'IndusInd Bank', ifscPrefix: 'INDB', type: 'Private Sector', headquarters: 'Mumbai', established: '1994', branches: '2,800+' },
    { sNo: 18, bankName: 'Yes Bank', ifscPrefix: 'YESB', type: 'Private Sector', headquarters: 'Mumbai', established: '2004', branches: '1,100+' },
    { sNo: 19, bankName: 'IDBI Bank', ifscPrefix: 'IBKL', type: 'Private Sector', headquarters: 'Mumbai', established: '1964', branches: '1,900+' },
    { sNo: 20, bankName: 'Federal Bank', ifscPrefix: 'FDRL', type: 'Private Sector', headquarters: 'Kochi', established: '1931', branches: '1,300+' },
    { sNo: 21, bankName: 'South Indian Bank', ifscPrefix: 'SIBL', type: 'Private Sector', headquarters: 'Thrissur', established: '1929', branches: '940+' },
    { sNo: 22, bankName: 'RBL Bank', ifscPrefix: 'RATN', type: 'Private Sector', headquarters: 'Mumbai', established: '1943', branches: '500+' },
    { sNo: 23, bankName: 'Bandhan Bank', ifscPrefix: 'BDBL', type: 'Private Sector', headquarters: 'Kolkata', established: '2015', branches: '5,600+' },
    { sNo: 24, bankName: 'IDFC First Bank', ifscPrefix: 'IDFB', type: 'Private Sector', headquarters: 'Mumbai', established: '2015', branches: '800+' },
    { sNo: 25, bankName: 'Karur Vysya Bank', ifscPrefix: 'KVBL', type: 'Private Sector', headquarters: 'Karur', established: '1916', branches: '800+' },
    { sNo: 26, bankName: 'City Union Bank', ifscPrefix: 'CIUB', type: 'Private Sector', headquarters: 'Kumbakonam', established: '1904', branches: '700+' },
    { sNo: 27, bankName: 'CSB Bank', ifscPrefix: 'CSBK', type: 'Private Sector', headquarters: 'Thrissur', established: '1920', branches: '400+' },
    { sNo: 28, bankName: 'DCB Bank', ifscPrefix: 'DCBL', type: 'Private Sector', headquarters: 'Mumbai', established: '1930', branches: '400+' },
    { sNo: 29, bankName: 'Dhanlaxmi Bank', ifscPrefix: 'DLXB', type: 'Private Sector', headquarters: 'Thrissur', established: '1927', branches: '270+' },
    { sNo: 30, bankName: 'Jammu & Kashmir Bank', ifscPrefix: 'JAKA', type: 'Private Sector', headquarters: 'Srinagar', established: '1938', branches: '950+' },
    // Small Finance Banks
    { sNo: 31, bankName: 'AU Small Finance Bank', ifscPrefix: 'AUBL', type: 'Small Finance', headquarters: 'Jaipur', established: '2017', branches: '1,000+' },
    { sNo: 32, bankName: 'Equitas Small Finance Bank', ifscPrefix: 'ESFB', type: 'Small Finance', headquarters: 'Chennai', established: '2016', branches: '900+' },
    { sNo: 33, bankName: 'Ujjivan Small Finance Bank', ifscPrefix: 'UJVN', type: 'Small Finance', headquarters: 'Bengaluru', established: '2017', branches: '600+' },
    { sNo: 34, bankName: 'Jana Small Finance Bank', ifscPrefix: 'JSFB', type: 'Small Finance', headquarters: 'Bengaluru', established: '2018', branches: '700+' },
    { sNo: 35, bankName: 'Fincare Small Finance Bank', ifscPrefix: 'FSFB', type: 'Small Finance', headquarters: 'Bengaluru', established: '2017', branches: '1,000+' },
    { sNo: 36, bankName: 'Suryoday Small Finance Bank', ifscPrefix: 'SURY', type: 'Small Finance', headquarters: 'Mumbai', established: '2017', branches: '570+' },
    // Payments Banks
    { sNo: 37, bankName: 'Airtel Payments Bank', ifscPrefix: 'AIRP', type: 'Payments Bank', headquarters: 'New Delhi', established: '2017', branches: 'Digital' },
    { sNo: 38, bankName: 'India Post Payments Bank', ifscPrefix: 'IPOS', type: 'Payments Bank', headquarters: 'New Delhi', established: '2018', branches: '1,55,000+' },
    { sNo: 39, bankName: 'Paytm Payments Bank', ifscPrefix: 'PYTM', type: 'Payments Bank', headquarters: 'Noida', established: '2017', branches: 'Digital' },
    { sNo: 40, bankName: 'Fino Payments Bank', ifscPrefix: 'FINO', type: 'Payments Bank', headquarters: 'Mumbai', established: '2017', branches: 'Digital' },
    // Regional Rural Banks (sample)
    { sNo: 41, bankName: 'Baroda UP Gramin Bank', ifscPrefix: 'BARB', type: 'Regional Rural', headquarters: 'Raebareli', established: '2019', branches: '1,500+' },
    { sNo: 42, bankName: 'Kerala Gramin Bank', ifscPrefix: 'KLGB', type: 'Regional Rural', headquarters: 'Malappuram', established: '2013', branches: '600+' },
    { sNo: 43, bankName: 'Andhra Pradesh Grameena Vikas Bank', ifscPrefix: 'APGV', type: 'Regional Rural', headquarters: 'Warangal', established: '2006', branches: '800+' },
    // Foreign Banks
    { sNo: 44, bankName: 'Citibank India', ifscPrefix: 'CITI', type: 'Foreign Bank', headquarters: 'Mumbai', established: '1902', branches: '35' },
    { sNo: 45, bankName: 'HSBC India', ifscPrefix: 'HSBC', type: 'Foreign Bank', headquarters: 'Mumbai', established: '1853', branches: '26' },
    { sNo: 46, bankName: 'Standard Chartered India', ifscPrefix: 'SCBL', type: 'Foreign Bank', headquarters: 'Mumbai', established: '1858', branches: '100' },
    { sNo: 47, bankName: 'Deutsche Bank India', ifscPrefix: 'DEUT', type: 'Foreign Bank', headquarters: 'Mumbai', established: '1980', branches: '18' },
    { sNo: 48, bankName: 'DBS Bank India', ifscPrefix: 'DBSS', type: 'Foreign Bank', headquarters: 'Mumbai', established: '1994', branches: '34' },
    // Co-op Banks
    { sNo: 49, bankName: 'Saraswat Co-operative Bank', ifscPrefix: 'SRCB', type: 'Co-operative', headquarters: 'Mumbai', established: '1918', branches: '280+' },
    { sNo: 50, bankName: 'Cosmos Co-operative Bank', ifscPrefix: 'COSB', type: 'Co-operative', headquarters: 'Pune', established: '1906', branches: '140+' },
    // More Small Finance Banks
    { sNo: 51, bankName: 'ESAF Small Finance Bank', ifscPrefix: 'ESAF', type: 'Small Finance', headquarters: 'Thrissur', established: '2017', branches: '700+' },
    { sNo: 52, bankName: 'Utkarsh Small Finance Bank', ifscPrefix: 'UTKS', type: 'Small Finance', headquarters: 'Varanasi', established: '2017', branches: '830+' },
    { sNo: 53, bankName: 'North East Small Finance Bank', ifscPrefix: 'NESF', type: 'Small Finance', headquarters: 'Guwahati', established: '2017', branches: '200+' },
    { sNo: 54, bankName: 'Capital Small Finance Bank', ifscPrefix: 'CLBL', type: 'Small Finance', headquarters: 'Jalandhar', established: '2016', branches: '170+' },
    { sNo: 55, bankName: 'Shivalik Small Finance Bank', ifscPrefix: 'SMCB', type: 'Small Finance', headquarters: 'Saharanpur', established: '2021', branches: '35+' },
    // More Regional Rural Banks
    { sNo: 56, bankName: 'Aryavart Bank', ifscPrefix: 'ARYA', type: 'Regional Rural', headquarters: 'Lucknow', established: '2019', branches: '400+' },
    { sNo: 57, bankName: 'Baroda Rajasthan Kshetriya Gramin Bank', ifscPrefix: 'BRGB', type: 'Regional Rural', headquarters: 'Ajmer', established: '2019', branches: '1,100+' },
    { sNo: 58, bankName: 'Punjab Gramin Bank', ifscPrefix: 'PUGB', type: 'Regional Rural', headquarters: 'Kapurthala', established: '2012', branches: '900+' },
    { sNo: 59, bankName: 'Sarva Haryana Gramin Bank', ifscPrefix: 'SHGB', type: 'Regional Rural', headquarters: 'Rohtak', established: '2014', branches: '680+' },
    { sNo: 60, bankName: 'Jharkhand Rajya Gramin Bank', ifscPrefix: 'JRGB', type: 'Regional Rural', headquarters: 'Ranchi', established: '2014', branches: '500+' },
    { sNo: 61, bankName: 'Chhattisgarh Rajya Gramin Bank', ifscPrefix: 'CRGB', type: 'Regional Rural', headquarters: 'Raipur', established: '2014', branches: '440+' },
    { sNo: 62, bankName: 'Tamil Nadu Grama Bank', ifscPrefix: 'TNGB', type: 'Regional Rural', headquarters: 'Salem', established: '2007', branches: '550+' },
    { sNo: 63, bankName: 'Karnataka Vikas Grameena Bank', ifscPrefix: 'KVGB', type: 'Regional Rural', headquarters: 'Dharwad', established: '2013', branches: '700+' },
    { sNo: 64, bankName: 'Madhya Pradesh Gramin Bank', ifscPrefix: 'MPGB', type: 'Regional Rural', headquarters: 'Indore', established: '2013', branches: '1,200+' },
    { sNo: 65, bankName: 'Odisha Gramya Bank', ifscPrefix: 'ODGB', type: 'Regional Rural', headquarters: 'Bhubaneswar', established: '2013', branches: '550+' },
    { sNo: 66, bankName: 'Prathama UP Gramin Bank', ifscPrefix: 'PUGB', type: 'Regional Rural', headquarters: 'Moradabad', established: '2019', branches: '900+' },
    { sNo: 67, bankName: 'Bangiya Gramin Vikash Bank', ifscPrefix: 'BGVB', type: 'Regional Rural', headquarters: 'Kolkata', established: '2014', branches: '800+' },
    { sNo: 68, bankName: 'Assam Gramin Vikash Bank', ifscPrefix: 'AGVB', type: 'Regional Rural', headquarters: 'Guwahati', established: '2007', branches: '350+' },
    { sNo: 69, bankName: 'Bihar Gramin Bank', ifscPrefix: 'BRGA', type: 'Regional Rural', headquarters: 'Begusarai', established: '2019', branches: '650+' },
    { sNo: 70, bankName: 'Dena Gujarat Gramin Bank', ifscPrefix: 'DGGB', type: 'Regional Rural', headquarters: 'Gandhinagar', established: '2019', branches: '350+' },
    // More Foreign Banks
    { sNo: 71, bankName: 'Barclays Bank India', ifscPrefix: 'BARC', type: 'Foreign Bank', headquarters: 'Mumbai', established: '1990', branches: '7' },
    { sNo: 72, bankName: 'Bank of America India', ifscPrefix: 'BOFA', type: 'Foreign Bank', headquarters: 'Mumbai', established: '1964', branches: '5' },
    { sNo: 73, bankName: 'JPMorgan Chase India', ifscPrefix: 'CHAS', type: 'Foreign Bank', headquarters: 'Mumbai', established: '1965', branches: '3' },
    { sNo: 74, bankName: 'BNP Paribas India', ifscPrefix: 'BNPA', type: 'Foreign Bank', headquarters: 'Mumbai', established: '1964', branches: '10' },
    { sNo: 75, bankName: 'Societe Generale India', ifscPrefix: 'SOGE', type: 'Foreign Bank', headquarters: 'Mumbai', established: '1985', branches: '4' },
    { sNo: 76, bankName: 'Mizuho Bank India', ifscPrefix: 'MHCB', type: 'Foreign Bank', headquarters: 'Mumbai', established: '2011', branches: '5' },
    { sNo: 77, bankName: 'MUFG Bank India', ifscPrefix: 'BOTM', type: 'Foreign Bank', headquarters: 'Mumbai', established: '1953', branches: '4' },
    { sNo: 78, bankName: 'Sumitomo Mitsui Bank India', ifscPrefix: 'SMBC', type: 'Foreign Bank', headquarters: 'Mumbai', established: '2003', branches: '3' },
    { sNo: 79, bankName: 'Credit Suisse India', ifscPrefix: 'CRES', type: 'Foreign Bank', headquarters: 'Mumbai', established: '1997', branches: '1' },
    { sNo: 80, bankName: 'Abu Dhabi Commercial Bank', ifscPrefix: 'ADCB', type: 'Foreign Bank', headquarters: 'Mumbai', established: '2000', branches: '2' },
    { sNo: 81, bankName: 'Emirates NBD India', ifscPrefix: 'EBIL', type: 'Foreign Bank', headquarters: 'Mumbai', established: '2017', branches: '3' },
    { sNo: 82, bankName: 'Doha Bank India', ifscPrefix: 'DOHB', type: 'Foreign Bank', headquarters: 'Mumbai', established: '2014', branches: '3' },
    { sNo: 83, bankName: 'SBM Bank India', ifscPrefix: 'STCB', type: 'Foreign Bank', headquarters: 'Mumbai', established: '2018', branches: '20' },
    { sNo: 84, bankName: 'First Abu Dhabi Bank India', ifscPrefix: 'NBAD', type: 'Foreign Bank', headquarters: 'Mumbai', established: '2009', branches: '3' },
    // More Co-operative Banks
    { sNo: 85, bankName: 'Shamrao Vithal Co-op Bank', ifscPrefix: 'SVCB', type: 'Co-operative', headquarters: 'Mumbai', established: '1906', branches: '200+' },
    { sNo: 86, bankName: 'Bassein Catholic Co-op Bank', ifscPrefix: 'BACB', type: 'Co-operative', headquarters: 'Vasai', established: '1966', branches: '70+' },
    { sNo: 87, bankName: 'Abhyudaya Co-op Bank', ifscPrefix: 'ABHY', type: 'Co-operative', headquarters: 'Mumbai', established: '1964', branches: '100+' },
    { sNo: 88, bankName: 'TJSB Sahakari Bank', ifscPrefix: 'TJSB', type: 'Co-operative', headquarters: 'Thane', established: '1972', branches: '100+' },
    { sNo: 89, bankName: 'Janata Sahakari Bank', ifscPrefix: 'JSBP', type: 'Co-operative', headquarters: 'Pune', established: '1948', branches: '60+' },
    { sNo: 90, bankName: 'Citizen Credit Co-op Bank', ifscPrefix: 'CCBL', type: 'Co-operative', headquarters: 'Mumbai', established: '1945', branches: '50+' },
    { sNo: 91, bankName: 'GP Parsik Sahakari Bank', ifscPrefix: 'GPPB', type: 'Co-operative', headquarters: 'Thane', established: '1984', branches: '20+' },
    { sNo: 92, bankName: 'Bharat Co-operative Bank', ifscPrefix: 'BCBM', type: 'Co-operative', headquarters: 'Mumbai', established: '1947', branches: '40+' },
    { sNo: 93, bankName: 'Zoroastrian Co-op Bank', ifscPrefix: 'ZCBL', type: 'Co-operative', headquarters: 'Mumbai', established: '1927', branches: '10+' },
    { sNo: 94, bankName: 'Nutan Nagarik Sahakari Bank', ifscPrefix: 'NNSB', type: 'Co-operative', headquarters: 'Ahmedabad', established: '1953', branches: '55+' },
    // Development Finance Institutions
    { sNo: 95, bankName: 'NABARD', ifscPrefix: 'NBRD', type: 'Development Bank', headquarters: 'Mumbai', established: '1982', branches: '31 (Regional)' },
    { sNo: 96, bankName: 'SIDBI', ifscPrefix: 'SIDB', type: 'Development Bank', headquarters: 'Lucknow', established: '1990', branches: '15 (Regional)' },
    { sNo: 97, bankName: 'EXIM Bank', ifscPrefix: 'EIBI', type: 'Development Bank', headquarters: 'Mumbai', established: '1982', branches: '19' },
    { sNo: 98, bankName: 'National Housing Bank', ifscPrefix: 'NHBA', type: 'Development Bank', headquarters: 'New Delhi', established: '1988', branches: '1 (HO)' },
    // Neobanks / Digital-first
    { sNo: 99, bankName: 'Jupiter (Powered by Federal Bank)', ifscPrefix: 'FDRL', type: 'Neobank', headquarters: 'Mumbai', established: '2021', branches: 'Digital' },
    { sNo: 100, bankName: 'Fi Money (Powered by Federal Bank)', ifscPrefix: 'FDRL', type: 'Neobank', headquarters: 'Bengaluru', established: '2021', branches: 'Digital' },
];
