export interface PinCodeEntry { sNo: number; pinCode: string; officeName: string; district: string; state: string; deliveryType: string; region: string; divisionName: string; }

export const indianPinCodesData: PinCodeEntry[] = [
    { sNo: 1, pinCode: '110001', officeName: 'Connaught Place', district: 'Central Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'New Delhi Central' },
    { sNo: 2, pinCode: '110002', officeName: 'Darya Ganj', district: 'Central Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'New Delhi Central' },
    { sNo: 3, pinCode: '110003', officeName: 'Civil Lines', district: 'North Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'Delhi North' },
    { sNo: 4, pinCode: '110005', officeName: 'Karol Bagh', district: 'Central Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'New Delhi Central' },
    { sNo: 5, pinCode: '110006', officeName: 'Sadar Bazaar', district: 'Central Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'New Delhi Central' },
    { sNo: 6, pinCode: '110007', officeName: 'Delhi Cantt', district: 'South West Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'New Delhi West' },
    { sNo: 7, pinCode: '110008', officeName: 'Patel Nagar', district: 'West Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'Delhi West' },
    { sNo: 8, pinCode: '110010', officeName: 'Defence Colony', district: 'South Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'New Delhi South' },
    { sNo: 9, pinCode: '110011', officeName: 'Nizamuddin', district: 'South East Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'New Delhi South' },
    { sNo: 10, pinCode: '110012', officeName: 'Lodhi Road', district: 'New Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'New Delhi GPO' },
    { sNo: 11, pinCode: '110016', officeName: 'Hauz Khas', district: 'South Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'New Delhi South' },
    { sNo: 12, pinCode: '110017', officeName: 'Malviya Nagar', district: 'South Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'New Delhi South' },
    { sNo: 13, pinCode: '110019', officeName: 'Kalkaji', district: 'South Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'New Delhi South' },
    { sNo: 14, pinCode: '110020', officeName: 'Okhla', district: 'South East Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'New Delhi South East' },
    { sNo: 15, pinCode: '110024', officeName: 'Lajpat Nagar', district: 'South Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'New Delhi South' },
    { sNo: 16, pinCode: '110025', officeName: 'Tughlakabad', district: 'South East Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'New Delhi South East' },
    { sNo: 17, pinCode: '110030', officeName: 'Vasant Vihar', district: 'South West Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'New Delhi West' },
    { sNo: 18, pinCode: '110044', officeName: 'Shahdara', district: 'Shahdara', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'Delhi East' },
    { sNo: 19, pinCode: '110048', officeName: 'Srinivaspuri', district: 'South East Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'New Delhi South East' },
    { sNo: 20, pinCode: '110049', officeName: 'East of Kailash', district: 'South Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'New Delhi South' },
    { sNo: 21, pinCode: '110052', officeName: 'Azadpur', district: 'North West Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'Delhi North' },
    { sNo: 22, pinCode: '110053', officeName: 'Timarpur', district: 'North Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'Delhi North' },
    { sNo: 23, pinCode: '110055', officeName: 'Jama Masjid', district: 'Central Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'New Delhi Central' },
    { sNo: 24, pinCode: '110060', officeName: 'Janakpuri', district: 'West Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'Delhi West' },
    { sNo: 25, pinCode: '110062', officeName: 'Hari Nagar', district: 'West Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'Delhi West' },
    { sNo: 26, pinCode: '110065', officeName: 'Saket', district: 'South Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'New Delhi South' },
    { sNo: 27, pinCode: '110075', officeName: 'Badarpur', district: 'South East Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'New Delhi South East' },
    { sNo: 28, pinCode: '110085', officeName: 'Dilshad Garden', district: 'Shahdara', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'Delhi East' },
    { sNo: 29, pinCode: '110092', officeName: 'Patparganj', district: 'East Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'Delhi East' },
    { sNo: 30, pinCode: '110096', officeName: 'Seelampur', district: 'North East Delhi', state: 'Delhi', deliveryType: 'Delivery', region: 'Delhi', divisionName: 'Delhi East' },
    { sNo: 31, pinCode: '400001', officeName: 'GPO Mumbai', district: 'Mumbai', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai GPO' },
    { sNo: 32, pinCode: '400002', officeName: 'Kalbadevi', district: 'Mumbai', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai Central' },
    { sNo: 33, pinCode: '400003', officeName: 'Mandvi', district: 'Mumbai', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai Central' },
    { sNo: 34, pinCode: '400004', officeName: 'Girgaon', district: 'Mumbai', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai Central' },
    { sNo: 35, pinCode: '400005', officeName: 'Colaba', district: 'Mumbai', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai GPO' },
    { sNo: 36, pinCode: '400007', officeName: 'Parel', district: 'Mumbai', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai Central' },
    { sNo: 37, pinCode: '400010', officeName: 'Mazgaon', district: 'Mumbai', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai Central' },
    { sNo: 38, pinCode: '400012', officeName: 'Lower Parel', district: 'Mumbai', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai Central' },
    { sNo: 39, pinCode: '400014', officeName: 'Dadar', district: 'Mumbai', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai City' },
    { sNo: 40, pinCode: '400016', officeName: 'Mahim', district: 'Mumbai', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai City' },
    { sNo: 41, pinCode: '400018', officeName: 'Worli', district: 'Mumbai', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai City' },
    { sNo: 42, pinCode: '400020', officeName: 'Churchgate', district: 'Mumbai', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai GPO' },
    { sNo: 43, pinCode: '400021', officeName: 'Nariman Point', district: 'Mumbai', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai GPO' },
    { sNo: 44, pinCode: '400025', officeName: 'Prabhadevi', district: 'Mumbai', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai City' },
    { sNo: 45, pinCode: '400028', officeName: 'Matunga', district: 'Mumbai', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai City' },
    { sNo: 46, pinCode: '400050', officeName: 'Bandra West', district: 'Mumbai Suburban', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai North' },
    { sNo: 47, pinCode: '400051', officeName: 'Bandra East', district: 'Mumbai Suburban', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai North' },
    { sNo: 48, pinCode: '400053', officeName: 'Andheri West', district: 'Mumbai Suburban', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai North' },
    { sNo: 49, pinCode: '400058', officeName: 'Andheri East', district: 'Mumbai Suburban', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai North' },
    { sNo: 50, pinCode: '400059', officeName: 'Santa Cruz West', district: 'Mumbai Suburban', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai North' },
    { sNo: 51, pinCode: '400069', officeName: 'Andheri MIDC', district: 'Mumbai Suburban', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai North' },
    { sNo: 52, pinCode: '400072', officeName: 'Kurla', district: 'Mumbai Suburban', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai East' },
    { sNo: 53, pinCode: '400076', officeName: 'Powai', district: 'Mumbai Suburban', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai East' },
    { sNo: 54, pinCode: '400080', officeName: 'Mulund', district: 'Mumbai Suburban', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai East' },
    { sNo: 55, pinCode: '400086', officeName: 'Ghatkopar', district: 'Mumbai Suburban', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai East' },
    { sNo: 56, pinCode: '400093', officeName: 'Borivali', district: 'Mumbai Suburban', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai North' },
    { sNo: 57, pinCode: '400097', officeName: 'Malad', district: 'Mumbai Suburban', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai North' },
    { sNo: 58, pinCode: '400099', officeName: 'Goregaon', district: 'Mumbai Suburban', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Mumbai North' },
    { sNo: 59, pinCode: '400104', officeName: 'Thane', district: 'Thane', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Thane' },
    { sNo: 60, pinCode: '411001', officeName: 'Pune GPO', district: 'Pune', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Pune' },
    { sNo: 61, pinCode: '411002', officeName: 'Budhwar Peth', district: 'Pune', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Pune' },
    { sNo: 62, pinCode: '411004', officeName: 'Camp Pune', district: 'Pune', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Pune' },
    { sNo: 63, pinCode: '411005', officeName: 'Shivaji Nagar', district: 'Pune', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Pune' },
    { sNo: 64, pinCode: '411014', officeName: 'Hadapsar', district: 'Pune', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Pune East' },
    { sNo: 65, pinCode: '411016', officeName: 'Bibvewadi', district: 'Pune', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Pune' },
    { sNo: 66, pinCode: '411030', officeName: 'Karve Nagar', district: 'Pune', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Pune West' },
    { sNo: 67, pinCode: '411038', officeName: 'Kothrud', district: 'Pune', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Pune West' },
    { sNo: 68, pinCode: '411041', officeName: 'Hinjewadi', district: 'Pune', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Pune West' },
    { sNo: 69, pinCode: '411057', officeName: 'Pimpri', district: 'Pune', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Pimpri' },
    { sNo: 70, pinCode: '560001', officeName: 'GPO Bangalore', district: 'Bangalore Urban', state: 'Karnataka', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Bangalore GPO' },
    { sNo: 71, pinCode: '560002', officeName: 'Frazer Town', district: 'Bangalore Urban', state: 'Karnataka', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Bangalore East' },
    { sNo: 72, pinCode: '560003', officeName: 'Rajajinagar', district: 'Bangalore Urban', state: 'Karnataka', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Bangalore West' },
    { sNo: 73, pinCode: '560004', officeName: 'Basavanagudi', district: 'Bangalore Urban', state: 'Karnataka', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Bangalore South' },
    { sNo: 74, pinCode: '560008', officeName: 'Shivajinagar', district: 'Bangalore Urban', state: 'Karnataka', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Bangalore GPO' },
    { sNo: 75, pinCode: '560010', officeName: 'Jayanagar', district: 'Bangalore Urban', state: 'Karnataka', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Bangalore South' },
    { sNo: 76, pinCode: '560011', officeName: 'Malleshwaram', district: 'Bangalore Urban', state: 'Karnataka', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Bangalore West' },
    { sNo: 77, pinCode: '560017', officeName: 'Koramangala', district: 'Bangalore Urban', state: 'Karnataka', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Bangalore South' },
    { sNo: 78, pinCode: '560034', officeName: 'Indiranagar', district: 'Bangalore Urban', state: 'Karnataka', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Bangalore East' },
    { sNo: 79, pinCode: '560038', officeName: 'Electronic City', district: 'Bangalore Urban', state: 'Karnataka', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Bangalore South' },
    { sNo: 80, pinCode: '560066', officeName: 'Whitefield', district: 'Bangalore Urban', state: 'Karnataka', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Bangalore East' },
    { sNo: 81, pinCode: '560100', officeName: 'Yelahanka', district: 'Bangalore Urban', state: 'Karnataka', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Bangalore North' },
    { sNo: 82, pinCode: '600001', officeName: 'GPO Chennai', district: 'Chennai', state: 'Tamil Nadu', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Chennai GPO' },
    { sNo: 83, pinCode: '600002', officeName: 'Anna Salai', district: 'Chennai', state: 'Tamil Nadu', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Chennai Central' },
    { sNo: 84, pinCode: '600003', officeName: 'Park Town', district: 'Chennai', state: 'Tamil Nadu', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Chennai GPO' },
    { sNo: 85, pinCode: '600006', officeName: 'Triplicane', district: 'Chennai', state: 'Tamil Nadu', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Chennai Central' },
    { sNo: 86, pinCode: '600010', officeName: 'Kilpauk', district: 'Chennai', state: 'Tamil Nadu', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Chennai North' },
    { sNo: 87, pinCode: '600017', officeName: 'T. Nagar', district: 'Chennai', state: 'Tamil Nadu', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Chennai South' },
    { sNo: 88, pinCode: '600020', officeName: 'Adyar', district: 'Chennai', state: 'Tamil Nadu', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Chennai South' },
    { sNo: 89, pinCode: '600032', officeName: 'Saidapet', district: 'Chennai', state: 'Tamil Nadu', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Chennai South' },
    { sNo: 90, pinCode: '600040', officeName: 'Guindy', district: 'Chennai', state: 'Tamil Nadu', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Chennai South' },
    { sNo: 91, pinCode: '600042', officeName: 'Velachery', district: 'Chennai', state: 'Tamil Nadu', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Chennai South' },
    { sNo: 92, pinCode: '600097', officeName: 'OMR', district: 'Chennai', state: 'Tamil Nadu', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Chennai South' },
    { sNo: 93, pinCode: '700001', officeName: 'GPO Kolkata', district: 'Kolkata', state: 'West Bengal', deliveryType: 'Delivery', region: 'Eastern', divisionName: 'Kolkata GPO' },
    { sNo: 94, pinCode: '700007', officeName: 'Bowbazar', district: 'Kolkata', state: 'West Bengal', deliveryType: 'Delivery', region: 'Eastern', divisionName: 'Kolkata Central' },
    { sNo: 95, pinCode: '700012', officeName: 'Gariahat', district: 'Kolkata', state: 'West Bengal', deliveryType: 'Delivery', region: 'Eastern', divisionName: 'Kolkata South' },
    { sNo: 96, pinCode: '700019', officeName: 'Ballygunge', district: 'Kolkata', state: 'West Bengal', deliveryType: 'Delivery', region: 'Eastern', divisionName: 'Kolkata South' },
    { sNo: 97, pinCode: '700020', officeName: 'Park Street', district: 'Kolkata', state: 'West Bengal', deliveryType: 'Delivery', region: 'Eastern', divisionName: 'Kolkata Central' },
    { sNo: 98, pinCode: '700029', officeName: 'Alipore', district: 'Kolkata', state: 'West Bengal', deliveryType: 'Delivery', region: 'Eastern', divisionName: 'Kolkata South' },
    { sNo: 99, pinCode: '700064', officeName: 'Salt Lake', district: 'Kolkata', state: 'West Bengal', deliveryType: 'Delivery', region: 'Eastern', divisionName: 'Kolkata North' },
    { sNo: 100, pinCode: '700091', officeName: 'New Town', district: 'Kolkata', state: 'West Bengal', deliveryType: 'Delivery', region: 'Eastern', divisionName: 'Kolkata North' },
    { sNo: 101, pinCode: '500001', officeName: 'Hyderabad GPO', district: 'Hyderabad', state: 'Telangana', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Hyderabad GPO' },
    { sNo: 102, pinCode: '500003', officeName: 'Koti', district: 'Hyderabad', state: 'Telangana', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Hyderabad Central' },
    { sNo: 103, pinCode: '500008', officeName: 'Banjara Hills', district: 'Hyderabad', state: 'Telangana', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Hyderabad West' },
    { sNo: 104, pinCode: '500016', officeName: 'Ameerpet', district: 'Hyderabad', state: 'Telangana', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Hyderabad West' },
    { sNo: 105, pinCode: '500032', officeName: 'Jubilee Hills', district: 'Hyderabad', state: 'Telangana', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Hyderabad West' },
    { sNo: 106, pinCode: '500034', officeName: 'Begumpet', district: 'Hyderabad', state: 'Telangana', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Hyderabad North' },
    { sNo: 107, pinCode: '500038', officeName: 'Secunderabad', district: 'Hyderabad', state: 'Telangana', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Secunderabad' },
    { sNo: 108, pinCode: '500072', officeName: 'HITEC City', district: 'Hyderabad', state: 'Telangana', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Hyderabad West' },
    { sNo: 109, pinCode: '500081', officeName: 'Gachibowli', district: 'Hyderabad', state: 'Telangana', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Hyderabad West' },
    { sNo: 110, pinCode: '500090', officeName: 'Kukatpally', district: 'Hyderabad', state: 'Telangana', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Hyderabad North' },
    { sNo: 111, pinCode: '380001', officeName: 'Ahmedabad GPO', district: 'Ahmedabad', state: 'Gujarat', deliveryType: 'Delivery', region: 'Western', divisionName: 'Ahmedabad GPO' },
    { sNo: 112, pinCode: '380006', officeName: 'Navrangpura', district: 'Ahmedabad', state: 'Gujarat', deliveryType: 'Delivery', region: 'Western', divisionName: 'Ahmedabad City' },
    { sNo: 113, pinCode: '380009', officeName: 'Ellis Bridge', district: 'Ahmedabad', state: 'Gujarat', deliveryType: 'Delivery', region: 'Western', divisionName: 'Ahmedabad City' },
    { sNo: 114, pinCode: '380013', officeName: 'C.G. Road', district: 'Ahmedabad', state: 'Gujarat', deliveryType: 'Delivery', region: 'Western', divisionName: 'Ahmedabad City' },
    { sNo: 115, pinCode: '380015', officeName: 'Satellite', district: 'Ahmedabad', state: 'Gujarat', deliveryType: 'Delivery', region: 'Western', divisionName: 'Ahmedabad West' },
    { sNo: 116, pinCode: '380054', officeName: 'S.G. Highway', district: 'Ahmedabad', state: 'Gujarat', deliveryType: 'Delivery', region: 'Western', divisionName: 'Ahmedabad West' },
    { sNo: 117, pinCode: '380058', officeName: 'Prahlad Nagar', district: 'Ahmedabad', state: 'Gujarat', deliveryType: 'Delivery', region: 'Western', divisionName: 'Ahmedabad West' },
    { sNo: 118, pinCode: '380059', officeName: 'Bopal', district: 'Ahmedabad', state: 'Gujarat', deliveryType: 'Delivery', region: 'Western', divisionName: 'Ahmedabad West' },
    { sNo: 119, pinCode: '302001', officeName: 'Jaipur GPO', district: 'Jaipur', state: 'Rajasthan', deliveryType: 'Delivery', region: 'Western', divisionName: 'Jaipur GPO' },
    { sNo: 120, pinCode: '302004', officeName: 'Bani Park', district: 'Jaipur', state: 'Rajasthan', deliveryType: 'Delivery', region: 'Western', divisionName: 'Jaipur City' },
    { sNo: 121, pinCode: '302015', officeName: 'Malviya Nagar Jaipur', district: 'Jaipur', state: 'Rajasthan', deliveryType: 'Delivery', region: 'Western', divisionName: 'Jaipur South' },
    { sNo: 122, pinCode: '302017', officeName: 'Mansarovar', district: 'Jaipur', state: 'Rajasthan', deliveryType: 'Delivery', region: 'Western', divisionName: 'Jaipur West' },
    { sNo: 123, pinCode: '302020', officeName: 'Vaishali Nagar', district: 'Jaipur', state: 'Rajasthan', deliveryType: 'Delivery', region: 'Western', divisionName: 'Jaipur West' },
    { sNo: 124, pinCode: '226001', officeName: 'Lucknow GPO', district: 'Lucknow', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Lucknow GPO' },
    { sNo: 125, pinCode: '226003', officeName: 'Hazratganj', district: 'Lucknow', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Lucknow City' },
    { sNo: 126, pinCode: '226010', officeName: 'Gomti Nagar', district: 'Lucknow', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Lucknow East' },
    { sNo: 127, pinCode: '226016', officeName: 'Aliganj', district: 'Lucknow', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Lucknow North' },
    { sNo: 128, pinCode: '226022', officeName: 'Indira Nagar Lucknow', district: 'Lucknow', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Lucknow East' },
    { sNo: 129, pinCode: '160001', officeName: 'Chandigarh GPO', district: 'Chandigarh', state: 'Chandigarh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Chandigarh' },
    { sNo: 130, pinCode: '160017', officeName: 'Sector 17', district: 'Chandigarh', state: 'Chandigarh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Chandigarh' },
    { sNo: 131, pinCode: '160022', officeName: 'Sector 22', district: 'Chandigarh', state: 'Chandigarh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Chandigarh' },
    { sNo: 132, pinCode: '160036', officeName: 'Sector 36', district: 'Chandigarh', state: 'Chandigarh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Chandigarh' },
    { sNo: 133, pinCode: '160047', officeName: 'Sector 47', district: 'Chandigarh', state: 'Chandigarh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Chandigarh' },
    { sNo: 134, pinCode: '462001', officeName: 'Bhopal GPO', district: 'Bhopal', state: 'Madhya Pradesh', deliveryType: 'Delivery', region: 'Central', divisionName: 'Bhopal' },
    { sNo: 135, pinCode: '462011', officeName: 'New Market Bhopal', district: 'Bhopal', state: 'Madhya Pradesh', deliveryType: 'Delivery', region: 'Central', divisionName: 'Bhopal City' },
    { sNo: 136, pinCode: '462016', officeName: 'Arera Colony', district: 'Bhopal', state: 'Madhya Pradesh', deliveryType: 'Delivery', region: 'Central', divisionName: 'Bhopal South' },
    { sNo: 137, pinCode: '462023', officeName: 'M.P. Nagar', district: 'Bhopal', state: 'Madhya Pradesh', deliveryType: 'Delivery', region: 'Central', divisionName: 'Bhopal South' },
    { sNo: 138, pinCode: '452001', officeName: 'Indore GPO', district: 'Indore', state: 'Madhya Pradesh', deliveryType: 'Delivery', region: 'Central', divisionName: 'Indore' },
    { sNo: 139, pinCode: '452010', officeName: 'Vijay Nagar Indore', district: 'Indore', state: 'Madhya Pradesh', deliveryType: 'Delivery', region: 'Central', divisionName: 'Indore City' },
    { sNo: 140, pinCode: '440001', officeName: 'Nagpur GPO', district: 'Nagpur', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Central', divisionName: 'Nagpur GPO' },
    { sNo: 141, pinCode: '440010', officeName: 'Dharampeth', district: 'Nagpur', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Central', divisionName: 'Nagpur City' },
    { sNo: 142, pinCode: '440012', officeName: 'Civil Lines Nagpur', district: 'Nagpur', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Central', divisionName: 'Nagpur City' },
    { sNo: 143, pinCode: '440022', officeName: 'Wardha Road', district: 'Nagpur', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Central', divisionName: 'Nagpur East' },
    { sNo: 144, pinCode: '201301', officeName: 'Noida Sector 1', district: 'Gautam Buddh Nagar', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Noida' },
    { sNo: 145, pinCode: '201303', officeName: 'Noida Sector 62', district: 'Gautam Buddh Nagar', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Noida' },
    { sNo: 146, pinCode: '201304', officeName: 'Greater Noida', district: 'Gautam Buddh Nagar', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Noida' },
    { sNo: 147, pinCode: '122001', officeName: 'Gurgaon', district: 'Gurgaon', state: 'Haryana', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Gurgaon' },
    { sNo: 148, pinCode: '122002', officeName: 'DLF Phase 1', district: 'Gurgaon', state: 'Haryana', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Gurgaon' },
    { sNo: 149, pinCode: '122009', officeName: 'Sector 29 Gurgaon', district: 'Gurgaon', state: 'Haryana', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Gurgaon' },
    { sNo: 150, pinCode: '122018', officeName: 'Cyber City', district: 'Gurgaon', state: 'Haryana', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Gurgaon' },
    // Surat
    { sNo: 151, pinCode: '395001', officeName: 'Surat GPO', district: 'Surat', state: 'Gujarat', deliveryType: 'Delivery', region: 'Western', divisionName: 'Surat' },
    { sNo: 152, pinCode: '395003', officeName: 'Athwa Lines', district: 'Surat', state: 'Gujarat', deliveryType: 'Delivery', region: 'Western', divisionName: 'Surat City' },
    { sNo: 153, pinCode: '395006', officeName: 'Adajan', district: 'Surat', state: 'Gujarat', deliveryType: 'Delivery', region: 'Western', divisionName: 'Surat West' },
    { sNo: 154, pinCode: '395007', officeName: 'Varachha', district: 'Surat', state: 'Gujarat', deliveryType: 'Delivery', region: 'Western', divisionName: 'Surat East' },
    { sNo: 155, pinCode: '395009', officeName: 'Vesu', district: 'Surat', state: 'Gujarat', deliveryType: 'Delivery', region: 'Western', divisionName: 'Surat West' },
    { sNo: 156, pinCode: '395010', officeName: 'Katargam', district: 'Surat', state: 'Gujarat', deliveryType: 'Delivery', region: 'Western', divisionName: 'Surat East' },
    // Vadodara
    { sNo: 157, pinCode: '390001', officeName: 'Vadodara GPO', district: 'Vadodara', state: 'Gujarat', deliveryType: 'Delivery', region: 'Western', divisionName: 'Vadodara' },
    { sNo: 158, pinCode: '390005', officeName: 'Fatehgunj', district: 'Vadodara', state: 'Gujarat', deliveryType: 'Delivery', region: 'Western', divisionName: 'Vadodara City' },
    { sNo: 159, pinCode: '390007', officeName: 'Alkapuri', district: 'Vadodara', state: 'Gujarat', deliveryType: 'Delivery', region: 'Western', divisionName: 'Vadodara City' },
    { sNo: 160, pinCode: '390015', officeName: 'Manjalpur', district: 'Vadodara', state: 'Gujarat', deliveryType: 'Delivery', region: 'Western', divisionName: 'Vadodara South' },
    // Kanpur
    { sNo: 161, pinCode: '208001', officeName: 'Kanpur GPO', district: 'Kanpur Nagar', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Kanpur' },
    { sNo: 162, pinCode: '208002', officeName: 'Meston Road', district: 'Kanpur Nagar', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Kanpur City' },
    { sNo: 163, pinCode: '208004', officeName: 'Swaroop Nagar', district: 'Kanpur Nagar', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Kanpur City' },
    { sNo: 164, pinCode: '208011', officeName: 'Kidwai Nagar', district: 'Kanpur Nagar', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Kanpur South' },
    { sNo: 165, pinCode: '208025', officeName: 'Kalyanpur', district: 'Kanpur Nagar', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Kanpur West' },
    // Varanasi
    { sNo: 166, pinCode: '221001', officeName: 'Varanasi GPO', district: 'Varanasi', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Varanasi' },
    { sNo: 167, pinCode: '221002', officeName: 'Dashashwamedh', district: 'Varanasi', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Varanasi City' },
    { sNo: 168, pinCode: '221005', officeName: 'Lanka', district: 'Varanasi', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Varanasi South' },
    { sNo: 169, pinCode: '221010', officeName: 'Sigra', district: 'Varanasi', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Varanasi City' },
    // Patna
    { sNo: 170, pinCode: '800001', officeName: 'Patna GPO', district: 'Patna', state: 'Bihar', deliveryType: 'Delivery', region: 'Eastern', divisionName: 'Patna' },
    { sNo: 171, pinCode: '800004', officeName: 'Bankipur', district: 'Patna', state: 'Bihar', deliveryType: 'Delivery', region: 'Eastern', divisionName: 'Patna City' },
    { sNo: 172, pinCode: '800006', officeName: 'Kankarbagh', district: 'Patna', state: 'Bihar', deliveryType: 'Delivery', region: 'Eastern', divisionName: 'Patna South' },
    { sNo: 173, pinCode: '800014', officeName: 'Boring Road', district: 'Patna', state: 'Bihar', deliveryType: 'Delivery', region: 'Eastern', divisionName: 'Patna City' },
    { sNo: 174, pinCode: '800020', officeName: 'Rajendra Nagar', district: 'Patna', state: 'Bihar', deliveryType: 'Delivery', region: 'Eastern', divisionName: 'Patna West' },
    { sNo: 175, pinCode: '800024', officeName: 'Danapur', district: 'Patna', state: 'Bihar', deliveryType: 'Delivery', region: 'Eastern', divisionName: 'Patna West' },
    // Ranchi
    { sNo: 176, pinCode: '834001', officeName: 'Ranchi GPO', district: 'Ranchi', state: 'Jharkhand', deliveryType: 'Delivery', region: 'Eastern', divisionName: 'Ranchi' },
    { sNo: 177, pinCode: '834002', officeName: 'Doranda', district: 'Ranchi', state: 'Jharkhand', deliveryType: 'Delivery', region: 'Eastern', divisionName: 'Ranchi City' },
    { sNo: 178, pinCode: '834008', officeName: 'Morabadi', district: 'Ranchi', state: 'Jharkhand', deliveryType: 'Delivery', region: 'Eastern', divisionName: 'Ranchi City' },
    // Guwahati
    { sNo: 179, pinCode: '781001', officeName: 'Guwahati GPO', district: 'Kamrup Metro', state: 'Assam', deliveryType: 'Delivery', region: 'Eastern', divisionName: 'Guwahati' },
    { sNo: 180, pinCode: '781003', officeName: 'Pan Bazar', district: 'Kamrup Metro', state: 'Assam', deliveryType: 'Delivery', region: 'Eastern', divisionName: 'Guwahati City' },
    { sNo: 181, pinCode: '781005', officeName: 'Paltan Bazar', district: 'Kamrup Metro', state: 'Assam', deliveryType: 'Delivery', region: 'Eastern', divisionName: 'Guwahati City' },
    { sNo: 182, pinCode: '781006', officeName: 'Uzanbazar', district: 'Kamrup Metro', state: 'Assam', deliveryType: 'Delivery', region: 'Eastern', divisionName: 'Guwahati City' },
    { sNo: 183, pinCode: '781022', officeName: 'Beltola', district: 'Kamrup Metro', state: 'Assam', deliveryType: 'Delivery', region: 'Eastern', divisionName: 'Guwahati South' },
    // Kochi
    { sNo: 184, pinCode: '682001', officeName: 'Fort Kochi', district: 'Ernakulam', state: 'Kerala', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Kochi' },
    { sNo: 185, pinCode: '682011', officeName: 'Ernakulam South', district: 'Ernakulam', state: 'Kerala', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Kochi City' },
    { sNo: 186, pinCode: '682016', officeName: 'Palarivattom', district: 'Ernakulam', state: 'Kerala', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Kochi East' },
    { sNo: 187, pinCode: '682017', officeName: 'Edappally', district: 'Ernakulam', state: 'Kerala', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Kochi East' },
    { sNo: 188, pinCode: '682024', officeName: 'Kakkanad', district: 'Ernakulam', state: 'Kerala', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Kochi East' },
    { sNo: 189, pinCode: '682030', officeName: 'Marine Drive', district: 'Ernakulam', state: 'Kerala', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Kochi City' },
    // Thiruvananthapuram
    { sNo: 190, pinCode: '695001', officeName: 'Thiruvananthapuram GPO', district: 'Thiruvananthapuram', state: 'Kerala', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Trivandrum' },
    { sNo: 191, pinCode: '695004', officeName: 'Thycaud', district: 'Thiruvananthapuram', state: 'Kerala', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Trivandrum City' },
    { sNo: 192, pinCode: '695014', officeName: 'Kazhakootam', district: 'Thiruvananthapuram', state: 'Kerala', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Trivandrum South' },
    { sNo: 193, pinCode: '695581', officeName: 'Technopark', district: 'Thiruvananthapuram', state: 'Kerala', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Trivandrum South' },
    // Coimbatore
    { sNo: 194, pinCode: '641001', officeName: 'Coimbatore GPO', district: 'Coimbatore', state: 'Tamil Nadu', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Coimbatore' },
    { sNo: 195, pinCode: '641002', officeName: 'Town Hall', district: 'Coimbatore', state: 'Tamil Nadu', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Coimbatore City' },
    { sNo: 196, pinCode: '641004', officeName: 'Peelamedu', district: 'Coimbatore', state: 'Tamil Nadu', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Coimbatore East' },
    { sNo: 197, pinCode: '641011', officeName: 'Gandhipuram', district: 'Coimbatore', state: 'Tamil Nadu', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Coimbatore City' },
    { sNo: 198, pinCode: '641014', officeName: 'Saravanampatti', district: 'Coimbatore', state: 'Tamil Nadu', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Coimbatore North' },
    { sNo: 199, pinCode: '641035', officeName: 'Singanallur', district: 'Coimbatore', state: 'Tamil Nadu', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Coimbatore East' },
    // Madurai
    { sNo: 200, pinCode: '625001', officeName: 'Madurai GPO', district: 'Madurai', state: 'Tamil Nadu', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Madurai' },
    { sNo: 201, pinCode: '625002', officeName: 'Meenakshi Temple', district: 'Madurai', state: 'Tamil Nadu', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Madurai City' },
    { sNo: 202, pinCode: '625009', officeName: 'Anna Nagar Madurai', district: 'Madurai', state: 'Tamil Nadu', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Madurai North' },
    { sNo: 203, pinCode: '625020', officeName: 'Thiruparankundram', district: 'Madurai', state: 'Tamil Nadu', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Madurai South' },
    // Vizag
    { sNo: 204, pinCode: '530001', officeName: 'Visakhapatnam GPO', district: 'Visakhapatnam', state: 'Andhra Pradesh', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Vizag' },
    { sNo: 205, pinCode: '530003', officeName: 'Dwaraka Nagar', district: 'Visakhapatnam', state: 'Andhra Pradesh', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Vizag City' },
    { sNo: 206, pinCode: '530016', officeName: 'Gajuwaka', district: 'Visakhapatnam', state: 'Andhra Pradesh', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Vizag North' },
    { sNo: 207, pinCode: '530017', officeName: 'MVP Colony', district: 'Visakhapatnam', state: 'Andhra Pradesh', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Vizag City' },
    { sNo: 208, pinCode: '530045', officeName: 'Madhurawada', district: 'Visakhapatnam', state: 'Andhra Pradesh', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Vizag West' },
    // Vijayawada
    { sNo: 209, pinCode: '520001', officeName: 'Vijayawada GPO', district: 'Krishna', state: 'Andhra Pradesh', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Vijayawada' },
    { sNo: 210, pinCode: '520002', officeName: 'Governorpet', district: 'Krishna', state: 'Andhra Pradesh', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Vijayawada City' },
    { sNo: 211, pinCode: '520010', officeName: 'Benz Circle', district: 'Krishna', state: 'Andhra Pradesh', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Vijayawada City' },
    // Mangalore
    { sNo: 212, pinCode: '575001', officeName: 'Mangalore GPO', district: 'Dakshina Kannada', state: 'Karnataka', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Mangalore' },
    { sNo: 213, pinCode: '575002', officeName: 'Hampankatta', district: 'Dakshina Kannada', state: 'Karnataka', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Mangalore City' },
    { sNo: 214, pinCode: '575003', officeName: 'Kankanady', district: 'Dakshina Kannada', state: 'Karnataka', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Mangalore City' },
    // Mysuru
    { sNo: 215, pinCode: '570001', officeName: 'Mysuru GPO', district: 'Mysuru', state: 'Karnataka', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Mysuru' },
    { sNo: 216, pinCode: '570004', officeName: 'Saraswathipuram', district: 'Mysuru', state: 'Karnataka', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Mysuru City' },
    { sNo: 217, pinCode: '570010', officeName: 'Vijayanagar Mysuru', district: 'Mysuru', state: 'Karnataka', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Mysuru South' },
    // Bhubaneswar
    { sNo: 218, pinCode: '751001', officeName: 'Bhubaneswar GPO', district: 'Khordha', state: 'Odisha', deliveryType: 'Delivery', region: 'Eastern', divisionName: 'Bhubaneswar' },
    { sNo: 219, pinCode: '751009', officeName: 'Saheed Nagar', district: 'Khordha', state: 'Odisha', deliveryType: 'Delivery', region: 'Eastern', divisionName: 'Bhubaneswar City' },
    { sNo: 220, pinCode: '751012', officeName: 'Jaydev Vihar', district: 'Khordha', state: 'Odisha', deliveryType: 'Delivery', region: 'Eastern', divisionName: 'Bhubaneswar North' },
    { sNo: 221, pinCode: '751024', officeName: 'Patia', district: 'Khordha', state: 'Odisha', deliveryType: 'Delivery', region: 'Eastern', divisionName: 'Bhubaneswar North' },
    // Raipur
    { sNo: 222, pinCode: '492001', officeName: 'Raipur GPO', district: 'Raipur', state: 'Chhattisgarh', deliveryType: 'Delivery', region: 'Central', divisionName: 'Raipur' },
    { sNo: 223, pinCode: '492007', officeName: 'Civil Lines Raipur', district: 'Raipur', state: 'Chhattisgarh', deliveryType: 'Delivery', region: 'Central', divisionName: 'Raipur City' },
    { sNo: 224, pinCode: '492009', officeName: 'Shankar Nagar', district: 'Raipur', state: 'Chhattisgarh', deliveryType: 'Delivery', region: 'Central', divisionName: 'Raipur City' },
    // Dehradun
    { sNo: 225, pinCode: '248001', officeName: 'Dehradun GPO', district: 'Dehradun', state: 'Uttarakhand', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Dehradun' },
    { sNo: 226, pinCode: '248003', officeName: 'Rajpur Road', district: 'Dehradun', state: 'Uttarakhand', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Dehradun City' },
    { sNo: 227, pinCode: '248006', officeName: 'Clement Town', district: 'Dehradun', state: 'Uttarakhand', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Dehradun South' },
    { sNo: 228, pinCode: '248009', officeName: 'ISBT Dehradun', district: 'Dehradun', state: 'Uttarakhand', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Dehradun City' },
    // Shimla
    { sNo: 229, pinCode: '171001', officeName: 'Shimla GPO', district: 'Shimla', state: 'Himachal Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Shimla' },
    { sNo: 230, pinCode: '171002', officeName: 'Mall Road Shimla', district: 'Shimla', state: 'Himachal Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Shimla City' },
    { sNo: 231, pinCode: '171004', officeName: 'Lakkar Bazar', district: 'Shimla', state: 'Himachal Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Shimla City' },
    // Agra
    { sNo: 232, pinCode: '282001', officeName: 'Agra GPO', district: 'Agra', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Agra' },
    { sNo: 233, pinCode: '282002', officeName: 'Sadar Bazar Agra', district: 'Agra', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Agra City' },
    { sNo: 234, pinCode: '282005', officeName: 'Dayal Bagh', district: 'Agra', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Agra North' },
    { sNo: 235, pinCode: '282007', officeName: 'Kamla Nagar Agra', district: 'Agra', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Agra South' },
    // Meerut
    { sNo: 236, pinCode: '250001', officeName: 'Meerut GPO', district: 'Meerut', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Meerut' },
    { sNo: 237, pinCode: '250002', officeName: 'Sadar Meerut', district: 'Meerut', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Meerut City' },
    { sNo: 238, pinCode: '250004', officeName: 'Shastri Nagar Meerut', district: 'Meerut', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Meerut City' },
    // Amritsar
    { sNo: 239, pinCode: '143001', officeName: 'Amritsar GPO', district: 'Amritsar', state: 'Punjab', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Amritsar' },
    { sNo: 240, pinCode: '143006', officeName: 'Lawrence Road', district: 'Amritsar', state: 'Punjab', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Amritsar City' },
    { sNo: 241, pinCode: '143008', officeName: 'Ranjit Avenue', district: 'Amritsar', state: 'Punjab', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Amritsar City' },
    // Ludhiana
    { sNo: 242, pinCode: '141001', officeName: 'Ludhiana GPO', district: 'Ludhiana', state: 'Punjab', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Ludhiana' },
    { sNo: 243, pinCode: '141002', officeName: 'Civil Lines Ludhiana', district: 'Ludhiana', state: 'Punjab', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Ludhiana City' },
    { sNo: 244, pinCode: '141008', officeName: 'Model Town Ludhiana', district: 'Ludhiana', state: 'Punjab', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Ludhiana City' },
    // Jodhpur
    { sNo: 245, pinCode: '342001', officeName: 'Jodhpur GPO', district: 'Jodhpur', state: 'Rajasthan', deliveryType: 'Delivery', region: 'Western', divisionName: 'Jodhpur' },
    { sNo: 246, pinCode: '342003', officeName: 'Sardarpura', district: 'Jodhpur', state: 'Rajasthan', deliveryType: 'Delivery', region: 'Western', divisionName: 'Jodhpur City' },
    { sNo: 247, pinCode: '342005', officeName: 'Paota', district: 'Jodhpur', state: 'Rajasthan', deliveryType: 'Delivery', region: 'Western', divisionName: 'Jodhpur City' },
    // Udaipur
    { sNo: 248, pinCode: '313001', officeName: 'Udaipur GPO', district: 'Udaipur', state: 'Rajasthan', deliveryType: 'Delivery', region: 'Western', divisionName: 'Udaipur' },
    { sNo: 249, pinCode: '313002', officeName: 'Hiran Magri', district: 'Udaipur', state: 'Rajasthan', deliveryType: 'Delivery', region: 'Western', divisionName: 'Udaipur City' },
    { sNo: 250, pinCode: '313004', officeName: 'Fateh Sagar', district: 'Udaipur', state: 'Rajasthan', deliveryType: 'Delivery', region: 'Western', divisionName: 'Udaipur City' },
    // Kota
    { sNo: 251, pinCode: '324001', officeName: 'Kota GPO', district: 'Kota', state: 'Rajasthan', deliveryType: 'Delivery', region: 'Western', divisionName: 'Kota' },
    { sNo: 252, pinCode: '324005', officeName: 'Talwandi', district: 'Kota', state: 'Rajasthan', deliveryType: 'Delivery', region: 'Western', divisionName: 'Kota City' },
    { sNo: 253, pinCode: '324007', officeName: 'Dadabari', district: 'Kota', state: 'Rajasthan', deliveryType: 'Delivery', region: 'Western', divisionName: 'Kota City' },
    // Jammu
    { sNo: 254, pinCode: '180001', officeName: 'Jammu GPO', district: 'Jammu', state: 'Jammu & Kashmir', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Jammu' },
    { sNo: 255, pinCode: '180004', officeName: 'Gandhi Nagar Jammu', district: 'Jammu', state: 'Jammu & Kashmir', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Jammu City' },
    { sNo: 256, pinCode: '180006', officeName: 'Trikuta Nagar', district: 'Jammu', state: 'Jammu & Kashmir', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Jammu City' },
    // Srinagar
    { sNo: 257, pinCode: '190001', officeName: 'Srinagar GPO', district: 'Srinagar', state: 'Jammu & Kashmir', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Srinagar' },
    { sNo: 258, pinCode: '190006', officeName: 'Lal Chowk', district: 'Srinagar', state: 'Jammu & Kashmir', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Srinagar City' },
    { sNo: 259, pinCode: '190008', officeName: 'Rajbagh', district: 'Srinagar', state: 'Jammu & Kashmir', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Srinagar City' },
    // Rajkot
    { sNo: 260, pinCode: '360001', officeName: 'Rajkot GPO', district: 'Rajkot', state: 'Gujarat', deliveryType: 'Delivery', region: 'Western', divisionName: 'Rajkot' },
    { sNo: 261, pinCode: '360002', officeName: 'Kalawad Road', district: 'Rajkot', state: 'Gujarat', deliveryType: 'Delivery', region: 'Western', divisionName: 'Rajkot City' },
    { sNo: 262, pinCode: '360005', officeName: 'University Road Rajkot', district: 'Rajkot', state: 'Gujarat', deliveryType: 'Delivery', region: 'Western', divisionName: 'Rajkot City' },
    // Nashik
    { sNo: 263, pinCode: '422001', officeName: 'Nashik GPO', district: 'Nashik', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Nashik' },
    { sNo: 264, pinCode: '422003', officeName: 'College Road Nashik', district: 'Nashik', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Nashik City' },
    { sNo: 265, pinCode: '422005', officeName: 'Gangapur Road', district: 'Nashik', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Nashik North' },
    // Aurangabad
    { sNo: 266, pinCode: '431001', officeName: 'Aurangabad GPO', district: 'Aurangabad', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Aurangabad' },
    { sNo: 267, pinCode: '431003', officeName: 'Cidco Aurangabad', district: 'Aurangabad', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Aurangabad City' },
    { sNo: 268, pinCode: '431005', officeName: 'Waluj', district: 'Aurangabad', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Aurangabad MIDC' },
    // Kolhapur
    { sNo: 269, pinCode: '416001', officeName: 'Kolhapur GPO', district: 'Kolhapur', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Kolhapur' },
    { sNo: 270, pinCode: '416003', officeName: 'Rajarampuri', district: 'Kolhapur', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Kolhapur City' },
    // Solapur
    { sNo: 271, pinCode: '413001', officeName: 'Solapur GPO', district: 'Solapur', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Solapur' },
    { sNo: 272, pinCode: '413003', officeName: 'Railway Lines Solapur', district: 'Solapur', state: 'Maharashtra', deliveryType: 'Delivery', region: 'Western', divisionName: 'Solapur City' },
    // Thrissur
    { sNo: 273, pinCode: '680001', officeName: 'Thrissur GPO', district: 'Thrissur', state: 'Kerala', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Thrissur' },
    { sNo: 274, pinCode: '680003', officeName: 'Swaraj Round', district: 'Thrissur', state: 'Kerala', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Thrissur City' },
    { sNo: 275, pinCode: '680005', officeName: 'Punkunnam', district: 'Thrissur', state: 'Kerala', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Thrissur City' },
    // Kozhikode
    { sNo: 276, pinCode: '673001', officeName: 'Kozhikode GPO', district: 'Kozhikode', state: 'Kerala', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Kozhikode' },
    { sNo: 277, pinCode: '673004', officeName: 'Mankavu', district: 'Kozhikode', state: 'Kerala', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Kozhikode City' },
    { sNo: 278, pinCode: '673006', officeName: 'Mavoor Road', district: 'Kozhikode', state: 'Kerala', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Kozhikode City' },
    // Gorakhpur
    { sNo: 279, pinCode: '273001', officeName: 'Gorakhpur GPO', district: 'Gorakhpur', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Gorakhpur' },
    { sNo: 280, pinCode: '273004', officeName: 'Mohaddipur', district: 'Gorakhpur', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Gorakhpur City' },
    // Allahabad (Prayagraj)
    { sNo: 281, pinCode: '211001', officeName: 'Allahabad GPO', district: 'Prayagraj', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Prayagraj' },
    { sNo: 282, pinCode: '211002', officeName: 'Civil Lines Prayagraj', district: 'Prayagraj', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Prayagraj City' },
    { sNo: 283, pinCode: '211004', officeName: 'Katra', district: 'Prayagraj', state: 'Uttar Pradesh', deliveryType: 'Delivery', region: 'Northern', divisionName: 'Prayagraj City' },
    // Gwalior
    { sNo: 284, pinCode: '474001', officeName: 'Gwalior GPO', district: 'Gwalior', state: 'Madhya Pradesh', deliveryType: 'Delivery', region: 'Central', divisionName: 'Gwalior' },
    { sNo: 285, pinCode: '474002', officeName: 'Lashkar', district: 'Gwalior', state: 'Madhya Pradesh', deliveryType: 'Delivery', region: 'Central', divisionName: 'Gwalior City' },
    { sNo: 286, pinCode: '474009', officeName: 'City Centre Gwalior', district: 'Gwalior', state: 'Madhya Pradesh', deliveryType: 'Delivery', region: 'Central', divisionName: 'Gwalior City' },
    // Jabalpur
    { sNo: 287, pinCode: '482001', officeName: 'Jabalpur GPO', district: 'Jabalpur', state: 'Madhya Pradesh', deliveryType: 'Delivery', region: 'Central', divisionName: 'Jabalpur' },
    { sNo: 288, pinCode: '482002', officeName: 'Wright Town', district: 'Jabalpur', state: 'Madhya Pradesh', deliveryType: 'Delivery', region: 'Central', divisionName: 'Jabalpur City' },
    // Tiruchirappalli
    { sNo: 289, pinCode: '620001', officeName: 'Tiruchirappalli GPO', district: 'Tiruchirappalli', state: 'Tamil Nadu', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Trichy' },
    { sNo: 290, pinCode: '620002', officeName: 'Srirangam', district: 'Tiruchirappalli', state: 'Tamil Nadu', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Trichy City' },
    { sNo: 291, pinCode: '620017', officeName: 'Thillai Nagar', district: 'Tiruchirappalli', state: 'Tamil Nadu', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Trichy City' },
    // Salem
    { sNo: 292, pinCode: '636001', officeName: 'Salem GPO', district: 'Salem', state: 'Tamil Nadu', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Salem' },
    { sNo: 293, pinCode: '636004', officeName: 'Fairlands', district: 'Salem', state: 'Tamil Nadu', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Salem City' },
    // Hubli-Dharwad
    { sNo: 294, pinCode: '580001', officeName: 'Hubli GPO', district: 'Dharwad', state: 'Karnataka', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Hubli' },
    { sNo: 295, pinCode: '580020', officeName: 'Vidyanagar Hubli', district: 'Dharwad', state: 'Karnataka', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Hubli City' },
    { sNo: 296, pinCode: '580001', officeName: 'Dharwad GPO', district: 'Dharwad', state: 'Karnataka', deliveryType: 'Delivery', region: 'Southern', divisionName: 'Dharwad' },
    // Panaji (Goa)
    { sNo: 297, pinCode: '403001', officeName: 'Panaji GPO', district: 'North Goa', state: 'Goa', deliveryType: 'Delivery', region: 'Western', divisionName: 'Goa' },
    { sNo: 298, pinCode: '403401', officeName: 'Mapusa', district: 'North Goa', state: 'Goa', deliveryType: 'Delivery', region: 'Western', divisionName: 'Goa North' },
    { sNo: 299, pinCode: '403601', officeName: 'Margao', district: 'South Goa', state: 'Goa', deliveryType: 'Delivery', region: 'Western', divisionName: 'Goa South' },
    { sNo: 300, pinCode: '403602', officeName: 'Vasco da Gama', district: 'South Goa', state: 'Goa', deliveryType: 'Delivery', region: 'Western', divisionName: 'Goa South' },
];
