export interface HolidayEntry { sNo: number; date: string; day: string; holiday: string; type: 'National' | 'Restricted' | 'State'; applicableStates: string; }

export const indianHolidaysData: HolidayEntry[] = [
    // National Holidays (Gazetted)
    { sNo: 1, date: '26-Jan', day: 'Sunday', holiday: 'Republic Day', type: 'National', applicableStates: 'All India' },
    { sNo: 2, date: '15-Aug', day: 'Friday', holiday: 'Independence Day', type: 'National', applicableStates: 'All India' },
    { sNo: 3, date: '02-Oct', day: 'Thursday', holiday: 'Mahatma Gandhi Jayanti', type: 'National', applicableStates: 'All India' },
    // Gazetted Holidays
    { sNo: 4, date: '14-Jan', day: 'Tuesday', holiday: 'Makar Sankranti / Pongal', type: 'Restricted', applicableStates: 'All India / TN, AP, TS, KA' },
    { sNo: 5, date: '26-Jan', day: 'Sunday', holiday: 'Republic Day', type: 'National', applicableStates: 'All India' },
    { sNo: 6, date: '19-Feb', day: 'Wednesday', holiday: 'Shivaji Jayanti', type: 'State', applicableStates: 'Maharashtra' },
    { sNo: 7, date: '26-Feb', day: 'Wednesday', holiday: 'Maha Shivaratri', type: 'Restricted', applicableStates: 'All India' },
    { sNo: 8, date: '14-Mar', day: 'Friday', holiday: 'Holi', type: 'Restricted', applicableStates: 'North India (UP, RJ, MP, HR, DL, BR)' },
    { sNo: 9, date: '30-Mar', day: 'Sunday', holiday: 'Ugadi / Gudi Padwa', type: 'State', applicableStates: 'MH, KA, AP, TS' },
    { sNo: 10, date: '31-Mar', day: 'Monday', holiday: 'Id-ul-Fitr (Eid)', type: 'Restricted', applicableStates: 'All India' },
    { sNo: 11, date: '06-Apr', day: 'Sunday', holiday: 'Ram Navami', type: 'Restricted', applicableStates: 'All India' },
    { sNo: 12, date: '10-Apr', day: 'Thursday', holiday: 'Mahavir Jayanti', type: 'Restricted', applicableStates: 'All India' },
    { sNo: 13, date: '14-Apr', day: 'Monday', holiday: 'Dr. Ambedkar Jayanti', type: 'Restricted', applicableStates: 'All India' },
    { sNo: 14, date: '14-Apr', day: 'Monday', holiday: 'Tamil New Year (Puthandu)', type: 'State', applicableStates: 'Tamil Nadu' },
    { sNo: 15, date: '15-Apr', day: 'Tuesday', holiday: 'Bengali New Year (Pohela Boishakh)', type: 'State', applicableStates: 'West Bengal' },
    { sNo: 16, date: '15-Apr', day: 'Tuesday', holiday: 'Vishu', type: 'State', applicableStates: 'Kerala' },
    { sNo: 17, date: '18-Apr', day: 'Friday', holiday: 'Good Friday', type: 'Restricted', applicableStates: 'All India' },
    { sNo: 18, date: '01-May', day: 'Thursday', holiday: 'May Day / Workers Day', type: 'State', applicableStates: 'TN, KA, KL, WB, AP, TS' },
    { sNo: 19, date: '12-May', day: 'Monday', holiday: 'Buddha Purnima', type: 'Restricted', applicableStates: 'All India' },
    { sNo: 20, date: '07-Jun', day: 'Saturday', holiday: 'Eid ul-Adha (Bakrid)', type: 'Restricted', applicableStates: 'All India' },
    { sNo: 21, date: '06-Jul', day: 'Sunday', holiday: 'Muharram', type: 'Restricted', applicableStates: 'All India' },
    { sNo: 22, date: '15-Aug', day: 'Friday', holiday: 'Independence Day', type: 'National', applicableStates: 'All India' },
    { sNo: 23, date: '16-Aug', day: 'Saturday', holiday: 'Janmashtami', type: 'Restricted', applicableStates: 'All India' },
    { sNo: 24, date: '27-Aug', day: 'Wednesday', holiday: 'Onam', type: 'State', applicableStates: 'Kerala' },
    { sNo: 25, date: '05-Sep', day: 'Friday', holiday: 'Milad-un-Nabi (Prophet Birthday)', type: 'Restricted', applicableStates: 'All India' },
    { sNo: 26, date: '02-Oct', day: 'Thursday', holiday: 'Mahatma Gandhi Jayanti', type: 'National', applicableStates: 'All India' },
    { sNo: 27, date: '02-Oct', day: 'Thursday', holiday: 'Dussehra (Vijaya Dashami)', type: 'Restricted', applicableStates: 'All India' },
    { sNo: 28, date: '20-Oct', day: 'Monday', holiday: 'Diwali (Deepavali)', type: 'Restricted', applicableStates: 'All India' },
    { sNo: 29, date: '21-Oct', day: 'Tuesday', holiday: 'Diwali (Day 2) / Govardhan Puja', type: 'Restricted', applicableStates: 'North India' },
    { sNo: 30, date: '22-Oct', day: 'Wednesday', holiday: 'Bhai Dooj', type: 'Restricted', applicableStates: 'North India' },
    { sNo: 31, date: '05-Nov', day: 'Wednesday', holiday: 'Guru Nanak Jayanti', type: 'Restricted', applicableStates: 'All India' },
    { sNo: 32, date: '14-Nov', day: 'Friday', holiday: 'Children\'s Day (Nehru Jayanti)', type: 'Restricted', applicableStates: 'All India' },
    { sNo: 33, date: '01-Nov', day: 'Saturday', holiday: 'Kannada Rajyotsava', type: 'State', applicableStates: 'Karnataka' },
    { sNo: 34, date: '01-Nov', day: 'Saturday', holiday: 'Kerala Piravi', type: 'State', applicableStates: 'Kerala' },
    { sNo: 35, date: '01-May', day: 'Thursday', holiday: 'Maharashtra Day', type: 'State', applicableStates: 'Maharashtra' },
    { sNo: 36, date: '01-May', day: 'Thursday', holiday: 'Gujarat Day', type: 'State', applicableStates: 'Gujarat' },
    { sNo: 37, date: '15-Jan', day: 'Wednesday', holiday: 'Pongal (Day 2 - Thiruvalluvar Day)', type: 'State', applicableStates: 'Tamil Nadu' },
    { sNo: 38, date: '23-Jan', day: 'Thursday', holiday: 'Netaji Subhas Chandra Bose Jayanti', type: 'State', applicableStates: 'West Bengal, Odisha' },
    { sNo: 39, date: '25-Dec', day: 'Thursday', holiday: 'Christmas Day', type: 'Restricted', applicableStates: 'All India' },
    { sNo: 40, date: '02-Jun', day: 'Monday', holiday: 'Telangana Formation Day', type: 'State', applicableStates: 'Telangana' },
    { sNo: 41, date: '01-Nov', day: 'Saturday', holiday: 'Chhattisgarh Rajyotsav', type: 'State', applicableStates: 'Chhattisgarh' },
    { sNo: 42, date: '15-Nov', day: 'Saturday', holiday: 'Birsa Munda Jayanti', type: 'State', applicableStates: 'Jharkhand' },
    { sNo: 43, date: '09-Aug', day: 'Saturday', holiday: 'Quit India Day', type: 'Restricted', applicableStates: 'All India' },
    { sNo: 44, date: '19-Nov', day: 'Wednesday', holiday: 'Guru Nanak Dev Prakash Purab', type: 'State', applicableStates: 'Punjab' },
    { sNo: 45, date: '06-Dec', day: 'Saturday', holiday: 'Mahaparinirvan Diwas', type: 'State', applicableStates: 'Maharashtra' },
    // More State Formation Days
    { sNo: 46, date: '01-Jun', day: 'Sunday', holiday: 'Statehood Day', type: 'State', applicableStates: 'Rajasthan' },
    { sNo: 47, date: '01-Mar', day: 'Saturday', holiday: 'Statehood Day', type: 'State', applicableStates: 'Uttarakhand' },
    { sNo: 48, date: '09-Nov', day: 'Sunday', holiday: 'Uttarakhand Formation Day', type: 'State', applicableStates: 'Uttarakhand' },
    { sNo: 49, date: '15-Nov', day: 'Saturday', holiday: 'Jharkhand Foundation Day', type: 'State', applicableStates: 'Jharkhand' },
    { sNo: 50, date: '02-Jun', day: 'Monday', holiday: 'Andhra Pradesh Formation Day', type: 'State', applicableStates: 'Andhra Pradesh' },
    { sNo: 51, date: '01-Apr', day: 'Tuesday', holiday: 'Odisha Day (Utkal Divas)', type: 'State', applicableStates: 'Odisha' },
    { sNo: 52, date: '15-Apr', day: 'Tuesday', holiday: 'Assamese New Year (Rongali Bihu)', type: 'State', applicableStates: 'Assam' },
    // More Regional Festivals
    { sNo: 53, date: '15-Jan', day: 'Wednesday', holiday: 'Magh Bihu', type: 'State', applicableStates: 'Assam' },
    { sNo: 54, date: '14-Jan', day: 'Tuesday', holiday: 'Lohri', type: 'State', applicableStates: 'Punjab, Haryana, Delhi' },
    { sNo: 55, date: '25-Apr', day: 'Friday', holiday: 'Basava Jayanti', type: 'State', applicableStates: 'Karnataka' },
    { sNo: 56, date: '11-Sep', day: 'Thursday', holiday: 'Ganesh Chaturthi', type: 'State', applicableStates: 'Maharashtra, KA, AP, TS, Goa' },
    { sNo: 57, date: '01-Oct', day: 'Wednesday', holiday: 'Navratri (Day 1)', type: 'Restricted', applicableStates: 'All India' },
    { sNo: 58, date: '09-Oct', day: 'Thursday', holiday: 'Durga Ashtami', type: 'Restricted', applicableStates: 'All India' },
    { sNo: 59, date: '10-Oct', day: 'Friday', holiday: 'Maha Navami', type: 'Restricted', applicableStates: 'All India (esp WB)' },
    { sNo: 60, date: '17-Oct', day: 'Friday', holiday: 'Karva Chauth', type: 'Restricted', applicableStates: 'North India (DL, HR, RJ, UP)' },
    { sNo: 61, date: '19-Oct', day: 'Sunday', holiday: 'Dhanteras', type: 'Restricted', applicableStates: 'All India' },
    { sNo: 62, date: '22-Oct', day: 'Wednesday', holiday: 'Chhath Puja', type: 'State', applicableStates: 'Bihar, Jharkhand, UP' },
    { sNo: 63, date: '13-Jan', day: 'Monday', holiday: 'Lohri Eve', type: 'State', applicableStates: 'Punjab, Haryana' },
    { sNo: 64, date: '29-Jun', day: 'Sunday', holiday: 'Rath Yatra', type: 'State', applicableStates: 'Odisha' },
    { sNo: 65, date: '17-Sep', day: 'Wednesday', holiday: 'Vishwakarma Puja', type: 'State', applicableStates: 'Bihar, WB, Jharkhand, Odisha' },
    // Additional Bank Holidays
    { sNo: 66, date: '01-Apr', day: 'Tuesday', holiday: 'Bank Closing (Annual)', type: 'Restricted', applicableStates: 'All India (Banks)' },
    { sNo: 67, date: '30-Sep', day: 'Tuesday', holiday: 'Bank Closing (Half Year)', type: 'Restricted', applicableStates: 'All India (Banks)' },
    { sNo: 68, date: '02-Apr', day: 'Wednesday', holiday: 'Bank Closing (2nd day)', type: 'Restricted', applicableStates: 'All India (Banks)' },
    // More restricted optional holidays
    { sNo: 69, date: '24-Apr', day: 'Thursday', holiday: 'Chaitra Sukhladi', type: 'Restricted', applicableStates: 'All India' },
    { sNo: 70, date: '06-May', day: 'Tuesday', holiday: 'Guru Rabindranath Tagore Jayanti', type: 'State', applicableStates: 'West Bengal' },
    { sNo: 71, date: '13-Nov', day: 'Thursday', holiday: 'Kartik Purnima', type: 'Restricted', applicableStates: 'North India' },
    { sNo: 72, date: '24-Nov', day: 'Monday', holiday: 'Guru Teg Bahadur Martyrdom', type: 'Restricted', applicableStates: 'Punjab, Delhi' },
    { sNo: 73, date: '24-Dec', day: 'Wednesday', holiday: 'Christmas Eve', type: 'Restricted', applicableStates: 'All India' },
    { sNo: 74, date: '31-Dec', day: 'Wednesday', holiday: 'New Year Eve', type: 'Restricted', applicableStates: 'All India' },
    { sNo: 75, date: '23-Mar', day: 'Sunday', holiday: 'Shaheed Diwas (Bhagat Singh)', type: 'Restricted', applicableStates: 'Punjab, Haryana, Delhi' },
];
