export interface StockEntry { sNo: number; company: string; symbol: string; index: 'Nifty 50' | 'Sensex' | 'Both'; sector: string; marketCap: string; weight: string; }

export const indianStockMarketData: StockEntry[] = [
    { sNo: 1, company: 'Reliance Industries', symbol: 'RELIANCE', index: 'Both', sector: 'Energy / Conglomerate', marketCap: '₹20,50,000 Cr', weight: '10.2%' },
    { sNo: 2, company: 'Tata Consultancy Services (TCS)', symbol: 'TCS', index: 'Both', sector: 'IT Services', marketCap: '₹15,80,000 Cr', weight: '4.1%' },
    { sNo: 3, company: 'HDFC Bank', symbol: 'HDFCBANK', index: 'Both', sector: 'Banking', marketCap: '₹14,20,000 Cr', weight: '13.1%' },
    { sNo: 4, company: 'ICICI Bank', symbol: 'ICICIBANK', index: 'Both', sector: 'Banking', marketCap: '₹9,50,000 Cr', weight: '8.3%' },
    { sNo: 5, company: 'Infosys', symbol: 'INFY', index: 'Both', sector: 'IT Services', marketCap: '₹7,80,000 Cr', weight: '5.8%' },
    { sNo: 6, company: 'Bharti Airtel', symbol: 'BHARTIARTL', index: 'Both', sector: 'Telecom', marketCap: '₹9,20,000 Cr', weight: '3.5%' },
    { sNo: 7, company: 'ITC', symbol: 'ITC', index: 'Both', sector: 'FMCG / Hotels', marketCap: '₹6,10,000 Cr', weight: '4.2%' },
    { sNo: 8, company: 'State Bank of India', symbol: 'SBIN', index: 'Both', sector: 'Banking', marketCap: '₹7,50,000 Cr', weight: '3.1%' },
    { sNo: 9, company: 'Hindustan Unilever', symbol: 'HINDUNILVR', index: 'Both', sector: 'FMCG', marketCap: '₹5,50,000 Cr', weight: '2.5%' },
    { sNo: 10, company: 'Larsen & Toubro', symbol: 'LT', index: 'Both', sector: 'Infrastructure', marketCap: '₹5,40,000 Cr', weight: '3.8%' },
    { sNo: 11, company: 'Kotak Mahindra Bank', symbol: 'KOTAKBANK', index: 'Both', sector: 'Banking', marketCap: '₹4,20,000 Cr', weight: '2.7%' },
    { sNo: 12, company: 'Bajaj Finance', symbol: 'BAJFINANCE', index: 'Both', sector: 'NBFC', marketCap: '₹5,10,000 Cr', weight: '2.3%' },
    { sNo: 13, company: 'Tata Motors', symbol: 'TATAMOTORS', index: 'Both', sector: 'Automobile', marketCap: '₹3,90,000 Cr', weight: '1.5%' },
    { sNo: 14, company: 'HCL Technologies', symbol: 'HCLTECH', index: 'Both', sector: 'IT Services', marketCap: '₹4,30,000 Cr', weight: '1.8%' },
    { sNo: 15, company: 'Asian Paints', symbol: 'ASIANPAINT', index: 'Both', sector: 'Chemicals / Paints', marketCap: '₹2,80,000 Cr', weight: '1.1%' },
    { sNo: 16, company: 'Axis Bank', symbol: 'AXISBANK', index: 'Both', sector: 'Banking', marketCap: '₹3,60,000 Cr', weight: '2.8%' },
    { sNo: 17, company: 'Sun Pharma', symbol: 'SUNPHARMA', index: 'Both', sector: 'Pharma', marketCap: '₹4,10,000 Cr', weight: '1.9%' },
    { sNo: 18, company: 'Mahindra & Mahindra', symbol: 'M&M', index: 'Both', sector: 'Automobile', marketCap: '₹3,80,000 Cr', weight: '2.1%' },
    { sNo: 19, company: 'Maruti Suzuki', symbol: 'MARUTI', index: 'Both', sector: 'Automobile', marketCap: '₹3,50,000 Cr', weight: '1.6%' },
    { sNo: 20, company: 'Wipro', symbol: 'WIPRO', index: 'Both', sector: 'IT Services', marketCap: '₹2,60,000 Cr', weight: '0.9%' },
    { sNo: 21, company: 'Titan Company', symbol: 'TITAN', index: 'Both', sector: 'Consumer / Jewellery', marketCap: '₹3,20,000 Cr', weight: '1.4%' },
    { sNo: 22, company: 'Tata Steel', symbol: 'TATASTEEL', index: 'Both', sector: 'Metals & Steel', marketCap: '₹2,10,000 Cr', weight: '1.2%' },
    { sNo: 23, company: 'UltraTech Cement', symbol: 'ULTRACEMCO', index: 'Both', sector: 'Cement', marketCap: '₹3,10,000 Cr', weight: '1.5%' },
    { sNo: 24, company: 'Nestle India', symbol: 'NESTLEIND', index: 'Nifty 50', sector: 'FMCG', marketCap: '₹2,30,000 Cr', weight: '0.8%' },
    { sNo: 25, company: 'NTPC', symbol: 'NTPC', index: 'Both', sector: 'Power / Energy', marketCap: '₹3,70,000 Cr', weight: '1.7%' },
    { sNo: 26, company: 'Power Grid Corp', symbol: 'POWERGRID', index: 'Both', sector: 'Power / Energy', marketCap: '₹2,80,000 Cr', weight: '1.3%' },
    { sNo: 27, company: 'IndusInd Bank', symbol: 'INDUSINDBK', index: 'Both', sector: 'Banking', marketCap: '₹1,10,000 Cr', weight: '0.6%' },
    { sNo: 28, company: 'Bajaj Finserv', symbol: 'BAJAJFINSV', index: 'Nifty 50', sector: 'NBFC / Insurance', marketCap: '₹2,60,000 Cr', weight: '0.9%' },
    { sNo: 29, company: 'Adani Enterprises', symbol: 'ADANIENT', index: 'Nifty 50', sector: 'Conglomerate', marketCap: '₹3,40,000 Cr', weight: '1.1%' },
    { sNo: 30, company: 'Adani Ports', symbol: 'ADANIPORTS', index: 'Both', sector: 'Port / Logistics', marketCap: '₹3,00,000 Cr', weight: '1.4%' },
    { sNo: 31, company: 'Bajaj Auto', symbol: 'BAJAJ-AUTO', index: 'Nifty 50', sector: 'Automobile', marketCap: '₹2,90,000 Cr', weight: '1.0%' },
    { sNo: 32, company: 'Tech Mahindra', symbol: 'TECHM', index: 'Both', sector: 'IT Services', marketCap: '₹1,50,000 Cr', weight: '0.6%' },
    { sNo: 33, company: 'Coal India', symbol: 'COALINDIA', index: 'Nifty 50', sector: 'Mining', marketCap: '₹2,80,000 Cr', weight: '0.9%' },
    { sNo: 34, company: 'Grasim Industries', symbol: 'GRASIM', index: 'Nifty 50', sector: 'Cement / Diversified', marketCap: '₹1,80,000 Cr', weight: '0.8%' },
    { sNo: 35, company: 'BPCL', symbol: 'BPCL', index: 'Nifty 50', sector: 'Oil & Gas', marketCap: '₹1,40,000 Cr', weight: '0.5%' },
    { sNo: 36, company: 'Cipla', symbol: 'CIPLA', index: 'Nifty 50', sector: 'Pharma', marketCap: '₹1,20,000 Cr', weight: '0.7%' },
    { sNo: 37, company: 'Dr. Reddy\'s Labs', symbol: 'DRREDDY', index: 'Nifty 50', sector: 'Pharma', marketCap: '₹1,10,000 Cr', weight: '0.6%' },
    { sNo: 38, company: 'Eicher Motors', symbol: 'EICHERMOT', index: 'Nifty 50', sector: 'Automobile', marketCap: '₹1,30,000 Cr', weight: '0.5%' },
    { sNo: 39, company: 'Hero MotoCorp', symbol: 'HEROMOTOCO', index: 'Nifty 50', sector: 'Automobile', marketCap: '₹1,00,000 Cr', weight: '0.4%' },
    { sNo: 40, company: 'Hindalco', symbol: 'HINDALCO', index: 'Nifty 50', sector: 'Metals', marketCap: '₹1,50,000 Cr', weight: '0.7%' },
    { sNo: 41, company: 'JSW Steel', symbol: 'JSWSTEEL', index: 'Nifty 50', sector: 'Metals & Steel', marketCap: '₹2,40,000 Cr', weight: '1.0%' },
    { sNo: 42, company: 'ONGC', symbol: 'ONGC', index: 'Nifty 50', sector: 'Oil & Gas', marketCap: '₹3,30,000 Cr', weight: '1.2%' },
    { sNo: 43, company: 'Shriram Finance', symbol: 'SHRIRAMFIN', index: 'Nifty 50', sector: 'NBFC', marketCap: '₹1,20,000 Cr', weight: '0.5%' },
    { sNo: 44, company: 'Apollo Hospitals', symbol: 'APOLLOHOSP', index: 'Nifty 50', sector: 'Healthcare', marketCap: '₹95,000 Cr', weight: '0.5%' },
    { sNo: 45, company: 'Britannia Industries', symbol: 'BRITANNIA', index: 'Nifty 50', sector: 'FMCG', marketCap: '₹1,10,000 Cr', weight: '0.4%' },
    { sNo: 46, company: 'Divis Labs', symbol: 'DIVISLAB', index: 'Nifty 50', sector: 'Pharma', marketCap: '₹1,05,000 Cr', weight: '0.4%' },
    { sNo: 47, company: 'SBI Life Insurance', symbol: 'SBILIFE', index: 'Nifty 50', sector: 'Insurance', marketCap: '₹1,50,000 Cr', weight: '0.6%' },
    { sNo: 48, company: 'Tata Consumer Products', symbol: 'TATACONSUM', index: 'Nifty 50', sector: 'FMCG', marketCap: '₹1,10,000 Cr', weight: '0.4%' },
    { sNo: 49, company: 'Bharat Electronics', symbol: 'BEL', index: 'Nifty 50', sector: 'Defence / Electronics', marketCap: '₹2,10,000 Cr', weight: '0.8%' },
    { sNo: 50, company: 'Trent', symbol: 'TRENT', index: 'Nifty 50', sector: 'Retail', marketCap: '₹2,30,000 Cr', weight: '0.7%' },
    // Nifty Next 50
    { sNo: 51, company: 'Pidilite Industries', symbol: 'PIDILITIND', index: 'Nifty 50', sector: 'Chemicals / Adhesives', marketCap: '₹1,50,000 Cr', weight: '0.5%' },
    { sNo: 52, company: 'Havells India', symbol: 'HAVELLS', index: 'Nifty 50', sector: 'Consumer Electronics', marketCap: '₹1,10,000 Cr', weight: '0.4%' },
    { sNo: 53, company: 'Godrej Consumer Products', symbol: 'GODREJCP', index: 'Nifty 50', sector: 'FMCG', marketCap: '₹1,05,000 Cr', weight: '0.4%' },
    { sNo: 54, company: 'Dalmia Bharat', symbol: 'DALBHARAT', index: 'Nifty 50', sector: 'Cement', marketCap: '₹35,000 Cr', weight: '0.2%' },
    { sNo: 55, company: 'ABB India', symbol: 'ABB', index: 'Nifty 50', sector: 'Industrial', marketCap: '₹1,40,000 Cr', weight: '0.4%' },
    { sNo: 56, company: 'HDFC Life Insurance', symbol: 'HDFCLIFE', index: 'Nifty 50', sector: 'Insurance', marketCap: '₹1,30,000 Cr', weight: '0.5%' },
    { sNo: 57, company: 'Zomato', symbol: 'ZOMATO', index: 'Nifty 50', sector: 'Food Tech / Internet', marketCap: '₹1,80,000 Cr', weight: '0.6%' },
    { sNo: 58, company: 'Indian Oil Corporation', symbol: 'IOC', index: 'Sensex', sector: 'Oil & Gas', marketCap: '₹2,10,000 Cr', weight: '0.8%' },
    { sNo: 59, company: 'Hindustan Petroleum', symbol: 'HINDPETRO', index: 'Sensex', sector: 'Oil & Gas', marketCap: '₹85,000 Cr', weight: '0.3%' },
    { sNo: 60, company: 'Vedanta', symbol: 'VEDL', index: 'Sensex', sector: 'Mining / Metals', marketCap: '₹1,70,000 Cr', weight: '0.5%' },
    { sNo: 61, company: 'Ambuja Cements', symbol: 'AMBUJACEM', index: 'Sensex', sector: 'Cement', marketCap: '₹1,30,000 Cr', weight: '0.4%' },
    { sNo: 62, company: 'ACC', symbol: 'ACC', index: 'Sensex', sector: 'Cement', marketCap: '₹45,000 Cr', weight: '0.2%' },
    { sNo: 63, company: 'Siemens India', symbol: 'SIEMENS', index: 'Sensex', sector: 'Industrial', marketCap: '₹1,90,000 Cr', weight: '0.5%' },
    { sNo: 64, company: 'Torrent Pharmaceuticals', symbol: 'TORNTPHARM', index: 'Sensex', sector: 'Pharma', marketCap: '₹80,000 Cr', weight: '0.3%' },
    { sNo: 65, company: 'Aurobindo Pharma', symbol: 'AUROPHARMA', index: 'Sensex', sector: 'Pharma', marketCap: '₹65,000 Cr', weight: '0.2%' },
    { sNo: 66, company: 'Lupin', symbol: 'LUPIN', index: 'Sensex', sector: 'Pharma', marketCap: '₹85,000 Cr', weight: '0.3%' },
    { sNo: 67, company: 'Biocon', symbol: 'BIOCON', index: 'Sensex', sector: 'Biotech / Pharma', marketCap: '₹35,000 Cr', weight: '0.1%' },
    { sNo: 68, company: 'MRF', symbol: 'MRF', index: 'Sensex', sector: 'Tyres', marketCap: '₹55,000 Cr', weight: '0.2%' },
    { sNo: 69, company: 'Motherson Sumi', symbol: 'MOTHERSON', index: 'Sensex', sector: 'Auto Ancillary', marketCap: '₹90,000 Cr', weight: '0.3%' },
    { sNo: 70, company: 'Bosch', symbol: 'BOSCHLTD', index: 'Sensex', sector: 'Auto Ancillary', marketCap: '₹95,000 Cr', weight: '0.3%' },
    { sNo: 71, company: 'Berger Paints', symbol: 'BERGEPAINT', index: 'Sensex', sector: 'Paints', marketCap: '₹70,000 Cr', weight: '0.2%' },
    { sNo: 72, company: 'Info Edge (Naukri)', symbol: 'NAUKRI', index: 'Sensex', sector: 'Internet / HR', marketCap: '₹95,000 Cr', weight: '0.3%' },
    { sNo: 73, company: 'LTIMindtree', symbol: 'LTIM', index: 'Sensex', sector: 'IT Services', marketCap: '₹1,65,000 Cr', weight: '0.5%' },
    { sNo: 74, company: 'Mphasis', symbol: 'MPHASIS', index: 'Sensex', sector: 'IT Services', marketCap: '₹55,000 Cr', weight: '0.2%' },
    { sNo: 75, company: 'Persistent Systems', symbol: 'PERSISTENT', index: 'Sensex', sector: 'IT Services', marketCap: '₹75,000 Cr', weight: '0.3%' },
    { sNo: 76, company: 'Coforge', symbol: 'COFORGE', index: 'Sensex', sector: 'IT Services', marketCap: '₹40,000 Cr', weight: '0.2%' },
    { sNo: 77, company: 'L&T Technology Services', symbol: 'LTTS', index: 'Sensex', sector: 'IT / Engineering', marketCap: '₹50,000 Cr', weight: '0.2%' },
    { sNo: 78, company: 'SBI Cards', symbol: 'SBICARD', index: 'Sensex', sector: 'Financial Services', marketCap: '₹70,000 Cr', weight: '0.2%' },
    { sNo: 79, company: 'ICICI Prudential Life', symbol: 'ICICIPRULI', index: 'Sensex', sector: 'Insurance', marketCap: '₹85,000 Cr', weight: '0.3%' },
    { sNo: 80, company: 'Max Financial Services', symbol: 'MFSL', index: 'Sensex', sector: 'Insurance', marketCap: '₹40,000 Cr', weight: '0.2%' },
    { sNo: 81, company: 'General Insurance Corp', symbol: 'GICRE', index: 'Sensex', sector: 'Insurance', marketCap: '₹55,000 Cr', weight: '0.2%' },
    { sNo: 82, company: 'Adani Green Energy', symbol: 'ADANIGREEN', index: 'Sensex', sector: 'Renewable Energy', marketCap: '₹2,60,000 Cr', weight: '0.7%' },
    { sNo: 83, company: 'Adani Total Gas', symbol: 'ATGL', index: 'Sensex', sector: 'Gas Distribution', marketCap: '₹1,10,000 Cr', weight: '0.3%' },
    { sNo: 84, company: 'Adani Power', symbol: 'ADANIPOWER', index: 'Sensex', sector: 'Power', marketCap: '₹2,40,000 Cr', weight: '0.6%' },
    { sNo: 85, company: 'Tata Power', symbol: 'TATAPOWER', index: 'Sensex', sector: 'Power / Renewable', marketCap: '₹1,40,000 Cr', weight: '0.4%' },
    { sNo: 86, company: 'NHPC', symbol: 'NHPC', index: 'Sensex', sector: 'Hydropower', marketCap: '₹95,000 Cr', weight: '0.3%' },
    { sNo: 87, company: 'Indian Railway Finance Corp', symbol: 'IRFC', index: 'Sensex', sector: 'NBFC / Railway', marketCap: '₹2,00,000 Cr', weight: '0.5%' },
    { sNo: 88, company: 'HAL (Hindustan Aeronautics)', symbol: 'HAL', index: 'Sensex', sector: 'Defence / Aerospace', marketCap: '₹3,20,000 Cr', weight: '0.9%' },
    { sNo: 89, company: 'Mazagon Dock Shipbuilders', symbol: 'MAZDOCK', index: 'Sensex', sector: 'Defence / Shipbuilding', marketCap: '₹70,000 Cr', weight: '0.2%' },
    { sNo: 90, company: 'Bharat Dynamics', symbol: 'BDL', index: 'Sensex', sector: 'Defence / Missiles', marketCap: '₹45,000 Cr', weight: '0.2%' },
    { sNo: 91, company: 'Dixon Technologies', symbol: 'DIXON', index: 'Sensex', sector: 'Electronics Mfg', marketCap: '₹85,000 Cr', weight: '0.3%' },
    { sNo: 92, company: 'Page Industries', symbol: 'PAGEIND', index: 'Sensex', sector: 'Textiles / Apparel', marketCap: '₹45,000 Cr', weight: '0.2%' },
    { sNo: 93, company: 'Dabur India', symbol: 'DABUR', index: 'Sensex', sector: 'FMCG', marketCap: '₹90,000 Cr', weight: '0.3%' },
    { sNo: 94, company: 'Marico', symbol: 'MARICO', index: 'Sensex', sector: 'FMCG', marketCap: '₹85,000 Cr', weight: '0.3%' },
    { sNo: 95, company: 'Colgate-Palmolive India', symbol: 'COLPAL', index: 'Sensex', sector: 'FMCG', marketCap: '₹70,000 Cr', weight: '0.2%' },
    { sNo: 96, company: 'Jubilant FoodWorks', symbol: 'JUBLFOOD', index: 'Sensex', sector: 'QSR / Food', marketCap: '₹40,000 Cr', weight: '0.2%' },
    { sNo: 97, company: 'Varun Beverages', symbol: 'VBL', index: 'Sensex', sector: 'Beverages', marketCap: '₹1,80,000 Cr', weight: '0.5%' },
    { sNo: 98, company: 'Avenue Supermarts (DMart)', symbol: 'DMART', index: 'Sensex', sector: 'Retail', marketCap: '₹2,80,000 Cr', weight: '0.8%' },
    { sNo: 99, company: 'Zydus Lifesciences', symbol: 'ZYDUSLIFE', index: 'Sensex', sector: 'Pharma', marketCap: '₹90,000 Cr', weight: '0.3%' },
    { sNo: 100, company: 'Cholamandalam Investment', symbol: 'CHOLAFIN', index: 'Sensex', sector: 'NBFC', marketCap: '₹1,10,000 Cr', weight: '0.3%' },
];
