// Section 80 Deductions — Complete list under Income Tax Act (FY 2025-26)
// Old Tax Regime deductions; most NOT available under New Regime

export interface Section80Entry {
    sNo: number;
    section: string;
    title: string;
    maxLimit: string;
    eligibility: string;
    description: string;
    availableInNewRegime: boolean;
    remarks: string;
}

export const section80DeductionsData: Section80Entry[] = [
{sNo:1,section:'80C',title:'Investments & Savings',maxLimit:'₹1,50,000',eligibility:'Individual / HUF',description:'PPF, EPF, ELSS, NSC, 5yr FD, Life Insurance premium, Home Loan principal, Children tuition fees (max 2 children), Sukanya Samriddhi, Senior Citizen Savings Scheme',availableInNewRegime:false,remarks:'Most popular deduction; combined with 80CCC & 80CCD(1)'},
{sNo:2,section:'80CCC',title:'Pension Fund Contribution',maxLimit:'₹1,50,000',eligibility:'Individual',description:'Contribution to annuity plan of LIC or other insurer',availableInNewRegime:false,remarks:'Combined limit with 80C & 80CCD(1) of ₹1.5L'},
{sNo:3,section:'80CCD(1)',title:'NPS Employee Contribution',maxLimit:'₹1,50,000',eligibility:'Individual (Employee)',description:'Employee contribution to NPS Tier-1 (max 10% of salary for salaried, 20% of GTI for self-employed)',availableInNewRegime:false,remarks:'Combined limit with 80C & 80CCC of ₹1.5L'},
{sNo:4,section:'80CCD(1B)',title:'NPS Additional Contribution',maxLimit:'₹50,000',eligibility:'Individual',description:'Additional contribution to NPS Tier-1 beyond ₹1.5L limit of 80C',availableInNewRegime:false,remarks:'Over & above 80C limit; total NPS benefit up to ₹2L'},
{sNo:5,section:'80CCD(2)',title:'NPS Employer Contribution',maxLimit:'14% of Salary (Central Govt) / 10% (Others)',eligibility:'Employee',description:'Employer contribution to NPS — not included in ₹1.5L limit',availableInNewRegime:true,remarks:'Available in BOTH Old & New regime'},
{sNo:6,section:'80D',title:'Health Insurance Premium',maxLimit:'₹25,000 / ₹50,000 (Sr Citizen)',eligibility:'Individual / HUF',description:'Self/spouse/children: ₹25K (<60yr) or ₹50K (≥60yr). Parents: additional ₹25K or ₹50K. Preventive check-up ₹5K within limit.',availableInNewRegime:false,remarks:'Max ₹1L if self + parents are senior citizens'},
{sNo:7,section:'80DD',title:'Disabled Dependent Maintenance',maxLimit:'₹75,000 / ₹1,25,000 (Severe)',eligibility:'Individual (Resident)',description:'Expenditure on maintenance or medical treatment of disabled dependent (40-79%: ₹75K; ≥80%: ₹1.25L)',availableInNewRegime:false,remarks:'Fixed deduction regardless of actual expense'},
{sNo:8,section:'80DDB',title:'Medical Treatment (Specified Diseases)',maxLimit:'₹40,000 / ₹1,00,000 (Sr Citizen)',eligibility:'Individual / HUF (Resident)',description:'Treatment for specified diseases (cancer, AIDS, chronic renal failure, neurological diseases). Self or dependent.',availableInNewRegime:false,remarks:'Certificate from specialist required; reduced by insurance received'},
{sNo:9,section:'80E',title:'Interest on Education Loan',maxLimit:'No upper limit',eligibility:'Individual',description:'Interest paid on education loan for higher studies for self, spouse, children, or ward. Max 8 years from repayment start.',availableInNewRegime:false,remarks:'Only interest portion; principal via 80C; must be from notified institution'},
{sNo:10,section:'80EE',title:'Interest on Housing Loan (First-time)',maxLimit:'₹50,000',eligibility:'Individual (First-time buyer)',description:'Loan sanctioned in FY 2016-17; loan ≤₹35L; property value ≤₹50L; no other house owned at sanction date.',availableInNewRegime:false,remarks:'Over & above Sec 24(b) ₹2L limit; now mostly see 80EEA'},
{sNo:11,section:'80EEA',title:'Interest on Affordable Housing Loan',maxLimit:'₹1,50,000',eligibility:'Individual (First-time buyer)',description:'Loan sanctioned Apr 2019 - Mar 2022; stamp duty value ≤₹45L; no other house owned.',availableInNewRegime:false,remarks:'Over & above Sec 24(b) ₹2L; total interest benefit up to ₹3.5L'},
{sNo:12,section:'80EEB',title:'Interest on Electric Vehicle Loan',maxLimit:'₹1,50,000',eligibility:'Individual',description:'Interest on loan for purchase of electric vehicle; loan sanctioned Apr 2019 - Mar 2023.',availableInNewRegime:false,remarks:'Encourages EV adoption'},
{sNo:13,section:'80G',title:'Donations to Charitable Institutions',maxLimit:'50% or 100% (with/without qualifying limit)',eligibility:'All Assessees',description:'100% dedn: PM Relief Fund, National Defence Fund. 50% dedn to approved trusts. Subject to 10% of Adjusted GTI for qualifying donations. Cash >₹2000 not eligible.',availableInNewRegime:false,remarks:'Donation receipt & 80G certificate required'},
{sNo:14,section:'80GG',title:'Rent Paid (no HRA)',maxLimit:'₹60,000/year (₹5,000/month)',eligibility:'Individual',description:'Least of: (a) ₹5000/month, (b) 25% of total income, (c) Rent paid minus 10% of total income. Must file Form 10BA.',availableInNewRegime:false,remarks:'Only when HRA not received from employer'},
{sNo:15,section:'80GGA',title:'Donations for Scientific Research',maxLimit:'100%',eligibility:'All Assessees (No business income)',description:'Donations to approved scientific research associations, rural development, or conservation programs.',availableInNewRegime:false,remarks:'Not for taxpayers with business/profession income'},
{sNo:16,section:'80GGB',title:'Company Political Donations',maxLimit:'No limit',eligibility:'Indian Companies',description:'Contributions by companies to political parties or electoral trust. Must be non-cash.',availableInNewRegime:false,remarks:'CSR cannot be claimed'},
{sNo:17,section:'80GGC',title:'Individual Political Donations',maxLimit:'No limit',eligibility:'Individuals / HUF / Firms / AOP',description:'Contributions to political parties or electoral trust. Cash not eligible.',availableInNewRegime:false,remarks:'Not available to local authorities or artificial juridical persons'},
{sNo:18,section:'80IA',title:'Deductions for Infrastructure',maxLimit:'100% of profits',eligibility:'Undertakings',description:'Profits from developing/operating infrastructure facilities like highways, ports, water treatment, etc.',availableInNewRegime:false,remarks:'10 consecutive years out of 15/20 years'},
{sNo:19,section:'80IAB',title:'SEZ Developer Deduction',maxLimit:'100% of profits',eligibility:'SEZ Developers',description:'Profits from SEZ approved development activities.',availableInNewRegime:false,remarks:'10 consecutive of 15 years from notification'},
{sNo:20,section:'80JJAA',title:'Employment Generation Deduction',maxLimit:'30% of additional employee cost for 3 AYs',eligibility:'All Assessees (with business income)',description:'30% deduction on additional wages for 3 years for new employees (salary ≤₹25K/month, employed ≥240 days).',availableInNewRegime:true,remarks:'Available in BOTH Old & New regime. Encourages job creation.'},
{sNo:21,section:'80P',title:'Co-operative Society Income',maxLimit:'100% / Specific',eligibility:'Co-operative Societies',description:'Profits from banking, credit, marketing of agricultural produce, cottage industries, etc.',availableInNewRegime:false,remarks:'Not available to co-op banks after amendment'},
{sNo:22,section:'80QQB',title:'Royalty Income from Books',maxLimit:'₹3,00,000',eligibility:'Individual (Resident Author)',description:'Royalty or copyright income from literary, artistic, or scientific works (excluding textbooks & periodicals).',availableInNewRegime:false,remarks:'Author must be first owner of copyright'},
{sNo:23,section:'80RRB',title:'Royalty on Patents',maxLimit:'₹3,00,000',eligibility:'Individual (Resident Patentee)',description:'Income from royalty on patents registered after 01-Apr-2003.',availableInNewRegime:false,remarks:'Patent must be registered under Patents Act 1970'},
{sNo:24,section:'80TTA',title:'Interest on Savings Account',maxLimit:'₹10,000',eligibility:'Individual / HUF (Non-Senior Citizen)',description:'Interest earned from savings accounts in banks, co-operative societies, or post offices. FD/RD interest not eligible.',availableInNewRegime:false,remarks:'Not for senior citizens (they use 80TTB)'},
{sNo:25,section:'80TTB',title:'Interest for Senior Citizens',maxLimit:'₹50,000',eligibility:'Individual (Senior Citizen ≥60yr)',description:'Interest from savings, FD, RD in banks, co-operative societies, or post office.',availableInNewRegime:false,remarks:'Replaces 80TTA for senior citizens'},
{sNo:26,section:'80U',title:'Disability of Assessee',maxLimit:'₹75,000 / ₹1,25,000 (Severe)',eligibility:'Individual (Resident)',description:'40-79% disability: ₹75K. ≥80% severe disability: ₹1.25L. Certificate from authorized medical authority required.',availableInNewRegime:false,remarks:'Fixed deduction; no proof of expense needed; Form 10-IA'},
];
